MetaMask/core

src/ComposableController.ts
src/KeyringController.ts

This PR is a placeholder to keep track of the changes I made for https://github.com/MetaMask/MetaMask/compare/redux-persist?expand=1

Initial state

---

src/KeyringController.ts

By moving this.keyring to a WeakMap that is not exported with the rest of the `KeyringController`, we keep the same functionality with the difference that we don't expose any of the sensitive stuff to the outside world.
BEFORE:
AFTER:

Move this.keyring to WeakMap

---

src/ComposableController.test.ts
src/TokenRatesController.test.ts
src/TokenRatesController.ts

This PR updates `TokenRatesController` to work with new Balanc3 API.

Handle balanc3 new API

---

package-lock.json
src/KeyringController.ts

Protect exportAccount and added secure exportSeedPhrase method (requires password)

Fix export keyring data

---

src/TransactionController.ts

This PR adds transaction data coming from etherscan.

Save transaction data from etherscan

---

src/KeyringController.ts

@estebanmino While working in the import pkey feature I found out this two calls were missing. We need to get this in ASAP because of the audit and release a new version.

Add missing fullUpdate calls to KeyringController

---

package-lock.json
package.json
src/AssetsController.test.ts
src/AssetsController.ts
src/AssetsDetectionController.test.ts
src/AssetsDetectionController.ts

This PR:
- Downgrade jest to last stable version for typescript.
- Improves collectibles detection. If collectible contract information is not found when auto detecting collectible (bad internet connection or open sea failure), collectibles are not being added. A test was added simulating this behavior, if information is not found the auto detection is going to wait for the next time `detectCollectibles` is triggered.

Improve collectible detection

---

src/AccountTrackerController.test.ts
src/AccountTrackerController.ts

Forgot to update this Controller in #77

Fix polling in AccountTrackerController

---

src/TransactionController.test.ts
src/TransactionController.ts

This change fixes a warning introduced by https://github.com/MetaMask/gaba/pull/76

Bugfix: fix transaction to undefined warning

---

README.md

https://github.com/MetaMask/gaba/commit/5b0e56aa874c3ec75aabe0fd06de818e78a22c9b swapped order of initialization args,
fix some typos

readme: re-order initialization args

---

src/AssetsController.test.ts
src/AssetsController.ts
src/AssetsDetectionController.ts
src/util.ts

This PR adds the ability to set an API key to be used with OpenSea. If it's not set, it will default to the open api endpoint.

Feature: collectibles api key

---

src/TransactionController.test.ts
src/TransactionController.ts

This pull request updates the `TransactionController` by adding a new method that stops a pending transaction by sending a 0 ETH transaction to the `from` address with a higher gas price.

feature: add ability to stop a transaction

---

src/AssetsController.test.ts
src/AssetsController.ts
src/AssetsDetectionController.ts
src/util.test.ts
src/util.ts

This PR adds some improvements to assets detection:
1. Use of `safelyExecute` inside each individual assets detection methods, `detectTokens` and `detectCollectibles`. With this we can use these methods directly and handle errors.
2. Collectibles without `image` or `name` are now accepted, following the EIP.
3. Added a util method, `fetchTimeout` to handle requests to external APIs.
4. Use of `fetchTimeout` in collectibles detection.

Improvement: assets detection

---

npm-shrinkwrap.json
package.json
src/user/AddressBookController.ts
tests/AddressBookController.test.ts
tests/ComposableController.test.ts

Revert "add xtend to address book to prevent state overwrite on extension update"

---

package.json

Use npm release of eth-contract-metadata

---

src/assets/AssetsDetectionController.ts
tests/AssetsDetectionController.test.ts

This pr adds the ability to remove collectibles that the user doesn't have while `detectCollectibles`

Feature: remove collectibles while detecting

---

src/network/NetworkController.ts
src/util.ts
tests/util.test.ts

This PR handles goerli test network

Feature: goerli support

---

npm-shrinkwrap.json

deps - update the shrink wrap for eth-contract-metadata 

---

npm-shrinkwrap.json

Fixes #122
This PR commits required changes to the `npm-shrinkwrap.json` file, allowing `npm ci` to produce a correct install.

Sync npm-shrinkwrap.json file

---

src/ComposableController.ts
src/keyring/KeyringController.ts
src/network/NetworkStatusController.ts
src/third-party/PhishingController.ts

This PR fixes a few typos found throughout the comments.

Fix typos in comments

---

npm-shrinkwrap.json
src/message-manager/TypedMessageManager.ts
src/util.ts
tests/util.test.ts

This PR removes enforcement to provide `chainId` for EIP-712 signatures.

bugfix: eip712 valIdation

---

tsconfig.json

Enable inlineSources for TypeScript source maps

---

npm-shrinkwrap.json
package.json
src/assets/AssetsController.ts
src/assets/CurrencyRateController.ts
src/keyring/KeyringController.ts
src/transaction/TransactionController.ts
tests/CurrencyRateController.test.ts

This pull request represents `v1.9.3` that will be published.
I've cherry-picked #194 & #195 here to avoid having #192 go out in this release.

Version 1.9.3

---

src/assets/AssetsController.ts
src/user/AddressBookController.ts

This PR fixes up two instances where the JSDoc comments didn't reflect the implementation.

Fix JSDoc params

---

yarn.lock

This change resolves 2 security advisories by updating our handlebars version.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.8 <4.0.0 || >=4.5.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ typedoc                                                      │
├───────────────┼──────────────────────────────────────────────────── …
```

Use handlebars@4.7.3

---

README.md
package.json

Rename `gaba` to `@metamask/controllers`

gaba -> @metamask/controllers

---

README.md

This PR updates the release and publishing steps documented in the README.

Update Release & Publishing steps

---

package.json
src/transaction/TransactionController.ts
src/user/PreferencesController.ts
yarn.lock

`eth-json-rpc-errors` -> `eth-rpc-errors` update

eth-rpc-errors

---

.eslintrc.js
tests/TransactionController.test.ts

This PR enables `callback-return` and fixes the issue it raised.

Enable and fix callback-return issues

---

package.json
yarn.lock

Prepares for `web3-provider-engine` upgrade.

eth-json-rpc-infura@5.1.0

---

package.json
yarn.lock

Not breaking for our purposes.

eth-rpc-errors@3.0.0

---

package.json
tests/CurrencyRateController.test.ts
yarn.lock

- `web3-provider-engine@16.0.1`
- `fetch-mock@9.10.7`
- Upgraded to fix tests, and it was also out of date.

web3-provider-engine@16.0.1

---

.eslintrc.js
package.json
src/assets/AssetsController.ts
src/assets/AssetsDetectionController.ts
src/assets/CurrencyRateController.ts
src/keyring/KeyringController.ts
src/message-manager/MessageManager.ts
src/message-manager/PersonalMessageManager.ts
src/message-manager/TypedMessageManager.ts
src/network/NetworkController.ts
src/third-party/EnsController.ts
src/transaction/TransactionController.ts
src/user/AddressBookController.ts
src/user/PreferencesController.ts
src/util.ts
tests/CurrencyRateController.test.ts

This PR updates the prettier command we run on CI (via `yarn format`) to _check_ the files versus writing them out. We were writing out the files but then discarding those changes implicitly when the job would complete.

Fix Prettier commands

---

package.json
src/transaction/TransactionController.ts
yarn.lock

- Update `eth-rpc-errors` to `4.0.0`

eth-rpc-errors@4.0.0

---

src/approval/ApprovalController.ts
src/index.ts
tests/ApprovalController.test.js

The approval controller was never exported. This fixes that.

Fix approval controller exports

---

package.json
yarn.lock

`eth-sig-util` was accidentally pinned.

Unpin eth-sig-util

---

src/util.ts
tests/util.test.ts

This PR robustifies the `watchAsset` type checks and returns appropriate RPC errors.

Fix watch asset validation and errors

---

src/transaction/TransactionController.ts

This change should have been included along with #351 but was missed

Remove AlethioTransactionMeta

---

src/transaction/TransactionController.test.ts
src/transaction/TransactionController.ts

there were some things missing in the previous alethio work. this should account for aforementioned missing things.

Add normalizeTokenTx

---

src/assets/AssetsController.ts

The asset metadata type has been updated to conditionally require the `error` field for errors, and disallow it for non-errors. This allows us to remove the non-null assertion used in the 'finished' callback, as now TypeScript can infer that the `error` field must be present if the status is `failed`.

Improve asset metadata type

---

src/assets/TokenListController.test.ts
src/assets/TokenListController.ts

Adding iconURL to the Token type defined in the TokeListcontroller.
```
type Token = {
name: string;
address: string;
decimals: number;
symbol: string;
occurrences: number;
aggregators: string[];
iconUrl: string;
};
```

Adding iconurl to TokenListController

---

CHANGELOG.md
package.json

proposed changelog: 
- **BREAKING**: Removes AssetsController and adds CollectiblesController and TokensController in its place([#518](https://github.com/MetaMask/controllers/pull/518))

v13.0.0 release

---

src/apis/token-service.test.ts
src/apis/token-service.ts
src/assets/AssetsDetectionController.test.ts
src/assets/TokenListController.test.ts

The PR updates the token list api with https://token-api.metaswap.codefi.network/

Updating the token list api 

---

src/assets/CollectiblesController.ts

- ADDED:
- Adds method getValidIpfsGatewayFormat to ensure validIpfsGateway format for retrieving ipfs assets

ensure valid ipfsGateWay format for retrieiving ipfs assets

---

src/gas/fetchBlockFeeHistory.ts

Fix typo in fetchBlockFeeHistory.ts

---

tsconfig.json

Disable redundant `tsconfig` rules that are already covered by `eslint`.
**Checklist**
**Issue**
Resolves #694

Disable redundant tsconfig rules

---

jest.config.js

Fix glob that determined which files we collect coverage for
- FIXED:
- Fix glob that determined which files we collect coverage for
**Checklist**

Fix coverage glob

---

src/transaction/TransactionController.ts

Fix typo in TransactionController.ts

---

README.md

First swing at updating these instructions detailing the new publish environment we've now added here.

Update publish instructions

---

package.json
src/keyring/KeyringController.test.ts
yarn.lock

Bump `eth-keyring-controller` to `7.0.1`. Adapt tests accordingly.

Bump eth-keyring-controller to 7.0.1

---

src/index.ts
src/notification/NotificationController.test.ts
src/notification/NotificationController.ts
src/ratelimit/RateLimitController.test.ts
src/ratelimit/RateLimitController.ts

**Export NotificationController and fix types**
- Export NotificationController
- Fix conflicting types for controller actions
- FIXED:
- Export NotificationController
- Fix conflicting types for controller actions
**Checklist**

Export NotificationController and fix types

---

src/assets/assetsUtil.test.ts
src/assets/assetsUtil.ts

Add utils to format tokens from token list controller
3 of 7 PRs for https://github.com/MetaMask/controllers/pull/763

[Token Detection V2] 3 of 7 - Add utils to format tokens from TokenListController

---

package.json
src/keyring/KeyringController.ts
yarn.lock

- CHANGED:
- Bump `eth-keyring-controller` to v7.0.2

bump eth-keyring-controller to v7.0.2

---

src/assets/TokenDetectionController.test.ts
src/assets/TokenListController.test.ts
src/assets/TokenListController.ts
src/assets/assetsUtil.ts

Always pull from dynamic token list from TokenListController
5 of 7 PRs for https://github.com/MetaMask/controllers/pull/763

[Token Detection V2] 5 of 7 - Always pull from dynamic token list from TokenListController

---

src/assets/AssetsContractController.test.ts
src/assets/Standards/ERC20Standard.test.ts
src/assets/Standards/ERC20Standard.ts
src/assets/Standards/standards-types.ts

Fix an issue parsing non-standard ERC20 responses.
- FIXED:
- Fix an issue parsing non-standard ERC20 responses
**Checklist**
**Issue**
Resolves #???

Fix issues parsing non-standard ERC20 responses

---

src/assets/CollectibleDetectionController.test.ts
src/assets/CollectibleDetectionController.ts
src/assets/CollectiblesController.test.ts
src/assets/CollectiblesController.ts
src/constants.ts
src/util.ts

Routes all requests we make to OpenSea in `controllers` through the proxy server recently deployed by Codefi.

Re-point OS API calls to Codefi proxy

---

src/assets/CollectiblesController.test.ts

The `CollectibleController` tests have been refactored such that the controller construction step is now in a function rather than the `beforeEach` hook. This lets us construct the controller differently in specific tests.

Refactor `CollectibleController` tests

---

src/assets/TokenListController.test.ts

**Brittle TokenListController test**
Depending on setTimeouts to wait long enough for something to be finished is not good. 
Subscribing to the thing we want is much better.
- FIXED:
- TokenListController test that fails about 60% of the time (80% on tuesdays :trollface:)
**Checklist**
**Issue**
Resolves #???

Fixed brittle TokenListController test

---

src/third-party/PhishingController.test.ts
src/third-party/PhishingController.ts
src/util.ts

Changed endpoints hosting the phishing list to use Codefi, as cache invalidation is more frequent here
**PR Title**
Update phishing endpoints and fix issues with new implementation
This PR updates the phishing endpoints used in the PhishingController and fixes a few issues with the new implementation that were blockers from using it in the extension.
- CHANGED:
- Changed endpoints used in PhishingController
- FIXED:
- Fix issue with network failures bubbling up from PhishingController
- Fix issue with parallel network requests
**Checklist**

Update phishing endpoints and fix issues with new implementation

---

README.md

**Fix link for assets-controllers**
- Fix link for assets-controllers
- FIXED:
- Fix link for assets-controllers
**Checklist**

Fix link for assets-controllers

---

packages/network-controller/src/NetworkController.ts

The `lookupNetwork` method now blocks on completion of the async network call that it makes to get the network ID. This method was already an `async` function, but it was not blocking the sole async operation so it always returned synchronously in practice.
- CHANGED:
- [`@metamask/network-controller`] The `lookupNework` method will not return until after it has finished getting the network ID.
**Checklist**

[network-controller] Make `lookupNetwork` async

---

packages/network-controller/src/NetworkController.test.ts
packages/network-controller/src/NetworkController.ts

This PR Makes `getEIP1559Compatibility` method async
Related issue [#1022](https://app.zenhub.com/workspaces/core-621e46b4d7103800171d1b02/issues/gh/metamask/core/1022)

make getEIP1559Compatibility async

---

package.json
packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/package.json

Revert "Release/43.0.0"

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This is just a follow up to add a test for the `restoreLedgerKeyring` method.

Restore Ledger Keyring test

---

packages/controller-utils/package.json
packages/controller-utils/src/index.ts
packages/controller-utils/src/logger.ts
packages/controller-utils/src/siwe.test.ts
packages/controller-utils/src/siwe.ts
packages/message-manager/src/PersonalMessageManager.test.ts
packages/message-manager/src/PersonalMessageManager.ts
yarn.lock

**Add SIWE detection method to `controller/utils`**
- This PR aims to move `detectSIWE` (https://github.com/MetaMask/metamask-extension/blob/cedef121a36184cde4eae448ef510733fa301072/shared/modules/siwe.js#L34) method into `controller/utils` so that `PersonalMessageManager` can consume it and potentially be used both on mobile and extension in the future.  
- There will be a following PR for the extension to consume this method from `controller/utils` and delete the duplicated code within the extension. 
- ADDED:
- Adds SIWE detection support for PersonalMessageManager
- Adds detectSIWE helper to `controller/utils`
**Checklist**

feat: Add SIWE detection support for PersonalMessageManager

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/ens-controller/CHANGELOG.md
packages/ens-controller/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/permission-controller/CHANGELOG.md
packages/permission-controller/package.json
packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json

Releases changes between `43.0.0` and `44.0.0`

Release 44.0.0

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/phishing-controller/CHANGELOG.md
packages/phishing-controller/package.json

See the changelog for more details

Release 45.0.0

---

packages/network-controller/tests/provider-api-tests/shared-tests.ts

A network client test description has been updated to reflect what the test is demonstrating. The current description contradicts the test.
N/A

Fix test description

---

packages/assets-controllers/CHANGELOG.md
packages/controller-utils/CHANGELOG.md
packages/message-manager/CHANGELOG.md

A previous changelog release had changes left as uncategorized. This PR aims to solve that

fix changelog

---

packages/keyring-controller/src/KeyringController.test.ts

This PR groups KeyringController's tests by target method.
_Note: Even if they are now grouped by the "targeted" method, some of them still rely on multiple KeyringController methods; this makes it harder to identify sources of failures, but that goes beyond this PR's scope._
- **CHANGED**: Tests order and groups
* Fixes #1152

Change tests structure in core KeyringController

---

packages/network-controller/tests/NetworkController.test.ts

The network controller `lookupNetwork` unit tests have been refactored to be more similar to the extension unit tests.
None
This relates to #1200

Refactor `lookupNetwork` unit tests

---

packages/network-controller/tests/NetworkController.test.ts

The network controller unit tests have been refactored to simplify the setup steps related to the controller messenger. The messenger is now constructed by the `withController` helper function, rather than being manually setup in each test that references it.
The `waitForPublishedEvents` helper function has been simplified as well. It now matches the extension implementation more closely.
None
Relates to https://github.com/MetaMask/core/issues/1197

Simplify network controller unit test setup

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR changes the returned object of `addNewAccount` method from KeyringController. The method now returns the added account address along with the keyring current mem state.
- **BREAKING**: Changed `addNewAccount` returned object
* Fixes #1243

Change addNewAccount return object

---

packages/network-controller/tests/fake-provider-engine.ts

In some NetworkController unit tests it is useful to mock a network request, but then do something before the request completes, such as switching the network while `net_version` is being requested. On the extension side we've solved this by allowing a `beforeCompleting` option to be specified when providing the network request stub. This commit copies that same option.
N/A
Reduces the scope of #1116

Add beforeCompleting option to FakeProviderStub

---

package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json

Release the following packages only:
- `@metamask/signature-controller@1.0.0`
- `@metamask/message-manager@4.0.0`

Release 50.0.0

---

packages/network-controller/tests/NetworkController.test.ts

The `lookupNetwork` tests have been refactored in preparation for reusing these test cases for other methods (in #1318). The two separate blocks for Infura v.s. custom networks have been consolidated into one block, and some tests have been modified to no longer test for the absence of events (instead asserting the expected end-state expected).
None
This relates to #1210

Refactor `lookupNetwork` tests

---

.github/workflows/publish-release.yml

whoops :shrug: 
i put the announce on the wrong job in #1328 so this fixes that by adding it to the dry-run

announce on the dry-run, not the actual deploy

---

packages/network-controller/tests/NetworkController.test.ts

The "lookup network" function is called internally in multiple methods, and has a wide range of impacts. This has led to increasingly verbose tests and inconsistencies in coverage.
All tests related to the lookup network step have been consolidated in a helper function. This helper function is invoked separately for each method that internally calls `lookupNetwork` (and for the tests that call `lookupNetwork` directly). The one exception to this is `rollbackToPreviousProvider`, which is not tested using this helper function due to difficulties in abstracting the necessary test setup.
None
This relates to #1210

Refactor `lookupNetwork` test cases

---

package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json

Immediate release for `signature-controller`

Release 52.0.0

---

packages/network-controller/tests/NetworkController.test.ts

This makes it easier to visually compare differences in the
NetworkController unit tests between extension and this repo.
(None)

Sync NetworkController.destroy tests w/ extension

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json

Release new minor version of `approval-controller`.
See changelog for details.

Release 54.0.0

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/logging-controller/CHANGELOG.md
packages/logging-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/package.json

Release 55.0.0

---

packages/network-controller/tests/NetworkController.test.ts

The "happy path" test for NetworkController's `getEthQuery` action verifies the behavior of the action by mocking the `eth-query` module to return a fake EthQuery instance and asserting that the action returns this instance. While this is very straightforward, it ends up interfering with the provider initialization routine when the test is set up (as NetworkController uses `eth-query` under the hood to talk to the network, and now it's not doing anything). For some reason, this has no negative consequences here on the core side, but when this test is copied to the extension side, it fails to run for that reason.
Instead of mocking `eth-query`, we simply attempt to use the EthQuery instance that the `getEthQuery` action returns in order to talk to the network and verify that the result is …

Improve test for NC getEthQuery action

---

packages/network-controller/tests/NetworkController.test.ts

These tests exists within the test suite for the extension version of NetworkController, but not here.
Note that in this case, if no provider has been initialized, the provider and block tracker are undefined instead of null. This is due to slight differences in the constructor between this version and extension.
For reference, see the extension: https://github.com/MetaMask/metamask-extension/blob/63c402155d53b0575b23ef7bd8458116867dc722/app/scripts/controllers/network/network-controller.test.ts#L534
(None)

Add missing tests for getProviderAndBlockTracker

---

packages/network-controller/tests/NetworkController.test.ts

These tests were present on the extension side, but not here.
For reference, see the extension: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/network/network-controller.test.ts#L851
(None)

Add missing tests for getEIP1559Compatibility

---

packages/network-controller/tests/NetworkController.test.ts

This test is present on the extension side, but not here.
For reference, see the extension: https://github.com/MetaMask/metamask-extension/blob/a5c370cdfa6bb42ab0a2e8d78a6387aa1dd17758/app/scripts/controllers/network/network-controller.test.ts#L3931
(None)

Add missing upsertNetworkConfiguration test

---

.github/workflows/lint-build-test.yml

There is a low likelihood that building, linting, or validating the changelog will fail in different versions of Node. Out of the Node versions that we support, choose the least one to run these jobs.
(None)

Don't build/lint/check across Node versions

---

packages/network-controller/tests/NetworkController.test.ts

These tests did not reflect their descriptions in that a provider was supposed to have been set. That should now be the case.
(None)

Fix tests for NetworkController getEIP1559Compatibility

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json

Release 56.0.0

---

.github/pull_request_template.md
docs/contributing.md

This repo contains a PR template to help contributors understand how to fill out the description for a new PR. The template is intended more for reference, however, and so it does not go into detail on the differences between the Description and Changes sections. This leads to PR descriptions that lack the detail that the Shared Libraries team would prefer in order to
ensure that pull requests can be reviewed more thoroughly and that changelogs can be compiled more quickly and contain more high-quality information after a release is issued.
This commit attempts to improve pull request descriptions going forward by adding a new section to the Contributing document. It also updates the pull request template to:
- Rename Description to Explanation so as not to overload the term "description" …

Encourage better PR descriptions

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json

This reverts commit 24f306c036279e3c5691a020b18c8862cfcb55ce.

Revert "Release/57.0.0 (#1430)"

---

package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json

Release 59.0.0

---

.github/workflows/main.yml

Updates actionlint to support new field used in #1452 .
Targeting: #1452.
Fixes: https://github.com/MetaMask/core/actions/runs/5384764744/jobs/9773066321?pr=1452

ci: rhysd/actionlint v1.6.25

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json

Release 61.0.0

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json

Release:
- `@metamask/approval-controller`
- `@metamask/signature-controller`
- `@metamask/message-manager`
- `@metamask/controller-utils`
See change logs for details.

Release 63.0.0

---

package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/package.json

Release 64.0.0

---

packages/base-controller/src/ControllerMessenger.test.ts
packages/base-controller/src/ControllerMessenger.ts

Controller messenger subscribers can no longer interrupt the flow of execution when they throw an error. Instead, any errors from a subscriber are thrown in a timeout hander. This ensures that the errors are still logged to the console and captured by Sentry without breaking the controller the event was published from.
Event subscribers should never throw. Any case where it does throw is a bug that may leave the wallet in an unrecoverable state. Originally we decided to not prevent event publishing from throwing because we want to be certain this never happens, and letting the error bubble up seemed like the "noisiest" way of handling it.
However, we've found that the current strategy does inadvertently make these errors hard to discover sometimes. If the method that triggered the event …

Prevent event publish from throwing error

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/base-controller/CHANGELOG.md
packages/base-controller/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json

Release 65.0.0

---

.github/workflows/main.yml

When creating a new release branch via `create-release-branch`, it is common for an engineer to add a new commit to the branch to adjust the changelogs and then push up the branch. Due to how GitHub works and how we've set up this repo, this results in creating a PR with the title "Release/X.Y.Z", and that will be the final commit message when the PR is squashed & merged. Unfortunately a commit called "Release/X.Y.Z" is not considered a release commit by our `is-release` release action, as we've configured it to recognize "Release X.Y.Z" (note the lack of slash), and so this will not result in a new release being published.
To address this, this commit adds "Release/X.Y.Z" as a valid release commit message.
This process bug came up a while back in Slack. Search for "skipping release job" …

Extend set of allowed release commit messages

---

packages/assets-controllers/src/TokenRatesController.test.ts

Missing test cases found in #1512 have been added.
N/A
None

Add additional `TokenRateController` tests

---

packages/assets-controllers/src/TokenListController.test.ts
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts
packages/transaction-controller/src/TransactionController.test.ts

fixes #1462 
Added selectedNetworkClientId to network controller state
- **ADDED**: selectedNetworkClientId to network controller state

Added selectedNetworkClientId to network controller

---

package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json

Release 70.0.0

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

As making calls to Keyrings directly is unsafe as changes are not reflected to `EthKeyringController` and `KeyringController` states, we need a way to manually trigger an update of persisted and memory keyrings from `KeyringController`.
To do that, we can add a `persistAllKeyrings` which internally calls and returns `EthKeyringController.persistAllKeyrings`
* See https://github.com/MetaMask/metamask-extension/pull/20202#discussion_r1274873634
- **ADDED**: Added `persistAllKeyrings` method

Add `persistAllKeyrings` method

---

packages/network-controller/src/NetworkController.ts

getLatestBlock should always use network clients from the registry

---

package.json
packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/package.json

New release of PreferenceController to add another preference for security alerts.

Release 72.0.0

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

The extension `TransactionController` persists in a `blockTimestamp` value for each confirmed transaction. The reason for including this property in the transaction state in the core is to support the unification initiative between the core and extension.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1073
- **ADDED**:  add `blockTimestamp` to the transaction state and persists the value for each confirmed transaction

Persist blockTimestamp to transaction state

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils.ts

This PR aims to implement `updateTransactionGasFees` to controller public API.
It also introduces gas related interfaces to `TransactionMeta` and `Transaction` types. 
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1099
- **ADDED**: Add `updateTransactionGasFees` public method to `TransactionController`

Add `updateTransactionGasFees` public method

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/ens-controller/package.json
packages/gas-fee-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/selected-network-controller/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
yarn.lock

Release 77.0.0

---

packages/controller-utils/src/constants.ts
packages/network-controller/tests/NetworkController.test.ts

Updated linea goerli explorer url.

fix: update linea goerli explorer url

---

packages/keyring-controller/src/KeyringController.ts

As some keyrings support `options: Record<string, unknown>` as the last optional argument of the [`signTransaction` method](https://github.com/MetaMask/utils/blob/4589c755e3005024c9071dd0c23c933335c3efa4/src/keyring.ts#L145), and [EthKeyringController as well](https://github.com/MetaMask/KeyringController/blob/fade19ef6df884eba037f7406eb3dea95549effa/src/KeyringController.ts#L392C16-L392C16), we should add this to KeyringController too - so that clients are able to pass it downstream.
* Fixes #1788 
- **FIXED**: `signTransaction` now accepts an optional `opts: Record<string, unknown>` argument to support `signTransaction` from `Keyring` type

Add `opts` argument to `signTransaction`

---

packages/transaction-controller/src/TransactionController.ts

If a transaction fails just after it's added to a block, we initially default to marking the transaction as confirmed (success). Here, we are adding an extra check that verifies status before confirming.
https://github.com/MetaMask/metamask-mobile/issues/6834
https://github.com/MetaMask/metamask-mobile/pull/7350
- **ADDED**: Call `checkTxReceiptStatusIsFailed` after transaction is added to a block

verify transaction status before confirming

---

packages/assets-controllers/src/NftDetectionController.ts
packages/network-controller/src/index.ts

this is to fix this error when making preview build: https://github.com/MetaMask/core/actions/runs/6616880359
- **ADDED**: export NetworkClient from create-network-clien
- **FIXED**: import NetworkClient from exported package instead of `network-controller/src/...`

import from dist not src

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/package.json
packages/permission-controller/package.json
packages/queued-request-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Small release to get a new approval controller feature out and unblock an ongoing snaps release.

Release 83.0.0

---

merged-packages/json-rpc-engine/package.json
packages/eth-json-rpc-provider/package.json

Removes some unused prepack scripts that fail when trying to release.

Remove unused prepack scripts

---

packages/polling-controller/src/index.ts

- **ADDED**: export for PollingControllerOnly

Added export for PollingControllerOnly

---

.eslintrc.js
packages/network-controller/tests/provider-api-tests/helpers.ts
packages/phishing-controller/src/utils.test.ts

We don't need to disable this rule; we can honor it instead.
Fixes #1924.
(No consumer-facing changes)

Re-enable import/no-named-as-default-member

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

This PR adds `updatePreviousGasParams` public method which is used in the extension UI.
Fixes the final part of https://github.com/MetaMask/MetaMask-planning/issues/962
- **Added**: Add `updatePreviousGasParams` public method to `TransactionController`

Add `updatePreviousGasParams` to `TransactionController`

---

packages/network-controller/package.json
yarn.lock

Update dependency `@metamask/eth-json-rpc-middleware` in network controller.
MetaMask/MetaMask-planning#1461

Update @metamask/eth-json-rpc-middleware in network controller

---

.github/workflows/publish-release.yml

Currently, when publishing a new release of the monorepo, an attempt is made to publish packages whose versions have not changed and therefore do not need publishing. This causes the `publish-npm` step in the release workflow to appear to fail, which can be seen by looking at any recent release of the monorepo ([this one][1], for instance).
This problem is solved in the current version of `action-npm-publish`, but we are not using this version consistently: we are using it for the dry run, but not for the "real" run.
This commit bumps this action to 4.x so that this problem goes away. I've confirmed this on a [fork of `core`][2] (this run also failed, but only because the NPM token was invalid; you should be able to see that it skipped all packages but the first).
[1]: …

Bump npm-publish action to 4.x

---

packages/transaction-controller/src/TransactionController.test.ts

This PR aims to mock `console.error` on particular unit test cases to keep console clean. 
- **Added**: Mock `console.error` in particular unit tests to keep console clean.

Mock console.error in particular `TransactionController` tests

---

packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.ts

NetworkClientConfiguration does not have the required information to make switch ethereum chaini word properly. The details required are actually inside of NetworkConfigurations, or if the network is an infura one, we fall back to using the networkClientConfiguration.
Branch of extension using this preview: https://github.com/MetaMask/metamask-extension/tree/queue-nickanme-fix-preview
- **FIXED**: NetworkConfigurations wiill be used in place of NetworkClientConfgurations when possible.

Fix network nicknames

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/signature-controller/CHANGELOG.md
packages/signature-controller/package.json
yarn.lock

Release 92.0.0

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

This PR adds an `updateEditableParams` method which allows the clients to update specific properties in the `TransactionParams`. 
#Fixes (task will be converted to issue soon)
- **ADDED**: `updateEditableParams`  method to allow clients to update specific transaction parameters.

Add `updateEditableParams` in Transaction Controller

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/types.ts
packages/network-controller/CHANGELOG.md
packages/network-controller/jest.config.js
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

Currently, if you have the ID of a network client for a custom network and you want to get information like the ticker or nickname for that network, you have to have a reference to the network controller so you can look up that network client ID in the list of network configurations. It's very roundabout, and we can do better.
This commit introduces a method on NetworkController, `getNetworkConfigurationByNetworkClientId`, that can be used to retrieve the network configuration that corresponds to a custom network given a network client ID. Although the concept of a network configuration was created for custom networks, this method also works for a built-in network client ID by constructing a "fake" network configuration.
This commit also introduces a controller action so that the network …

Add getNetworkConfigurationByNetworkClientId

---

package.json
packages/address-book-controller/package.json
packages/assets-controllers/package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/ens-controller/package.json
packages/gas-fee-controller/package.json
packages/logging-controller/package.json
packages/message-manager/package.json
packages/network-controller/package.json
packages/permission-controller/package.json
packages/phishing-controller/package.json
packages/polling-controller/package.json
packages/preferences-controller/package.json
packages/queued-request-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Release 95.0.0

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

Release 105.0.0

---

packages/assets-controllers/src/AssetsContractController.test.ts

The `AssetsContractController` tests now use mocks rather than real `PreferencesController` instances. This should make the tests easier to read, and it decouples the `PreferencesController` further from the asset controllers.
No changes

refactor(assets-controllers): Simplify `AssetsContractController` tests

---

packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
packages/transaction-controller/src/utils/gas.test.ts

Fixes the PendingTransactionTracker specs. The specs should probably be cleaned up to use a helper rather than relying on mocking in beforeEach

Fix pendingTx spec

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

* Change `onBootCleanup` to submit approved tx for all chains, not just currently selected
* Add `chainId` fallback to `getEthQuery`
* Fixes https://github.com/MetaMask/MetaMask-planning/issues/1893

Transaction multichain onBootCleanup all chains

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/tsconfig.build.json
packages/transaction-controller/tsconfig.json

fix broken tests

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

* Add optional networkClientId to start/stopIncomingTransactionPolling and updateIncomingTransactions
* if not provided, action applies to _all_ incomingTransactionHelpers
See https://github.com/MetaMask/MetaMask-planning/issues/1894

Jl/mmp 1894/transaction multichain incoming transaction network client

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

* Update `startIncomingTransactionPolling`, `stopIncomingTransactionPolling`, `updateIncomingTransactions`
* Accepts optional networkClientIds array 
* targets global IncomingTransactionHelper if no networkClientIds provided
* Add `stopAllIncomingTransactionPolling`
* Add specs for above methods
* Update specs to return unique mocked helper instances rather than singleton

Jl/mmp 1889/transaction multichain incoming transaction tests

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts

* Add missing mocked rpc requests
* Add missing ApprovalController

Fix first TransactionController Integration spec

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts

Transaction multichain integration

---

packages/transaction-controller/src/TransactionController.ts

use correct nonce tracker for approve transaction

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/helpers/PendingTransactionTracker.ts

Transaction multichain lifecycle

---

packages/network-controller/src/create-network-client.ts
packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/helpers/EtherscanMocks.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
packages/transaction-controller/src/utils/etherscan.ts
yarn.lock

* Add `startIncomingTransactionPolling` spec
* Add `stopIncomingTransactionPolling` spec
* Add `stopAllIncomingTransactionPolling` spec
* Add `updateIncomingTransactions` spec
* Instantiate `EtherscanRemoteTransactionSource` per `IncomingTransactionTracker`

Add initial IncomingTransactionPolling integration spec 

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts

Transaction multichain multiple networks

---

packages/transaction-controller/src/TransactionController.ts

* Cleanup updateGasProperties
* Use chainId from txMeta instead of the providers

Cleanup updateGasProperties

---

packages/transaction-controller/src/TransactionController.ts

* Fix refreshing trackMap and EtherscanRemoteTransactionSourceMap 

Fix trackingMap and EtherscanRemoteTxSource maps removals

---

packages/transaction-controller/src/TransactionController.ts

remove getNetworkClientIdForDomain

---

packages/transaction-controller/src/TransactionController.ts

Fix pending tx options mutlichain instantiation

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts

Added feature flag for multichain

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts

change getNetworkState to getChainId for IncomingTxHelper

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts

fix comment

---

packages/transaction-controller/src/TransactionController.ts

remove another comment

---

packages/transaction-controller/src/TransactionController.ts

only poll for pending transactions on base pendingTransactionTracker when networkController state changes occur

Fix pendingTransaction polling listener

---

packages/transaction-controller/src/TransactionController.ts

* Move all # private methods below the public ones in TransactionController

move # private to bottom of TxController

---

packages/transaction-controller/src/TransactionController.ts

Modify cancel transaction rate

---

packages/transaction-controller/src/TransactionController.ts

* Make some properties and methods # private

Make properties and methods # private

---

packages/transaction-controller/src/TransactionController.ts

remove @type

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts

* Remove feature flag setter
* Rename `enableMultichain` to `isMultichainEnabled`

Rename to isMultichainEnabled. Remove setter

---

packages/transaction-controller/src/TransactionController.ts

* Add and export `TransactionControllerOptions` type
* Export existing option types

Add TransactionControllerOptions

---

packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts

The current number of requests queued by the `QueuedRequestController` is currently stored as a private instance variable and exposed by the `length` method and the `countChanged` event. This works, but the conventional way of tracking and sharing state is to use controller state. This is what controller state is for, and more broadly this is why controllers exist: to manage state.
To better align with our conventions, the requests queue length has been migrated into controller state. It is now represented by the state property `queuedRequestCount`.
The old `length` method and `countChanged` event remains, but they have been marked as deprecated. They can be removed in a future release.
Additionally, types have been added for the built-in `stateChanged` event and `getState` action.
This …

refactor(queued-request-controller): Migrate request count to state

---

packages/approval-controller/package.json
packages/assets-controllers/package.json
packages/json-rpc-engine/package.json
packages/network-controller/package.json
packages/permission-controller/package.json
packages/queued-request-controller/package.json
packages/rate-limit-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This bumps `@metamask/rpc-errors` to `^6.2.0` to solve a type error when using `@metamask/permission-controller`:
```
node_modules/@metamask/permission-controller/dist/errors.d.ts:22:107 - error TS7016: Could not find a declaration file for module '@metamask/rpc-errors/dist/utils'. '/Users/morten/Development/MetaMask/snaps/node_modules/@metamask/rpc-errors/dist/utils.js' implicitly has an 'any' type.
```
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.
- **CHANGED**: Bump …

Bump `@metamask/rpc-errors` to `^6.2.0`

---

.github/workflows/ensure-blocking-pr-labels-absent.yml

The `DO-NOT-MERGE` label is designed to prevent other people from merging a PR (perhaps because it is blocking another PR or for some other reason). In reality, however, this is merely an alert, and it is still possible for a PR which has this label to be merged.
This commit adds a GitHub workflow which runs when opening a PR or changing the labels for a PR and fails if the PR has a `DO-NOT-MERGE` label. Once this workflow is in place, the
`ensure-block-pr-labels-absent` check can be added to the branch protection settings to truly enforce that a PR cannot be merged while the label is in place.
The extension has a similar check: https://github.com/MetaMask/metamask-extension/blob/275523a24e4f496384943f107369810cd93aa86e/.github/workflows/check-pr-labels.yml. I simplified the workflow. …

Add workflow to check presence of DO-NOT-MERGE

---

.github/workflows/ensure-blocking-pr-labels-absent.yml

Updating a branch against its base branch from the GitHub UI seems to reset the status of the `ensure-blocking-pr-labels-absent` check, but since it only runs when a PR is opened or when labels are added or removed, it won't get run again, keeping the PR in limbo. Adding `synchronize` to the list of actions fixes this.
(N/A)

Check labels for a PR when it is updated

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts

In this test, it seems that two `eth_sendRawTransaction` requests are occurring when only one transaction was added. I am not 100% sure why this is, but we've seen this type of problem in tests that use a combination of HTTP requests mocked via Nock as well as the block tracker, so my best guess is that there is some state which is not cleaned up correctly and is therefore bleeding into other tests. The solution to add an extra request mock is a bit of a band-aid, but considering that we haven't seen this problem for any other test, it should fix it for the time being.
Fixes #4054.
(N/A)

Fix intermittently failing TransactionController test

---

packages/assets-controllers/src/token-prices-service/codefi-v2.ts

Updates the jsdoc for const `SUPPORTED_CHAIN_IDS` to mention it is used by `CodefiTokenPricesServiceV2`
N/A

fix: jsdoc update

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/constants.ts
packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.ts
packages/transaction-controller/src/helpers/GasFeePoller.test.ts
packages/transaction-controller/src/helpers/GasFeePoller.ts
packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/layer1-gas-fee-flow.test.ts
packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts
yarn.lock

This PR implements and activates `OptimisimLayer1GasFeeFlow` for Optimisim based transactions.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1944
- **ADDED**: Implement and activate `OptimisimLayer1GasFeeFlow` for Optimisim based transactions

feat: implement `OptimismLayer1GasFeeFlow`

---

packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

Add GasFeeController and TransactionController to release

---

package.json
packages/assets-controllers/package.json
packages/ens-controller/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/polling-controller/package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This reverts commit 1b11436cef3195290d700198bc31356ccda5a756. This release PR had an improperly formatted title and was missing a package.
(None)

Revert "Release v133.0.0 (#4111)"

---

packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR is a step necessary for [this changes](https://github.com/MetaMask/core/pull/4182) to work. Some of our public functions (that mutate state) call other public function (which also mutate state): when those will be behind a mutex, it will cause a deadlock.
Functionality and API should be unchanged.
* Related to #4182
* Related to https://github.com/MetaMask/MetaMask-planning/issues/2366
- **CHANGED**: Mutable public methods no longer call other mutable public methods internally

[keyring-controller] Avoid calling mutable public functions internally

---

packages/permission-controller/ARCHITECTURE.md

Copy edits to the permission controller's `ARCHITECTURE.md`.
None.

docs(permission-controller): Update ARCHITECTURE.md

---

packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

This PR goal is to add `useTransactionSimulations` to `PreferencesController`
* Fixing part of https://github.com/MetaMask/mobile-planning/issues/1720
- **ADDED**: Add `useTransactionSimulations` preference

Add `useTransactionSimulations` preference

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in NftController to get the currently selected chain, but `selectedNetworkClientId` can be used instead. This commit makes that transition so that we can fully drop `providerConfig`.
(Included in PR.)

NftController: providerConfig -> selectedNetworkClientId

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/constants.ts
packages/transaction-controller/src/errors.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/simulation-api.test.ts
packages/transaction-controller/src/utils/simulation-api.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts

This PR aims to add support of simulation data to transaction controller mobile patch.

Add simulation data support to mobile transaction controller patch

---

packages/accounts-controller/package.json
packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/tests/mocks.ts
packages/assets-controllers/package.json
packages/chain-controller/package.json
packages/keyring-controller/package.json
yarn.lock

Bump to latest `@metamask/providers`.
This is causing issues:
- https://github.com/MetaMask/keyring-api/issues/331
- **CHANGED**: Bump `@metamask/accounts-controller` from `^6.1.1` to `^6.4.0`  
- **CHANGED**: Bump `@metamask/assets-controller` from `^6.1.1` to `^6.4.0`  
- **CHANGED**: Bump `@metamask/chain-controller` from `^6.1.1` to `^6.4.0`  
- **CHANGED**: Bump `@metamask/keyring-controller` from `^6.1.1` to `^6.4.0`

deps: @metamask/keyring-api@^6.1.1->^6.4.0

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils.ts

This PR fixes couple edge cases in order to prepare `TransactionController` to support simulations.

fix: fix update transaction history on simulation update

---

package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
yarn.lock

**Patch release**
- `@metamask/selected-network-controller` to v15.0.1

Release 160.0.0

---

packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/chain-controller/package.json
packages/keyring-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Bumps `@metamask/keyring-api` to 8.0.0 and `@metamask/eth-snap-keyring` to 4.3.1.
- **CHANGED**: Bump @metamask/keyring-api from 6.4.0 to 8.0.0.
- **CHANGED**: Bump @metamask/eth-snap-keyring from 4.1.1 to 4.3.1.
- **CHANGED**: Bump @metamask/keyring-api from 6.4.0 to 8.0.0.
- **CHANGED**: Bump @metamask/keyring-api from 6.4.0 to 8.0.0.
- **CHANGED**: Bump @metamask/keyring-api from 6.4.0 to 8.0.0.
- **CHANGED**: Bump @metamask/keyring-api from 6.4.0 to 8.0.0.

chore(deps): bump @metamask/{keyring-api,eth-snap-keyring}

---

packages/assets-controllers/src/index.ts

Add the missing export TokenBalancesControllerState to the exported types in [assets-controllers]
* Fixes [#4534](https://github.com/MetaMask/core/issues/4534)
- **Added**:  Export `TokenBalancesControllerState` type.

fix: export TokenBalancesControllerState

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

Releases new version of `@metamask/notification-services-controller` & `@metamask/profile-sync-controller`. This adds fixes found in extension and infura SDK integration.

Release 178.0.0

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/chain-controller/CHANGELOG.md
packages/chain-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

- Contributes to #3651
- Follows from https://github.com/MetaMask/core/pull/3645
```md
- Bump `@metamask/snaps-sdk` from `^6.1.0` to `^6.1.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
- Bump `@metamask/snaps-utils` from `^7.8.0` to `^7.8.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
```
```md
- Bump `@metamask/snaps-controllers` from `^9.3.0` to `^9.3.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
- Bump `@metamask/snaps-sdk` from `^6.1.0` to `^6.1.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
- Bump `@metamask/snaps-utils` from `^7.8.0` to `^7.8.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
```
```md
- Bump `@metamask/snaps-controllers` from `^9.3.0` to `^9.3.1` ([#4547](https://github.com/MetaMask/core/pull/4547))
- Bump …
```

Bump `@metamask/snaps-{controllers,sdk,utils}` and remove yarn resolution for `@metamask/providers`

---

packages/assets-controllers/src/AssetsContractController.ts

- See https://github.com/MetaMask/core/issues/4072
```md
- Add public readonly property `name` to `AssetsContractController` and assign "AssetsContractController" as its value.
```

Add public `name` property to `AssetsContractController` class

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

Release Candidate v182. Includes patch updates & fixes to `@metamask/profile-sync-controller` and `@metamask/notification-services-controller`
N/A
See changelog diffs.

Initialize Release 182.0.0

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

Release proposal scoped for only `@metamask/transaction-controller`.

Release 183.0.0

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This is a release candidate for v195.0.0.
- `@metamask/profile-sync-controller@0.3.0`
- `@metamask/notification-services-controller@0.3.0`
```md
- Bump `@metamask/profile-sync-controller` from `^0.2.1` to `^0.3.0` ([#4643](https://github.com/MetaMask/core/pull/4657))
- Bump `@metamask/notification-services-controller` from `^0.2.1` to `^0.3.0` ([#4643](https://github.com/MetaMask/core/pull/4657))
```

Release 195.0.0

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR adds a `maxSyncInterval` for account syncing, that will prevent subsequent syncs after a successful one for a determined amount of time.
This will help attach the account sync "big sync" method to clients' contexts.
[NOTIFY-866](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-866)
- **ADDED**: Add throttling to account syncing
[NOTIFY-866]: https://consensyssoftware.atlassian.net/browse/NOTIFY-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add throttling to account syncing

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This is a release candidate for v196.0.0.
- `@metamask/profile-sync-controller@0.4.0`
- `@metamask/notification-services-controller@0.4.0`
```md
- Bump `@metamask/profile-sync-controller` from `^0.3.0` to `^0.4.0` ([#4661](https://github.com/MetaMask/core/pull/4661))
- Bump `@metamask/notification-services-controller` from `^0.3.0` to `^0.4.0` ([#4661](https://github.com/MetaMask/core/pull/4661))
```

Release 196.0.0

---

packages/accounts-controller/src/index.ts

- **ADDED**: export `AccountsControllerAccountRenamedEvent` type

chore: export `AccountsControllerAccountRenamedEvent` type

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This is a release candidate for version `203.0.0`. See the changelogs for more details.
- `@metamask/notification-services-controller@0.6.0`
- `@metamask/profile-sync-controller@0.7.0`
https://consensyssoftware.atlassian.net/browse/NOTIFY-1110
```md
- Bump `@metamask/notification-services-controller` from `^0.5.1` to `^0.6.0` ([#4710](https://github.com/MetaMask/core/pull/4710))
- Bump `@metamask/profile-sync-controller` from `^0.6.0` to `^0.7.0` ([#4710](https://github.com/MetaMask/core/pull/4710))
```

Release 203.0.0

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This is a release candidate for version `204.0.0`. See the changelogs for more details.
- `@metamask/notification-services-controller@0.7.0`
- `@metamask/profile-sync-controller@0.8.0`
https://consensyssoftware.atlassian.net/browse/NOTIFY-1117
```md
- Bump `@metamask/notification-services-controller` from `^0.6.0` to `^0.7.0` ([#4712](https://github.com/MetaMask/core/pull/4712))
- Bump `@metamask/profile-sync-controller` from `^0.7.0` to `^0.8.0` ([#4712](https://github.com/MetaMask/core/pull/4712))
```

Release 204.0.0

---

.github/pull_request_template.md

Update pull request template to encourage the creation of client pull requests before breaking changes are merged.

chore: add client pull requests to pull request template

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This is a RC for v205.0.0. See changelog for more details
- @metamask/notification-services-controller@0.8.0
- @metamask/profile-sync-controller@0.8.1
https://consensyssoftware.atlassian.net/browse/NOTIFY-1145
```ms
- Bump `@metamask/notification-services-controller` from `^0.7.0` to `^0.8.0` ([#4722](https://github.com/MetaMask/core/pull/4722))
- Bump `@metamask/profile-sync-controller` from `^0.8.0` to `^0.8.1` ([#4722](https://github.com/MetaMask/core/pull/4722))
```

Release 205.0.0

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/chain-controller/CHANGELOG.md
packages/chain-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/notification-controller/CHANGELOG.md
packages/notification-controller/package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/permission-controller/package.json
packages/preferences-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This is a RC for v208.0.0. See changelog for more details
Initial attempt:
- https://github.com/MetaMask/core/pull/4731
Revert of the failing 208.0.0:
- https://github.com/MetaMask/core/pull/4733
N/A

Release 208.0.0

---

packages/multichain/package.json

Added ESM exports for multichain package

Added exports for multichain package

---

packages/eth-json-rpc-provider/package.json
yarn.lock

- **deps(eth-json-rpc-provider): @metamask/rpc-errors@^6.3.1->^7.0.0**
- #4798 
- #4773 
- #4769 
- **CHANGED**: Update `@metamask/rpc-errors` from `^6.3.1` to `^7.0.0`

deps(eth-json-rpc-provider): @metamask/rpc-errors@^6.3.1->^7.0.0

---

yarn.config.cjs

These are not needed after:
- #4769
- #4769
Nothing

chore(constraints): remove resolved inconsistency exceptions

---

packages/phishing-controller/src/PhishingController.ts

The current C2 domain blocklist fetch interval is set to 15 minutes. After discussing with Samczsun, we determined it's best to lower this interval, as drainers have started switching C2s more quickly since C2 detection was rolled out. 
This update only affects the fetch interval for the C2 blocklist.
- **CHANGED**: Lowered the C2_DOMAIN_BLOCKLIST_REFRESH_INTERVAL from 15 minutes to 5 minutes.

chore: lower c2 blocklist fetch interval

---

packages/phishing-controller/src/PhishingDetector.test.ts
packages/phishing-controller/src/PhishingDetector.ts
packages/phishing-controller/src/utils.test.ts
packages/phishing-controller/src/utils.ts

Fixes General extension perfomance issues

fix: extension performance issues 

---

.github/CODEOWNERS

- Applies change that was intended to be included in https://github.com/MetaMask/core/pull/4750.
No user-facing changes.

Add `phishing-controller` to package release section of CODEOWNERS file

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokensController.ts

clean up PR for token autodetection controller
- **CHANGED**:  change some variables names

fix: clean-up token autodetection

---

packages/assets-controllers/src/TokensController.ts

If the `clientNetworkId` is provided in the parameters, it must be used to fetch the `chainId`. Failing to do so could lead to importing the wrong token when transitioning to multichain.
- **CHANGED**: use networkClientId passed on parameter should be used to get the chainId

fix: fix add tokens and take chainId from networkID if provided

---

packages/assets-controllers/src/TokensController.test.ts
packages/assets-controllers/src/TokensController.ts

The `ignoreTokens` function does not include `networkClientId` as a parameter, which can lead to errors when attempting to hide a token that belongs to a different chain. The function currently searches for tokens within the current chain only. To resolve this issue, the solution is to add `networkClientId` as a parameter, ensuring the function operates correctly across chains.
- **CHANGED**:  the function ignore tokens can take now networkClientId as optional parameter

feat: add networkClientId as param for func ignoreTokens

---

packages/transaction-controller/src/helpers/TransactionPoller.ts

Update the transaction polling variables.
While these are initially static constants, they will be controlled by remote feature flags in a subsequent PR.

chore: update transaction polling variables

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This reverts commit 704d3ce16b336faa2538024beb84cf5200ccc372.
This did not perform the release action as the squashed commit was invalid (it contained back-ticks).
N/A

Revert: "Release `257.0.0` (#4969)"

---

packages/user-operation-controller/CHANGELOG.md

The changelog for `@metamask/user-operation-controller` version `18.0.0` contains a typo. The entry for the version mistakenly mentions `@metamask/accounts-controller` instead of the correct package, `@metamask/transaction-controller`, for the bump.

chore: user-operation-controller changelog typo

---

packages/multichain/src/middlewares/multichainMethodCallValidator.test.ts
packages/multichain/src/middlewares/multichainMethodCallValidator.ts
packages/multichain/src/scope/types.ts

remove caip lifecycle method param types

---

packages/network-controller/package.json
yarn.lock

Bumping `@metamask/eth-json-rpc-middleware` from `^15.0.0` to `^15.0.1`
```
- Bump `@metamask/eth-block-tracker` from `^11.0.1` to `^11.0.3` ([#347](https://github.com/MetaMask/eth-json-rpc-middleware/pull/347))
```
* Related to https://github.com/MetaMask/metamask-extension/issues/17040
- **CHANGED**: Bump `@metamask/eth-json-rpc-middleware` from `^15.0.0` to `^15.0.1`

chore(deps): bump `@metamask/eth-json-rpc-middleware` to `^15.0.1`

---

packages/assets-controllers/package.json
yarn.lock

This peer dependency has been wrongly removed with my previous PR. I'm just re-adding it.
- https://github.com/MetaMask/core/pull/4695
N/A (will be unchanged for the next release)

fix(assets-controllers): fix missing peer dependency

---

package.json
packages/remote-feature-flag-controller/CHANGELOG.md
packages/remote-feature-flag-controller/package.json

Added support for threshold-based feature flag scoping in `remote-feature-flag-controller`
N/A
N/A

Release 271.0.0

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/validation.test.ts
packages/transaction-controller/src/utils/validation.ts

Add hex validation to the `gas` and `gasLimit` properties on `txParams`.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3826
- **ADDED**: Hex validation for `gas` and `gasLimit`

fix: Prevent invalid gas limit

---

eslint-warning-thresholds.json

The number of Prettier warnings has gone down by 3.
(N/A, developer-only change)

Update ESLint warning thresholds

---

package.json
packages/multichain/CHANGELOG.md
packages/multichain/package.json

This reverts commit 83eae03ce731ab036522bd0b890bd0b5238fd6f6 (Release v288.0.0)

Revert "Release/288.0.0 (#5184)"

---

packages/network-controller/src/rpc-service/rpc-service.test.ts
packages/network-controller/src/rpc-service/rpc-service.ts

Add a new `failoverService` option to RpcService. This allows consumers to forward the request to another RPC service in the event that an RPC endpoint is proven to be unreliable (i.e. after attempting the request 5 times, the endpoint is unreachable, returns a a non-200 response, or returns a response that is not JSON-decodable).
Closes #4992.
(N/A; RpcService is not public yet so no changelog updates)

Add failover support to RpcService

---

packages/assets-controllers/src/AccountTrackerController.test.ts
packages/assets-controllers/src/AccountTrackerController.ts
packages/assets-controllers/src/AssetsContractController.test.ts
packages/assets-controllers/src/AssetsContractController.ts
packages/assets-controllers/src/CurrencyRateController.test.ts
packages/assets-controllers/src/CurrencyRateController.ts
packages/assets-controllers/src/MultichainBalancesController/MultichainBalancesController.test.ts
packages/assets-controllers/src/MultichainBalancesController/MultichainBalancesController.ts
packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts
packages/assets-controllers/src/RatesController/RatesController.test.ts
packages/assets-controllers/src/RatesController/types.ts
packages/assets-controllers/src/TokenBalancesController.test.ts
packages/assets-controllers/src/TokenBalancesController.ts
packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts
packages/assets-controllers/src/TokenListController.test.ts
packages/assets-controllers/src/TokenListController.ts
packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts
packages/assets-controllers/src/TokensController.test.ts
packages/assets-controllers/src/TokensController.ts

Rename `ControllerMessenger` to `Messenger` in the `@metamask/assets-controllers` package.

chore(assets): Rename `ControllerMessenger` to `Messenger`

---

packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/multichain-transactions-controller/CHANGELOG.md
packages/multichain-transactions-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This PR bumps:
- `@metamask/keyring-api` from `^16.1.0` to `^17.0.0` [CHANGELOG](https://github.com/MetaMask/accounts/blob/main/packages/keyring-api/CHANGELOG.md#1700)
- `@metamask/eth-snap-keyring` from `^9.1.1` to `^10.0.0` [CHANGELOG](https://github.com/MetaMask/accounts/blob/main/packages/keyring-snap-bridge/CHANGELOG.md#1000)
See CHANGELOG for changes

chore: bump `@metamask/{keyring-api,eth-snap-keyring}`

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts

Our constructor fired account calls even when the wallet was locked.
We added similar logic as push notifications to ensure we only make the initialise call after the wallet is unlocked.
N/A
- **ADDED**: lock conditional checks when initialising accounts inside the NotificationServicesController
- **ADDED**: accounts initialise call when the wallet is unlocked

feat: better handle notification account tracking on wallet unlock

---

eslint-warning-thresholds.json
packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts

The previous approach used `Math.floor()` for bucket assignment
```
const bucketIndex = Math.floor(value buckets);
distribution[bucketIndex === buckets ? buckets - 1 : bucketIndex] += 1;
```
This created edge case issues where values near bucket boundaries (like 0.299 vs 0.301) could fall into different buckets. With random number generation, these edge cases would sometimes cluster differently between test runs, causing sporadic failures.
- 0.299 → bucket 2
- 0.301 → bucket 3
(Even though they're very close values)
While the new approach consistently handles them:
- 0.299 → explicitly in range [0.2, 0.3]
- 0.301 → explicitly in range [0.3, 0.4]
Key improvements:
1. **Explicit Range Boundaries**: Clear `min` and `max` values for each range, eliminating ambiguity at boundaries
2. **Better …

fix(5383): flaky user-segmentation-utils distribution test fix

---

package.json
yarn.lock

This PR bumps `@metamask/create-release-branch` to `^4.1.0`

chore: bump `@metamask/create-release-branch` to `^4.1.0`

---

packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.test.ts
packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.ts

Currently we do not support annonucements on multiple platforms (e.g. the recent "Update" announcement did not go live due to this and we needed to quickly split the announcement into separate ones for portfolio and extension).
This uses the `[in]` query from contentful to allow us to fetch shared announcements.
E.g. if there is an announcement for portfolio and extension, then we will correctly fetch it.
- **FIXED**: Fetch feature announcements that are shared across different platforms (portfolio/extension/mobile)

fix: add support for fetching shared announcements cross platforms

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

Updating to latest version of the shared workflow

fix(actions): Update to latest version of shared workflow

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

Missed content permissions. Adding them now.

Fix contents permissions

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

Updating to use token which will hopefully help correct the current error.

fix(actions): update token to the token setup for adding PRs

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts
packages/transaction-controller/src/constants.ts
tests/mock-network.ts

Revert "feat: add `MegaEth Testnet` as default network"

---

packages/transaction-controller/CHANGELOG.md

[Recently merged PR](https://github.com/MetaMask/core/pull/5394/files) unintentionally added changelog entries into already released section, this PR aims to fix that.
* Related to https://github.com/MetaMask/core/pull/5394/files
No changelog entry needed.

fix: Adjust changelog

---

packages/keyring-controller/CHANGELOG.md

After releasing `@metamask/keyring-controller@19.2.2`, the main changelog needs to be updated to include the backport release
N/A

chore: update changelog after backport release

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/simulation.ts

Simulate type-4 transactions using a code override in order to verify the impact of any included `data`.
Relates to: [#4506](https://github.com/MetaMask/MetaMask-planning/issues/4506)

fix: type-4 transaction simulation

---

packages/keyring-controller/CHANGELOG.md

These `@metamask/keyring-controller` releases are being deprecated because they are affected by [this issue](https://github.com/MetaMask/core/issues/5532):
- 19.2.0
- 19.2.1
- 20.0.0
- 21.0.0
- **DEPRECATED**: Versions 19.2.0, 19.2.1, 20.0.0, 21.0.0

chore: deprecate `@metamask/keyring-controller` versions

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/types.ts

Add the property occurrences to the bridge token model
Fixes: [mms-1799](https://consensyssoftware.atlassian.net/browse/MMS-1799)
- Occurrences added to BridgeToken type

chore: mms-1799 Bridge Token Occurrences

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/types.ts

Add transaction type to identify payment transactions used in gasless functionality.

chore: add gas payment transaction type

---

package.json
packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/package.json
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/CHANGELOG.md
packages/user-operation-controller/package.json
yarn.lock

Major releases of:
- `@metamask/transaction-controller`
- `@metamask/bridge-controller`
- `@metamask/bridge-status-controller`
- `@metamask/user-operation-controller`

Release 348.0.0

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/batch.ts
packages/transaction-controller/src/utils/validation.ts

This PR aims to pass the `origin` for batch transactions. Additionally, skip the origin validation based on the `batch` type.
Fixes https://github.com/MetaMask/metamask-extension/issues/31516

skip origin validation for batch transactions

---

packages/keyring-controller/src/KeyringController.ts

add comment to `useCachedKey` condition
Related to none

chore: add comment to `useCachedKey` condition

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

Workflow was updated in github tools to allow for non-filtered adding of issues. This just updates to the latest workflow

Update to use latest workflow

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/batch.ts
packages/transaction-controller/src/utils/validation.test.ts
packages/transaction-controller/src/utils/validation.ts

- Prevent external calls to internal accounts only if data included.
- Query alternate chains in parallel in `isAtomicBatchSupported` method.
- Use new error codes for:
- Duplicate batch ID.
- Batch size limit.

feat: enhance batch support

---

.github/workflows/main.yml

Related to https://github.com/MetaMask/core/pull/5709, this allows concurrency on main branches to allow semantic releases.

CHANGED - allow concurrency on main

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/tests/mocks/mockEncryptor.ts

The `MockEncryptor` class used in  `KeyringController.test.ts` uses a `cacheVal` variable declared outside of the class. This causes tests to reuse the value and be interdependent.
* Fixes https://github.com/MetaMask/core/issues/5744
The `no-changelog` has been added, because there are no consumer-level changes

test: fix mock encryptor test shared global state

---

.github/CODEOWNERS

The package is now co-maintained by the accounts team and the wallet framework team.
N/A

chore: Update keyring-controller ownership

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/types.ts

- Added `lendingDeposit` to `TransactionTypes` in `@metamask/transaction-controller`

feat: added lendingDeposit to TransactionTypes

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/DeFiPositionsController/fetch-positions.ts

Updates the URL for the defi position API to use the production deployment, which was unavailable before.

chore: update defi api url

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/types.ts
packages/bridge-controller/tests/mock-quotes-sol-erc20.json
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/bridge-status-controller.ts

Updates the QuoteResponse type to match the bridge-api's response
Fixes https://consensyssoftware.atlassian.net/browse/MMS-2402

chore: rename bridgePriceData -> priceData

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts
packages/transaction-controller/src/utils/feature-flags.test.ts
packages/transaction-controller/src/utils/feature-flags.ts

Add feature flag to configure incoming transactions polling interval remotely.

feat: add feature flag for incoming transactions polling interval

---

packages/bridge-controller/src/utils/validators.test.ts

This PR adds a test for extra fields in the Bridge feature flags response.
Related to https://github.com/MetaMask/core/pull/5834

chore: add a test for extra fields in validator

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/index.ts
packages/bridge-controller/src/utils/feature-flags.test.ts
packages/bridge-controller/src/utils/feature-flags.ts

This PR consumes the new `bridgeConfigV2` field from LaunchDarkly.
Related to #5834, #5835

chore: update bridge config to v2

---

.github/CODEOWNERS
README.md
packages/error-reporting-service/CHANGELOG.md
packages/error-reporting-service/LICENSE
packages/error-reporting-service/README.md
packages/error-reporting-service/jest.config.js
packages/error-reporting-service/package.json
packages/error-reporting-service/src/error-reporting-service.test.ts
packages/error-reporting-service/src/error-reporting-service.ts
packages/error-reporting-service/src/index.ts
packages/error-reporting-service/tsconfig.build.json
packages/error-reporting-service/tsconfig.json
packages/error-reporting-service/typedoc.json
teams.json
tsconfig.build.json
tsconfig.json
yarn.lock

This package makes it possible for any module to report an error to an error reporting app (such as Sentry). The exact mechanism to do so is customizable, and the service object exposes a messenger action so that modules can report the error without needing direct access to the service object itself.
Fixes https://github.com/MetaMask/core/issues/5545.

Add `@metamask/error-reporting-service`

---

package.json
packages/address-book-controller/CHANGELOG.md
packages/address-book-controller/package.json
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

This reverts commit 3c94dddf3a8fa63f1bb82cd8f8bef2e6ab1602ea.

Revert "Release 422.0.0 (#5904)"

---

package.json
packages/foundryup/CHANGELOG.md
packages/foundryup/package.json

This reverts commit c1b21eaa693756c8bd6f16dc41f88532e1d0cda0.

Revert "Release/423.0.0 (#5907)"

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/utils/__snapshots__/fetch.test.ts.snap
packages/bridge-controller/src/utils/fetch.test.ts
packages/bridge-controller/src/utils/fetch.ts
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/utils/__snapshots__/validators.test.ts.snap
packages/bridge-status-controller/src/utils/validators.ts

Improves response validation traces by logging all invalid fields. Currently the logs only include the first detected failure. View test snapshot updates to see how this changes the logged data

chore: log all bridge-api validation errors

---

packages/transaction-controller/CHANGELOG.md

Move entry to correct release.

chore: fix transaction controller changelog

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/__snapshots__/bridge-controller.test.ts.snap
packages/bridge-controller/src/bridge-controller.test.ts
packages/bridge-controller/src/bridge-controller.ts
packages/bridge-controller/src/utils/snaps.ts

Fixes
- snap call can block quote fetching
- excessive snap getMinimumBalanceForRentExemption calls

fix: bridge getMinimumBalanceForRentExemption params and blocking fetch

---

packages/account-tree-controller/src/AccountTreeController.ts

Use proper type `metadata` type for `AccountWallet`.
N/A
N/A

fix(account-tree-controller): fix `AccountWallet` type

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.ts

feat(account-tree-controller): add missing `stateChange` event to `AccountTreeControllerEvents`

---

packages/phishing-controller/CHANGELOG.md
packages/phishing-controller/src/types.ts

Adds 'Verified' to `RecommendedAction`. This will empower extension and mobile to show trust signals for dapps.

feat: `Verified` added to `RecommendedAction`

---

packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/utils/transaction.test.ts
packages/bridge-status-controller/src/utils/transaction.ts

fix: parse tx signature from onClientRequest response

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/index.ts

Adding missing exports.
N/A
N/A

fix(account-tree-controller): missing exports

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts
packages/account-tree-controller/src/names.ts

Align naming based on the design specs.
N/A
N/A

fix(account-tree-controller): fix naming

---

packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts

Remove `Buffer` usage from seedless onboarding controller

fix: remove buffer usage in seedless controller

---

.github/CODEOWNERS
yarn.config.cjs

Update `CODEOWNERS` for the `core-platform` team.

chore: Update `CODEOWNERS` for `core-platform`

---

.github/workflows/changelog-check.yml

This PR updates the changelog-check workflow to use the latest version from commit  [`fc6fe1a3fb591f6afa61f0dbbe7698bd50fab9c7`](https://github.com/MetaMask/github-tools/commit/fc6fe1a3fb591f6afa61f0dbbe7698bd50fab9c7)

chore(changelog-check): update to latest version with optimized `package.json` validation

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
packages/seedless-onboarding-controller/src/constants.ts

- Error handling added when max key chain length is reached.
- Optional param added in submitGlobalPassword  to define the maxKeyChainLength, default = 5.

Fix- max key chain length

---

packages/seedless-onboarding-controller/package.json
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
packages/seedless-onboarding-controller/src/constants.ts
yarn.lock

- This PR optimizes seedless login change password function by removing the need of rehydrating key from backend.

Optimize changePassword flow

---

packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/bridge-status-controller.ts

This PR ports the changes from https://github.com/MetaMask/core/commit/81394cab0c8d8d2e703cabfb348331cfabf4366a into `main`, which was originally for a [Mobile patch](https://github.com/MetaMask/metamask-mobile/pull/17574)

fix: mobile hw approval tx failing immediately

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/MultichainAccountWallet.ts

Just an oversight of this PR ([found by Cursor](https://github.com/MetaMask/core/pull/6216#discussion_r2245259904)):
- https://github.com/MetaMask/core/pull/6216
N/A
N/A

refactor(multichain-account-service): remove duplicated function `toMultichainAccountWalletId`

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/index.ts

fix(multichain-account-service): add missing exports

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/utils/validators.ts

Adds a schema for the new price impact threshold feature flag to the types for `PlatformConfigSchema`

feat: add price impact threshold schema

---

package.json
packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/package.json
packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/package.json
packages/multichain-account-service/src/MultichainAccountGroup.ts
packages/multichain-account-service/src/MultichainAccountService.test.ts
packages/multichain-account-service/src/MultichainAccountService.ts
packages/multichain-account-service/src/MultichainAccountWallet.test.ts
packages/multichain-account-service/src/MultichainAccountWallet.ts
packages/multichain-account-service/src/providers/BaseAccountProvider.ts
packages/multichain-account-service/src/providers/EvmAccountProvider.test.ts
packages/multichain-account-service/src/providers/EvmAccountProvider.ts
packages/multichain-account-service/src/providers/SolAccountProvider.test.ts
packages/multichain-account-service/src/providers/SolAccountProvider.ts
packages/multichain-account-service/src/tests/accounts.ts
packages/multichain-account-service/src/types.ts
yarn.lock

Adding new methods to create a multichain account for a given index or the next index.
N/A
N/A

feat(multichain-account-service): add multichain account create operations support

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/bridge-controller/package.json
yarn.lock

This reverts commit 87ac15349d5a729daa2e2459ad7bc83971457572.

Revert "Release 488.0.0 (#6249)"

---

packages/account-tree-controller/src/AccountTreeController.ts

docs(account-tree-controller): add missing jsdocs

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts

This PR fixes the vault creation with incorrect `revokeToken` value after fetching new revoke token asynchronously. 
FIxes https://github.com/MetaMask/metamask-extension/issues/34945

fix: fixed persisting incorrect revoke token in vault

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/types.ts

Add `perpsDeposit` to `TransactionType`.

feat: add perps transaction type

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts

Updating the state metadata to use `anonymous='false'` for sensitive fields.

Seedless onboarding: Set anonymous='false' for sensitive fields

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/selectors/stringify-balance.test.ts
packages/assets-controllers/src/selectors/stringify-balance.ts
packages/assets-controllers/src/selectors/token-selectors.test.ts
packages/assets-controllers/src/selectors/token-selectors.ts

Adds `rawBalance` to new asset selector as requested by @MetaMask/confirmations .

feat: add-raw-balance-to-selector

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

This PR is required for https://github.com/MetaMask/metamask-extension/pull/35296 and https://github.com/MetaMask/metamask-extension/pull/35300

feat: Add isGasFeeIncluded property

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/balance-changes.test.ts
packages/transaction-controller/src/utils/balance-changes.ts

The property is returned by the transaction simulation results.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/5677

feat: Add 'gasUsed' to transaction metadata

---

packages/network-enablement-controller/CHANGELOG.md
packages/network-enablement-controller/src/NetworkEnablementController.test.ts
packages/network-enablement-controller/src/NetworkEnablementController.ts
packages/network-enablement-controller/src/types.ts

We're adding Solana and Bitcoin devnet/testnet support to the network enablement controller.

chore: adds Solana & Bitcoin testnets

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/MultichainAccountGroup.test.ts
packages/multichain-account-service/src/MultichainAccountGroup.ts
packages/multichain-account-service/src/MultichainAccountWallet.test.ts
packages/multichain-account-service/src/MultichainAccountWallet.ts

refactor(multichain-account-service)!: rename `align{,Group}`

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/index.test.ts
packages/controller-utils/src/index.ts

chore: export missing constant NETWORKS_BYPASSING_VALIDATION

---

packages/subscription-controller/CHANGELOG.md
packages/subscription-controller/src/types.ts

- Add `CryptoPaymentMethodError` error response to `SubscriptionCryptoPaymentMethod`
- Make `rawTransaction` in `UpdatePaymentMethodCryptoRequest` optional for top up case

feat: add crypto payment method error
