- package-lock.json
- package.json
- src/AssetsController.test.ts
- src/AssetsController.ts
- src/ComposableController.test.ts
- src/PreferencesController.test.ts
- src/PreferencesController.ts
- src/TokenRatesController.test.ts
- src/TokenRatesController.ts
- src/index.ts
This PR adds AssetsController in order to support assets on it. First two assets supported are tokens (ERC20) and collectibles (ERC721).
Related https://github.com/MetaMask/gaba/pull/17
BLOCKER: eth-contract-metadata is not the official, we should decide what to do with collectibles metadata before merge.
> Assets controller

- src/ComposableController.test.ts
- src/NetworkController.ts
- src/PreferencesController.test.ts
- src/PreferencesController.ts
This PR adds a list of frequent RPC urls in `PreferencesController`, with the objective of adding custom RPC urls.
> Frequent RPC list

- package.json
- src/AssetsController.test.ts
- src/AssetsDetectionController.test.ts
The branch we were using (`3.0.1-subscription-fix`) has been deleted and now you can't run npm i gaba
> Update eth-block-tracker dep and bump version

- src/PreferencesController.ts
This PR fixes some Preferences Controller state updating inside GABA but not in the general state.
> Update Preferences state

- package-lock.json
- package.json
- src/KeyringController.ts
GABA `KeyringController` state only exposes the encrypted vault but for account rendering purposes it's good to expose all the keyrings, their types and they public keys of each one (which is what the extension is already doing). This PR attempts to expose that new `keyrings` flag.
> Expose keyrings

- src/KeyringController.ts
I was doing `keyring.getAccounts().map` but when you're starting from scratch there's no keyring and undefined.map() breaks.
> Make sure accounts is always an  Array

- .travis.yml
- package-lock.json
- package.json
- src/CurrencyRateController.test.ts
- src/CurrencyRateController.ts
- src/KeyringController.ts
- tslint.json
This pull request cleans up `CurrencyRatesController` and adds support for a new configuration parameter: `baseAsset`.
> CurrencyRatesController: add baseAsset support

- src/TransactionController.ts
This PR defines `gas` as '0x5208' (21000) when transaction `to` is undefined.
> Basic usage gas when transaction to is undefined

- src/BlockHistoryController.test.ts
- src/BlockHistoryController.ts
There was a bug in the blocktracker's backfill function that was getting the same last block 40 times instead of the last 40 blocks.
Added a test to cover that scenario
Fixes #27
> Fix BlockHistoryController

- src/KeyringController.ts
After merging #37 we lost visibility of `isUnlocked` in the keyring state. This PR fixes that, which is currently breaking web3 injection on the mobile app.
(Test failures have nothing to do with this PR)
> Expose isUnlocked on KeyringController

- package-lock.json
- src/AssetsContractController.test.ts
- src/AssetsContractController.ts
- src/AssetsController.test.ts
- src/AssetsController.ts
- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
- src/TokenBalancesController.test.ts
- src/TokenRatesController.test.ts
This PR solves an edge case when an asset is added manually, while at the same time is being auto detected in the background. To solve this a semaphore is included in `addCollectible` and `addToken` methods.
It also includes a refactor of some controllers related to assets and their tests.
> Add semaphore when adding assets

- src/NetworkController.ts
This PR makes sure that `lookupNetwork` in `NetworkController` is working as expected.
Issue:
Sometimes the provider is being initialized with the `defaultState` provider, that in this case is `rinkeby`, independent of the network that the client using GABA is trying to set.
Logic:
`this.ethQuery.sendAsync` it's always initialized with this `defaultState`, while at the same time the client tries to update the network using the same method. 
As it is an async method, sometimes the client request finishes first (for example setting the provider in `mainnet`), then `defaultState` (`rinkeby`) is the last to be updated, setting it as the `network`. Happening here https://github.com/MetaMask/gaba/blob/659ee7b7da6875f2ba9b3628444e2c986e27d394/src/NetworkController.ts#L173
To solve this a …
> Add semaphore to lookupNetwork

- src/KeyringController.ts
Before this PR the keyring was returning the latest existent vault which was causing the following problem.
I'm logged in with keyring A which has password B
I log out.
I create a new wallet with password C
Now I get keyring A with password C.
TL;DR: When you create a new wallet it should ignore whatever wallet existed before and create a new one.
> Don't use previous vault

- src/KeyringController.ts
Otherwise there are no accounts exposed until the next time GABA initializes.
This fixes an issue on the mobile app that makes the account list to be empty after importing from seed.
> Keyrings needs to update after import from seed

- src/TransactionController.test.ts
- src/TransactionController.ts
Because queryTransactionStatuses is running inside a setInterval we're telling GABA that the state was updated even when there are no changes.
This PR adds a flag to make sure the state gets updated only when at least 1 TX status changed.
> Only update TransactionController state if got updates

- src/TokenRatesController.ts
As explained here https://github.com/MetaMask/metamask-extension/pull/6005, for some tokens balanc2 returns the usd conversion not the native currency being asked.
> Set balanc3 autoconversion off

- package-lock.json
- package.json
- src/AssetsContractController.test.ts
- src/AssetsContractController.ts
- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
The `AssetsDetectionController` has been querying every single ERC20 contract in the `eth-contract-map` package (106 in total) every 3 minutes to see if the `selectedAddress` has a positive balance and start watching that token.  
That can be done in a single call by querying a smart contract: https://github.com/wbobeirne/eth-balance-checker/blob/master/contracts/BalanceChecker.sol
So instead of 106 requests / 3 minutes, we're doing 1, which results in 2100 requests less made to Infura per hour.
CC: @frankiebee 
I'll submit a similar PR to the extension shortly since the difference is huge and it's not that big of a change.
> Avoid 2100 requests / hour to Infura

- src/AssetsContractController.test.ts
- src/AssetsContractController.ts
- src/TokenRatesController.ts
This PR adds support for ERC721 `ownerOf` method in `AssetsContractController`.
> Add contract ownerOf support

- src/AssetsController.test.ts
- src/AssetsController.ts
- src/ComposableController.test.ts
This PR adds a new interface called `CollectibleContract` and related methods to `AssetsController` to handle collectible contract information.
> Introduce collectible contract

- src/AssetsContractController.test.ts
- src/AssetsContractController.ts
- src/AssetsController.test.ts
- src/AssetsController.ts
- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
- src/ComposableController.test.ts
- src/util.test.ts
- src/util.ts
- tsconfig.json
This PR introduces several changes in the way collectibles are handled.
1. Auto-detection of collectibles is made completely using OpenSea API.
2. A new object called `CollectibleContract` was created to handle all collectible contract information as name, image, description, total supply, address and symbol. Maintaining the responsibility of the object `Collectible` to handle individual collectible information.
3. Added two methods to interact with collectible contracts, in order to get name and symbol. This is important for users adding collectibles in test nets.
4. If users add collectibles that are not in OpenSea API (probably using test nets) and those contracts respect `ERC721 Metatada Interface`, those manually added collectibles are still going to fetch name and image to be …
> Reorder collectibles detection and structure

- src/TransactionController.ts
I forgot to filter for the network and as a result it was always returning the last incoming tx block from mainnet (which has the highest block number)
> return last incoming tx block number for current network ONLY

- .travis.yml
- src/AccountTrackerController.ts
- src/AssetsController.ts
- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
- src/ComposableController.test.ts
- src/NetworkController.test.ts
- src/NetworkController.ts
I've spent some time on the app side trying to identify the bottlenecks and this is the stuff I found:
- Change network controller polling from 8 to 12 seconds (Based on https://etherscan.io/chart/blocktime blocktime was never below 13) so by changing this we're doing 30% less requests.
- Update account balance in state right after each individual request. The state wasn't updating immediately causing a noticeable delay in the UI.
- Make "mainnet" the default network. This is how every client is supposed to initialize by default so we're avoiding extra requests to another network on startup.
- Prevent asset detection (tokens & collectibles) if the selectedAddress wasn't set. 
`provider` and `selectedAddress` are two independent config settings and we should only try to detect assets once …
> Performance updates

- src/TransactionController.ts
There was a bug estimating gas for ETH transactions with data on it, returning always 21000. This PR fixes that situation.
> Fix gas estimation

- src/util.test.ts
- src/util.ts
This PR updates transaction value validation to only accept valid integer numbers.
Resolves https://github.com/MetaMask/gaba/issues/68
> Update transaction value validation

- src/KeyringController.test.ts
- src/KeyringController.ts
This PR adds full coverage tests of `KeyringController`.
Resolves https://github.com/MetaMask/gaba/issues/66
> Add KeyringController tests

- src/TransactionController.test.ts
- src/TransactionController.ts
- src/util.test.ts
- src/util.ts
This PR adds `toSmartContract` attribute to `TransactionMeta` object, it shows whether the transaction was sent to a smart contract or not, request that is being done only once when the tx is fetched. 
This avoids requesting this information (hitting infura) each time we render a transaction or having the audit issue caching this information.
> Transaction to smart contract

- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
- src/CurrencyRateController.test.ts
- src/CurrencyRateController.ts
- src/NetworkStatusController.test.ts
- src/NetworkStatusController.ts
- src/PhishingController.test.ts
- src/PhishingController.ts
- src/ShapeShiftController.test.ts
- src/ShapeShiftController.ts
- src/TokenBalancesController.test.ts
- src/TokenBalancesController.ts
- src/TokenRatesController.test.ts
- src/TokenRatesController.ts
- src/TransactionController.test.ts
- src/TransactionController.ts
This PR fixes a couple of things:
- Replaces all `setInterval` ocurrences for recursive `setTimeout`
- Polling will wait for the last call to finish (or fail) before triggering a new one
- Prevent multiple calls to happen on init (`CurrencyController` and `TokenRatesController`) by disabling the controller until after init.
Fixes #64
> Fix polling

- src/AddressBookController.test.ts
- src/AddressBookController.ts
- src/ComposableController.test.ts
- src/PreferencesController.test.ts
- src/PreferencesController.ts
- src/util.test.ts
- src/util.ts
This pull request does the following:
- `safelyExecute` optionally logs errors and provides an optional retry logic path.
- The `AddressBookController` validates newly-added addresses.
- The `PreferencesController` loosely checks local RPC URLs (though this was technically unnecessary since we're checking against a constant string value [we set internally](https://github.com/MetaMask/gaba/blob/master/src/NetworkController.ts#L50).)
Fixes #65
Fixes #67
Fixes #70
> bugfix: add address validation and improve safelyExecute

- src/AssetsController.test.ts
- src/AssetsController.ts
- src/ComposableController.test.ts
- src/TokenRatesController.ts
- src/TransactionController.ts
- src/util.test.ts
- src/util.ts
This PR adds support to handle EIP747 from `AssetsController` and was mostly inspired mostly on how we handle transactions in `TransactionController`.
For now these methods only support `Token`s, but was meant to easily add new types of assets in the future.
> Feature: EIP747 watchAsset

- src/AssetsDetectionController.ts
Forgot to convert with ` toChecksumAddress` before  comparing against the already ignored assets
> use checksum addresses for comparison in ignoreLists

- src/AccountTrackerController.ts
- src/AssetsDetectionController.ts
- src/BaseController.test.ts
- src/BaseController.ts
- src/CurrencyRateController.test.ts
- src/CurrencyRateController.ts
- src/NetworkStatusController.ts
- src/PhishingController.ts
- src/ShapeShiftController.ts
- src/TokenBalancesController.ts
- src/TokenRatesController.test.ts
- src/TokenRatesController.ts
- src/TransactionController.ts
Right now the`configure` method sets again every single existing value in `internalConfig` every time is called.  As a side effect, all the class properties that are declared as setters are being called, triggering undesired behaviors (like multiple repeated API calls).
This PR adds a new optional flag (backwards compatible) that lets the controller update specific parts of the config.
> Enable partial updates to controller config

- npm-shrinkwrap.json
This pull request adds an [NPM shrinkwrap configuration file](https://docs.npmjs.com/files/shrinkwrap.json.html) so consumers of this package are forces to respect its lockfile.
> feature: add shrinkwrap NPM configuration file

- src/ComposableController.test.ts
- src/PreferencesController.test.ts
- src/PreferencesController.ts
This PR adds `ipfsGateway` to `PreferencesController` state. The idea of it is maintaining `ipfsGateway` on state and be able to update it.
> Feature: Choose IPFS gateway

- src/TokenRatesController.test.ts
- src/TokenRatesController.ts
This pull request updates the `TokenRatesController` to use the CoinGecko API instead of the Balanc3 API that will be shut down in the near future. The API seemed to hold up under the local stress tests I did (50+ tokens per request at 100 requests per minute - the rate limit max - for several minutes).
Resolves #83
> feature: switch token pricing to CoinGecko API

- src/AssetsController.test.ts
- src/AssetsController.ts
- src/AssetsDetectionController.test.ts
This PR maintain changes made in #86 adding specific methods to remove and ignore assets, and maintaining remove assets methods before that PR. 
The motivation of this is to maintain independent methods in `AssetsController`. This change produced that all removed assets would be immediately ignored without having an option to remove without ignore.
> Bugfix: remove and ignore assets

- src/AssetsDetectionController.test.ts
- src/AssetsDetectionController.ts
This PR changes the image we're using to display collectibles to use the original collectible url.
> bugfix: collectibles original image

- src/AssetsController.test.ts
- src/AssetsController.ts
Doing QA of this previous PR https://github.com/MetaMask/gaba/pull/99, noticed that there was method without change. The original bug was solved (when auto detecting assets), but it was still there for manually added a collectible. Added types to make sure this won't happen again.
> bugfix: add collectible original image

- src/CurrencyRateController.ts
- tests/CurrencyRateController.test.ts
This PR adds a semaphore to `updateExchangeRate`, this was causing wrong conversion rates.
If the app sets native currency as ETH and then DAI, `fetchExchangeRate` could finish first for DAI, producing that ETH conversion rate is set to state because it finished later, even though it was called first.
> Bugfix: update exchange rates

- src/assets/TokenRatesController.ts
This pr fixes a bug introduced in https://github.com/MetaMask/gaba/commit/6499e74a64523265c2cc614ead1c95011abc394e 
Changing `nativeCurrency` of `CurrencyRateController` to `ETH` (capital letters) broke the query to CoinGecko. This pr makes sure that native currency is always sent in lower case.
> Bugfix: token rates

- src/assets/TokenBalancesController.ts
- tsconfig.json
This PR updates the TypeScript config to produce type declaration files into the `dist` folder, allowing TypeScript consumers to properly get type information. I've exported `BN` from `TokenBalancesController.ts` as it's used in the `TokenBalancesState`, which itself is public.
> Add declaration files for TypeScript consumers

- src/assets/AssetsContractController.ts
This PR handles empty array result from `getBalancesInSingleCall` in `AssetsContractController`. It also fixes the type.
> Handle empty result from getBalancesInSingleCall

- .editorconfig
This PR adds `npm-shrinkwrap.json` to the EditorConfig file alongside the `package*.json` files.
> Add npm-shrinkwrap settings to the EditorConfig file

- .editorconfig
- .travis.yml
This PR updates the Travis config to:
1. Use the job-based config<sup>[\[1\]](https://docs.travis-ci.com/user/build-stages/)</sup>
2. Test `npm ci` in addition to `npm install`
> Use job-based Travis config, test CI install

- src/util.ts
- tests/util.test.ts
This PR removes extraneous test output, namely disabling logging of the error from the `utils#safelyExecute` test case.
> Remove all extraneous test output

- src/BaseController.ts
This PR simplifies the return statement in `BaseController#unsubscribe` where we were previously testing a boolean and returning the same value.
> Simplify BaseController#unsubscribe return statement

- src/transaction/TransactionController.ts
This PR removes the exception thrown when `this.sign` is falsy in the `TransactionController`'s `approveTransaction` method.
**Why is using exceptions as flow control not great?**
See also: [\[1\]][1], [\[2\]][2], [\[3\]][3], and [\[4\]][4]
[1]:https://web.archive.org/web/20140430044213/http://c2.com/cgi-bin/wiki?DontUseExceptionsForFlowControl
[2]:https://softwareengineering.stackexchange.com/q/189222/114526
[3]:https://stackoverflow.com/q/729379/1267663
[4]:https://stackoverflow.com/a/47016061/1267663
The case where `this.sign` is falsy isn't _exceptional_ and we know immediately how to handle it and what error message is associated with it. As such, we can immediately fail the tx and return early from the method.
> Fail tx directly if sign method missing

- src/assets/AssetsDetectionController.ts
- tests/AssetsDetectionController.test.ts
There is a limit for detecting collectibles that defaults to 20, for users with more than 20 collectibles it won't show all of their collectibles. I updated the limit to 300, that's the maximum limit we can get.
> bugfix: collectibles detection

- src/user/PreferencesController.ts
This PR fixes a small nitpick with the import for `AddressBookController` in the `PreferencesController`—the import path is navigating up and back into the same directory.
> Fix import path for AddressBookController

- src/user/AddressBookController.ts
- tests/AddressBookController.test.ts
This PR updates the `AddressBookController` to make its API more consistent and intuitive with two changes:
1. Symmetry in the `add`/`delete` return values—both methods now return a boolean to indicate success
2. Normalize addresses to allow ensure that case differences in the addresses doesn't fail silently (also helped by pt. 1)
> Update AddressBookController API

- npm-shrinkwrap.json
- package.json
- src/assets/AssetsController.ts
- src/assets/AssetsDetectionController.ts
- src/assets/TokenRatesController.ts
- src/keyring/KeyringController.ts
- src/transaction/TransactionController.ts
- src/user/AddressBookController.ts
- src/user/PreferencesController.ts
- src/util.ts
- tests/KeyringController.test.ts
This PR updates the direct `ethereumjs-util` dependency to v6, which includes TypeScript definitions. There are no relevant breaking changes to GABA's _direct_ usage:<sup>[\[1\]][1]</sup>
> - [BREAKING] Fixed signature to comply with Geth and Parity in `toRpcSig()` changing 
`v` from 0/1 to 27/28, this changes the resulting signature buffer, see PR [#139](https://github.com/ethereumjs/ethereumjs-util/pull/139)
> - [BREAKING] Remove deprecated `sha3`-named constants and methods (see `v5.2.0` release),
see PR [#154](https://github.com/ethereumjs/ethereumjs-util/pull/154)
I've changed the places where `ethereumjs-util` are being `require`'d to use TypeScript imports where possible (minus `BN` whose types don't match the usages and #141). …
> Update to ethereumjs-util@6

- tests/KeyringController.test.ts
This PR fixes the following deprecation warning that appears when running the tests:
```
(node:83313) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
> Remove deprecated Buffer constructor

- src/user/AddressBookController.ts
- src/util.ts
- tests/AddressBookController.test.ts
- tests/ComposableController.test.ts
- tests/util.test.ts
previously the address book was only keyed by address, so a user was only allowed to have one entry per address regardless of network
> update addressBook with entries by chainId

- npm-shrinkwrap.json
- package.json
- src/third-party/EnsController.ts
- src/user/AddressBookController.ts
- src/util.ts
- tests/ComposableController.test.ts
- tests/EnsController.test.ts
- tests/util.test.ts
Adds an `EnsController`. It keeps track of ENS name and their resolved addresses for the purpose of taking some useful action (e.g. warning the user in the UI).
Addresses and ENS names (see `util.ts:normalizeEnsName`) are normalized before being added. ENS name normalization added to address book controller as well.
ENS name normalization and verification should be updated in the extension if this change is integrated. That should amount to importing `normalizeEnsName` from `src/util.ts`.
> Add EnsController

- npm-shrinkwrap.json
- package.json
- src/assets/AssetsContractController.ts
- src/assets/AssetsController.ts
- src/assets/AssetsDetectionController.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenBalancesController.ts
- src/assets/TokenRatesController.ts
- src/index.ts
- src/keyring/KeyringController.ts
- src/network/NetworkStatusController.ts
- src/third-party/PhishingController.ts
- src/third-party/ShapeShiftController.ts
- src/transaction/TransactionController.ts
- src/util.ts
- tests/CurrencyRateController.test.ts
- tests/setupTests.ts
- tests/util.test.ts
The `fetch` API will throw an exception if a network error is encountered during a `fetch` invocation, but an unsuccessful response will not. We should never assume that the response from `fetch` is
successful without checking first. We can't even assume that successfully calling `.json()` on a request implies that it succeeded, because failed responses can pass information in the response body as well.
A `successfulFetch` utility method has been added that verifies the fetch response was successful, and throws an error if it was not. This method is now used for the other two `fetch` utility methods, and each instance of `fetch` has been updated to use one of these methods.
New tests have been added for `successfulFetch`. `fetch-mock` was updated to make it easier to specify the status of …
> Handle unsuccessful fetch

- .npmignore
- package.json
Updates `.npmignore` and `package.json` to allow for running `npm publish` in project root folder, as opposed to `dist`. This will add our missing readme to NPM.
> Setup project for publishing from root folder

- src/assets/CurrencyRateController.ts
- tests/CurrencyRateController.test.ts
re: https://github.com/MetaMask/metamask-extension/issues/6710
re: the pinning, when I installed this I got tsc `Version 3.6.4`
which resulted in the following:
```
src/util.ts:113:4 - error TS2322: Type 'any' is not assignable to type 'never'.
113  		normalizedTransaction[key] = NORMALIZERS[key](transaction[key]);
~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```
builds fine with `3.5.3`
> Persist currentCurrency from state when re-initialising controller

- src/transaction/TransactionController.ts
- tests/TransactionController.test.ts
This PR
- Adds a `speedUpTransaction` method to be able to speed up transactions
- Fixes `cancelTransaction` update since it wasn't working correctly
> Feature: speed up transaction

- src/network/NetworkController.ts
There is a bug happening between stopping the provider listener and setting a new provider.
By doing 
https://github.com/MetaMask/gaba/compare/bugfix/provider-stop?expand=1#diff-e6a23ff500e4183b5eba5bca9a0df0bdL136
we're unsubscribing the provider to handle errors from 
https://github.com/MetaMask/gaba/compare/bugfix/provider-stop?expand=1#diff-e6a23ff500e4183b5eba5bca9a0df0bdL101
causing that we have an active provider exposed to throwable errors without handling it properly.
This PR sets a threshold to stop it after a new provider is set, to make sure that we're not exposed to errors coming from the provider.
> bugfix: provider stop

- src/user/PreferencesController.ts
- tests/PreferencesController.test.ts
This PR adds a new `setSelectedAddress` method to `PreferencesController` to update selected address.
> feature: preferences set selected address

- tests/TokenRatesController.test.ts
This PR adds mocks for `TokenRatesController` since these tests usually fail because of third party api.
> Tests: token rates mocks

- src/transaction/TransactionController.ts
We have seen a bunch of  error like this one in mobile that looks like : `"[object Object]`
This is the reason:
This PR fixes the issue by passing the error object instead.
> Return tx errors correctly

- src/transaction/TransactionController.ts
When users try to stop or cancel txs several times gasPrice is not being handled correctly, this pr makes sure that's going to be always an integer number.
> bugfix: stop speedup txs

- src/assets/AssetsController.ts
- src/assets/CurrencyRateController.ts
- src/keyring/KeyringController.ts
- src/transaction/TransactionController.ts
A `try ... finally` block has been added to most places where a mutex is used, to ensure that any error thrown before the lock has been released will not result in a deadlock.
The `finally` block will execute after the `try` block, but it will not interfere with any returned values or thrown errors (so long as nothing is thrown or returned within the `finally` block).
> Prevent deadlocks resulting from errors thrown before releasing mutex

- tests/AccountTrackerController.test.ts
- tests/AssetsController.test.ts
- tests/TransactionController.test.ts
This PR adds the existing project ID to all Infura v3 endpoints.
> Add project ID to all Infura endpoints

- .gitignore
- package.json
- src/transaction/TransactionController.ts
- src/util.ts
- yarn.lock
re: https://github.com/MetaMask/metamask-mobile/issues/1314
I've confirmed that after this we get functionality similar to the extension in the mobile app:
**todo**
> Use eth json rpc errors

- .gitignore
- npm-shrinkwrap.json
- package.json
- src/transaction/TransactionController.ts
- tests/AccountTrackerController.test.ts
- tests/AssetsController.test.ts
- tests/TransactionController.test.ts
> Use eth errors

- yarn.lock
This PR updates our `handlebars` dependency to the latest published version, which drops its `optimist` dependency. Our indirect dependency on `optimist` was keeping a version of `minimist` around that has an active security advisory.
> Use handlebars@4.7.6

- yarn.lock
This PR updates `mkdirp` to remove our indirect dependency on `minimist@0`
> Use mkdirp@0.5.5

- src/third-party/PhishingController.ts
- tests/PhishingController.test.ts
Refs #219
This PR removes the usage of the `https://api.infura.io/v2/blacklist` endpoint, replacing it with fetching the config from GitHub directly.
> Poll GitHub for phishing config file

- yarn.lock
This PR updates `yargs-parser` in our dependency tree to address 25 security advisories of the form shown below. See also: https://www.npmjs.com/advisories/1500.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest …
```
> Use yargs-parser@18.1.2

- package.json
This PR adds the `.publishConfig` entry to the `package.json` file that is required to publish a public scoped npm package.
> Add publish config for scoped pkg

- package.json
- yarn.lock
This PR updates the version of TypeScript used to the latest `3.8.x`.
> Use typescript@3.8.3

- src/third-party/PhishingController.ts
This change updates the `PhishingController` config request logic to:
1. Use the official GitHub API for repo contents (see #219)
2. Handle 403 responses, as the GH API will rate limit with that status code
Note that the current query interval, 180000 ms, will be fewer than 60 requests per hour:
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.
And, per the docs, 304 responses don't count towards the rate limit:
> Making a conditional request and receiving a 304 response does not count against your Rate Limit, so we encourage you to use it whenever possible.
See also:
- [GitHub REST API v3 - Media Types](https://developer.github.com/v3/media/)
- …
> Update phishing config request logic

- src/third-party/PhishingController.ts
- tests/PhishingController.test.ts
This PR lowers the rate at which we are checking the phishing blocklist from every 3 minutes to every 60 minutes.
> Lower phishing config poll rate to 1 req/hr

- src/third-party/PhishingController.ts
Refs #219
At the request of GitHub, this change updates how we query for the latest blocklist content. We now hit [jsDelivr][1] instead of the GitHub API.
[1]:https://www.jsdelivr.com
> Use jsDelivr instead of the GitHub API for content

- package.json
This PR adds a `prepublishOnly` script entry to run the build process before publishing.
> Add prepublishOnly build script

- yarn.lock
This PR updates `ts-jest` to address a security advisory with `yargs-parser`.
See https://www.npmjs.com/advisories/1500 for more information.
The `yarn audit` output:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ts-jest …
```
> Use ts-jest@25.5.1

- src/network/NetworkController.ts
This PR removes a duplicate call to `setupInfuraProvider` and merges all of the Infura cases into the single call.
> Remove duplicate call to setupInfuraProvider

- src/BaseController.ts
The `initialState` and `initialConfig` properties are only assigned in the constructor so they can be marked as `readonly`.
> Mark initial state and config as readonly

- package.json
- src/network/NetworkController.ts
- tests/NetworkController.test.ts
- yarn.lock
This PR updates the project to use Infura's v3 API.
Tasks:
**Breaking change**:
A project ID is now required for all instantiations of the `NetworkController` that are backed by Infura.
```ts
const controller = new NetworkController({
infuraProjectId: 'foo',
}, {
network: '1',
provider: { type: 'mainnet' },
});
```
> Use Infura v3 API

- .eslintrc.js
- src/util.ts
This PR enables `require-unicode-regexp` and fixes/suppresses the issues raised. I've suppressed the 2nd instance as that regex is already slated for updating and will require more attention to make sure it correctly handles unicode.
> Enable and fix require-unicode-regexp issues

- .eslintignore
- .eslintrc.js
This PR moves the ESLint ignore patterns into the `.eslintrc.js` file to keep everything together.
> Move ESLint ignore patterns into config

- .eslintrc.js
- tests/AddressBookController.test.ts
- tests/PreferencesController.test.ts
- tests/TypedMessageManager.test.ts
- tests/util.test.ts
This PR enables `jest/no-identical-title` and fixes the issues raised. 5 issues were fixed, one of which was a duplicate test.
> Enable and fix jest/no-identical-title issues

- src/third-party/PhishingController.ts
Refs #256
This PR removes the ` If-None-Match` header from the requests for the phishing list. The header was a holder from the old implementation that used GitHub's content API (#232) and is no longer needed. (The header also caused the request to fail when a UA enforced `Access-Control-Allow-Headers`, which is missing on the jsDelivr response.)
Removing this header reverts the fetch cache mode to `default`:
> `"default"`
>
> Fetch will inspect the HTTP cache on the way to the network. If the HTTP cache contains a matching fresh response it will be returned. If the HTTP cache contains a matching stale-while-revalidate response it will be returned, and a conditional network fetch will be made to update the entry in the HTTP cache. If the HTTP cache contains a matching stale response, a …
> Remove If-None-Match header from phishing config requests

- package.json
- yarn.lock
Required for `web3-provider-engine` upgrade. This dependency is also quite dated.
> isomorphic-fetch@3.0.0

- src/keyring/KeyringController.ts
- tests/KeyringController.test.ts
This adds a new method for adding accounts _without_ updating identities in the preferences controller
this is currently being used in https://github.com/MetaMask/metamask-mobile/pull/1879
> Add addNewAccountWithoutUpdate method

- .circleci/config.yml
- package.json
- src/approval/ApprovalController.ts
- tests/ApprovalController.test.js
- tests/ApprovalController.test.ts
- yarn.lock
This PR adds a generic "approval" controller for managing user confirmations and displaying them in the MetaMask UI. The controller is designed to be used in both the extension and mobile.
The approval controller accepts a single config argument, `showApprovalRequest`, which is a function that should trigger the display of a user confirmation in the MetaMask UI. `ApprovalController.addAndShowApprovalRequest` adds a pending request to the controller's state, and _then_ calls `showApprovalRequest`. This allows the UI to select the pending request via the approval controller's state.
Optionally, a pending request can be added without calling `showApprovalRequest`, via `ApprovalController.add`.
The approval controller was originally implemented in JavaScript in [this extension …
> Add approval controller

- src/assets/CurrencyRateController.ts
- tests/ComposableController.test.ts
- tests/CurrencyRateController.test.ts
For analytics purposes in metamask-extension, we have a need of always knowing the the ETH to USD rate, even when the users selected currency is not USD. This PR updates the CurrencyController so that it can be passed a `includeUSDRate` config property that ensures that the exchange rate for `USD` is always fetched, in addition to whatever the `currentCurrency` is.
> CurrencyController can be configured to always fetch usd rate

- package.json
- src/keyring/KeyringController.ts
- src/util.ts
- tests/KeyringController.test.ts
- yarn.lock
- `eth-sig-util@3.0.0`
- Because this version uses TypeScript, we had to cast variables in certain places to `any`. The package makes runtime type checks wherever we do so, and we catch any errors thrown.
> eth-sig-util@3.0.0

- src/approval/ApprovalController.ts
- tests/ApprovalController.test.js
- tests/ApprovalController.test.ts
Adds two methods to the approval controller:
- `getTotalApprovalCount`, for getting the total count of all approvals, regardless of origin and type
- `getApprovalCount`, for getting the count of all approvals by origin, type, or both
We need this for e.g. the the `updateBadge` functionality in the MetaMask extension. Implementing the methods on the controller itself is better than hacking it on at the consumer layer.
> Add approval controller count methods

- src/approval/ApprovalController.ts
#304 added the methods. This adds the state. Also properly initializes this controller, which wasn't happening previously. It's clearly not always necessary, but the constructor should always call `BaseController.initialize()`.
> Add approval controller count state

- package.json
- src/keyring/KeyringController.ts
- tests/KeyringController.test.ts
- yarn.lock
Bumped the `eth-keyring-controller` to **6.1.0** to be able to access the lock/unlock events.
Also added two functions `onLock` and `onUnlock` so that we can add listeners for those events.
> Add lock and unlock events with a bump on the keyring controller

- package.json
- yarn.lock
Remove `jsdom` as explicit dependency (it's brought in by others), and fix the lockfile, which needed updating.
> Remove jsdom, fix lockfile

- package.json
- src/assets/AssetsDetectionController.ts
- yarn.lock
This PR replaces `eth-contract-metadata` with `@metamask/contract-metadata`. The package was just renamed. It's also been updated.
> @metamask/contract-metadata

- src/approval/ApprovalController.ts
- tests/ApprovalController.test.js
- tests/ApprovalController.test.ts
Removes the default approval controller type, and requires an explicitly specified type for all approvals.
> Remove default approval controller type

- package.json
- src/network/NetworkController.ts
- src/transaction/TransactionController.ts
- tests/AssetsController.test.ts
- tests/AssetsDetectionController.test.ts
- tests/ComposableController.test.ts
- tests/NetworkController.test.ts
- tests/TransactionController.test.ts
This PR makes sure that all custom rpc networks have a valid chainId, and disregard the usage of networkId in favor of chainId
> Enforce chainId

- src/assets/TokenBalancesController.ts
- src/assets/TokenRatesController.ts
- tests/TokenBalancesController.test.ts
this allows for tokens to have a `balanceError` property... surprisingly similar to: https://github.com/MetaMask/eth-token-tracker/pull/53/files#diff-da4ef0bd8d62fc58923ab92dc5a94b4fdaeaa2a36242311727356d7e3f1d44d0R79
re: [#2128](https://github.com/MetaMask/metamask-mobile/issues/2128)
> Add try/catch for `assetsContract.getBalanceOf`

- package.json
- yarn.lock
This includes various new tokens, and changes to token metadata.
> Update `@metamask/contract-metadata` from v1.19 to v1.22

- package.json
- tsconfig.json
- typedoc.json
- yarn.lock
This update had a few breaking changes, most of which [were introduced in v20](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0). The options were moved into a separate config file, and some of them were no longer required.
This update includes a variety of improvements and bug fixes.
> Update `typedoc` from v0.15 to v20.20

- package.json
- src/assets/AccountTrackerController.ts
- src/transaction/TransactionController.ts
- src/util.ts
- tests/TransactionController.test.ts
- tests/util.test.ts
- yarn.lock
There were 2 issues on the `AccountTrackerController`
1. For some reason we were using `ethjs-query` only on this controller, I moved to `eth-query` since it was used for other controllers, including the extension's controllers
2. We were seeing some cases where `getBalance` calls were stuck, making the polling process of this controller a heavy process. If the `getBalance` call was stuck, the controller never dropped it and since that process is every 500ms, made the mobile app behave poorly, specially on android. Now if the response doesn't get in time, the `getBalance` call will be dismissed and it will continue to the next poll iteration using `safelyExecuteWithTimeout`.
There's also a new util `query` that was on the `TransactionController` but now is used in …
> Account tracker improvement

- yarn.lock
This update includes dependency changes. Most notably, `async-mutex` is no longer a dependency, which should help solve some TypeScript errors we were seeing on the prototype controller redesign branch.
> Update `eth-json-rpc-filters` in lockfile

- package.json
- src/assets/AccountTrackerController.ts
- src/assets/AssetsController.ts
- src/assets/CurrencyRateController.ts
- src/keyring/KeyringController.ts
- src/network/NetworkController.ts
- src/transaction/TransactionController.ts
- yarn.lock
We've had issues with `await-semaphore` causing TypeScript errors due to mistakes in how it is packaged. It generally seems to be abandoned.
`async-mutex` is more actively maintained, has better documentation and test coverage, and is API-compatible for our usage.
> Replace `await-semaphore` with `async-mutex`

- package.json
- src/assets/AssetsController.ts
- src/message-manager/MessageManager.ts
- src/message-manager/PersonalMessageManager.ts
- src/message-manager/TypedMessageManager.ts
- src/transaction/TransactionController.ts
- yarn.lock
This update includes changes to the package export. The various different versions of `uuid` that used to be provided by path are now named exports, and the default export has been removed.
Our imports have been updated to use the new named export, [as per the migration guide](https://github.com/uuidjs/uuid#upgrading-from-uuid3x).
> Update `uuid` from `v3.3.3` to `v8.3.2`

- .eslintrc.js
The `docs` directory includes auto-generated JavaScript that does not follow our lint rules.
> Add `docs` to list of ignored eslint patterns

- .eslintrc.js
- package.json
- yarn.lock
This update includes the update from `eslint` v6 to v7. In this release the Node.js-specific rules were broken out into a separate plugin (`eslint-plugin-node`), which is now also required.
Any broken rules have been temporarily disabled, to be addressed in a future PR.
> Update `@metamask/eslint-config` from v3 to v4.1.0

- tsconfig.json
This file was the only one in the repo to use tabs for indentation. It has been updated to use spaces.
> Fix `tsconfig.json` indentation

- package.json
- tests/AssetsDetectionController.test.ts
- tests/CurrencyRateController.test.ts
- tests/PhishingController.test.ts
- tests/TokenRatesController.test.ts
- yarn.lock
`sinon` has been updated from v7 to v9. There have been no breaking changes that affect our usage.
The types we were using were _far_ behind though, so updating those has revealed pre-existing mistakes in how we were using `sinon` in a few places.
For one of the type errors, I replaced a `window.fetch` mock with `nock`, as that seemed like the simplest way to fix the type error.
> Update `sinon` and `@types/sinon` to latest versions

- src/approval/ApprovalController.ts
The `ApprovalController` was not great at counting. If you tried to delete an approval that didn't exist, or if you tried to add an approval that already existed, it would miscount the current number of pending approvals.
Validation was in place already to prevent both scenarios, so in practice this shouldn't be possible without calling private functions. But still, preventing it entirely was trivial, so here it is.
> Prevent `ApprovalController` counting mismatch

- src/apis/crypto-compare.test.ts
- src/apis/crypto-compare.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/CurrencyRateController.ts
The CryptoCompare API interactions have been extracted from the CurrencyRateController and moved into a separate module.
This is part of #337. The API interactions have been extracted to simplify the controller, and make it easier to thoroughly test the API interactions and the controller logic.
> Extract CryptoCompare API

- package.json
- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
- yarn.lock
This is the new base controller we'll be transitioning to as part of the controller redesign (#337). It has been added as a separate module so that we can transition each controller more easily, one at a time.
Additional features will be added in future PRs (e.g. schema, messaging).
> Add Base Controller v2

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
Subscribers of the new BaseController will now also receive a patch for each state change, in addition to a copy of the new state. Patches can make it easier to efficiently serialize state updates.
This was done as part of the controller redesign (#337).
> Send patches to state subscribers

- src/message-manager/AbstractMessageManager.test.ts
- src/message-manager/AbstractMessageManager.ts
The error thrown when trying to set the status of a non-existent message was broken. The first variable in the error message resolved to `undefined`. It has been updated to reference the type of the controller that threw the error.
> Fix AbstractMessageManager error

- .eslintrc.js
- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
The BaseController state now uses `unknown` rather than `any` as the type for state properties. `unknown` is more type-safe than `any` in cases like this where we don't know what type to expect. [See here for details](https://github.com/Microsoft/TypeScript/pull/24439).
This was suggested by @rekmarks during review of #362: ([comment](https://github.com/MetaMask/controllers/pull/362#discussion_r581338608))
The mock controller state in the base controller tests now uses a type alias for the controller state rather than an interface. This was required to get around [an incompatibility between `Record<string, unknown>` and interfaces](https://github.com/Microsoft/TypeScript/issues/15300#issuecomment-702872440).
The `@typescript-eslint/consistent-type-definitions` ESLint rule has been …
> Use `unknown` rather than `any` for BaseController state

- package.json
- src/assets/AccountTrackerController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenRatesController.test.ts
- src/message-manager/MessageManager.test.ts
- src/message-manager/MessageManager.ts
- src/message-manager/PersonalMessageManager.test.ts
- src/message-manager/PersonalMessageManager.ts
- src/message-manager/TypedMessageManager.test.ts
- src/message-manager/TypedMessageManager.ts
- src/third-party/PhishingController.test.ts
- src/transaction/TransactionController.ts
- yarn.lock
TypeScript [has been updated to v4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/). I'm not aware of any changes that impact our code, but the update did highlight a few new minor errors in our code for some reason. These have all been fixed. There was also a breaking change that affected us: `resolve` parameters for Promises are no longer optional. We're not required to use `Promise<void>` for any Promises not returning a value.
> Update to TypeScript 4.1

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
State metadata has been added to the new BaseController constructor as a required constructor parameter. The metadata describes how to derive the state that should be persisted, and how to derive an 'anonymized' representation of the controller state.
The metadata describes top-level properties only, but it allows you to define a function to derive the anonymized or persistent state for each property. The only requirement of this derivation function is that the output is also valid JSON.
This is part of the controller redesign (#337).
> Add BaseControllerV2 state metadata

- src/BaseControllerV2.ts
The JSON types (`Json` and `IsJsonable`) have been improved:
* The last part of the `Json` union type was redundant, and has been removed (`Partial<Record<never, never>>`).
* A check has been added to `IsJsonable` to prevent the use of numeric keys in objects. In testing I've found this doesn't prevent all cases of this, but it does prevent some.
[`IsJsonable` playground link with tests](https://www.typescriptlang.org/play?#code/C4TwDgpgBGBOCWBbex4DdoF4oDsCuANgQLABQUFUAPlAEYD29BEAhjmZdbnorRLB0o0AzsAQ4A5mTKhIUACIQAZvBwoIBEADl6wAFLD6OFrWZRsACgsBKcwD4obELZp4cAE2WqI76aVnQAJLCBkYmzAA8ACoOmIIA9PFQAMIAFhAAxgDWUPBKUMDpsNAsxY44ILhGALQAVobGptABwlDFcBDCEDjAPrk4BelQbvBGCUk6vQBcw11Q9PnAeGDMraqD8K0qsKJQGUbuKKMDwvCe1aIQYK2Hogi0eKgYewdHYQQF4J3jUBZd0KlgMBrlNEhIUKk8LQAHT7RDxZAZWD0QxKYDxKJfADKSPgYHRm2EeE68QA …
> Improve JSON types

- package.json
- yarn.lock
This update includes support for TypeScript v4.1 features, such as template literal types.
> Update prettier from v2.1.1 to v2.2.1

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
- src/ControllerMessenger.test.ts
- src/ControllerMessenger.ts
Adds a controller messaging system, which will be used to facilitate inter-controller communication. The controller messenger acts as a message broker, passing actions and events back and forth between controllers. It is _fully type safe_.
This idea was described in the [Controller Messaging System proposal](https://www.notion.so/Controller-Messaging-System-617efb02b9e54bd0a0b0e44c6f776d85).
This controller messenger doesn't yet support attenuation, so it's not yet possible to restrict which actions and events are interacted with. That will be coming in a later PR.
> Add controller messaging system

- .eslintrc.js
At some point each of these three rules was disabled because there were lint violations present. Now there are none, so the entries disabling these rules have been removed.
* `'@typescript-eslint/no-shadow'`: We don't use this rule for some reason. We probably should, but until then we don't need to disable it.
* `@typescript-eslint/space-before-function-paren`: Our ESLint config repo (`@metamask/eslint-config`) was updated to match this in v4.0.0, so this override was redundant
* `jest/no-truthy-falsy`: This rule is disabled because it's deprecated in favour of `jest/no-restricted-matchers`.
> Remove unnecessary ESLint rules

- .eslintrc.js
- package.json
- yarn.lock
The `node/no-extraneous-require` and `import/no-extraneous-dependencies` rules have been re-enabled. The one violation was `ethereumjs-tx`, which is a module we are using that wasn't listed among our dependencies. It has been added, using the version that was being used in practice via another dependency (which was v1.3.7).
> Add missing dependency and disallow extraneous requires

- package.json
This field is recommended by the [TypeScript documentation about publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). It helps consumers find the type declarations.
> Add `types` manifest field

- package.json
- src/assets/AssetsController.ts
- src/message-manager/MessageManager.ts
- src/message-manager/PersonalMessageManager.ts
- src/message-manager/TypedMessageManager.ts
- src/transaction/TransactionController.ts
- yarn.lock
Our use of the dependency `uuid` is now type-checked. The imports have been updated to use `import` rather than `require`, and the package `@types/uuid` has been added to bring in type definitions.
> Ensure `uuid` is type-checked

- package.json
- yarn.lock
TypeScript has been [updated to v4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/). I'm not aware of any changes that impact our code.
`@typescript-eslint/eslint-plugin` and `typedoc` were both updated to a version that supports TypeScript v4.2.
> Update TypeScript to v4.2

- src/util.ts
`jsonschema` is now imported using `import` rather than `require`. This ensures that TypeScript is type checking our usage of the module, rather than typing it as `any`.
No other changes were required.
> Import `jsonschema` using `import`

- src/keyring/KeyringController.ts
The `signTransaction` method of the KeyringController had specified the wrong type for the `transaction` parameter. It mistakenly declared it as being of type `Transaction`, the same type we use in our Transaction controller.
Instead the type it expects is an instance of `ethereumjs-tx`. This package doesn't have type definitions though, so for now I've changed it to `unknown`, and updated the JSDoc comment to explain what it should be.
> Fix `signTransaction` transaction parameter type

- .eslintrc.js
This rule was mistakenly removed in #393. It was not unused - it was in fact enabled, and prevented variable shadowing.
I've added a comment explaining this. I've also added a comment explaining why `@typescript-eslint/indent` is disabled, so we don't make a similar mistake there in the future.
> Restore `@typescript-eslint/no-shadow` ESLint rule

- src/approval/ApprovalController.test.ts
The types used in the ApprovalController tests for sinon tests were wrong. `typeof sinon.spy` was being used to get the spy type, but this returns the type of the `spy()` function, not of a spy instance.
Instead the type `SinonSpy` is used instead. This type is provided by the `@types/sinon` package. For some reason it seems to provide more correct type information than `ReturnType<typeof sinon['spy']>`, though I'm not sure why.
The sinon import was updated to use `import` rather than `require` as well, as TypeScript seemingly doesn't type anything that is imported using `require`.
This introduced two new type errors caused by us using private methods in the test. I've silenced these errors for now by casting to `any`, but we should update these tests later to stop relying upon internals.
> Fix sinon types in ApprovalController tests

- src/keyring/KeyringController.test.ts
- tests/mocks/mockEncryptor.ts
The mock encryptor we use for the KeyringController tests has been migrated to TypeScript. It has also been converted from an object literal to a class, as it seemed a bit more conventional that way. The `encrypt` function is also no longer a sinon stub - the stub functionality was not used at all.
> Migrate mock encryptor to TypeScript

- src/assets/AccountTrackerController.ts
- src/assets/AssetsController.ts
- src/assets/CurrencyRateController.ts
- src/keyring/KeyringController.ts
- src/network/NetworkController.ts
- src/transaction/TransactionController.ts
`async-mutex` is now imported using `import` rather than `require`. This ensures that TypeScript is type checking our usage of the module, rather than typing it as `any`.
No other changes were required.
> Import `async-mutex` using `import`

- src/assets/AssetsContractController.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenBalancesController.ts
- src/transaction/TransactionController.ts
- src/util.test.ts
We have been using inconsistent types for token balances. We use a `BN` in most places, but if we fail to find a balance we set it to the number `0`.
We now use `BN` in all cases; `new BN(0)` is the fallback now instead of `0`.
This error was made possible because of various type errors surrounding `BN` and these balances. `typeof BN` was used as the type instead of `BN`, because `BN` was imported using `require` and TypeScript was treating it as a value rather than a class, and unhelpfully suggested using `typeof BN`. This resulted in the type being `any` in effect.
We now import `BN` using `import`, and use `BN` as the type.
This highlighted another problem as well: the return type of the `getBalancesInSingleCall` function in `AssetsContractController` was incorrect. It claimed to …
> Use consistent type for token balances

- .eslintrc.js
- package.json
- yarn.lock
The TypeScript lint rules were being applied to all files covered by the linter, including JavaScript files. Surprisingly this hasn't been much of an issue (I guess most of them are compatible with JavaScript too?), but it became an obstacle when trying to re-enable the rule `@typescript-eslint/no-shadow`.
TypeScript lint rules are now only applied to TypeScript files.
A new dependency was required to ensure we could import TypeScript modules from JavaScript modules. We do this in one place at the moment, in the JavaScript tests for the ApprovalController. Apparently the ESLint `import` plugin doesn't know how to resolve TypeScript modules without a custom resolver. We hadn't encountered this problem previously because `import/no-unresolved` was disabled in our TypeScript ESLint config, …
> Only apply TypeScript lint rules to `.ts` files

- .eslintrc.js
- src/ComposableController.ts
- src/assets/AssetsController.ts
- src/assets/CurrencyRateController.ts
- src/message-manager/AbstractMessageManager.test.ts
- src/network/NetworkController.ts
- src/third-party/EnsController.ts
- src/transaction/TransactionController.ts
- src/util.ts
The ESLint rule `@typescript-eslint/prefer-optional-chain` has been re-enabled. All rule violations have been updated to use the optional chain operator.
> Prefer optional chain

- .eslintrc.js
The rule `@typescript-eslint/no-unused-vars` has been re-enabled with a rule adjustment: sibling properties to the rest operator are now ignored. This is helpful for cases where you want to use the rest operator to _exclude_ certain properties, which we've done once in the NetworkController.
A TODO comment has been left about migrating this rule adjustment back into `@metamask/eslint-config`.
> Re-enable the `@typescript-eslint/no-unused-vars` rule

- src/transaction/TransactionController.ts
Allow the client to specify a nonce rather than using the network (but still falling back)
This is used in https://github.com/MetaMask/metamask-mobile/pull/2371
> Allow custom nonce

- .eslintrc.js
The rule `@typescript-eslint/member-delimiter-style` was being set with the exact same options used in `@metamask/eslint-config/config/typescript`. It was redundant, so it has been removed.
> Remove unnecessary ESLint rule override

- src/transaction/TransactionController.test.ts
- src/transaction/TransactionController.ts
The TransactionMeta type now uses an enum rather than a string for the `status` property. This enum also determines whether the `error` property is present. This allows us to get rid of the non-null assertion used previously to reference this `error` property, as the type system is now capable of determining that the property exists all on its own.
A default error was added for any failed transactions from the Etherscan API, as they didn't have an `error` property beforehand. The error simply states that the transaction failed, as unfortunately I don't know that there is any more information available about the nature of the failure.
> Improve TransactionMeta type

- src/BaseControllerV2.test.ts
- src/ControllerMessenger.test.ts
- src/apis/crypto-compare.test.ts
- src/approval/ApprovalController.test.ts
- src/assets/AssetsController.test.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/TokenRatesController.test.ts
- src/third-party/PhishingController.test.ts
- src/util.test.ts
- src/util.ts
- tsconfig.json
This flag makes it easier to work with ES5 dependencies in TypeScript, and it improves type checking for all dependencies by ensuring namespace imports aren't called accidentally. It is described in more detail in [the changelog where it was introduced](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop).
In particular, see this note:
>Note: The new behavior is added under a flag to avoid unwarranted breaks to existing code bases. **We highly recommend applying it both to new and existing projects**. For existing projects, namespace imports (`import * as express from "express"; express();`) will need to be converted to default imports (`import express from "express"; express();`).
Any …
> Enable `esModuleInterop`

- .eslintrc.js
- src/assets/AssetsController.ts
- src/keyring/KeyringController.test.ts
- src/keyring/KeyringController.ts
- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
- src/util.test.ts
- src/util.ts
The `default-case` ESLint rule has been re-enabled, and all violations have been addressed. Most of the default causes will throw an error, because the function couldn't function properly in that circumstance. There was one case (`getBuyURL`) where it seemed reasonable to return undefined, so the behaviour was left unchanged.
Tests have been added for any default cases in reachable code. One istanbul ignore comment was used for an unreachable default case.
> Re-enable `default-case` ESLint rule

- .eslintrc.js
- src/assets/AccountTrackerController.test.ts
- src/assets/AccountTrackerController.ts
- src/assets/AssetsContractController.test.ts
- src/assets/AssetsContractController.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenRatesController.test.ts
- src/assets/TokenRatesController.ts
- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
The `accessor-pairs` ESLint rule has been re-enabled, which requires any setter to have a corresponding getter (and vice-versa).
All of our rule violations were for properties that we use only as setters. In each case a getter was added that throws an error, which should help prevent accidental use of the getter. The default behaviour was to return `undefined`, which could lead to silent failures.
Long-term we should stop using setters like this. If we want to allow changing a property but not accessing, we can use a method. Methods are generally easier to understand than setters because it's clear to the consumer that side-effects are possible, and they have more informative type signatures (e.g. they can return a Promise when they perform some async operation, so that the caller knows …
> Re-enable `accessor-pairs` ESLint rule

- .eslintrc.js
- src/assets/CurrencyRateController.ts
- src/transaction/TransactionController.ts
- src/util.ts
The `consistent-return` ESLint rule has been re-enabled, and all rule violations have been fixed. Mostly this consisted of explicitly returning `undefined` in a few places, to reassure ESLint that it was intentional to return `undefined` in some branches but not others.
> Re-enable `consistent-return` ESLint rule

- src/index.ts
- src/notification/NotificationController.ts
- tests/NotificationController.test.ts
The controller adds the notifications to the state and keeps and updates the status of whether it is seen by the user or not. 
Associated to issue [#23](https://github.com/MetaMask/MetaMask-planning/issues/23)
> Add the controller for what's new notification for feature announcements 

- .eslintrc.js
- package.json
- src/assets/AccountTrackerController.test.ts
- src/assets/AccountTrackerController.ts
- src/assets/AssetsContractController.test.ts
- src/assets/AssetsContractController.ts
- src/assets/AssetsController.test.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/AssetsDetectionController.ts
- src/assets/TokenBalancesController.test.ts
- src/dependencies.d.ts
- src/keyring/KeyringController.test.ts
- src/keyring/KeyringController.ts
- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
- src/third-party/PhishingController.ts
- src/transaction/TransactionController.test.ts
- src/transaction/TransactionController.ts
- src/util.test.ts
- src/util.ts
- yarn.lock
The ESLint rule `@typescript-eslint/no-require-imports` has been re-enabled, which prevents using `require` to import modules. We have been using `require` in this codebase primarily to avoid the warning from TypeScript about each dependency that lacks types. That warning has been adding an empty declaration for each third-party module we use that lacks types. Effectively this declares them as type `any`.
> Disallow using `require` for imports

- src/message-manager/TypedMessageManager.ts
The `NetworkController` is lised as a required controller of the `TypedMessageManager` controller, but it is not used. It has been removed.
> Remove unused required controller

- src/keyring/KeyringController.ts
- src/user/PreferencesController.test.ts
- src/user/PreferencesController.ts
The `selectedAddress` state is now reset to the first identity if the current selected address is removed during an update. This is to ensure the `selectedAddress` is never set to an address that is not present in state.
This was already being done manually after each invocation of `updateIdentities` where account removal was anticipated. For mobile this is mostly a non-functional change, except that now this update happens in a single state update rather than over the course of two successive updates.
> Update `selectedAddress` when identities are updated

- src/assets/AssetsContractController.test.ts
- src/assets/AssetsContractController.ts
- src/assets/AssetsController.ts
Contract address validation has been added to the `getCollectibleTokenURI` method. This validation was already present in the one place where `getCollectibleTokenURI` is called, so overall this is basically a refactor with no functional changes, except that the API of each of these controllers has changed. It's a non-functional change from mobile's perspective though.
It might seem more appropriate to throw an error if the address isn't an NFT, rather than returning an empty string. But this is the pre- existing behaviour, so it has been preserved for now.
> Add contract address validation

- .eslintrc.js
- src/util.ts
This PR fixes one line that uses a "useless escape". I removed the escape character, as well as added the u flag, resolving two eslint issues. I then removed the disable for this rule in the eslint config.
> Remove no-useless-escape lint rule

- .eslintrc.js
The ESLint rule `@typescript-eslint/no-non-null-assertion` has been re-enabled. The last of the rule violations was removed in #406.
> Re-enable `@typescript-eslint/no-non-null-assertion`

- .eslintrc.js
- src/util.test.ts
This PR refactors 3 tests that do not use an expect statement. 
Two of such tests were checking if functions SafelyExecute and SafelyExecuteWithTimeout from utils would resolve even if an error was thrown. I refactored them by wrapping them in an await statement and expecting it to resolve. 
The last test aimed to make sure a parameterized function is called. It was done in a creative way that did not use expect. I refactored it by passing in a mocked function and checking that it was called correctly.
> Resolve Jest "expect-expect" lint rule

- .eslintrc.js
- src/assets/AssetsController.ts
The rules of this lint rule is outlined here: https://eslint.org/docs/rules/no-prototype-builtins 
I mimicked how they recommend we solve the lint issue. 
Simple two-liner! Removed lint rule from eslint config, refactored line that was causing the issue according to docs.
> Remove Lint Rule "no-prototype-builtins"

- .eslintrc.js
- src/BaseController.test.ts
- src/BaseControllerV2.test.ts
- src/ControllerMessenger.test.ts
- src/assets/AccountTrackerController.test.ts
- src/assets/AssetsContractController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/TokenRatesController.test.ts
- src/keyring/KeyringController.test.ts
- src/network/NetworkController.test.ts
- src/third-party/EnsController.test.ts
- src/util.test.ts
This PR aims to remove the eslint exception involving empty tothrow messages by replacing .tothrow() calls with .tothrow('error message').
> Add messages to empty tothrow calls

- src/notification/NotificationController.test.ts
The notification controller unit tests are now alongside the controller. They had accidentally been left in the `test` directory, because the re-organization of our tests in #354 was done after the notification controller had been written.
> Move Notification controller unit tests

- .eslintrc.js
- src/assets/AccountTrackerController.test.ts
- src/assets/AssetsController.test.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenRatesController.test.ts
- src/message-manager/MessageManager.test.ts
- src/message-manager/PersonalMessageManager.test.ts
- src/message-manager/TypedMessageManager.test.ts
- src/network/NetworkController.test.ts
- src/third-party/PhishingController.test.ts
- src/transaction/TransactionController.test.ts
This [rule](https://github.com/jest-community/eslint-plugin-jest/blob/v24.1.5/docs/rules/no-test-return-statement.md) triggers a warning if you use a return statement inside of a test body.
All tests that return a promise are instead awaited.
> remove ESLint no-test-return 

- .eslintrc.js
- src/assets/AccountTrackerController.test.ts
- src/assets/AssetsController.test.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenRatesController.test.ts
- src/message-manager/MessageManager.test.ts
- src/message-manager/PersonalMessageManager.test.ts
- src/message-manager/TypedMessageManager.test.ts
- src/network/NetworkController.test.ts
- src/third-party/PhishingController.test.ts
- src/transaction/TransactionController.test.ts
- src/util.test.ts
This PR adopts this pattern for async tests when testing exceptions: 
`await expect(yourFunction()).rejects.toThrow()`
> Use exception helpers instead of try catch 

- src/assets/TokenBalancesController.test.ts
- src/assets/TokenBalancesController.ts
The `BN` export was removed in #398. I hadn't anticipated at the time that this would constitute a breaking change. It turns out that this export was relied upon in mobile in one place.
It has been temporarily restored, along with a comment that suggests we remove it in the next major version.
> Restore `BN` export

- .eslintrc.js
A comment now explains why the ESLint rule `camelcase` is disabled. A comment explaining that the other rules should probably be re-enabled has also been added.
As we continue to re-renable these lint rules, we should ensure any modifications or disabled rules have comments explaining why the change from the default config was necessary.
> Add comment to explain why `camelcase` is disabled

- src/util.test.ts
- src/util.ts
This increases the maximum token length that can be suggested via `wallet_watchAsset` from 6 to 11, which matches the maximum symbol length for custom tokens added on the MetaMask extension.
> Support longer token symbols via `wallet_watchAsset`

- .eslintrc.js
- src/approval/ApprovalController.test.ts
- src/assets/AssetsController.test.ts
- src/message-manager/MessageManager.test.ts
- src/message-manager/PersonalMessageManager.test.ts
- src/message-manager/TypedMessageManager.test.ts
- src/transaction/TransactionController.test.ts
This PR refactors the way the tests catch errors. Currently they are wrapped in promises, but instead it can be refactored to use a jest trick of await expect(function).rejects.toThrow('error message'). Using this trick, we can remove this lint rule.
> Remove ESLint jest/valid-expect-in-promise

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
- src/ControllerMessenger.test.ts
- src/ControllerMessenger.ts
A method has been added to the controller messenger that returns a _restricted_ instance of the controller messenger. This instance is restricted to registering actions and events within a particular namespace, typically being the name of the controller. Access to event subscriptions and calling actions is also restricted based on the given allowlist for each.
This is meant to address feedback left on the [Controller Messaging System proposal](https://www.notion.so/Controller-Messaging-System-617efb02b9e54bd0a0b0e44c6f776d85).
> Add restricted controller messenger

- README.md
- src/BaseController.test.ts
- src/BaseController.ts
- src/ComposableController.test.ts
- src/ComposableController.ts
- src/assets/AccountTrackerController.test.ts
- src/assets/AccountTrackerController.ts
- src/assets/AssetsController.test.ts
- src/assets/AssetsController.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/AssetsDetectionController.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenBalancesController.ts
- src/assets/TokenRatesController.test.ts
- src/assets/TokenRatesController.ts
- src/keyring/KeyringController.test.ts
- src/keyring/KeyringController.ts
- src/transaction/TransactionController.test.ts
- src/transaction/TransactionController.ts
- src/user/PreferencesController.ts
We now setup inter-controller communication using dependency injection rather than the `context` property. Any dependency a controller has is passed in via a constructor parameter. This was done in preparation for migrating to BaseControllerV2 and the new controller messaging system - it's just a temporary solution that will let us migrate controllers one at a time.
The style of dependency injection here matches the extension (at least with the newer controllers anyway). Specific methods and state snapshots are injected rather than entire controllers, to help simplify unit tests and make it easier to understand how controllers interact.
The mobile PR that demonstrates this is here: https://github.com/MetaMask/metamask-mobile/pull/2416
> Use DI for controller communication rather than context

- src/ControllerMessenger.ts
The `ExtractEventHandler` type used internally in the ControllerMessenger module was mistyped as `ExtractEvenHandler`.
> Fix typo in internal ControllerMessenger type

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
- src/ControllerMessenger.test.ts
- src/ControllerMessenger.ts
The restricted controller messenger now allows omitting allowedActions and allowedEvents. Technically it already allowed this, but it required setting the type of the allowed actions/events to an empty string. Now the type is `never` if no actions/events are used.
> Optional AllowedEvents/AllowedActions

- src/BaseControllerV2.ts
- src/ComposableController.test.ts
- src/ComposableController.ts
- src/ControllerMessenger.ts
The ComposableController now supports controllers that are based upon BaseControllerV2. These newer controllers use the controller messaging system to communicate, so the messenger is now a required constructor parameter if any BaseControllerV2 controllers are used.
The `name` property in `BaseControllerV2` had to be made public for the ComposableController to properly construct its state. This seems OK. It was only kept private initially until a use was found for it.
> Add BaseControllerV2 support to ComposableController

- src/BaseControllerV2.test.ts
The unit tests for BaseControllerV2 have been updated to be more concise and (hopefully) slightly easier to read. The restricted controller setup was moved to a helper function, and common elements of various types were extracted and re-used.
There were a few cases where I could have used the controller name variable in a string literal, but chose not to (for example, the `allowedActions` string literals). This is because of the poor state of type inference right now for string literal types in TypeScript. They would get inferred as type `string` each time, which resulted in a type error. The only way to get it to work was to follow it with `as '[the string literal type]', which is strictly worse than just using the string literal in the first place. There are some improvements planned …
> Simplify BaseControllerV2 tests

- .eslintrc.js
Enables `jest/no-test-return-statement`. There were no violations of this rule.
> Enable jest/no-test-return-statement

- .eslintrc.js
- src/message-manager/AbstractMessageManager.test.ts
- src/message-manager/MessageManager.test.ts
- src/message-manager/PersonalMessageManager.test.ts
- src/message-manager/TypedMessageManager.test.ts
Following the closure of #423, this PR enables `jest/no-conditional-expect` and fixes all related errors.
I had to add manual type guards in some places per @Gudahtt's suggestion, since TypeScript does not understand that `expect(value).not.toBeUndefined()` guarantees that `value` is not undefined.
> Enable jest/no-conditional-expect

- .eslintrc.js
- src/ControllerMessenger.test.ts
- src/apis/crypto-compare.test.ts
- src/approval/ApprovalController.test.ts
- src/third-party/EnsController.test.ts
- src/user/AddressBookController.test.ts
This PR removes the local `jest/no-restricted-matchers` config. This amounted to replacing instances of `toBeTruthy` and `toBeFalsy` with more specific matchers. The removal of the config and the replacement of each matcher were split into separate commits for ease-of-review.
Fun fact: Every instance of `toBeTruthy` was just replaced with `toStrictEqual(true)` in a single find-and-replace operation.
~Pending #449~
> Remove restricted matchers exceptions

- src/BaseControllerV2.ts
- src/ControllerMessenger.ts
Apparently `never` is never needed in a type union. You can pass in `never` as _any_ generic parameter without there being a type error. I had not understood that `never` worked this way.
> Remove ineffectual `| never` type unions

- src/BaseControllerV2.ts
The `StateChangeEvent` type constraint was completely broken - it was functionally equivalent to `any`. This is because it operates _statically_ on the generic type parameter given, which was always `any` for the parameter `E`. And of course `any extends ___` always evaluates to `true`.
The type has now been simplified to use `any` directly.
> Remove redundant type constraint in BaseControllerV2

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
This allows getting the state of the controller via the controller messenger.
> Add `getState` action to BaseControllerV2

- src/BaseControllerV2.ts
- src/ComposableController.ts
When adding support for BaseControllerV2 to the ComposableController in #447, we accidentally removed support for using two different versions of the BaseController in the same ComposableController. This is because we used the `instanceof` operator to check whether a controller was extended from BaseController.
The `instanceof` check has been replaced by a check for the `subscribe` function. It seems unlikely that a BaseControllerV2 controller will ever have a `subscribe` function because the controller messenger will be used for all events.
> Restore ComposableController compatibility between different BaseControllers

- src/ComposableController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenRatesController.test.ts
The CurrencyRateController has been migrated to the new base controller. The configuration can now only be set during construction, as it was never changed at runtime in practice with the old controller. Similarly, the `disable` function was removed as it wasn't relied upon in practice.
One major change is that the controller doesn't poll after being constructed. The "start" method must be called for polling to start. The "start" and "stop" methods have been added to loosely follow the conventions used in `metamask-extension` to allow starting and stopping polling for the purpose of reducing network traffic.
A few tests required substantial updates because of this change. The ComposableController tests were easiest to fix by deleting the use of the CurrencyRateController completely, since …
> Migrate CurrencyRateController to BaseControllerV2

- src/BaseControllerV2.test.ts
- src/ControllerMessenger.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/CurrencyRateController.ts
The `getRestricted` method has been improved to further narrow the types of the restricted messaging controller. This allows BaseControllerV2-based controllers to have full type safety for their usage of the controller messenger.
The BaseController itself still doesn't have a type-safe controller messenger; that will be dealt with in a later PR (if we ever get it working).
> Improve restricted messenger types for controllers

- CHANGELOG.md
- package.json
- yarn.lock
The CHANGELOG is now using the KeepAChangelog format exactly, as required by our `@metamask/auto-changelog` tool. It has also been added as a dev dependency to make updating the changelog easier.
This can be tested by running the command: `yarn auto-changelog validate --repo https://github.com/MetaMask/controllers`
> Normalize CHANGELOG format

- src/BaseControllerV2.ts
- src/index.ts
Since `BaseControllerV2` states can't contain `unknown` values because of its stringent type checking, we should export the `Json` type that is defined in that module. Consumers will have to use something very much like it if they require something similar to `unknown` (i.e., a generic type that must be narrowed).
> Export `BaseControllerV2` `Json` type

- README.md
Updates the readme instructions for publishing following the deletion of the `master` branch and renaming `develop` to `main`. Also removes the reference and link to the auto docs for this package, which was already broken before we deleted the `gh-pages` branch.
> Add new publishing instructions

- src/assets/AssetsDetectionController.test.ts
- src/assets/AssetsDetectionController.ts
In `detectTokens()` of AssetsDetectionController, the check for the address value in the `Asset.state.tokens` list was defaulting to `false` as tokenAddress list is a list of `Token objects` instead of `address strings`, thereby sending all the tokens addresses in the contractMap for balance check even if it is already present in `Asset.state.tokens`.
The fix will be to map the `address string` to tokenAddresses list instead of `Token objects` and also check if the address from the contractMap is included in the tokenAddresses list while looping through each object in contractMap.
> Mapping token address strings instead of Token objects while checking for new tokens

- src/ComposableController.test.ts
- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
- src/transaction/TransactionController.test.ts
get tests passing for https://github.com/MetaMask/controllers/pull/494
> Update tests for draft gas controller

- src/util.test.ts
- src/util.ts
Fixes the decToGwei method by changing toFixed(3) to toFixed(9) and changing BN_1000 to BN_1GWEI_IN_WEI which was '1_000' but is now '1_000_000_000';
> Fix dec to gwi

- package.json
- src/dependencies.d.ts
- src/util.test.ts
- src/util.ts
- yarn.lock
I needed a hex wei to dec gwei conversion utility and i didn't see one existed. I also saw we already have ethjs-unit included as dependency of a dependency, this is what web3.js uses for its .toWei/.fromWei functions...
It uses BN under the hood but is far more robust than our utilities.
> use ethjs-unit for unit conversions

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/gas/gas-util.test.ts
- src/gas/gas-util.ts
1. must supply new method 'getIsMainnet' that will be called when polling to determine if, in the absence of EIP-1559 compatibility, the metaswaps API should be hit for gas estimates.
2. the old `fetchLegacyGasPriceEstimate` has been renamed to `fetchEthGasPriceEstimate` because eth_gasPrice is not legacy, it is just a fall back.
3. a new `fetchLegacyGasPriceEstimates` (note plurality Estimate**s**) is the method that will return metaswaps API estimates.
1. gasEstimateType will be returned in state as well, and can be any of 'none' | 'legacy' | 'fee-market' or 'eth_gasPrice'. A constant is exported to prevent issues with string typos. 
2. when receiving a gasPrice from eth_gasPrice the result will be returned in dec gwei instead of hex wei.
> Add metaswaps API and normalize all gas fee units to dec gwei

- src/gas/GasFeeController.ts
This makes it such that the state tree of the Gas Fee Controller is variable, but also known, and you can use `state.gasEstimateType === GAS_ESTIMATE_TYPES.FEE_MARKET` and the like to put Typescript in the branch that has the gasEstimate shape typed. This removes the need to have helper methods to check for object structure to identify type. 
This also has a 'NONE' state that can be used to identify states in which we can rely on no values (still loading values)
> update types to be more identifiable

- src/gas/GasFeeController.ts
Updates some documentation for clarity
> docs updates

- CHANGELOG.md
- package.json
This is identical to v10.2.0, except the major version number has been incremented to reflect that it includes a breaking change. v10.2.0 will be deprecated.
> v11.0.0 release

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/gas/gas-util.test.ts
- src/gas/gas-util.ts
This PR does the following:
1. renames 'getIsMainnet' to 'getCurrentNetworkLegacyGasAPICompatibility'
2. adds a 'getChainId' argument to the controller
3. adds support for providing API endpoint URLs int the controller
4. Supports replacing `<chain_id>` in provided URLs.
Goals:
1. Presumably if the API meets the spec put together in our mock data, we can swap out URLs without rebuilding/re-releasing
2. Support networks like Binance that has its own gas estimation API.
> make more configurable

- CHANGELOG.md
- package.json
proposed changelog: 
- Added GasFeeController to provide gas fee estimates [#494](https://github.com/MetaMask/controllers/pull/494)
- **BREAKING**: Added chainId support to TokenRatesControllers [#476](https://github.com/MetaMask/controllers/pull/476)
- The breaking change here is that TokenRatesController constructor now requires a onNetworkStateChange listener
- Added iconUrl to Token type in TokenListController [#512](https://github.com/MetaMask/controllers/pull/512)
> v12.0.0 release

- .github/workflows/build-lint-test.yml
- README.md
- package.json
The changelog is now validated during CI. The validation differs depending on whether the branch is a release branch or not, so the README was updated to clarify what naming convention we're now using for release branches.
The `repository` entry in `package.json` was updated to use HTTPS, because that is the format supported by `auto-changelog`.
> Add changelog validation to CI

- src/ComposableController.test.ts
- src/assets/AssetsDetectionController.test.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
- src/user/PreferencesController.test.ts
- src/user/PreferencesController.ts
If the user does not want to use the token service API to get the token details, this fallback to fetch from the `contract-metadata` will be called. The value of `useStaticTokenList` will determine which token list will be loaded to the TokenListcontroller state, the true value of which will call the Static token list from the `contract-metadata`, and a false value will fetch the token list from token service API. The cache will be stored only for when the token service API is used, when the user switch to the static token list the cache will be cleared.
> Adding a fallback for tokenList API service based on user preference

- .github/workflows/create-release-pr.yml
- .github/workflows/publish-release.yml
- README.md
The new release automation GitHub actions have been added, along with updated release instructions. This was all copied from the MetaMask module template.
The "License" section has also been removed from the README. It seemed pointless, since the LICENSE file is easy to find and highlighted by both GitHub and npm.
> Add release automation

- package.json
- src/assets/AssetsDetectionController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenRatesController.ts
- src/assets/TokensController.test.ts
- src/assets/TokensController.ts
- yarn.lock
Until we support collectibles in the extension, we need the controller that tracks token state to be aware of whether tokens are ERC721, in order to support behavior in the extension that prevents users from attempting to send ERC721 tokens and losing gas in a transaction we cannot execute. 
This PR adds the isERC721 flag to tokens in the TokensController with all of the required methods and wiring to land it in the extension (an upcoming PR in the extension repo).
> adding ERC721 detection to TokensController

- src/assets/TokensController.ts
revert error handling of supportsInterface method to catch all with no rethrow:
```
currently we see a variety of errors across different networks when
token contracts are not ERC721 compatible. We need to figure out a better
way of differentiating token interface types but for now if we get an error
we have to assume the token is not ERC721 compatible.
```
> revert error handling of supportsInterface method

- src/gas/GasFeeController.ts
This PR adds an `options` object to `fetchGasFeeEstimates` and `_fetchGasFeeEstimateData`. Options include `shouldUpdateState: boolean` property to decide wether to update state or not, `true` by default.
> Add options to GasFeeController fetchGasFeeEstimates

- package.json
- src/network/NetworkController.ts
- src/transaction/TransactionController.ts
- src/util.test.ts
- src/util.ts
- yarn.lock
EIP1559 functionality including speedUp and cancel.
This still needs to be updated with main, but I am going to move it out of Draft now as I think it's ready for initial review.
> Add EIP1559 support including `speedUpTransaction` and `stopTransaction`

- src/ControllerMessenger.ts
The unrestricted controller messenger implementation contained a couple of unnecessary calls to `Collection.set`. This PR removes them.
Every removed / changed instance consisted of mutating the object value (actually also collections) of some key in a collection, and then setting the key to the same object value. Mutating the object value of a collection does not affect the collection's reference to said object, so those calls were unnecessary.
> Remove uneccessary calls to Collection.set in contoller messenger

- src/assets/CollectiblesController.ts
- src/assets/TokensController.ts
This seeks to resolve a host of issues that can arise when token addresses with different casing slip through.
> Add case insensitive checks for token addresses in collectibles and tokens controllers

- src/gas/GasFeeController.ts
This is to deal with an edge case @danjm discovered where in the extension you can have a transaction in progress (which starts polling) and then if you switch network you're potentially getting the wrong quotes. This resets polling on network change if there's any polling already in progress.
> Reset polling onNetworkStateChange

- src/gas/gas-util.test.ts
- src/gas/gas-util.ts
- src/util.test.ts
- src/util.ts
`gweiDecToWEIBN` uses `toWei` from `ethjs-unit`
`toWei` will throw an error if it receives more than 9 decimal places when converting from gwei (because WEI cannot have decimal parts)
given that `gweiDecToWEIBN` can receive data from an external api, errors can happen if that data is flawed in having too many decimal places.
This PR ensures that such faulty data is correctly handled.
> Make gweiDecToWEIBN util resilient against params with too many decimals

- src/apis/token-service.test.ts
- src/apis/token-service.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
1. should throw if api returns a json error. api returns a 200 ok but with json error obj
we should check for that an elevate to an error
2. token lookup uri is wrong. fixed. (nice catch @NiranjanaBinoy !)
3. return types were wrong, fixed.
4. added fallback value for `safelyExecute` usage
5. removed unsound `safelyExecute` usage
i guess this is a breaking change bc types?
> TokenService improvements

- src/gas/GasFeeController.ts
- src/network/NetworkController.ts
This PR addresses the problem of the resetPolling being called on every network controller state change, so more frequent than necessary. We now check by chainId if the network changed and we don't update the network controller properties if they are the same.
> Fix `resetPolling` functionality

- src/BaseControllerV2.test.ts
- src/BaseControllerV2.ts
- src/ComposableController.test.ts
- src/ControllerMessenger.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenListController.ts
- src/gas/GasFeeController.ts
The new base controller now accepts the messenger type as a generic parameter, rather than hard-coding it to be `RestrictedControllerMessenger<N, any, any, string, string>`. This allows controllers to use the messenger directly without sacrificing any type safety.
Note: this is a **breaking change**, because anyone extending `BaseControllerV2` will now be required to supply an additional generic parameter.
> Improve BaseControllerV2 messenger type

- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
To make sure the TokenList id fetched from the API only when there is a change in chainId or UsestaticTokenList flag specifically and clear all previous polling interval schedules before scheduling a polling interval.
> Adding polling restart for TokenList Fetch

- src/util.ts
That which serves no purpose is to be eradicated.
Everything in the `export default` block was already a named export, so this quite literally serves no purpose. This is probably a breaking change anyway, but ¯\\\_(ツ)\_/¯
> Remove redundant default export from util.ts

- package.json
- src/assets/TokenListController.ts
- yarn.lock
**Add abort-controller polyfill**
- FIXED:
- Add abort-controller polyfill, which fixes the broken contract in release v15.0.0 where we introduced a use of AbortController without updating the node engine requirement in package.json to atleast node v15.0.0 where support for AbortController was added.
> Add abort-controller polyfill

- src/assets/TokenListController.ts
🤦 
- FIXED:
- Fixes error thrown when attempting to instantiate `AbortController` (polyfill) constructor as a named import. Despite the package seeming to support named imports, this change seems to be required for the TokenListController to not blow up.
> Change AbortController to default import

- src/apis/token-service.test.ts
- src/apis/token-service.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
Fixes #589 
Removing SyncToken functionality from TokenListController and token-service as usage of this function from our application may result in the API being syncing constantly.
> Removing syncToken functionality

- src/apis/token-service.ts
Fixes: #593 
We need to enable http caching for token API from our side
> Enabling http caching for token service

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
There was a bug in `getGasFeeEstimatesAndStartPolling` that could result in multiple fetch requests to the gas api being made, despite the `pollTokens` related logic meant to prevent this.
> If pollTokens is empty, it immediately fetches the gas estimates, but doesn't add the poll token until after the fetch has finished.
> So every single call will result in a new network request until the first one finishes. Then it will behave correctly and ensure only a single poll is active.
This PR fixes this by ensuring that the `pollTokens` are set before the asyncronous call. Tests are added that fail without this change and succeed with it.
> Fix bug that allowed for multiple fetch requests instantiate from getGasFeeEstimatesAndStartPolling

- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
Fixes #587 
For test networks, the tokenList object should be cleared as the API does not support the test networks and auto-detection should be disabled.
> Setting tokenList to empty object in test networks

- src/gas/GasFeeController.ts
- src/gas/gas-util.test.ts
- src/gas/gas-util.ts
**PR Title**
- Add optional clientId param to GasFeeController
We accept the clientId param in the GasFeeController and pass it into the gas api via the request header. This allows the gas api to determine the origin of each request and collect better metrics and thus perform better analysis to better understand bugs and user behavior across the clients.
I manually tested this change out on the extension. I passed `clientId: extension` into the GasFeeController instance and watched the client id header (e.g. `x-client-id: extension`) populate on every request to the gas api.
- ADDED:
- Add optional clientId param to the GasFeeController
- Assign param to object's `this` variable
- Pass `this.clientId` into fetchGasEstimates and fetchLegacyPriceGasEstimates calls
- From …
> Add client id header to GasFeeController

- src/BaseControllerV2.ts
- src/assets/TokenListController.ts
- src/gas/GasFeeController.ts
- src/index.ts
This removes the `IsJsonable` utility type from `BaseControllerV2`. We can get away with just using the `Json` type, and requiring that state generics extend `Record<string, Json>`.
With this change, `BaseControllerV2` state types may not contain any interfaces. Controllers that were using interfaces have been updated.
> Remove IsJsonable

- src/assets/TokenRatesController.test.ts
- src/assets/TokenRatesController.ts
- src/constants.ts
**Token Rates Controller Enhancement**
Currently we cannot provide fiat conversion rates for some custom networks (Polygon for one) [even though it is a supported coingecko platform](https://www.coingecko.com/api/documentations/v3#/asset_platforms/get_asset_platforms), because the native currency of the network [is not a supported vs_currency](https://www.coingecko.com/api/documentations/v3#/simple/get_simple_supported_vs_currencies) for querying exchange rates via their [exchange rate endpoint](https://www.coingecko.com/api/documentations/v3#/simple/get_simple_token_price__id_). This PR makes it possible to provide these fiat conversions by using `ETH` as a fallback vs_currency when the native currency is not supported and then simply updating the returned conversion rates so that they …
> Make TokenRatesController support fiat conversion for more networks

- src/gas/GasFeeController.ts
The return type of the `_fetchGasFeeEstimates` method (and the `fetchGasFeeEstimates` method, transitively) of the GasFeeController has been updated to remove the `| undefined`. It never returns `undefined`.
> Fix return type of `fetchGasFeeEstimates`

- src/ControllerMessenger.ts
These return statements would always return `undefined`. They have been removed to make the JSDoc comment easier to write in a later PR.
> Remove unnecessary return statements

- src/assets/CurrencyRateController.test.ts
- src/assets/CurrencyRateController.ts
**Update the conversionDate return *
- conversionDate value was always returned even when the fetch getPricingURL was failing (offline for example). Then, the extension is receiving the conversion date if there is no network. 
-  This issue is relate to https://github.com/MetaMask/metamask-extension/issues/10741. 
**FIXES:**  The purpose of this PR is to return a good timestamp if the fetch was a success otherwise null (like current conversionRate value )
**BREAKING:** Metamask extension now has to update the SettingsTab component. This is currently in progress in the PR https://github.com/MetaMask/metamask-extension/pull/12422
> Fix update conversionDate return

- src/approval/ApprovalController.ts
This was probably a bad idea to begin with, and ultimately not that helpful.
> Stop overloading ApprovalController.has signature

- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectibleDetectionController.ts
- src/assets/TokenDetectionController.test.ts
- src/assets/TokenDetectionController.ts
- BREAKING: Removes call to start polling from the constructors of CollectibleDetectionController and TokenDetectionController.
- Consumers of either of these Controllers who wish to immediately start polling upon instantiation will need to call the start method on the controller right after instantiating the controller.
> Remove polling start call in detection controllers' constructors

- src/gas/GasFeeController.test.ts
The tests for GasFeeController are currently lacking in a few ways:
* `nock` is being used to test that requests are being used to obtain
data; however, GasFeeController takes functions as arguments which can
be used to stub out those requests, thereby removing the need for
`nock`.
* The logic within `getGasFeeEstimatesAndStartPolling` is not being
fully exercised, specifically the polling code.
* There are no tests for `disconnectPoller`.
* There are no explicit tests for `stopPolling`.
* The logic within `_fetchGasFeeEstimateData` is not being fully
exercised, specifically with regard to  how the result of `getChainId`
changes the URL that ends up being hit for both EIP-1559 and
non-EIP-1559 flows.
* There are tests categorized under a `getChainId` describe block which
are actually for …
> Refactor and backfill GasFeeController tests

- src/ComposableController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectibleDetectionController.ts
- src/user/PreferencesController.test.ts
- src/user/PreferencesController.ts
As part of the security/UX prerequisites for bringing NFTs into the extension (and for enhancing security for in mobile) we are adding a user preference to allow users to toggle on or off collectible auto-detection, just as we have previously done with ERC-20 Token detection.
[NFT in Extension designs](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=772%3A10496):
This PR adds the preference to the PreferencesController and reads that setting in the CollectibleDetectionController to determine whether to detect/poll for collectibles.
> Add preference to enable/disable collectible detection

- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
It seemed to not make much sense to make a call to the CollectiblesController in the background to validate ownership, immediately before calling the same controller to add that collectible. This PR adds a new method `addCollectibleVerifyOwnership` which wraps the addCollectible method together with the validation step.
> Add new method `addCollectibleVerifyOwnership`

- src/assets/CollectiblesController.ts
In cases where a collectible contract that has been detected from OpenSea API does not have an image_url (collection logo), we should not short-circuit the auto-detection of the NFTs associated with that contract. It seems the original reasoning for this was that we assumed that the image_url (collection logo) was a good proxy for whether the contract had useable data. While testing development of NFTs on the extension I came across several instances where this was not a good proxy and valid NFT assets were not detected as a result. 
Context: If a contract is not added to CollectibleContracts state [we do not add the collectible to state](https://github.com/MetaMask/controllers/blob/3497fa8cad2a206d914bbac5d8914045467a39f5/src/assets/CollectiblesController.ts#L924)
- CHANGED:
- Modify …
> Modify requirements for adding opensea detected contract

- src/ComposableController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectibleDetectionController.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- src/user/PreferencesController.test.ts
- src/user/PreferencesController.ts
- BREAKING:
- openSeaEnabled preference is introduced and defaulted to false on the preferencesController. This value is used to determine whether the collectiblesController makes use of OpenSea's API for fetching collectible data.
- Consumers who use the collectibleDetectionController and collectibleController who wish to continue use of OpenSea's API will either need to configure openSeaEnabled to true after instantiating the controller now or expose a toggle for users to change the openSeaEnabled state in the preferences controller.
- FIXED:
- fixes issue introduced in https://github.com/MetaMask/controllers/pull/638 where polling collectibleDetection polling was not properly stopped when useCollectibleDetection preference is set to false.
> add openSeaEnabled preference

- src/ComposableController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectibleDetectionController.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- REMOVED
- [BREAKING] Both `collectibles` and `collectibleContracts` are removed from `CollectiblesController` state. 
- FIXED:
- [BREAKING] Change auto detection from `boolean` to an object containing `address` and `chainId` that was used to autodetect.
**Checklist**
**Issue**
Related https://github.com/MetaMask/metamask-mobile/issues/3335
> Add detection params (userAddress, chainId) and remove duplicate source of truth

- src/assets/CollectiblesController.ts
- FIXED:
- Fix issue where chainId is formatted differently in manual collectible add and detection add flows.
> adapting new collectiblesController shape

- src/assets/CollectibleDetectionController.ts
- src/assets/CollectiblesController.ts
- REMOVED:
- Removes the chainId format normalization introduced in https://github.com/MetaMask/controllers/pull/644 and adapted for in https://github.com/MetaMask/controllers/pull/648
- This normalization was not needed and caused issues when consumers had chainId formats other than decimal.
> remove chainid normalization

- src/assets/CollectibleDetectionController.ts
- src/assets/CollectiblesController.ts
- FIXED:
- Avoid overwriting `collection` property from `getCollectibleInformation`, this was causing `collection.image_url` to be `null`.
**Checklist**
> Fix collectibles collection images

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/gas/determineGasFeeCalculations.test.ts
- src/gas/determineGasFeeCalculations.ts
We would like to introduce another fallback to how we estimate gas fees
in a future commit — namely, we want to use `eth_feeHistory` for
EIP-1559 networks if the usual API is down. To do this, the existing
code around gas fee estimates needs to be refactored. This is the first
in a two-part refactor, extracting the majority of the code in
`GasFeeController._fetchGasFeeEstimateData` to `gas-util`. In addition
to making room for more changes, this also allows us to test this code
in isolation from the polling code that already exists in
GasFeeController.
Note that I am using the term "calculations" to encompass the data that
`_fetchGasFeeEstimateData` returns. This is because `gasFeeEstimates` is
an intermediate value that can also be packaged with
`estimatedGasFeeTimeBounds`, so …
> Extract determineGasFeeCalculations

- package.json
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- src/util.test.ts
- src/util.ts
- yarn.lock
- CHANGED:
-**BREAKING** Change IPFS URL generation to use subdomains and [cidV1s over cidV0s](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats), in order to enhance [origin based security](https://docs.ipfs.io/concepts/ipfs-gateway/#subdomain) in our use of IPFS assets
- Consumers using IPFS Gateway which do not support subdomain formats will need to set the new config value 'useIPFSSubdomains' on CollectiblesController to false in order to have continued IPFS resolution support.
> Fix ipfs address generation

- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
Feature to allow the user to set a collectible as favorite. This logic was implemented in the mobile app layer, but for simplicity it was decided to move it to the controllers layer.
- [MM Mobile PR ](https://github.com/MetaMask/metamask-mobile/pull/3373)
> [FEAT] Favorite Collectibles

- src/approval/ApprovalController.test.ts
- src/approval/ApprovalController.ts
`ApprovalController.clear` rejects all pending approvals and clears the state of the controller. This PR adds a "rejection error" parameter to the `clear` method and removes the default error. We decided that there is no reasonable default for this method, since `clear` may be called for a variety of different reasons.
> Add caller-specified error for ApprovalController.clear

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/gas/determineGasFeeCalculations.test.ts
- src/gas/fetchBlockFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.ts
- src/gas/gas-util.ts
[The Metaswap API now includes a `networkCongestion` property when
requesting EIP-1559-compatible gas fee estimates.][1] This value, which is a
number from 0 to 1, where 0 represents "not congested" and 1 represents
"extremely congested", can be used to communicate the status of the
network to users when they are sending transactions.
This commit ensures that GasFeeController includes `networkCongestion`
as part of the state it persists, no matter if using the Metaswap API to
obtain this information or falling back to `eth_feeHistory`.
This is a part of the EIP-1559 v2 work.
[1]: https://gitlab.com/ConsenSys/codefi/products/metaswap/gas-api/-/commit/e5d56eded4a2d23118464a2c6df32c75a3b058e5
> Pull in networkCongestion along with gas estimates

- src/constants.ts
- src/gas/fetchBlockFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/BlockFeeHistoryDatasetFetcher.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateNetworkCongestion.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateNetworkCongestion.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/fetchLatestBlock.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/medianOf.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/types.ts
In future commits we will bring in more gas fee related data points from
the MetaSwap API. When we do this, we will have to implement fallbacks
for all of these data points. Every data point is different and will
require a different strategy and different testing. This commit breaks
up the existing fallback code so this is a lot easier to do.
> Refactor EIP-1559 v2 fallback code to ease expansion

- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/gas/determineGasFeeCalculations.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/BlockFeeHistoryDatasetFetcher.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateBaseFeeRange.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateBaseFeeRange.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateBaseFeeTrend.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateBaseFeeTrend.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeRange.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeRange.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeTrend.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeTrend.ts
- src/gas/gas-util.ts
Several new properties are now available from the `/suggestedGasFees`
endpoint in the MetaSwap API. This commit updates GasFeeController to
store these properties in state when polling for gas fee estimates and
implements fallback code for the underlying datapoints. This way we can
use these values to display different UI elements to users when they are
sending transactions.
The properties are:
* `historicalBaseFeeRange` — minimum and maximum values for the base
fees over the past 200 blocks
* `baseFeeTrend` — an indicator for which direction the base fee is
moving based on the current pending block vs. the latest block
* `latestPriorityFeeRange` — minimum and maximum values for the priority
fees in the latest block
* `historicalPriorityFeeRange` — minimum and maximum values for priority …
> Pull in remaining EIP-1559 v2 datapoints

- src/gas/fetchBlockFeeHistory.test.ts
- src/gas/fetchBlockFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/BlockFeeHistoryDatasetFetcher.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeRange.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculatePriorityFeeTrend.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/fetchLatestBlock.ts
After integration-testing both the fallback and non-fallback code
responsible for pulling gas fee estimates, there were a few fixes
needed:
* `ethQuery.latestBlock()` was not being called correctly.
* For some datapoints, we need to pull the estimated base fee for the
next block. This adds an `includeNextBlock` option to
`fetchBlockFeeHistory` so that this is possible. It also splits the
`FeeHistoryBlock` type into two types, because the next block won't
have information about gas used ratios or priority fees (because there
is no transaction data associated with the next block, as it doesn't
exist).
* One of the allowed values for the `endBlock` argument to
`fetchBlockFeeHistory` was "pending". This breaks
`fetchBlockFeeHistory`, so this has been removed.
* Some of the datapoints were …
> Add finish to EIP-1559 v2 gas estimate code 

- package.json
- src/dependencies.d.ts
- src/keyring/KeyringController.ts
- src/util.ts
- yarn.lock
**PR Title**
- Use `stripHexPrefix` from `ethereumjs-util` instead of `ethjs-util`
_this imports a utility function from a different dependency so we can remove `ethjs-util`_
> Use stripHexPrefix from ethereumjs-util and ditch ethjs-util

- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- ADDED:
- Adds `isCurrentlyOwned` field to the Collectible Type and a method to check whether each of the collectibles in state collection associated with currently active address/chainId combination are still owned by this address and update this new `isCurrentlyOwned` value accordingly.
> Add method to check and update collectible ownership state

- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- ADDED:
- Adds an optional parameter `accountParams` (an object containing a `userAddress` and `chainId`) to method `checkAndUpdateSingleCollectibleOwnershipStatus`, which when uses the passed `userAddress` and `chainId` to find the collectible that should be updated.
> Enhance checkAndUpdateSingleCollectibleOwnershipStatus to use use passed accountParams for selectedAddress and chainId

- src/assets/Standards/ERC20Standard.ts
- CHANGED:
- Makes the `userAddress` argument to the `getDetails` method on the ERC20Standard class optional.
> small improvement to ERC20Standard class

- src/permissions/endowments/network-access.test.ts
- src/permissions/endowments/network-access.ts
Expose `WebSocket` for network access endowment.
- ADDED:
- Expose `WebSocket` for network access endowment.
**Checklist**
> Expose WebSocket for network access

- src/ComposableController.test.ts
- src/assets/AssetsContractController.test.ts
- src/assets/AssetsContractController.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/Standards/CollectibleStandards/ERC1155/ERC1155Standard.ts
- src/assets/Standards/CollectibleStandards/ERC721/ERC721Standard.test.ts
- src/assets/Standards/CollectibleStandards/ERC721/ERC721Standard.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenDetectionController.test.ts
- ADDED:
- **BREAKING** Adds functionality to fetch and return token images as part of `getDetails` calls on ERC721Standard and ERC1155Standard
- This change is breaking because it requires that the AssetsContractController (on which the ERC721Standard and ERC1155Standard are instantiated) be passed a listener for `onPreferencesStateChange` from the `PreferencesController` so that it can use the user's preferred IPFSGateway to fetch any images hosted on IPFS. Consumers will have to pass `onPreferencesStateChange` in an options object (first arg) to the AssetsContractController constructor when initializing.
Resolves #689
> **BREAKING**: Fetch and return token image as part of `getDetails` calls on ERC721Standard and ERC1155Standard

- src/gas/fetchGasEstimatesViaEthFeeHistory.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/BlockFeeHistoryDatasetFetcher.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/BlockFeeHistoryDatasetFetcher.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateNetworkCongestion.test.ts
- src/gas/fetchGasEstimatesViaEthFeeHistory/calculateNetworkCongestion.ts
Usually we use the MetaSwap API for gas fee estimates, but if that is
down for some reason, we fall back to hitting Infura directly.
A little while ago we were working on some UI improvements to the
extension around gas fees, and to support this some changes to the
MetaSwap API were made so that it requests the last 20,000 blocks from
the network and uses their data to obtain a baseline for base fees so
that we can display a network stability/congestion meter.
We made the same changes to the gas fee estimation fallback logic.
**This ended up being a very bad decision.** Because none of the the
requests to Infura that the fallback logic makes are cached, when the
MetaSwap API goes down, the number of requests made to Infura
skyrockets and Infura suffers performance-wise. This problem …
> Reduce load on Infura in gas estimate fallback

- src/gas/fetchBlockFeeHistory.test.ts
- src/gas/fetchBlockFeeHistory.ts
**PR Title**
GasController: Don't fall back to eth_gasPrice if node returns empty fee history
go-ethereum based chains never return empty baseFeePerGas because this is omitted in the serializer:
```
type feeHistoryResult struct {
OldestBlock  *hexutil.Big     `json:"oldestBlock"`
Reward       [][]*hexutil.Big `json:"reward,omitempty"`
BaseFee      []*hexutil.Big   `json:"baseFeePerGas,omitempty"` <---
GasUsedRatio []float64        `json:"gasUsedRatio"`
}
```
Current code checks for `baseFeePerGas.length > 0` without checking for the occurence of this element.
This leads to an exception and in later flow to fallback to eth_gasPrice mode
- FIXED:
no feeMarket mode available in case one of past requests return no results
**Checklist**
**Issue**
> [GasController] Check for undefined basefeePerGas

- src/ratelimit/RateLimitController.test.ts
- src/ratelimit/RateLimitController.ts
Fix an issue with RateLimitController where we applied the timeout too aggressively
- CHANGED:
- Changed RateLimitController to only apply timeout once for each time window
**Checklist**
> Fix RateLimitController aggressive timeout issue

- src/assets/AssetsContractController.ts
- CHANGED:
- Make `getTokenStandardAndDetails` function signature reflect that the second arg is optional. Consumers of this method can continue to pass the `userAddress` as a second option if they are wanting to query for the user balance of an ERC20 token.
> Make getTokenStandardAndDetails function signature reflect that the second arg is optional

- src/keyring/KeyringController.test.ts
- src/keyring/KeyringController.ts
Fixes: https://github.com/MetaMask/pm-security/issues/45
Catch and ignore errors thrown by `ethereumjs-util` methods `toBuffer` or `isValidPrivate` while importing an account. Throw an error we control (`Cannot import invalid private key.`) instead.
> Catch errors thrown from ethereumjs-util methods in keyring controller

- package.json
- yarn.lock
**Bump dependency version eth-phishing-detect**
- Bumps dependency version of `eth-phishing-detect` to include logic to convert absolute fully qualified domain name to the fully qualified domain name
- BREAKING:
- FIXED:
- CHANGED:
-  Dependency version
- REMOVED:
- 
- ADDED:
- 
- DEPRECATED:
-
- SECURITY:
- 
**Checklist**
**Issue**
Resolves #???
> Bump dependency version eth-phishing-detect

- __mocks__/uuid.js
- package.json
- src/assets/AccountTrackerController.test.ts
- src/assets/AccountTrackerController.ts
- src/keyring/KeyringController.test.ts
- src/keyring/KeyringController.ts
- yarn.lock
**Add QR hardware support**
- CHANGED:
- Change `signTypedMessage` method to support QR hardware. 
- ADDED:
- Add QR hardware Keyring 
- Add QR hardware's interactive methods, including read keyring, submit signature and related methods.
**Checklist**
> Support QR hardware

- .gitattributes
This normalizes line endings and instructs GitHub not to collapse
`yarn.lock`.
> Copy .gitattributes from template repo

- tsconfig.build.json
- tsconfig.json
A previous commit updated the TypeScript configuration so TypeScript
would better recognize type definition files whose purpose was to
backfill types for existing packages. After testing, this revealed a
misunderstanding of the `paths` option in `tsconfig.json`.
It turns out that `paths` completely overrides how TypeScript resolves
modules and locates type definition files for modules. The consequence
of this option is that if a module includes type definitions, but we
also supply type definitions for that module in `types/`, then our type
definitions will win. This degrades the developer experience: sometimes,
a package already has types, but we merely need to *augment* those
types in some way. The `paths` option makes it impossible to do this.
This commit keeps the `types/` directory …
> Fix inclusion of module-augmenting .d.ts's

- package.json
- yarn.lock
Bumps @lavamoat/allow-scripts to version 2.0.2. This required re-running `yarn allow-scripts auto` and rewriting most of the LavaMoat config.
> @lavamoat/allow-scripts@2.0.2

- src/permissions/PermissionController.test.ts
- src/permissions/PermissionController.ts
Adds a controller messenger action for `PermissionController.revokePermissionForAllSubjects`. We currently call the underlying function directly in the extension, but we'd like to encapsulate that call in the `SnapController`, which is where it should occur.
> Add `PermissionController.revokePermissionForAllSubjects` action

- .github/workflows/publish-release.yml
It would appear that `github.event.pull_request.base.sha` is actually _not_ what we want here.
Instead we use `github.sha` which will ensure we get the "The commit SHA that triggered the workflow run."
Additionally we set `ignore-scripts true` in our npm config so we can skip the `prePublish` step (which runs `yarn build` again).
> Use `github.sha` for publish jobs

- src/permissions/PermissionController.test.ts
- src/permissions/PermissionController.ts
This is needed to allow a new UI page for Snaps. We want to ask the user for approval for an update, showing new permissions on the same page. This will be implemented as a new ApprovalController request in SnapController and then call to grantPermissions in PermissionController. Related PR: https://github.com/MetaMask/snaps-skunkworks/pull/322
> Added GrantPermissions action to PermissionsController

- package.json
- yarn.lock
The update to TypeScript v4.3 includes no changes that require updates. It does include many new features that we can now take advantage of though, like the new `override` keyword and `#private` class elements.
See the release announcement for more details: https://devblogs.microsoft.com/typescript/announcing-typescript-4-3
The TypeScript ESLint modules required updating in order to support the new `override` keyword.
> Update to TypeScript v4.3

- src/ComposableController.test.ts
- src/ComposableController.ts
- src/assets/AccountTrackerController.ts
- src/assets/AssetsContractController.ts
- src/assets/CollectibleDetectionController.ts
- src/assets/CollectiblesController.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenBalancesController.ts
- src/assets/TokenDetectionController.ts
- src/assets/TokenListController.ts
- src/assets/TokenRatesController.ts
- src/assets/TokensController.ts
- src/gas/GasFeeController.ts
- src/keyring/KeyringController.ts
- src/message-manager/AbstractMessageManager.ts
- src/message-manager/MessageManager.ts
- src/message-manager/PersonalMessageManager.ts
- src/message-manager/TypedMessageManager.ts
- src/network/NetworkController.ts
- src/permissions/errors.ts
- src/third-party/EnsController.ts
- src/third-party/PhishingController.ts
- src/transaction/TransactionController.ts
- src/user/AddressBookController.ts
- src/user/PreferencesController.ts
The `override` keyword has been added in all places where we are overriding a method or field. This was done by temporarily enabling the `noImplicitOverride` flag. I didn't leave the flag set because there is still an error to resolve in a dependency before we can leave it on.
> Add `override` keyword

- src/util.test.ts
- src/util.ts
The `retry` parameter of `safelyExecute` was unused, so it has been removed. Generally this parameter does not seem useful, and we are trying to remove all uses of this function anyway.
This makes updating to TypeScript v4.4 slightly easier, because the invocation of the retry function is a type error on that version (because `error` is `unknown`).
> Remove unused `retry` parameter from `safelyExecute`

- src/apis/token-service.test.ts
- src/assets/CollectiblesController.test.ts
These describe blocks reference a method name. The capitalization now matches the method name.
> Fix the capitalization on two describe blocks

- src/apis/token-service.test.ts
- src/apis/token-service.ts
The tests for the token service API have been expanded to cover error scenarios.
A new timeout optional parameter was added to make testing easier. The default timeout remains unchanged.
> Add token service timeout param and improve tests

- jest.config.js
- src/assets/CurrencyRateController.test.ts
The `restoreMocks` Jest setting has been enabled, which will automatically restore any mocks created using Jest after each test. See here for more information: https://jestjs.io/docs/configuration#restoremocks-boolean
Note that this will not affect standalone Jest mocks. It only affects mocks that replace a method/field on a pre-existing object.
A manual mock restoration was removed from the CurrencyRateController tests, as the mock should now be restored automatically instead.
> Enable `restoreMocks` Jest setting

- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenDetectionController.test.ts
Sinon uses the "default sandbox" by default, and this is sufficient for everything we are using Sinon for. People tend to use the `createSandbox` method because they misunderstand how sandboxes work. This often results in interwoven use of a module-specific sandbox and the default sandbox, which leads to errors.
Instead we should use the default sandbox and restore it after each test.
> Remove sinon sandboxes

- src/BaseController.test.ts
- src/BaseControllerV2.test.ts
- src/ComposableController.test.ts
- src/approval/ApprovalController.test.ts
- src/assets/AccountTrackerController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CurrencyRateController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenDetectionController.test.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenRatesController.test.ts
- src/assets/TokensController.test.ts
- src/gas/GasFeeController.test.ts
- src/keyring/KeyringController.test.ts
- src/network/NetworkController.test.ts
- src/third-party/PhishingController.test.ts
- src/transaction/TransactionController.test.ts
`sinon.restore()` is now called after each test in any test suite that uses `sinon` for anything. This is recommended by the Sinon docs in their general setup instructions to avoid memory leaks.
> Call `sinon.restore()` after each test using sinon

- package.json
- src/BaseControllerV2.ts
- src/apis/token-service.ts
- src/approval/ApprovalController.ts
- src/assets/CollectiblesController.ts
- src/assets/CurrencyRateController.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenRatesController.ts
- src/assets/TokensController.ts
- src/gas/determineGasFeeCalculations.ts
- src/keyring/KeyringController.test.ts
- src/permissions/PermissionController.ts
- src/util.test.ts
- yarn.lock
See the release announcement for more details about v4.4: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/
The main breaking change that affected us was the change in the default type of the `catch` error parameter from `any` to `unknown`. This was resolved in some places by changing the expected type to `unknown`. In cases where we need it to be an `Error` or where we use an `Error` property, the type is now checked at runtime.
A minor change was needed in `BaseControlelrV2` as well, because TypeScript wasn't happy with the fact that it was never initialized for some reason, even though it wasn't supposed to be initialized (it was set to `never`). But initializing it as `undefined` serves the exact same purpose and resolved the error.
> Update TypeScript to v4.4

- package.json
- yarn.lock
See the TypeScript v4.5 release announcement for more information: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/
None of the breaking changes affected this repository.
> Update TypeScript to v4.5

- package.json
- yarn.lock
See the TypeScript v4.6 release announcement for more information: https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/
This update included no breaking changes for this repository.
Closes #792
> Update to TypeScript v4.6

- src/apis/token-service.test.ts
- src/apis/token-service.ts
Throw on failure for fetchTokenMetadata in token service
1 of 7 PRs for https://github.com/MetaMask/controllers/pull/763
> [Token Detection V2] 1 of 7 - Throw on failure for fetchTokenMetadata in token service

- src/util.test.ts
- src/util.ts
Add enum and util to check for supported token detection networks
2 of 7 PRs for https://github.com/MetaMask/controllers/pull/763
> [Token Detection V2] 2 of 7 - Add enum and util to check for supported token detection networks

- src/apis/token-service.test.ts
- src/apis/token-service.ts
Reverts [this commit](https://github.com/MetaMask/controllers/commit/d4030cff97344d6a919bfc0cf1dc786e771e27b5) so that we can cut a patch release for this package (v29.0.1). Will re-add this commit after the release is cut/published.
> Revert "[Token Detection V2] 1 of 7 - Throw on failure for fetchTokenMetadata in token service (#812)"

- src/apis/token-service.test.ts
- src/apis/token-service.ts
This reverts commit a25d90906137f85ea9853018f7c3fbe0cfd67df1. It was temporarily reverted to avoid making a breaking change in v29.0.1.
The original PR was #812, and it was reverted in #824.
> Revert "Revert "[Token Detection V2] 1 of 7"

- src/ComposableController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
- src/constants.ts
Addresses subtasks on https://github.com/MetaMask/metamask-extension/issues/13477
**BREAKING** - add method `trackMetaMetricsEvent` passed to `CollectiblesController` in options object to and call it to broadcast `Token Added` event when a `collectible`/`nft` is added to state.
> NFT auto detect metrics

- src/assets/Standards/CollectibleStandards/ERC1155/ERC1155Standard.ts
- src/assets/Standards/CollectibleStandards/ERC721/ERC721Standard.test.ts
- src/assets/Standards/CollectibleStandards/ERC721/ERC721Standard.ts
Some ERC721 contracts (e.g. [Decentraland](https://etherscan.io/address/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d#readProxyContract)) only partially implement the metadata interface ([described in the original EIP](https://eips.ethereum.org/EIPS/eip-721)). We should query for fields included on the interface (`name`, `symbol` and `tokenURI`) regardless of whether or not the interface is fully implemented.
- CHANGED:
- Removed requirement that EIP721 metadata be fully implemented to query for `name`, `symbol` and `tokenURI` fields on a contract.
**Checklist**
**Issue**
Resolves https://github.com/MetaMask/metamask-extension/issues/14459 & https://github.com/MetaMask/metamask-extension/issues/14589 & https://github.com/MetaMask/metamask-extension/issues/14518
> Query for name and symbol on ERC721 contracts regardless of whether or not they support the metadata interface

- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
This is a part of #763 
Based on the recent conversation with the core team, a proposal was made to update the `polling interval for the token list api to 24 hrs` rather than the current 1 hour and we are also updating the `occurrences limit to 3`, ie the dynamic list will contain only those tokens that will be present in at least 3 lists/aggregators.
Related Notion doc: 
https://www.notion.so/Improve-token-detection-support-custom-networks-aka-TDF-v2-fb3ef7b7299c4ddb8e9481c2b22f1e87#af9a0a475d024c5d8e8ada65cf9e764f
> [Token Detection V2] Refining the polling interval and the occurrences limit for the Dynamic token list

- .github/workflows/publish-release.yml
This adds a dry run publish just prior to the actual npm publish so the person approving the publish can check the dry-run output of the preceding job to verify the publish does what's expected.
I've tested this action using a similar flow in a personal project here: https://github.com/rickycodes/card/actions/runs/2391846238
> Add dry run publish just before actual publish

- src/assets/CollectiblesController.test.ts
- src/assets/CollectiblesController.ts
The `onCollectibleAdded` constructor parameter for the `CollectiblesController` is now optional. This parameter is meant for making it easier to add metrics. If the caller does not need to use this event, there is no reason to require it.
**Checklist**
> Make `onCollectibleAdded` parameter optional

- src/apis/token-service.ts
- src/assets/TokenListController.ts
- src/assets/assetsUtil.ts
- src/constants.ts
- src/util.test.ts
- src/util.ts
A semi breaking change was introduced here https://github.com/MetaMask/controllers/pull/806/files#diff-c2ec75b01a3b2e2e1284df7c48ad4c80a26ea7f1455167cc8390d91ca865b854R149 which prevents an [extension e2e test](https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/tests/add-hide-token.spec.js#L69) which mocks an API request for the token-list [here](https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/mock-e2e.js#L128) from working properly.
cc @Cal-L
> Add local ganache network chainId as a SupportedTokenListNetwork

- src/assets/TokenDetectionController.test.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
We are introducing a new state variable `preventPollingOnNetworkRestart` which has a default value of `false` in order to prevent third-party token list polling while changing the network when token detection is OFF. This is intended for use in the extension now in order to enable the user from opting out of using the third-party api. A true value for the variable will clear out the `tokenList` and `tokensChainsCache` and we are stopping the polling from the extension side and a false value will restart the polling and continue with the previous behavior.
> Prevent third party token list polling in the Extension when token detection is OFF

- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
preventPollingOnNetworkRestart property is introduced in [#861](https://github.com/MetaMask/controllers/pull/861) to prevent the third party token list fetch in extension during network restart. This property should be optional as this is extension-specific and can be avoided on mobile.
> Making preventPollingOnNetworkRestart optional in TokenListController

- .github/workflows/publish-release.yml
- package.json
- scripts/check-version.sh
- scripts/prepack.sh
This introduces some changes to our publishing configuration such that we release from `main` instead of `release/*` branches
<strike>I'm opening this as a WIP Draft PR because this relies on: https://github.com/MetaMask/action-publish-release/pull/46 and a release of it.</strike>
(that's been addressed now and this is fully ready)
I've created a script for `prepack` that can be skipped in CI via `SKIP_PREPACK` environment variable. this is because we don't want a new build in CI prior to publish, we just want to pick up the cache from the previous build. <strike>I still needed to cache `node_modules` because yarn now complains about the state file and it'll halt you from running any yarn scripts if that's not in order (even if we're not using those files for the actual …
> Fix publishing configuration, closes #858

- .github/workflows/publish-release.yml
in #873 I added several filters to steps and @mcmire had some feedback:
> I wish we could only check for IS_RELEASE == 'true' a few times
so I thought on it and realised that the `check-release` _step_ could instead be a _job_ and the following jobs would rely on it.
This removes the need for so many `if:` filters
example of a skip: https://github.com/rickycodes/controllers/actions/runs/2657273697 (again this should only happen if the GitHub actions bot should do something _other_ than release... which hasn't happened in this repository... _yet_).
example of release: https://github.com/rickycodes/controllers/actions/runs/2657220356 (again, last publish job is failing because the `NPM_TOKEN` is not correctly set in that environment).
> turn check-release step into job

- src/index.ts
We need to use `formatIconUrlWithProxy` in extension for formating the token iconURL to proxy for the tokens from swap API. Since the extension is currently using a static token list for the scenario when token detection is OFF on MAINNET, we cannot use the proxy iconUrl from the dynamic token list as the default one for swap.
> Exporting formatIconUrlWithProxy to format iconUrl Proxy for tokens from swaps api

- .github/workflows/publish-release.yml
Slight update to the filter to ensure it also meets criteria in the off chance the release PR is merged without squash.
> Update `is-release` filter

- src/permissions/Caveat.test.ts
- src/permissions/Caveat.ts
- src/permissions/Permission.ts
- src/permissions/PermissionController.test.ts
- src/permissions/PermissionController.ts
- src/permissions/errors.ts
This PR adds caveat support for endowment permissions, see the linked issue for why this is needed now. This is mainly a typing change, but adds a small defensive validation measure to prevent type mismatches.
- CHANGED:
- Allowed endowment permissions to specify caveats
**Checklist**
**Issue**
Resolves #877
> Support caveats on endowment permissions

- README.md
- package.json
**Debugging tests via DevTools**
- Added debug mode for testing with debuggers
- Document using test:debug (with references)
- ADDED:
- debug mode for testing with debuggers
- We need to be able to easily step through the code with DevTools while running tests so that we can reasonably begin to address #493 (or any complex controller interaction for that matter).
**Checklist**
- [ x ] Tests are included if applicable
- [ x ] Any added code is fully documented
Thx @shanejonas for the nudge on this one :)
> Added debug mode for testing with debuggers

- src/assets/TokensController.test.ts
**Fixed TokensController.addToken tests to be deterministic**
Tests were failing because a couple tests were depending on the object key ordering from https://github.com/MetaMask/contract-metadata 
object key ordering cannot be relied upon in tests. Object key ordering is non-deterministic, and typically changes across node versions and platforms.
- FIXED:
- TokensController tests now pass more (and will be more reliable in the future)
**Checklist**
**Issue**
Resolves #900
> Fixed tests to be deterministic

- src/third-party/PhishingController.test.ts
- src/third-party/PhishingController.ts
**PR Title**
problems:
1. Constructor starts polling, which is async. Starting async actions in a contructor makes testing hard.
2. `test` depends on `state.whitelist` which is set async via `poll` > `updatePhishingLists`. It is a sync function, which creates race conditions.
solution:
1. make test, have it update the phishing list if necessary
2. remove polling
- BREAKING:
- `phishingController.test` now returns a `Promise<EthPhishingDetectResult>`
- instead of calling poll with a new interval to change the interval, use `phishingController.setRefreshInterval` or `phishingController.configure({ refreshInterval: 123 })` (configure will be deprecated when we switch to using BaseController V2)
- FIXED:
- race conditions in Phishing controller tests
**Checklist**
- [ x ] …
> Phishing controller test method should be async and it should not poll

- package.json
- src/assets/Standards/ERC20Standard.ts
- src/assets/TokensController.ts
- yarn.lock
This is [part of an effort](https://github.com/MetaMask/metamask-extension/pull/15461) to remove any `ethers` submodules that are not used in the extension dependency tree by replacing all imports of `ethers` for the used submodule itself
- CHANGED:
- Simply replaces the "umbrella" version of `ethers` with the submodules that we actually use: `@ethersproject/contracts` & `@ethersproject/providers`.
> Replace `ethers` with submodules `@ethersproject/contracts` & `@ethersproject/providers`

- src/approval/ApprovalController.ts
- src/approval/errors.ts
- src/approval/index.ts
- src/index.ts
- src/permissions/index.ts
Adding new error type and exporting them from module.
These are need to add error handling in MetamaskController.
> Adding new error types and exporting them from module

- README.md
- package.json
- yarn.lock
It's far too common to create or update a pull request, receive an
approval, and then realize that you can't merge it because CI is saying
that you have linter violations. Ideally, you could always run the
linter before you push, but this step is easy to forget.
To solve this problem, this commit provides a way to install a Git hook
via `simple-git-hooks` which will run `yarn lint` pre-push. If there are
any linter violations, pushing will fail and you can run `yarn lint:fix`
to fix them (or fix them manually).
Note that a previous solution to this problem, submitted as a PR to the
extension repo, involved the use of `lint-staged` to run the linter
against staged files pre-commit. I've changed the workflow to pre-push
because ESLint, when supplied with TypeScript rules, can take a long …
> Add Git hook to run linter before pushing

- src/third-party/PhishingController.test.ts
- src/third-party/PhishingController.ts
The PhishingController tests now use fetch mocks for all tests that use fetch. `nock` is used to disable any network unmocked network requests. This should make the test suite more reliable, as it won't be affected by intermittent network failures anymore. To some degree it makes the tests more readable as well by making it more clear what is happening, at the cost of making them more verbose.
A few other minor improvements have been made as well, such as removing redundant tests and removing unnecessary generic type parameters. An unnecessary cast has been removed from the PhishingController as well.
I was tempted to make many further improvements to the tests beyond here, to make them easier to read, more in-line with our conventions, and more comprehensive. But I stopped here so that …
> Improve PhishingController tests

- package.json
- yarn.lock
- CHANGED:
The keystone team graciously upgrade the version of ethereumjs-util that they use in [bc-ur-registry-eth](https://www.npmjs.com/package/@keystonehq/bc-ur-registry-eth) and [metamask-airgapped-keyring](https://www.npmjs.com/package/@keystonehq/metamask-airgapped-keyring), [per our request](https://consensys.slack.com/archives/C029LTNQ56C/p1663027917069789).
Since this upgrade bumps us several minor versions we should do a thorough test of the Keystone integration as part of the QA for this PR.
Background context:
We're currently trying to trim down our bundle size and as part of that effort we're attempting to replace the heavy secp256k1-node [implementation](https://www.npmjs.com/package/secp256k1) out of our dependency graph with the @noble/secp256k1 …
> bump @keystonehq/metamask-airgapped-keyring to latest version

- src/ComposableController.test.ts
- src/ComposableController.ts
- src/assets/AssetsContractController.test.ts
- src/assets/CollectibleDetectionController.test.ts
- src/assets/CollectiblesController.test.ts
- src/assets/TokenBalancesController.test.ts
- src/assets/TokenDetectionController.test.ts
- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
- src/assets/TokenRatesController.test.ts
- src/assets/TokensController.test.ts
- src/gas/GasFeeController.test.ts
- src/gas/GasFeeController.ts
- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
**NetworkController update to extend from BaseControllerV2**
swaps out the base controller, implements messenger, fixes all the tests associated
- BREAKING:
- NetworkController constructor now takes a `ControllerMessenger`
- subscriptions should be made on the messenger, not the controller
- listen for providerChange if you want to receive updates once lookupNetwork has completed 
- CHANGED:
- NetworkController uses BaseControllerV2
**Checklist**
**Issue**
#902
> Refactor NetworkController to BaseControllerV2

- src/assets/Standards/ERC20Standard.test.ts
- src/assets/Standards/ERC20Standard.ts
This PR fixes some issues with ERC20Standard and proxy contracts. Some proxy contracts return `0x` instead of reverting when an unknown method signature is used. This PR adds requirements for `symbol()` and `decimals()` to be non-empty.
- FIXED:
- Fix issues with empty responses in ERC20 standard
**Checklist**
**Issue**
Fixes https://github.com/MetaMask/metamask-extension/issues/16076
> Fix issues with empty responses in ERC20Standard

- jest.config.js
- src/third-party/PhishingController.test.ts
- src/third-party/PhishingController.ts
- tests/setupAfterEnv.ts
When a phishing configuration update is requested while an update is in-progress, we now wait for the in-progress update to finish instead of initiating another redundant update.
- FIXED:
- Prevent parallel phishing configuration updates
**Checklist**
> Prevent parallel phishing configuration updates

- src/third-party/PhishingController.test.ts
- src/third-party/PhishingController.ts
The `test` method for the PhishingController was recently made asynchronous so that it could update the phishing configuration if necessary. We found that in practice this was difficult to use, especially when handling multiple simultaneous tests.
The `test` method has been made synchronous again. Instead we can check whether the config is out of date using the new `isOutOfDate` method, and explicitly update the configuration if required.
- BREAKING:
- [PhishingController] The `test` method is now synchronous again.
- ADDED:
-  [PhishingController] Add `isOutOfDate` method for checking whether the current configuration is outdated
**Checklist**
> Make the PhishingController `test` synchronous

- src/assets/TokenListController.test.ts
- src/assets/TokenListController.ts
- src/gas/GasFeeController.ts
- FIXED:
- `onNetworkStateChanged` callback was mistakenly removed from `TokenListController` in v32.0.0. It is now added back and is available as an option alongside a messaging system subscription for syncing with `NetworkController` updates
> Make both callback and messaging system options for `TokenListController` & `GasFeeController` when listening to `NetworkController`

- tests/setupAfterEnv.ts
- types/global.d.ts
I have noticed that locally `yarn test` will succeed the first time, the will fail with a type error saying `toNeverResolve` is undefined. After running `yarn jest --clearCache`, tests will pass again once then fail again.
This custom Jest matcher was added in #930. Seemingly the way the type was added is causing this problem.
I'm not entirely sure what's going on here. Something about the way Jest is loading this file is making Jest confused about this type. I found that it works more reliably if the type is moved to a separate file in the `types` directory.
> Fix occasional type errors when running tests

- .editorconfig
It's common in Markdown to indent things by 4 spaces. If you want to make a code block, you can indent it by 4 spaces. If you want to nest a block inside of a block — say, a code block inside of a list item — you use 4 spaces.
Speaking of code blocks, we usually use *fenced* code blocks, which allows you to specify a language in which that code is written, and those don't need to be indented by 4 spaces. Within such a code block, the indentation convention is still usually 2 spaces, so that if indentation is set to 4 spaces via `.editorconfig`, one needs to constantly go back and adjust that indentation. This gets to be annoying after a while, so this commit removes that setting from `.editorconfig`.
> Keep indent size of 2 for Markdown files

- .github/workflows/lint-build-test.yml
Make a couple of updates to the GitHub workflow that executes on pushes to pull requests and `main`:
1. Lint before building instead of afterward. Why? Typically when running checks, the lint step fails more often than the build step, and compiling TypeScript can take longer than linting especially on larger repos like this one. Switching around these steps in the workflow config means that a developer who has pushed changes to their pull request is now able to monitor the GitHub checks in real time more easily, because if there any linting violations with their latest changes, the developer will be able to see them more quickly.
2. Validate the changelog directly after the  linting step. As with the linting step, the changelog validation step is likely to fail, especially on a release …
> Lint, then build, then test

- .github/workflows/create-release-pr.yml
- .github/workflows/lint-build-test.yml
- .github/workflows/publish-release.yml
This PR bumps the GitHub actions that we we use to the latest version, removing deprecation notices from our CI.
Similar to https://github.com/MetaMask/metamask-mobile/pull/5144
and https://github.com/MetaMask/snaps-monorepo/pull/853
> Bump actions

- src/network/NetworkController.test.ts
- src/network/NetworkController.ts
From version 30.0.2 to 32.0.2 the setProviderType method of NetworkController has changed, it was resetting the rpcTarget and the nickname and now it's not
- CHANGED:
The rpcTarget and nickname is turned to undefined when used the setProviderType
**Checklist**
**Issue**
Resolves #???
> NetworkController setProviderType doesn't reset the rpcTarget and nickname

- src/network/NetworkController.ts
This fixes a deadlock accidentally introduced as part of #903. That PR introduced an early exit in the `net_version` callback that did not release the lock.
**Checklist**
> Fix `lookupNetwork` deadlock

- src/subject-metadata/SubjectMetadataController.test.ts
- src/subject-metadata/SubjectMetadataController.ts
I've moved [the `SUBJECT_TYPES` enum from the extension](https://github.com/MetaMask/metamask-extension/blob/aba3b94c1abf80de322ddd440ae379b2303084cf/shared/constants/app.ts#L60-L72) to the `SubjectMetadataController`, and added a new field to specify the type in the metadata. I've also added a new method to get the subject metadata for a single origin, rather than getting the entire state. We need this for Snaps, in order to distinguish an origin between Snaps and other subject types.
In the extension we were already using `subjectType`, but this was not defined in the type (since it accepts any `Json` values). In the extension it's pretty much a case of using this exported enum, rather than the one defined in the extension, which I removed. It's implemented here: …
> Add subject type and method to get metadata by origin

- tsconfig.build.json
- tsconfig.json
The TransactionController package was missing from our TypeScript config, so it wasn't being built.
> Add TransactionController to tsconfig

- .github/workflows/lint-build-test.yml
The `--immutable-cache` flag is now used during CI in steps where the cache is expected to be populated. This ensures we are alerted if our CI is misconfigured.
> Use the `--immutable-cache` flag upon install

- packages/address-book-controller/package.json
- packages/announcement-controller/package.json
- packages/approval-controller/package.json
- packages/assets-controllers/package.json
- packages/base-controller/package.json
- packages/composable-controller/package.json
- packages/controller-utils/package.json
- packages/ens-controller/package.json
- packages/gas-fee-controller/package.json
- packages/keyring-controller/package.json
- packages/message-manager/package.json
- packages/network-controller/package.json
- packages/notification-controller/package.json
- packages/permission-controller/package.json
- packages/phishing-controller/package.json
- packages/preferences-controller/package.json
- packages/rate-limit-controller/package.json
- packages/subject-metadata-controller/package.json
- packages/transaction-controller/package.json
- yarn.lock
This allows us to issue prereleases.
> Bump @metamask/auto-changelog to 3.1.0

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
We discovered since these changes were made that when using `workflow_call`, the top-level workflow needs to explicitly grant access to any secrets used.
If we had tried to publish anything the publish step would have been lacking the `NPM_TOKEN` secret, resulting in two dry runs and no published package.
> Fix npm publishing

- packages/assets-controllers/src/index.ts
This function was previously available before the monorepo conversion under `src/util.ts` and has since been moved to `src/assetsUtil.ts` in `@metamask/assets-controllers`.
> Expose getFormattedIpfsUrl

- packages/approval-controller/package.json
- packages/approval-controller/src/ApprovalController.ts
- packages/approval-controller/tsconfig.build.json
- packages/approval-controller/tsconfig.json
- packages/base-controller/package.json
- packages/base-controller/src/BaseControllerV2.ts
- packages/base-controller/src/index.ts
- packages/base-controller/tsconfig.build.json
- packages/base-controller/tsconfig.json
- packages/controller-utils/package.json
- packages/controller-utils/src/types.ts
- packages/controller-utils/src/util.ts
- packages/controller-utils/tsconfig.build.json
- packages/controller-utils/tsconfig.json
- packages/permission-controller/src/PermissionController.test.ts
- packages/permission-controller/src/PermissionController.ts
- packages/subject-metadata-controller/package.json
- packages/subject-metadata-controller/src/SubjectMetadataController.test.ts
- packages/subject-metadata-controller/tsconfig.build.json
- packages/subject-metadata-controller/tsconfig.json
- yarn.lock
Currently, `controller-utils` depends on `base-controller` (in order to access the `Json` type). This seems wrong. Despite its imperfect name, `controller-utils` holds code that needs to be shared across the whole monorepo, so it should be the thing that everything depends on. This commit fixes that.
> Make controller-utils the trunk

- .github/workflows/main.yml
The `is-release` job was configured to only run for commits made by GitHub actions. Our old release workflow always started with a commit made by an action, so this was an easy way to skip all release steps for commits that obviously were not releases.
Our new workflow does not work this way, so this check no longer makes sense.
The `action-is-release` action should still work in determining whether or not the current commit is a release. It checks the contents of the commit, specifically whether or not the base manifest version has changed. This technique still works for our new workflow.
> Remove `is-release` condition

- .github/workflows/publish-preview.yml
- scripts/prepare-preview-manifest.sh
The preview build version names have been updated to include `preview.` in the prerelease version. This should make it more clear what the build is.
> Add "preview." to the preview build version

- packages/base-controller/src/BaseControllerV2.test.ts
- packages/base-controller/src/BaseControllerV2.ts
This PR is meant to preface snap update rollback work in the `SnapController`. As it stands, the `update` function in `BaseControllerV2` does not expose `inversePatches` produced by Immer's `produceWithPatches` function. The `update` function has been updated to expose `nextState`, `patches` and `inversePatches`. A function called `applyPatches` was added to apply any patches that a controller may grab from an `update` call. I'm aware that the extension treats rollbacks as "updates", however I do think that controllers should have access to the `produceWithPatches` call's resulting patches in case they wish to implement some further functionality beyond a simple update.
> Add `applyPatches` function to BaseControllerV2

- packages/base-controller/src/ControllerMessenger.ts
The `ActionHandler`, `EventHandler` and related types were previously not exported. We use these in `snaps-monorepo`, but currently have to copy them over.
> Export action and event handler types

- packages/phishing-controller/src/PhishingController.test.ts
- packages/phishing-controller/src/PhishingController.ts
**Pass in initial state to PhishingController and load the initialState from persisted state**
In Manifest V3, there's need to 
1. Persist phishingcontroller state
2. Load phishingcontroller from persistent state
Thos PR makes sure state is loaded from persistent state and also abstracts out the checks required before updating the lists
- BREAKING:
- All the code bases using PhishingController should continue to work as expected
- CHANGED:
-   We should call initialise before calling PhishingDetector controller.
- ADDED:
- Added `maybeUpdatePhishingLists` method so that controllers don't have to do the check logic anymore
**Checklist**
**Issue**
Resolves https://github.com/MetaMask/metamask-extension/issues/16551
> Add lastFetched PhishingController state

- packages/assets-controllers/src/AssetsContractController.ts
- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenDetectionController.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokenListController.ts
- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
- packages/composable-controller/src/ComposableController.test.ts
- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/gas-fee-controller/src/GasFeeController.ts
- packages/network-controller/src/NetworkController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
> Change naming of provider to providerConfig where applicable

- constraints.pro
- packages/assets-controllers/package.json
- packages/gas-fee-controller/package.json
- packages/permission-controller/package.json
- yarn.lock
Packages now list `peerDependencies` to represent the expectation that a specific package version is setup with the controller messenger. This ensures that projects using these packages get a warning upon install if they are using incompatible package versions.
This lets us safely make breaking changes to controller messenger events and actions.
The constraints needed adjustment to allow the same dependency to be declared both in `dependencies` and `peerDependencies`. The constraint now ensures packages aren't listed both in `dependencies` and `devDependencies` instead.
- FIXED:
- The following packages now warn if a required package is not present:
- `assets-controllers`
- `gas-fee-controller`
- `permission-controller`
**Checklist**
> Add peer dependencies between packages

- packages/assets-controllers/jest.config.js
- packages/assets-controllers/src/CurrencyRateController.test.ts
- packages/assets-controllers/src/CurrencyRateController.ts
- packages/assets-controllers/src/TokenRatesController.ts
**Allow network requests in instances of the CurrencyRate and TokenRate controllers to be disabled**
- BREAKING:
- A new private property is added to the CurrencyRateController: `enabled`. If this is false, then the function in that controller which makes network requests will not make any requests when called. This property is controlled by the `start` and `stop` methods, so that these methods will effectively enable or disable network requests. Previously, even if `stop` had been called, `setNativeCurrency` or `setCurrentCurrency` would trigger a network request. That is now prevented.
- FIXED:
- The TokenRatesController previously had a bug whereby if a `disabled` property was passed to the constructive as part of the `config` object, it would be ignored / overwritten …
> Allow network requests in instances of the CurrencyRate and TokenRate controllers to be disabled

- packages/announcement-controller/package.json
- packages/announcement-controller/src/AnnouncementController.test.ts
- packages/announcement-controller/src/AnnouncementController.ts
- yarn.lock
AnnouncementController migration to BaseControllerV2
Resolves #945
> AnnouncementController migration to BaseControllerV2

- .github/workflows/publish-preview.yml
- .gitignore
- scripts/generate-preview-build-message.ts
The build preview message now includes a link to the build preview instructions, and a collapsible list of all published packages.
> Improve build preview message

- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
Fixes [16854](https://github.com/MetaMask/metamask-extension/issues/16854) 
When used to import the detectedTokens by calling `addTokens` we should clear the `detectedTokens` and `allDetectedTokens[chainId][selectedAddress]` ie entry in `allDetectedTokens` for that particular chainId and selectedAddress, otherwise the data from allDetectedTokens getting repopulated/reloaded into the `detectedtokens` when the networkState or preferenceState changes.
Edit: upon further inspection, we had to do the same clearing for allTokens and allIgnoredtokens as well.
> DetectedTokens getting reloaded from allDetectedTokens even after the tokens are imported for a chain and selectedAddress

- constraints.pro
- package.json
A constraint has been added to ensure that the `bugs` field in `package.json` is always set to the correct value. This field was not covered by existing validation.
This constraint is useful for a subsequent PR, where the repository is renamed.
**Checklist**
> Add constraint for `bugs` field in `package.json`

- constraints.pro
When creating the monorepo template, it was useful to revise the Yarn constraints file so that the project/repo name could be changed without having to change a bunch of references in the file. This commit brings over those revisions:
* The repository URL is now used as a basis for the homepage URL and bugs URL, so it must be set appropriately (and if it is not, the user will see a suggestion in the correct format).
* Additionally, the comments above each constraint have been reworded to be more consistent and understandable, and comments have been added where missing.
* Finally, some pairs of constraints which test one thing for private packages and the opposite for public packages have been updated to apply to the root package vs. non-root packages where it made sense.
> Update Yarn constraints to remove reference to project/repo name

- packages/assets-controllers/src/index.ts
The function `isTokenDetectionSupportedForNetwork` is now exported from the `assets-controllets` package. This function was exported from the `utils` before this repository was split into separate packages. This function is used in `metamask-mobile`.
- CHANGED:
- [assets-controllers]: Export the function `isTokenDetectionSupportedForNetwork` 
**Checklist**
> Export `isTokenDetectionSupportedForNetwork` function

- package.json
- packages/announcement-controller/CHANGELOG.md
- packages/announcement-controller/package.json
- packages/assets-controllers/CHANGELOG.md
- packages/assets-controllers/package.json
Changelogs:
- **BREAKING:** Migrate to BaseControllerV2 ([#959](https://github.com/MetaMask/controllers/pull/959))
- The announcement controller now extends `BaseControllerV2` rather than `BaseController`, which includes the following changes:
- The constructor now accepts a single "args" object rather than positional parameters.
- A restricted controller messenger instance must be passed into the constructor.
- The controller configuration has been replaced by an `allAnnouncements` constructor parameter.
- The following properties previously inherited from `BaseController` are no longer present:
- `defaultConfig`
- `defaultState`
- `disabled`
- `config`
- `state`
- The following methods previously inherited from `BaseController` are no longer present:
- `configure`
- `notify`
- …
> Release 38.0.0

- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- yarn.lock
- CHANGED:
- Upgrades `eth-sig-util` (now `@metmask/eth-sig-util`) from v3.0.0 to v5.0.2. This upgrade contains several updates, including:
- consolidates the recoverTypedSignature, recoverTypedSignature_v4, recoverTypedSignatureLegacy functions into one that switch on a new version argument. 
- reduces dependency burden, removing `secp256k1` and `keccak` via as dependencies by upgrading from `ethereumjs-util@6.2.1` to its latest version `@ethereumjs/util@8.0.0` which uses lighter `noble` implementations for crypto functionality. Replaces `keccak` hashing with `keccak256` from `ethereum-cryptography/keccak`
> bump @metamask/eth-sig-util to latest

- packages/transaction-controller/src/index.ts
This function is used in mobile. It was exported prior to the monorepo release.
> Export `isEIP1559Transaction` function

- packages/assets-controllers/src/AccountTrackerController.test.ts
- packages/assets-controllers/src/CurrencyRateController.test.ts
- packages/assets-controllers/src/CurrencyRateController.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/assetsUtil.test.ts
- packages/controller-utils/src/constants.ts
- packages/controller-utils/src/types.ts
- packages/controller-utils/src/util.test.ts
- packages/controller-utils/src/util.ts
- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/network-controller/src/NetworkController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/transaction-controller/package.json
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/utils.test.ts
- yarn.lock
**PR Title**
Added support for Sepolia test network.
It was added Sepolia test network support to our Network Controller and Transaction controller, also on Transaction controller it was updated the package ethereumjs-common to version [2.6.1](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/CHANGELOG.md#261---2022-02-01)  to support Sepolia network
- BREAKING:
This update removes all the deprecated test networks, rinkeby, kovan and ropsten from this repo
Also, it allows to implement this [PR](https://github.com/MetaMask/metamask-mobile/pull/5458) to MetaMask Mobile support Sepolia
- CHANGED:
The test cases were changed to use sepolia and goerli instead of the deprecated networks.
Also it was increased the test coverage of network controller
- …
> Sepolia support

- packages/approval-controller/src/ApprovalController.test.ts
- packages/approval-controller/src/ApprovalController.ts
Closes #1056
Please see above issue for motivation behind this addition.
> Add `updateRequestState` action to `ApprovalController`

- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/network-controller/src/NetworkController.ts
**No NetworkController in tests**
**Description**:
Mocking the behaviour of the network controller makes the tests more flexible, and lessens the burden of cleanup / maintainability of the tests. This PR removes the `NetworkController` from the `TokenDetectionController` tests. 
partially fixes #1051
> Update TokenDetectionController tests to not create networkController

- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/assetsUtil.test.ts
- packages/assets-controllers/src/assetsUtil.ts
- packages/controller-utils/src/constants.ts
**PR Title**
- Migrates from *.metaswap.codefi.network  to *.metafi.codefi.network for `proxy` and `static` subdomains. MetaMask Platform API team is migrating from metaswap aws accounts to their own.
- BREAKING:
- Uses new subdomains for providing the opensea proxy and token icons cache.
- CHANGED:
- Uses new subdomains for providing the opensea proxy and token icons cache.
- New infrastructure enables a new mechanism to handle support requests for changes to token icons. Now https://github.com/MetaMask/contract-metadata will be the priority provider of icons, such that changes there will overwrite any existing token icons we're fetching and caching from other providers.
> API-125 - Migrated from metaswap to metafi subdomain for proxy and token icons

- docs/contributing.md
The command referenced in the contributor docs for publishing a preview build was incorrect. It has been updated to use the correct command.
See: https://github.com/MetaMask/core/blob/main/.github/workflows/publish-preview.yml#L10
> Fix docs for preview build comment command

- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- types/@metamask/eth-keyring-controller.d.ts
- types/eth-keyring-controller.d.ts
- yarn.lock
Fixes: #774  (not an initial target of this work)
Pulls in latest version - v10.0.0 - of `eth-keyring-controller` (now `@metamask/eth-keyring-controller`) and adapts according.
**BREAKING:** `exportSeedPhrase` now returns a `Uint8Array` typed SRP (can be converted to a string using [this approach](https://github.com/MetaMask/eth-hd-keyring/blob/main/index.js#L40)).  It was previously a Buffer.
> Bump eth-keyring-controller version to @metamask/eth-keyring-controller v10

- packages/assets-controllers/src/NftController.test.ts
**No NetworkController in tests**
**Description**:
Mocking the behaviour of the network controller makes the tests more flexible, and lessens the burden of cleanup / maintainability of the tests. This PR removes the `NetworkController` from the `NftController` tests. 
Relates to #1051
> Update NftController tests to not create networkController instance

- packages/assets-controllers/src/NftController.ts
Fixes [17206](https://github.com/MetaMask/metamask-extension/issues/17206)
Ideally, when a user previously owned an NFT, and then received the same one back, we'd put that NFT back into its own group. With the current implementation, the NFT is always stuck in the Previously Owned category, even when imported again. This PR is to update the Nft Controllers to add the NFT back to its own group if we are re-importing it.
> updated the previously owned state for nft

- packages/assets-controllers/src/TokensController.test.ts
**No NetworkController in tests**
**Description**:
Mocking the behaviour of the network controller makes the tests more flexible, and lessens the burden of cleanup / maintainability of the tests. This PR removes the `NetworkController` from the `TokenController` tests. 
Relates to #1051
> Update token controller tests to not create networkController instance

- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/network-controller/src/NetworkController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/transaction-controller/src/TransactionController.test.ts
This PR renames properties network controller state property to networkDetails.
Related issue [#1019](https://app.zenhub.com/workspaces/core-621e46b4d7103800171d1b02/issues/gh/metamask/core/1019)
> rename network controller properties state property

- packages/phishing-controller/src/PhishingController.ts
**Improve lookup time in PhishingController**
This PR creates a Set from `metamaskConfig.blocklist` in the `PhishingController`. The blocklist Set is later used as a lookup inside of a filter method. As a result, look up performance is significantly improved by using a `Set` + `has` method instead of `includes` method from an Array.
- CHANGED:
- `PhishingController.updatePhishingLists`
- Create a `Set` from `metamaskConfig.blocklist` to be used as lookup.
**Checklist**
**Issue**
Resolves https://github.com/metamask/metamask-mobile/issues/5382
> Use Set to improve lookup performance

- package.json
- packages/assets-controllers/CHANGELOG.md
- packages/assets-controllers/package.json
- packages/keyring-controller/CHANGELOG.md
- packages/keyring-controller/package.json
- packages/network-controller/CHANGELOG.md
- packages/network-controller/package.json
- packages/phishing-controller/CHANGELOG.md
- packages/phishing-controller/package.json
> Release 40.0.0

- packages/phishing-controller/src/PhishingController.ts
This interface was replaced by `PhishingStalelist` and `PhishingListState` in a recent PR (#1080), but we forgot to remove it.
**Checklist**
> Remove unused interface

- packages/network-controller/src/NetworkController.test.ts
- packages/network-controller/src/NetworkController.ts
**Remove EthQuery.sendAsync check from NetworkController**
- REMOVED:
- Removed unnecessary checks on EthQuery.sendAsync existence in `NetworkController.lookupNetwork` and `NetworkController. getEIP1559Compatibility`, as EthQuery will always have this method
- Removed test cases where EthQuery.sendAsync is undefined
**Checklist**
**Issue**
Resolves #1076
> Remove EthQuery.sendAsync check from NetworkController

- types/global.d.ts
The `toNeverResolve` custom matcher is now registered using a simpler type declaration. This also lets us remove an ESLint ignore comment.
> Simplify type of custom Jest matcher

- packages/gas-fee-controller/src/gas-util.test.ts
**Add tests for gas-util calculateTimeEstimate function**
- Increases code coverage for the GasFeeController
- ADDED:
- Additional test cases for the `calculateTimeEstimate` function. This was added to unblock the CI error found on #1083.
**Checklist**
> [GasFeeController] Add tests for gas-util calculateTimeEstimate function

- packages/gas-fee-controller/src/GasFeeController.ts
**[GasFeeController] Make the EIP-1559 gas fee endpoint a required argument**
-  This PR removes the default value given to the `EIP1559APIEndpoint` parameter of the GasFeeController. This server is no longer maintained, and consumers of this package should pass in their own gas fee endpoint. All MetaMask products already currently pass in their own API endpoint, and no additional changes are needed on their end.
- BREAKING:
- `EIP1559APIEndpoint` argument for the gas fee controller is now required.
**Checklist**
> BREAKING: Make the EIP-1559 endpoint a required argument for the GasFeeController

- packages/preferences-controller/src/PreferencesController.test.ts
- packages/preferences-controller/src/PreferencesController.ts
**PR Title**
Added disabledRpcMethodPreferences state to PreferencesController
- ADDED:
- Added a new key for storing which rpc methods we've deprecated, but want the user to be able to specify if they want to enable it again.
**Checklist**
**Issue**
Related to https://github.com/MetaMask/metamask-mobile/issues/5676
> Added disabledRpcMethodPreferences state to PreferencesController

- packages/keyring-controller/src/KeyringController.ts
**PR Title**
Ledger account missing on password reset 
- A brief description of changes. If the PR has breaking changes add `BREAKING:`
to the start of the PR title.
This PR fixes the bug where the Ledger account is missing on password reset 
**Checklist**
Resolves [#5721](https://github.com/MetaMask/metamask-mobile/issues/5721)
> Ledger account missing on password reset 

- .github/workflows/main.yml
**Always run `all-jobs-pass` to ensure all jobs have passed**
We require `all-jobs-pass` to complete for a PR to be merged. Currently if a job fails, `all-jobs-pass` shows up as "Skipped," bypassing the requirement. This PR changes it so `all-jobs-pass` always runs at the end of all other jobs, regardless of failures, and checks if a variable has been set, that only gets set when all jobs have passed.
For reference: https://github.com/MetaMask/snaps-monorepo/pull/1254#discussion_r1123523503
- CHANGED:
- Add new job that sets `passed` output.
- The `all-jobs-pass` job now checks if `passed === 'true'`.
> Always run `all-jobs-pass` to ensure all jobs have passed

- packages/ens-controller/src/EnsController.test.ts
- packages/ens-controller/src/EnsController.ts
This PR migrate the ens controller to new base api
Related issue [#1130](https://github.com/MetaMask/core/issues/1130)
> Convert the ENS controller to the BaseController v2 API

- packages/assets-controllers/package.json
- yarn.lock
**Bump contract metadata package version**
Bumping contract-metadata version following up on:
https://github.com/MetaMask/contract-metadata/pull/1169
https://github.com/MetaMask/contract-metadata/pull/1173
This PR is a blocker for [this other PR on the extension](https://github.com/MetaMask/metamask-extension/pull/18278) due to deduplication warnings.
- CHANGED:
- Bumped contract metadata package version
> bump contract metadata package version

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/NftDetectionController.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
- packages/controller-utils/src/constants.ts
- packages/controller-utils/src/types.test.ts
- packages/controller-utils/src/types.ts
- packages/keyring-controller/src/KeyringController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
- packages/network-controller/tests/provider-api-tests/shared-tests.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/utils.ts
- ADDED:
- adds a `rollbackToPreviousProvider` method like the one that exists [on the extension side](https://github.com/MetaMask/metamask-extension/blob/7a421e05c37658820298ded50c8949df16fc1f3f/app/scripts/controllers/network/network-controller.js#L290) `NetworkController`
Resolves #1024
> add rollbackToPreviousProvider method

- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
**Support watching assets on a specific account**
The purpose of the changes to is allow a user to store a watched asset to the token states in the `TokensController`. Why is this needed? The introduction of the Permission System on mobile now allows users to interact with Dapps using accounts that are different than what is active on their wallet screen. This dynamic makes it possible for users to watch assets under the active Dapp account, which may be different than the active wallet account. As a result, we needed to enable passing of an account address to both the `watchAsset` and `addToken` method, that would allow for storing of tokens under specific account addresses. All of the listed changes below is backwards compatible and code that uses the `TokensController` will not need to …
> Support watching assets on a specific account

- packages/phishing-controller/src/PhishingController.test.ts
- packages/phishing-controller/src/PhishingController.ts
- packages/phishing-controller/src/utils.test.ts
- packages/phishing-controller/src/utils.ts
**Refactor to new long-running phishing-detection API for phishing list updates**
- Refactors phishing-controller to use new curated experiences phishing list updates API for `GET /v1/diffsSince/:timestamp` to maximally reduce data transfer.
- FIXED:
- Re-added eth-phishing-detect attribution by drawing out `diff.targetList` from list type (`'fuzzylist' | 'blocklist' | 'allowlist'`) to a composed `${sourceList}.${listType}` like `'eth_phishing_detect_config.blocklist'`, then splitting client side to re-allow for multiple phishing-lists to be passed into the [eth-phishing-detect detector](https://github.com/MetaMask/core/pull/1123/files#diff-73fbecd61d9f85b57fee9c8377652f5563d90e026e54fa105ca91fcc2cbc076fR249).
- …
> API-217 - Refactored to new long-running phishing-detection API for phishing list updates

- packages/message-manager/src/AbstractMessageManager.test.ts
- packages/message-manager/src/AbstractMessageManager.ts
- packages/message-manager/src/MessageManager.test.ts
- packages/message-manager/src/MessageManager.ts
- packages/message-manager/src/PersonalMessageManager.test.ts
- packages/message-manager/src/PersonalMessageManager.ts
- packages/message-manager/src/TypedMessageManager.test.ts
- packages/message-manager/src/TypedMessageManager.ts
**Add security provider request to AbstractMessageManager**
This PR aims to move the security provider request from `SignController` in the extension to `AbstractMessageManager`, and support it in a generic way here in the core and potentially in mobile. 
NOTE: There will be a following PR for the extension to delete the duplicated code within the extension, and potentially following that a PR moving the  `securityProviderCheck` from the extension to core utils.
See the patched changes in the extension (ci): [branch](https://github.com/MetaMask/metamask-extension/tree/poc/security-provider) 
- CHANGED:
- Included a new param `securityProviderRequest` 
- Created a method `securityProviderCheck` to be called whenever an unapproved message is added if securityProviderRequest …
> feat: add security provider request to AbstractMessageManager

- packages/message-manager/src/AbstractMessageManager.test.ts
- packages/message-manager/src/AbstractMessageManager.ts
- packages/message-manager/src/EncryptionPublicKeyManager.test.ts
- packages/message-manager/src/EncryptionPublicKeyManager.ts
- packages/message-manager/src/index.ts
- packages/message-manager/src/utils.test.ts
- packages/message-manager/src/utils.ts
**Adds EncryptionPublicKeyManager**
- CHANGED:
- Extends `AbstractMessageManager` so that it can support other actions
- ADDED:
- Creates an `EncryptionPublicKeyManager` that will be used by `EncryptionPublicKeyController`.
**Checklist**
**Issue**
Resolves https://github.com/MetaMask/MetaMask-planning/issues/394
> Adds EncryptionPublicKeyManager

- tsconfig.packages.build.json
It is a frustrating experience to want to see the source code of a module that's being imported in one's editor only to be presented with the `.d.ts` file when the module is Cmd-clicked (or "Go to Definition" is otherwise invoked). To fix this, TypeScript needs to be configured to generate source maps alongside `.d.ts` files.
To test this, run `yarn:build`. All `.d.ts` files should have an accompanying `.d.ts.map` file.
**CHANGED:**
- Update `tsconfig.json` for all packages to enable `declarationMap`.
References https://github.com/MetaMask/metamask-module-template/pull/182.
> Generate source maps for type definition files

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
This PR adds a resetConnection method.
Related issue [#1023](https://github.com/MetaMask/core/issues/1023)
> Implement resetConnection method in network controller

- packages/network-controller/src/NetworkController.ts
- packages/transaction-controller/package.json
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/utils.test.ts
- packages/transaction-controller/src/utils.ts
- yarn.lock
Resolves: #1070 
- ADDED
- Adds `NonceTracker` package to transaction approval flow to manage transaction nonces. This functionality was previously handled by middleware in `web3-provider-engine which is slated to be removed. [#123](https://github.com/metamask/controllers/pull/123)
> Add nonce tracker to transactions controller

- packages/approval-controller/src/ApprovalController.test.ts
- packages/approval-controller/src/ApprovalController.ts
Currently all approval requests created by the `ApprovalController` are rate limited to a single pending approval request for each approval type and origin combination.
This is not yet required for some existing approval flows being migrated to use the `ApprovalController` hence the need for a way to exclude specific approval types from rate limiting to avoid any regressions in functionality and user expectation.
- **ADDED**: Optional `typesExcludedFromRateLimiting` parameter to the `ApprovalController` constructor to disable rate limiting for specific approval types.
- **CHANGED**: Data structure of `_origins` property to support multiple requests with same origin and type.
[[Bug]: Approval request with id not found.](https://github.com/MetaMask/metamask-extension/issues/18553)
> Exclude types from rate limiting in approval controller

- package.json
- packages/approval-controller/CHANGELOG.md
- packages/approval-controller/package.json
Non-breaking changes to the `ApprovalController` needed for an extension bug.
Adds an option to exclude types from rate limiting.
> Release 46.0.0

- packages/network-controller/tests/provider-api-tests/block-param.ts
- packages/network-controller/tests/provider-api-tests/no-block-param.ts
The network client test "queues requests while a previous identical call is still pending..." was emitting a console error due to an unmocked block tracker network call.
That call is now mocked, eliminating the error.
I am unsure why the second call is made during this test, but we suspect that it's because the first block tracker call isn't being cached until after the RPC call that triggered it has been resolved.
To reproduce, use `.only` on that test and run this command:
`yarn workspace @metamask/network-controller jest --coverage=false --verbose=false`
Before this change, that command should produce console errors. After this change, there will be none (though there are still lots of warnings).
N/A
This relates to #1178
> Eliminate console error when running test

- packages/network-controller/src/NetworkController.ts
The internal method `verifyNetwork` is now async. It performed an async call but didn't `await` it.
This method is only invoked as an internal event handler, so this didn't require any changes outside of that function (not even to tests). Effectively this is not a functional change in any way.
N/A
This relates to https://github.com/MetaMask/core/issues/1176
> Make `verifyNetwork` async

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The `initializeProvider` method has been made async. This method already triggered various async operations, but they were not being `await`-ed. Now they are, making this method easier to use and easier to test.
- **BREAKING**: The `initializeProvider` method is now `async`
This relates to https://github.com/MetaMask/metamask-extension/issues/18587
> Make `initializeProvider` async

- packages/network-controller/src/NetworkController.ts
The internal method `refreshNetwork` has been made async. The method already called an asynchronous method internally, but it was not `await`-ed. Now it is.
This method is only being called from within synchronous functions. They will be made async in later PRs.
Because the async call was the last operation, this change effectively has no functional impact.
N/A
This relates to https://github.com/MetaMask/core/issues/1176
> Make `refreshNetwork` async

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
The network controller method `setProviderType` is now async. It will not resolve until the network switch has completed.
- **BREAKING**: `setProviderType` is now async
This relates to #1176
> Make `setProviderType` async

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller method `setActiveNetwork` is now async. It will not resolve until the network switch has completed.
- **BREAKING**: `setActiveNetwork` is now async
This relates to https://github.com/MetaMask/core/issues/1176
> Make `setActiveNetwork` async

- packages/message-manager/src/AbstractMessageManager.test.ts
- packages/message-manager/src/AbstractMessageManager.ts
- packages/message-manager/src/DecryptMessageManager.test.ts
- packages/message-manager/src/DecryptMessageManager.ts
- packages/message-manager/src/EncryptionPublicKeyManager.test.ts
- packages/message-manager/src/MessageManager.test.ts
- packages/message-manager/src/PersonalMessageManager.test.ts
- packages/message-manager/src/index.ts
- packages/message-manager/src/utils.test.ts
- packages/message-manager/src/utils.ts
**Add `DecryptMessageManager` to message managers**
- CHANGED:
- Extends `AbstractMessageManager` adds `decrypted`
- ADDED:
- Adds `DecryptMessageManager` in order to consume it at `DecryptMessageController` on extension
**Checklist**
> Add DecryptMessageManager

- packages/controller-utils/src/util.ts
The `toHex` utility function now returns the `Hex` type rather than a `string`. The `Hex` type is a string that is guaranteed to start with `0x`.
This is a type-only change, there no no functional changes.
- CHANGED: The `toHex` function now returns the type `Hex`, which guarantees that the returned string starts with `0x`.
This was extracted from #1116, which addresses #970
> Improve return type of `toHex`

- packages/network-controller/src/NetworkController.ts
Internal network controller methods and fields are now private fields, using the JavaScript `#` syntax rather than the `private` TypeScript keyword.
- CHANGED: Use JavaScript private fields rather than `private` TypeScript keyword
Closes #1177
> Make network controller internal fields private

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
The network controller method `upsertNetworkConfiguration` is now async. If the option `setActive` is false, the flow of execution should be the same as before (apart from the change in return type). But if `setActive` is `true`, the method will not resolve until the network switch has completed (previously it would initiate the switch without waiting for it to complete).
- **BREAKING**: `upsertNetworkConfiguration` is now async
This relates to #1176
> Make `upsertNetworkConfiguration` async

- packages/assets-controllers/package.json
- packages/assets-controllers/src/TokenBalancesController.test.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
- packages/assets-controllers/tsconfig.build.json
- packages/assets-controllers/tsconfig.json
- packages/controller-utils/src/constants.ts
- yarn.lock
**BREAKING Adds messenger to token controller**
Adds a messenger to `TokensController` so that the confirmation can be triggered by sending a message to `ApprovalController`.
- BREAKING:
- The new messenger field in the constructor introduces a breaking change.
- CHANGED:
- It uses `ApprovalController` messages to initiate and complete the request instead of an event.
**Checklist**
**Issue**
Resolves https://github.com/MetaMask/MetaMask-planning/issues/409
> BREAKING Adds messenger to token controller

- packages/network-controller/package.json
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/constants.ts
- packages/network-controller/src/index.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/fake-provider-engine.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- yarn.lock
The network controller `network` state used to be set to `loading` if the network was loading or uninitialized, or to the network ID if the network had finished loading. Effectively it was tracking both the network ID for the current selected network, and the network status.
This state property has been split in two; now we track the network ID of the current selected network separately from the network status. The network status has been expanded to include more states as well.
- **BREAKING**: The `network` state has been replaced by `networkId` and `networkStatus`
- If you were using `network` to access the network ID, use `networkId` now instead. It will be set to `null` rather than `loading` if the network is not currently available.
- If you were using `network` to see if the network …
> Replace `network` state with `networkId` and `networkStatus`

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
The network controller state `isCustomNetwork` has been removed. This state was redundant; you can determine whether the current selected network is custom or not by checking the `providerConfig` state.
The one usage of this state in other packages was the transaction controller. It has been updated to use the provider configuration state instead.
- **BREAKING**: Remove `isCustomNetwork` state
- To check whether the current selected network is a custom network or not, check the `providerConfig.type` property. If it's set to `NetworkType.rpc` then it's a custom network, otherwise it's a built-in network.
Closes #1020
> Remove `isCustomNetwork`

- packages/network-controller/tests/NetworkController.test.ts
The `setProviderType` unit tests included a static set of network metadata that was not being used. It has been updated to use a list of just the network types, following examples in other tests.
None
This was done in pursuit of https://github.com/MetaMask/core/issues/1203, though the connection is fairly indirect (I'm on a tangent here)
> Simplify `setProviderType` unit tests

- package.json
- packages/assets-controllers/CHANGELOG.md
- packages/assets-controllers/package.json
- packages/controller-utils/CHANGELOG.md
- packages/controller-utils/package.json
- packages/message-manager/CHANGELOG.md
- packages/message-manager/package.json
Release changes only for 
- @metamask/assets-controllers
- @metamask/controller-utils
- @metamask/message-manager
> Release 47.0.0

- packages/permission-controller/src/Permission.ts
- packages/permission-controller/src/PermissionController.test.ts
- packages/permission-controller/src/PermissionController.ts
Adds a `subjectTypes` field to permission specifications, allowing certain permissions to be limited to access from certain subject types. 
If a request for permissions is made from a non-matching subject type we throw a method or endowment not found error.
- **Added**: Added `subjectTypes` field to permission specifications
- This field can be used to limit which subject types can request a given permission
> Restrict certain permissions by subject type

- packages/keyring-controller/src/KeyringController.test.ts
This PR stubs the PreferencesController used to create the KeyringController instance used in tests.
- **CHANGED**: Functions passed to KeyringController constructor during tests
* Fixes #1151
> Stub PreferencesController in KeyringController tests

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The `resetConnction` method has been updated to match the extension more closely. We now refresh the network when this is called, rather than just reconstructing the provider and checking EIP1559 status.
Unit tests have been updated to align more closely with the extension as well.
- CHANGED: Update `resetConnection` to perform network lookup (refresh network id and status) 
This was done to unblock #1203, but it also relates to #1023 and #1176
> Refresh network when connection is reset

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller method `resetConnection` has been made async. It will not resolve until after the network has been fully reset.
- CHANGED: `resetConnection` is now async
Relates to #1176
> Make `resetConnection` async

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller method `rollbackToPreviousProvider` has been made async. This method used to switch back to the previous network without waiting for the network switch operation to complete. Now it will not resolve until the switch has completed.
- CHANGED: `rollbackToPreviousProvider` is now async
Closes #1176
Fixes #1178
> Make `rollbackToPreviousProvider` async

- package.json
- packages/approval-controller/CHANGELOG.md
- packages/approval-controller/package.json
- packages/assets-controllers/CHANGELOG.md
- packages/assets-controllers/package.json
- packages/controller-utils/CHANGELOG.md
- packages/controller-utils/package.json
- packages/ens-controller/CHANGELOG.md
- packages/ens-controller/package.json
- packages/gas-fee-controller/CHANGELOG.md
- packages/gas-fee-controller/package.json
- packages/keyring-controller/CHANGELOG.md
- packages/keyring-controller/package.json
- packages/message-manager/CHANGELOG.md
- packages/message-manager/package.json
- packages/network-controller/CHANGELOG.md
- packages/network-controller/package.json
- packages/permission-controller/CHANGELOG.md
- packages/permission-controller/package.json
- packages/rate-limit-controller/CHANGELOG.md
- packages/rate-limit-controller/package.json
- packages/transaction-controller/CHANGELOG.md
- packages/transaction-controller/package.json
Release outstanding changes before bump to nodejs v16.
- 975a8c98 deps: eth-rpc-errors@4.0.0->4.0.2 (#1215)
- d94a7029 add WalletConnect in approval type (#1240)
- 7d5057b4 Merge extension ens controller (#1170)
- db046ee0 Stub PreferencesController in KeyringController tests (#1194)
- 99df8b57 add rollbackToPreviousProvider method (#1132)
- ced8c3c4 fix: prevent setResult to emit updateBadge but state updates (#1245)
- af9bb3c5 fix changelog (#1232)
- bd29cbc4 Make `rollbackToPreviousProvider` async (#1237)
- 11376760 Make `resetConnection` async (#1239)
- 383bcea2 Update EIP-1559 compatibility during network lookup (#1236)
- 360796a5 Refresh network when connection is reset (#1235)
- d7707a30 deps: bump web3-provider-engine@16.0.3->16.0.5 (#1212)
- 21e2a265 Simplify `setProviderType` …
> Release 49.0.0

- packages/controller-utils/src/util.test.ts
- packages/controller-utils/src/util.ts
- packages/ens-controller/src/EnsController.ts
- packages/notification-controller/package.json
- packages/notification-controller/src/NotificationController.ts
- packages/permission-controller/package.json
- packages/permission-controller/src/Caveat.ts
- packages/permission-controller/src/PermissionController.test.ts
- packages/permission-controller/src/PermissionController.ts
- yarn.lock
The `hasProperty` function in `@metamask/controller-utils` has been removed. Instead the `hasProperty` function from `@metamask/utils` is now used in its place. The `@metamask/utils` version of this function is functionally identical but has a better type signature.
- **BREAKING:** Remove the `hasProperty` function
Relates to #1204
> Remove duplicate `hasProperty` function

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller now requires an Infura project ID to be provided upon construction. This brings the network controller more in-line with the extension. Runtime validation has been added for the sake of making the merge with the extension network controller easier.
- **BREAKING:** The `infuraProjectId` constructor parameter is now required
Closes #1201
> Require Infura project ID

- .eslintrc.js
- packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
- packages/network-controller/tests/provider-api-tests/block-param.ts
- packages/network-controller/tests/provider-api-tests/no-block-param.ts
- packages/network-controller/tests/provider-api-tests/shared-tests.ts
- tests/helpers.ts
Our test helper modules have been covered by ESLint as though they were production code. This resulted in misleading coverage statistics and various erronous lint errors (which we've handled by disabling rules in affected files).
The ESLint configuration has been updated to consider any modules under a `tests` directory to be test helpers.
None
This helps reduce the scope of #1116
> Correctly lint test helpers

- packages/controller-utils/src/types.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/constants.ts
- packages/network-controller/src/logger.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller has been updated to detect when connecting to an Infura network fails due to the user being blocked. A new status has been added to reflect this state, and two events have been added (one for when a user is blocked, and one for when they are unblocked).
This status and these events are used by the extension to better explain why the network is not working in this scenario.
- **BREAKING:** The network status will now be "blocked" rather than "unavailable" when the user is blocked by Infura
- ADDED: The events "infuraIsBlocked" and "infuraIsUnblocked" have been added
Fixes #1200
> Add handling of Infura "blocked" status

- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/gas-fee-controller/src/GasFeeController.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
GasFeeController uses the same instance of EthQuery that NetworkController constructs when it constructs a new provider. It will then use that EthQuery instance later in order to make requests to the network.
A previous change removed a line from GasFeeController which accessed that EthQuery instance immediately in the constructor because it was thought that at point in time the provider had not been set yet. However, even if do not `await` the call to `initializeProvider` that occurs after NetworkController is instantiated, the provider will still be constructed synchronously.
This commit restores the removed line and adds tests for it.
- **FIXED**: Fix regression in GasFeeController where `ethQuery` was not being set until the network was switched. [Note: this entry may not be necessary …
> Fix GasFeeController to assign `ethQuery` initially

- packages/controller-utils/src/types.ts
- packages/network-controller/package.json
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/create-network-client.ts
- packages/network-controller/src/index.ts
- packages/network-controller/src/types.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/create-network-client.test.ts
- packages/network-controller/tests/customNetworkClient.test.ts
- packages/network-controller/tests/fake-block-tracker.ts
- types/web3-provider-engine.d.ts
- yarn.lock
The NetworkController will construct a provider that is designed to interface with either an Infura network or a custom RPC endpoint, depending on state, along with a block tracker. We call this pair the network client, and in the extension we have extracted its construction to a separate file. This commit follows the same pattern so that when we replace `web3-provider-engine` we don't have to introduce so many changes. It also consolidates the network client tests (which we still call the provider API tests, though that will be renamed at some point).
- **ADDED:** [`@metamask/controller-utils`] Add `InfuraNetworkType`
Reduces the scope of #1116.
> Extract network client construction from NetworkController

- packages/network-controller/tests/infuraNetworkClient.test.ts
The Infura network client tests are covered by the `create-network-client.test.ts` module. This additional module is redundant.
Done
This was accidentally left behind in #1285
> Remove redundant test suite

- packages/assets-controllers/src/TokenListController.test.ts
- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller provider config property `rpcTarget` has been renamed to `rpcUrl`. This makes it consistent with what we call this value in the network configuration, and it makes this more consistent with the extension.
- **BREAKING:** Rename provider configuration property `rpcTarget` to `rpcUrl`
Closes #1219
> Rename `rpcTarget` to `rpcUrl`

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR changes the behaviour of KeyringController's `addNewAccount` method: whenever a new account is created, it will not be selected.
- **CHANGED**: `addNewAccount` implementation
* Fixes: #1244
> addNewAccount doesn't select new account

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR changes the returned object of `importAccountWithStrategy` method from KeyringController. The method now returns the imported account address along with the keyring current mem state.
- **BREAKING**: Changed `importAccountWithStrategy` returned object
* Fixes #1248
> Change importAccountWithStrategy return

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR ports the private key length check added by [this PR](https://github.com/MetaMask/metamask-extension/pull/17763) on metamask-extension, to the KeyringController's `importAccountWithStrategy` method. 
- **ADDED**: check on `importAccountWithStrategy` for strategy `privateKey`
* Fixes #1247
> Check imported prv key length

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds the `accountCount` parameter to the `addNewAccount` method of the KeyringController, and uses it to make the function call idempotent.
- **BREAKING**: Added `accountCount: number` param to `addNewAccount` method
* Fixes #1242
> Make addNewAccount idempotent

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
- packages/network-controller/tests/provider-api-tests/block-param.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
All unnecessary ESLint ignore comments have been removed from the network controller package. Most of these were added before we had decent types setup for the network client tests.
The `mockRpcCall` function was converted from an arrow function to a function declaration to address lint errors, so the description was copied over from the extension.
None
Relates to #1116
> Remove unnecessary ESLint ignore comments

- packages/network-controller/tests/NetworkController.test.ts
In the NetworkController unit tests we use `setTimeout` to wait for events to occur. We also use `clearTimeout` in the same context to stop waiting if need be. Because we use fake timers in these tests we need the original versions of these functions and not the fake versions. We already capture the original version of `setTimeout` up front, but we don't do the same for `clearTimeout`, and that leads to a warning being printed when we use it. This commit captures `clearTimeout` up front as well to prevent this warning.
N/A
Reduces scope of #1116
> Remove warning in NetworkController unit tests

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/create-network-client.ts
- packages/network-controller/tests/NetworkController.test.ts
When constructing a non-Infura network client, the network `nickname` and `ticker` configuration properties were passed on down to `web3-provider-engine`. However these were entirely unused. There are no references to these in the `web3-provider-engine` package.
None
Relates to #1116
> Remove unused network client configuration

- packages/network-controller/tests/provider-api-tests/helpers.ts
The types used for the network client test helpers have been made more specific; the network type passed in is now required at a type-level to be an Infura network.
This was a type-only change because we were already only passing in Infura neworks for this option. This was done to make a later refactor PR simpler.
None
Relates to #1116
> Improve types used for network client test helpers

- packages/network-controller/tests/NetworkController.test.ts
The unit tests for NetworkController use an object of networks which is used in order to exercise code that creates an Infura provider. The NetworkController unit tests on the extension side, however, use an array instead of an object. This commit makes the two sides more consistent.
N/A
Reduces the scope of #1116.
> NetworkController: Normalize INFURA_NETWORKS array

- packages/network-controller/tests/NetworkController.test.ts
When we replace `web3-provider-engine`, we will intercept `eth_chainId` to return a static result, which, for custom RPC endpoints, will come from the chain ID in the provider config. This means that this chain ID must be convertable to a 0x-prefixed hex string. However, when we specify chain IDs in the NetworkController tests, we sometimes use fake hex numbers. So this commit fixes various references in the tests to fulfill this requirement and generally make chain IDs match what we would expect them to be in reality.
N/A
Reduces the scope of #1116.
> NetworkController: Fix chain IDs in tests

- packages/network-controller/tests/NetworkController.test.ts
The network controller unit tests have been updated to avoid importing a constants file from another package using a relative path import. As a general rule we should be using package imports whenever referencing modules in other packages.
None
This reduces the scope of #1116
> Use package import over relative import in test

- packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
- packages/network-controller/tests/provider-api-tests/block-param.ts
- packages/network-controller/tests/provider-api-tests/no-block-param.ts
- packages/network-controller/tests/provider-api-tests/not-handled-by-middleware.ts
- packages/network-controller/tests/provider-api-tests/shared-tests.ts
JSDoc comments have been added to functions used for the network client tests. These were copied from the extension.
None
This reduces the scope of #1116
> Add comments to network client test functions

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
Validation has been added to internal methods responsible for constructing a provider (upon initialization or after switching networks). They ensure that a custom provider has a chain ID and RPC URL set.
- **BREAKING:** The methods `initializeProvider`, `setActiveNetwork`, and `resetConnection` will now throw if the provider config is of type `rpc` but is missing an RPC URL or a chain ID.
- Previously the chain ID was not required to setup the provider.
- Previously if the RPC URL was omitted, no error would be thrown but the provider would not be setup.
- **BREAKING:** The method `setProviderType` will now throw when passed the type `rpc`.
- Previously no error would be thrown but the provider would not be setup.
This reduces the scope of #1116
> Add validation when setting up custom provider

- packages/network-controller/tests/create-network-client.test.ts
The tests for each network client type now use a separate `describe` block, ensuring that it's clear which type of client was being tested when a test fails.
None
Not related to any issues
> Add `describe` block per network client type

- packages/network-controller/tests/NetworkController.test.ts
The network controller `waitForStateChanges` test helper has been updated to accept the controller messenger as named argument rather than as a positional argument. This aligns better with our usual coding conventions and it makes these tests more aligned with the extension unit tests.
None
Relates to #1197
> Refactor `waitForStateChanges` test helper

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR refactors the `importAccountWithStrategy` method from KeyringController to not select the imported account.
As a new test case has been added, I took the chance to refactor tests groups for the `importAccountWithStrategy`.
- **CHANGED**: `KeyringController.importAccountWithStrategy` to not select imported address
* Fixes #1249
> `importAccountWithStrategy` shouldn't select address

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR changes the `KeyringController.createNewVaultAndRestore` method to not create a new vault if there is already an existing one. In this case, it will simply return the existing vault.
- **CHANGED**: `createNewVaultAndRestore` from KeyringController, to not overwrite existing vault.
* Fixes #1250
> Skip vault creation if one already exists

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/transaction-controller/src/TransactionController.test.ts
This PR changes the type of the `networkDetails` state property, using an `EIPS` object instead of `isEIP1559Compatible`
- **BREAKING**: Changed shape of `networkDetails` state property type
- Replace references to `networkDetails.isEIP1559Compatible` with `networkDetails.EIPS.1559`
* Fixes #1218
> Widen format of networkDetails

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
This PR adds the `destroy` method to stop the block tracker polling.
- **ADDED**: `destroy` method
* Fixes #1202
> Add `destroy` method

- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokenListController.ts
- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/gas-fee-controller/src/GasFeeController.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
Despite its name, the `providerConfigChange` event in NetworkController doesn't get emitted whenever the `providerConfig` property in state is changed. Rather, it gets updated as the very last step in `lookupNetwork`. This method is called:
- When the provider is initialized
- When the network is switched
- When the network is rolled back to the previous setting
- When `resetConnection` is called
`lookupNetwork` can also be called on its own.
If this were not enough, we already provide a way to listen for changes to a particular property in state: by passing a selector function to the `subscribe` method on the controller messenger.
So, this commit removes the `providerConfigChange` event from NetworkController. Instead of the following code:
```
messenger.subscribe( …
```
> NetworkController: Remove providerConfigChange event

- packages/network-controller/tests/NetworkController.test.ts
Most of the lookup network unit tests have been moved to a helper function, so that we can use them to test other methods in a later PR.
None
Relates to #1210
> Move lookup network tests to helper function

- packages/assets-controllers/src/AssetsContractController.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/assetsUtil.test.ts
- packages/assets-controllers/src/assetsUtil.ts
- packages/controller-utils/src/types.ts
Enable token detection for the Aurora network.
> Enable token detection for the Aurora network

- packages/network-controller/tests/NetworkController.test.ts
The `lookupNetworkTests` helper function has been updated to distinguish between the initial state and the expected provider config at the end of the operation under test.
Previously the `providerConfig` passed in was used as part of the initial state _and_ as the expected end state. This worked for operations like `resetConnection` and `lookupNetwork` where the network doesn't change, but it was incompatible with functions that change the active network.
None
Relates to #1210
> Refactor `lookupNetworkTests` helper function

- packages/network-controller/tests/NetworkController.test.ts
The network controller unit test helper function
`waitForPublishedEvents` has been updated to take all arguments as named rather than positional parameters. This makes the tests more aligned with the extension network controller unit tests.
None
Relates to #1197
> Refactor `waitForPublishedEvents` helper function

- packages/network-controller/tests/NetworkController.test.ts
The network controller unit test helpers `waitForPublishedEvents` and `waitForStateChanges` have been updated to use the option name `operation` instead of `produceStateChanges` or `produceEvents`. This makes them more closely aligned with the extension unit tests.
None
Relates to #1197
> Refactor test helper `operation` property name

- packages/network-controller/tests/NetworkController.test.ts
The network controller unit tests have been refactored to use a helper function to test the effects of the refresh network step. This step happens during a variety of different functions, and has the same effects each time.
All tests related to the refresh network step have been consolidated in a helper function. This helper function is invoked separately for each method that internally calls `#refreshNetwork`. The one exception to this is `rollbackToPreviousProvider`, which is not tested using this helper function due to difficulties in abstracting the necessary test setup.
None
This relates to #1210
> Refactor refresh network tests

- packages/network-controller/tests/NetworkController.test.ts
The network controller helper function `buildProviderConfig` now ensures that the provider configuration returned is valid for Infura networks. Previously it always returned valid RPC provider configs, but if the config was an Infura type it might be missing some properties.
None
Relates to #1197
> Improve `buildProviderConfig` helper function

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The network controller now emits the events `networkWillChange` and `networkDidChange` when the network is being refreshed. The event `networkWillChange` is emitted before the switch begins (before the network status is cleared), and the `networkDidChange` event is emitted after the new provider is setup (but before it has finished initializing).
- ADDED: The events `networkWillChange` and `networkDidChange` are emitted during `setProviderType`, `setActiveNetwork`, `resetConnection`, and `rollbackToPreviousProvider`
- The `networkWillChange` event is emitted before the network is switched (before the network status is cleared),
- The `networkDidChange` event is emitted after the new provider is setup (but before it has finished initializing).
Closes #1210
> Add network change events

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR removes the `validatePassword` method in favor of `verifyPassword`, using internally `EthKeyringController.verifyPassword` instead of manually comparing the provided password with the `EthKeyringController`'s state.
Now that `verifyPassword` is async, other methods that verify a password must now await; therefore, `exportSeedPhrase` and `exportAccount` have been made async too. 
- **REMOVED**: `validatePassword` method in favor of `verifyPassword`
- **ADDED**: `verifyPassword(psw: string): Promise<void>` method to use `EthKeyringController.verifyPassword`
- **BREAKING**: `exportAccount` has been made async
- **BREAKING**: `exportSeedPhrase` has been made async
* Fixes #1253
> Add verifyPassword and remove validatePassword

- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- yarn.lock
This PRs edits the `createNewVaultAndRestore` `seed` param type from `string` to `Uint8Array`
- **BREAKING**: `createNewVaultAndRestore` `seed` param type changed from `string` to `Uint8Array`
* Fixes #1251
> `createNewVaultAndRestore` handles seed as Uint8Array

- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/TokenDetectionController.test.ts
- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/assetsUtil.test.ts
- packages/controller-utils/src/constants.ts
- packages/controller-utils/src/types.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/create-network-client.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/transaction-controller/src/TransactionController.test.ts
The constant `NetworksChainId` was ambiguous in whether it referred to network or chain Ids, and it didn't match our enum naming conventions. It was also undocumented, and unclear in which networks it was intended to contain.
It has been replaced with a `ChainId` constant with documentation and a clear scope (built-in networks). A `BuiltInNetworks` enum has been added as well to make that more clear.
- **BREAKING**: Replace the `NetworksChainId` constant with `ChainId`
- Added: Add constants `BuiltInNetwork` and `ChainId`
Relates to #1209
> Replace `NetworksChainId` constant with `ChainId`

- packages/message-manager/src/AbstractMessageManager.test.ts
- packages/message-manager/src/AbstractMessageManager.ts
- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
Some messages (for example in MMI) have an intermediate state after being approved where they are not signed, due to the implicit delay in custodial signing.
This adds an `inProgress` status to messages which allows the user to continue using the extension while the message is being signed.
The method is also exposed via the Signature Controller.
- **<ADDED>**: Added a method to set a message status to "inProgress"
- Issue #1341 
- This [code-fencing PR](https://github.com/MetaMask/metamask-extension/pull/18770#discussion_r1185210107) is a dependent of this message.
> [MMI] add setMsgInProgress method to AbstractMessageManager

- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/TokensController.ts
The `networkType` configuration option has been removed from the NFT controller and the tokens controller. In both cases it was unused.
- **BREAKING:** Remove the `networkType` configuration option from `NftController` and `TokensController`
This relates to #1209
> Remove unused `networkType` configuration

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
Currently, `lookupNetwork` spawns two asynchronous operations. One operation fetches the network ID and the other determines whether the network supports EIP-1559. Because the second operation makes use of `getEIP1559Compatibility`, it results in changing the controller state implicitly. This is a bit strange, because `lookupNetwork` also changes the controller state. In the extension version of `lookupNetwork`, the steps are divided such that all state changes occur _after_ all asynchronous operations complete. This commit brings the behavior of `lookupNetwork` in line with the extension.
There should be no functional changes, so no changelog entry needed.
> Consolidate state changes in lookupNetwork

- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/NftDetectionController.ts
The NFT detection controller now supports NFT detection on any Ethereum Mainnet networks, including custom RPC endpoints. Previously this was only supported on the built-in Ethereum Mainnet. This restriction was likely not intentional in the first place (at least I can't think of a reason for it).
- **BREAKING:** Remove the `networkType` configuration option from the NFT detection controller
- CHANGED: Support NFT detection on Ethereum Mainnet custom RPC endpoints
This relates to #1209
> Support NFT detection on custom Mainnet RPC endpoints

- packages/ens-controller/package.json
- packages/ens-controller/src/EnsController.test.ts
- packages/ens-controller/src/EnsController.ts
- packages/ens-controller/tsconfig.build.json
- packages/ens-controller/tsconfig.json
- yarn.lock
The network change handler for the ENS controller has been broken since the PR #1170 due to a conflict with #1196, which was merged around the same time. It referenced the `network` property of the network state that we have removed.
The change handler has been updated to use `networkId` instead. Additionally, the `NetworkState` type has been imported so that we're less likely to make this mistake again.
- **Fixed**: Fix ENS controller failure to initialize after switching networks.
Relates to #1209
> Fix ENS controller network change handler

- packages/transaction-controller/src/TransactionController.ts
Incoming token transactions were given the correct chain ID on the `txMeta` object, but the `transaction` object inside of that was given a hard-coded chain ID of `1`. Likely we don't use this property for anything, since we only keep track of these transactions to display them as transaction history, and we'd use the `txMeta` property for filtering those. But the type requires this property to be set, so it should be correct.
- FIXED: Fix transaction parameters given to incoming token transactions
Relates to #1209
> Replace hard-coded `chainId` on incoming token transactions

- .github/workflows/publish-release.yml
Now that we've landed the changes in https://github.com/MetaMask/action-npm-publish/pull/37 we can safely turn this back on _without_ pinging all of `@metamask` :upside_down_face:
> Re-enable the slack bot

- packages/permission-controller/package.json
- packages/permission-controller/src/PermissionController.ts
- packages/permission-controller/src/rpc-methods/getPermissions.ts
- packages/permission-controller/src/rpc-methods/requestPermissions.ts
- packages/permission-controller/src/utils.ts
- yarn.lock
The `@metamask/types` package is no longer actively maintained, so it has been removed. Most types we used to get from there were migrated to `@metamask/utils` or can be gotten from `json-rpc-engine`.
Just one type had no replacement: `PermittedHandlerExport`. Since it is specific to the permission controller anyway, it was added to that package directly.
- CHANGED: The export `permissionRpcMethods` has a slightly different type; the second generic type variable of the `getPermissions` handler is now `undefined` rather than `void`
- CHANGED: The `@metamask/types` dependency has been removed
None
> Remove `@metamask/types`

- packages/message-manager/src/AbstractMessageManager.test.ts
- packages/message-manager/src/AbstractMessageManager.ts
- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
- **ADDED**: Metadata property of messages, plus a method to mutate it
- **ADDED**: A means of deferring the message setting as signed, via the params
- **ADDED**: Method to get all messages
- **ADDED**: Event to surface message signing to the client
* Fixes #1341
> Support MMI use cases in signing typed messages

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
If the network is changed multiple times in quick succession, multiple "instances" of `lookupNetwork` can get run simultaneously. This happens because each time the network is changed, `lookupNetwork` is called. Because we do not expect `lookupNetwork` to run synchronously — it makes HTTP requests and waits for them to complete — and because it makes changes to the state, this creates a race condition where the state may not reflect the last network that was selected.
Currently, to resolve this problem, `lookupNetwork` makes use of a mutex. This ensures that only one "instance" of `lookupNetwork` is running at a given time. However, this trades one problem for another, because as a result, on mobile, the UI will be slow to update, as the network controller has to "process" all of the …
> lookupNetwork: Drop mutex; bail on network change

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- packages/keyring-controller/tests/mocks/mockEncryptor.ts
This PR extends the `KeyringConfig` type to support `cacheEncryptionKey?: boolean`, and adds the `submitEncryptionKey` method, to unlock keyrings with encryption key and salt.
Tests have been refactored:  
* Test cases now use a `withController` util function to create a fully initialized KeyringController with custom parameters passed by tests themselves 
* `MockEncryptor` has been edited to better match the supported API and work with encryption keys.
- **ADDED**: `submitEncryptionKey` method
- **CHANGED**: `KeyringConfig` type to support optional `cacheEncryptionKey: boolean`
* Fixes #1257
* Fixes #1252
> Add submitEncryptionKey method

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
Hex and number responses from the `net_version` request are now accepted. While most chains return decimal strings for this request, some chains were returning hex responses instead and failing our validation for this request.
Support for number responses was added because it likely worked in older versions of the extension  as well, so support is maintained to avoid similar problems.
- CHANGED: Support hex and number responses to `net_version` requests
This is a port of the extension PR: https://github.com/MetaMask/metamask-extension/pull/19156
> Support hex and number `net_version` responses

- packages/rate-limit-controller/src/RateLimitController.test.ts
- packages/rate-limit-controller/src/RateLimitController.ts
This changes the `RateLimitController` so defining a rate limit for a specific method is possible.
This changes the structure of the passed API config object.
- BREAKING
* Fixes #1314
> BREAKING: Allow `RateLimitController` to define a rate-limit per method

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The `lookupNetwork` method has been updated to ensure the network details are updated correctly even when the network ID is the same as before.
A test has been added to confirm that this works. It was failing before this change.
When writing this test, I noticed that the previous test was broken as well. It was passing but it didn't setup the test scenario correctly (the network ID was changing, but it was expected not to). It has been fixed as well.
- FIXED: Update network details even when the network ID remains unchanged
> Update network details even when ID matches

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds the `getKeyringForAccount` method on `KeyringController`.
This method calls the homonym `EthKeyringController` method, which returns the Keyring including the provided account. Throws an error when no matching keyring is found.
- **ADDED**: `getKeyringForAccount` method
* Fixes: #1256
> Add `getKeyringForAccount` method

- packages/permission-controller/src/PermissionController.test.ts
- packages/permission-controller/src/PermissionController.ts
In the extension we pass a frozen array to the PermissionController, but TypeScript complains that it is expecting a mutable array, since we haven't specified the array to be readonly. This PR fixes that.
This shouldn't change anything functionally, merely correcting a type error.
- **Changed**: Make PermissionController `unrestrictedMethods` constructor arg `readonly`
> Make PermissionController `unrestrictedMethods` constructor arg readonly

- packages/network-controller/tests/NetworkController.test.ts
This makes it easier to visually compare differences in the
NetworkController unit tests between extension and this repo.
(None)
> Sync NetworkController constructor tests w/ extension

- packages/network-controller/tests/NetworkController.test.ts
These tests are present in the test suite for the extension version of NetworkController, but not here.
For reference, see:
- https://github.com/MetaMask/metamask-extension/blob/b7ef99847aabf8cf8e4fb6e14eb8469926a74eba/app/scripts/controllers/network/network-controller.test.ts#L2352
- https://github.com/MetaMask/metamask-extension/blob/b7ef99847aabf8cf8e4fb6e14eb8469926a74eba/app/scripts/controllers/network/network-controller.test.ts#L2288
(None)
> Add missing tests for setProviderType and setActiveNetwork

- packages/network-controller/tests/NetworkController.test.ts
The extension version of the tests for NetworkController use Jest snapshots to verify that the controller has the correct initial state after being constructed. This updates the tests to match.
(None)
> Use Jest snapshots for testing initial NetworkController state

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
`lookupNetwork`, a method in NetworkController, collects information about the network via two requests and stores that information in state. If either of these requests fails, it means that this step was unsuccessful, and we should reset all of the pieces of state that would ordinarily get updated after a call to `lookupNetwork` in order to match the initial state of the controller. The network ID and network status are correctly reset, but the network details aren't. To be specific, `networkDetails.EIPS[1559]` will be set to false to indicate that the network doesn't support EIP-1559. This isn't completely accurate, as we actually don't know that. This commit fixes this problem by removing the property instead of setting it to false.
- **CHANGED**: Update `lookupNetwork` to unset …
> Reset network details when lookupNetwork request fails

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
There are two ways in which the `getEIP1559Compatibility` method in this
version of NetworkController differs from the same method in the
extension version:
- In this version, if `getEIP1559Compatibility` is called and
`networkDetails.EIPS[1559]` in state is false, then the network is hit
again in order to update the property. In the extension, however,
that doesn't happen.
- In this version, if `getEIP1559Compatibility` is called but the
provider has not been set yet, then the network is assumed to support
EIP-1559 and the method returns true. In the extension, however,
the network is assumed to _not_ support EIP-1559 and the method
returns false.
With that in mind, this commit updates `getEIP1559Compatibility` to
better match the extension and updates the tests to match.
It also updates …
> Update getEIP1559Compatibility to match extension

- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
Modifies the error handling pattern for the wallet_watchAsset NFT support introduced in https://github.com/MetaMask/core/pull/1173. In that approach we were passing certain errors in the `requestData`  to the `ApprovalController` so that the errors could be displayed in the UI. We have elected to not pursue this approach because it diverges from the pattern of throwing these errors directly to the dApp we use everywhere else.
> Modify error handling for wallet_WatchAsset in NftController

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The extension version of NetworkController checks the `type` that's passed to `setProviderType` at runtime to ensure that it's not "rpc" and it matches the name of a known built-in Infura network. This commit copies those checks along with their tests.
(None)
For reference, see the extension: https://github.com/MetaMask/metamask-extension/blob/a5c370cdfa6bb42ab0a2e8d78a6387aa1dd17758/app/scripts/controllers/network/network-controller.ts#L710.
> Add runtime checks to NC setProviderType

- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- yarn.lock
This PR refactors `KeyringController` to extend `BaseControllerV2`. 
This controller's state is completely non-persistent and is kept in sync with the inner `EthKeyringController`'s memStore through event subscription. For this reason, the `fullUpdate` method is now unnecessary and has been removed - Tests have been refactored to use controller state for assertions so that this mechanism is implicitly well covered. 
All the methods that returned `fullUpdate`, now return the `KeyringController`'s state with `vault`, `encryptionKey` and `encryptionSalt` removed as sensitive data; these parameters can always be found with `KeyringController.state`  
- **BREAKING:** KeyringController now inherits from BaseControllerV2
- The constructor takes a single argument, an options bag, instead of three …
> Migrate KeyringController to BaseControllerV2

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
With this PR, the `KeyringController` emits an `accountRemoved` event with a `string` payload representing the account removed, whenever `removeAccount` method is called. 
- **ADDED**: `KeyringController:accountRemoved` event, fired whenever an account is removed through `removeAccount` method.
* Fixes #1260
> Fire `KeyringController:accountRemoved` event when removing account

- packages/approval-controller/src/ApprovalController.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
- a test to ensure that nfts are added to correct account/chainId when the user changes account/chain before accepting the pending request
> Add test for NFT added via `wallet_watchAsset`

- packages/approval-controller/src/ApprovalController.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/NftDetectionController.ts
- packages/assets-controllers/src/constants.ts
- packages/controller-utils/src/constants.ts
This PR decouples the `detection` parameter passed to the `addNft` method on the NftController, introducing more granular control over the logic within the function. Now instead of receiving a single `detection` argument as `{ chainId, accountAddress }` the presence of which was meant to both indicate that the nft being added was detected and which account/chainId to add the NFT to in state, there are two separate arguments `accountParams` and `source. 
This allows us to be more clear and explicit about the source of the NFT being added (manually, via dapp, or auto-detection) which in turn allows us finer tuned logic control and event handling for those different sources.
**Changelog entries:**
- **FIXED:** Fix ApprovalController constructor so that it accepts a messenger created via a …
> Disaggregate the `detection` param for `addNft()` 

- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
The extension offers a way to back up user customized settings in the
wallet and then restoring those settings later from a previous backup.
One of the settings that is preserved in this backup is the list of
custom networks. When restoring this list, the extension attempts to
update NetworkController's state directly. This worked in the extension
version of NetworkController, but it won't work with the version here in
core, as the `update` method in a controller that inherits from
BaseControllerV2 cannot be called from outside the controller itself.
To fix this, this commit adds a new method to NetworkController,
`loadBackup`, which ports the same functionality from the extension.
Related to https://github.com/MetaMask/metamask-extension/issues/17931.
- **ADDED:** Add `loadBackup` method …
> Add loadBackup method to NetworkController

- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
This PR aims to remove  `{ parseJsonData: boolean }` optional parameter from TypedMessage signer because it's never sent from extension. 
Here is the proof that this fix is working with that. https://github.com/MetaMask/metamask-extension/pull/19184
> Remove optional parameter from newUnsignedTypedMessage function

- packages/network-controller/src/index.ts
- packages/transaction-controller/package.json
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- yarn.lock
According to its types, TransactionController takes the proxy versions of the provider and block tracker that NetworkController exposes. However, this isn't really necessary, and in fact this introduces churn, because if anything around that proxy changes on the NetworkController side, then the tests for TransactionController need to change too. By relaxing the types so that TransactionController only need accept the _actual_ provider and block tracker interfaces rather than the proxies, it prevents the tests from having to be unnecessary updated and makes things simpler for consumers as well.
To make this change, `@metamask/network-controller` needed to be updated to not only expose its Provider type but also its BlockTracker type.
Related to https://github.com/MetaMask/core/pull/1439.
- …
> Simplify network types accepted by TransactionController

- packages/controller-utils/package.json
- packages/controller-utils/src/util.test.ts
- packages/controller-utils/src/util.ts
- packages/gas-fee-controller/src/gas-util.ts
- types/eth-query.d.ts
- yarn.lock
The `query` function was updated in #1266 to use `hasProperty` has part of an effect to improve the types being used. Unfortunately this had the unexpected affected of breaking this condition because `hasProperty` doesn't look up the prototype chain, but the method we were checking for was on the prototype. `hasProperty` is only meant to be used with plain objects.
The condition has been updated to use `in`, and the tests have been updated to use a more realistic EthQuery mock that has methods as prototypes.
To fix various type errors, an old inlined EthQueryLike type has been replaced by the real EthQuery type. This required adding `eth-query` as a dependency to the controller utils package.
Related to https://github.com/MetaMask/metamask-extension/issues/19735
- FIXED: Fix bug where …
> fix(controller-utils): Fix query function

- packages/approval-controller/src/ApprovalController.test.ts
- packages/approval-controller/src/ApprovalController.ts
- packages/controller-utils/src/constants.ts
Adds `success` and `error` methods to the `ApprovalController` to easily create standardised approvals to display success or error pages in the clients.
These methods both support optional arguments including `message`, `error`, and `header` to configure what text or components are displayed in the approval, plus `flowToEnd` which will end the specified flow when the result confirmation is approved.
This PR also includes some minor refactors for consistency, including:
- Replacing use of the `private` modifier with the `#` syntax to protect private properties and methods at runtime.
- Removing calls to any private methods from the unit tests.
- Grouping the many types into categories to simplify future additions.
- **ADDED**: `success` and `error` methods to display standardised result …
> Display result pages using the ApprovalController

- packages/message-manager/src/TypedMessageManager.test.ts
- packages/message-manager/src/TypedMessageManager.ts
- packages/message-manager/src/utils.test.ts
- packages/message-manager/src/utils.ts
`eth_signTypedData_v4` and `v3` should take an object as well as string for `data` parameter.
These changes are NON breaking.
Check out the issue below for a deeper explanation of the issue.
fixes https://github.com/MetaMask/metamask-extension/issues/18462
> eth_signTypedData_v4 and v3 should take an object as well as string for data parameter.

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
Update the `TransactionController` to await the approval request promise before automatically performing the relevant logic, either signing and submitting the transaction, or cancelling it.
This is part of the new confirmations architecture which aims to simplify the use of approvals in controllers, and decouple the public API from the concept of approval.
- **BREAKING**: Change the `approveTransaction` and `cancelTransaction` methods to private.
> Await approval promise in TransactionController

- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
This PR is aiming to add version in Typed Messages in Signature Controller while passing message data to messengers.
> Add sign version to approval message in Signature Controller

- .github/workflows/lint-build-test.yml
The CI workflows now succeed even when we fail to restore the cache. Cache restores occasionally fail, so we may as well continue with the workflow if we can do without it.
None
> Tolerate CI cache failures

- packages/assets-controllers/src/NftController.ts
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/854
Currently when `wallet_watchAsset` is called with type `ERC721` or `ERC1155`, we don't check whether the asset actually matches the type passed - we push it into a flow for suggested NFTs do a bunch of other validation, and if it passes we add it with the correct value for `standard` even if it doesn't match the `type` (standard) originally passed in the request. This adds validation of this type.
After:
https://github.com/MetaMask/core/assets/34557516/92a9bba5-c466-4ebc-b82c-b395649be52b
- **ADDED**: Adds validation that the standard of an NFT added via the `watchNFT` method matches the `type` argument passed with the request.
> add validation that the nft standard matches the type argument

- packages/network-controller/tests/NetworkController.test.ts
The tests for `upsertNetworkConfiguration` and `removeNetworkConfiguration` require improvement for a few reasons:
- Tests do not verify the full value of `networkConfigurations` in state.
- Not all code paths are being tested. For instance, `ticker` could be falsy or absent, so it needs two tests to confirm the behavior. Also the code path for the "update" version of the `upsertNetworkConfiguration` isn't being tested the same way as the "insert" version.
- The order of the tests is not as logical as it could be. The tests would be easier to follow if tests that exercise similar functionality were closer together (or even grouped together using `describe`).
- The "refresh network" functionality isn't being exercised when the `setActive` option is given as true.
(None)
> Rewrite network configuration management tests

- packages/preferences-controller/src/PreferencesController.test.ts
- packages/preferences-controller/src/PreferencesController.ts
Added a toggle for showing the test networks to mobile, added to the preferences controller a variable `showTestNetworks` to save the user preference.
- ADDED
Boolean for show test networks on the preferences controller.
> show test network

- packages/permission-controller/src/rpc-methods/index.ts
Had this odd issue with these tuple types when importing into mobile. This fixes it by explicitly stating the tuple types.
> Fixed issue with type types from permissions rpc methods

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
A cache miss during the release workflow guarantees that the release will fail. The cache has the build; without it, we have nothing to release.
The release workflows have been updated to fail on cache miss during the release workflow, ensuring that we spend less time diagnosing what failed in this scenario. We can proceed directly to retrying to workflow if this happens.
No changes
> Improve error message when cache fails during release

- packages/message-manager/src/TypedMessageManager.ts
Currently, when adding typed messages using the `TypedMessageManager`, it does not wait for the security provider request to be completed and for the message to be added before firing the `unapprovedMessage` event. This is causing errors in the clients as logic triggered by the event assumes the message is available.
This `await` is already present in the `PersonalMessageManager` and `MessageManager`.
Fixes [#19826](https://github.com/MetaMask/metamask-extension/issues/19826) in the extension pending release and adoption.
- **FIXED**: Race condition when adding typed messages
> Fix race condition when creating typed messages

- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
This PR adds a few necessary methods for MMI, we need to access the 3 message manager methods to get all the messages. Also need a method to act as a proxy to the `setMetadata` in message manager.
- **ADDED**: A method to set message metadata using the message manager -> `setMetadata`
- **ADDED**: A getter called `allMessages` to get all messages using the 3 managers
* Fixes https://github.com/MetaMask/core/issues/1341#issuecomment-1562893931
> MMI-3035 create the getAllMessages and setMetadata

- packages/controller-utils/src/constants.ts
- packages/controller-utils/src/types.test.ts
- packages/controller-utils/src/types.ts
- packages/network-controller/package.json
- packages/network-controller/tests/NetworkController.test.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- yarn.lock
- Added linea networks support in controller utils
- Added linea networks support in network controller
- Added linea networks support in transaction controller
- Updated `@metamask/eth-json-rpc-infura` package version to 8.1.0 to support linea networks
- **ADDED:** Add Linea networks to `TESTNET_TICKER_SYMBOLS`, `BUILT_IN_NETWORKS`, `NETWORK_ID_TO_ETHERS_NETWORK_NAME_MAP`, `InfuraNetworkType`, `NetworkType`, `BuiltInNetworkName`, `ChainId`, `NetworkId`, and `NetworksTicker`
- `isNetworkType` will now return true when given `linea-mainnet` or `linea-goerli`
- **ADDED:** Add support for Infura provider types `linea-mainnet` and `linea-goerli`
- **CHANGED:** Update `@metamask/eth-json-rpc-infura` package version to 8.1.0 to support Linea networks
- **CHANGED:** Update `approveTransaction`, …
> feat: add linea networks support

- package.json
- packages/controller-utils/CHANGELOG.md
- packages/controller-utils/package.json
- packages/keyring-controller/CHANGELOG.md
- packages/keyring-controller/package.json
- packages/message-manager/CHANGELOG.md
- packages/message-manager/package.json
- packages/network-controller/CHANGELOG.md
- packages/network-controller/package.json
- packages/transaction-controller/CHANGELOG.md
- packages/transaction-controller/package.json
> Release 66.0.0

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
The `TokenRatesController` was always initialized with `eth` as the default `nativeCurrency` configuration. This could result in the wrong rates being retrieved if the current network has a different currency symbol.
The constructor has been updated to require a `ticker` parameter, used to initialize the `nativeCurrency` configuation for the current network at time of construction.
- **BREAKING**: New required `ticker` constructor parameter for the `TokenRatesController`
- Fixed: Fix bug where token rates were incorrect if initialized with a non-Ethereum selected network.
- The condition that would fail is no longer possible, so there is no way to add a test case for it. The tests for this controller are very …
> Fix initial native currency `TokenRatesController` configuration

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
There is a bug present in the TokenRatesController where a network switch can result in token rates being requested for the wrong network.
This can happen when the network state update event comes before currency rate controller state update event. The controller only works correctly if the currency rate controller state update event happens first.
Instead of getting the ticker from the currency rate controller, we now get it directly from the network controller. This simplifies the controller and ensures that we always use the currency symbol corresponding with the current chain ID.
- **BREAKING**: Remove `onCurrencyRateStateChange` constructor parameter from TokenRatesController
- Fixed: Fix bug where token …
> Prevent bug where incorrect symbol used for token rates

- packages/assets-controllers/src/TokenRatesController.test.ts
Unnecessary `nock` calls have been removed from the `TokenRatesController` tests. Additionally, real network requests have been disabled for this test suite as a precaution.
None
> Remove unnecessary nock calls from `TokenRatesController` tests

- packages/assets-controllers/src/TokenRatesController.test.ts
The `TokenRatesController` test case for updating token rates has been simplifed by replacing controllers with stubs. The test was using a real `PreferencesController`, `NetworkController`, and `TokensController`.
None
> Simplify `TokenRatesController` update test case

- constraints.pro
- packages/assets-controllers/package.json
- packages/controller-utils/package.json
- packages/gas-fee-controller/package.json
- packages/network-controller/package.json
- packages/transaction-controller/package.json
- yarn.lock
We included `babel-runtime` as a dependency to a few packages because we thought it was an undocumented dependency of `eth-query`, but we had gotten it mixed up with `ethjs-query`. Really we only need this as a dependency in the transaction controller.
The constraints have been updated, and all unnecessary references to `babel-runtime` have been removed.
Additionally, in the one package where it's still required, `babel-runtime` has been made into a `peerDependency` instead of a direct dependency. This better reflects the requirement: we don't need to use it directly, we just need it to be available in the environment this package is run in.
The missing `babel-runtime` dependency was discovered in https://github.com/MetaMask/core/pull/341
- Changed: Remove `babel-runtime` dependency
- …
> Remove unnecessary `babel-runtime` dependencies

- package.json
None of the dependencies specified at the root are required to install any of the packages within the monorepo; they purely exist for development purposes. So moving them to `devDependencies` communicates their intended usage better.
(N/A)
> Update root manifest: 'dependencies' -> 'devDependencies'

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
The `TokenRatesController` no longer starts polling automatically. Instead the `start` method must be called to start polling. This makes the controller dramatically easier to test.
A `stop` method has been added as well, to stop polling.
The polling state is maintained independently from the `disabled` configuration property, as that is used today for a different purpose (`disabled` is used to to let users opt-out of using token rates).
- **BREAKING**: Disable automatic polling
- Polling must be started explicitly by calling the `start` method
- The token rates are not updated upon state changes when polling is disabled.
- **BREAKING**: Replace the `poll` method with `start`
- The `start` method does not offer a …
> Disable automatic token rate polling

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
The `TokenRateController` setters for `chainId` and `tokens` have been removed. These were confusing, unnecessary, and presented obstacles to testing asynchronous events triggered by these setters.
- **BREAKING**: Remove `TokenRatecontroller` setter for `chainId` and `tokens` properties
> Remove `TokenRateController` setters

- packages/address-book-controller/package.json
- packages/approval-controller/package.json
- packages/assets-controllers/package.json
- packages/base-controller/package.json
- packages/controller-utils/package.json
- packages/ens-controller/package.json
- packages/gas-fee-controller/package.json
- packages/keyring-controller/package.json
- packages/keyring-controller/src/KeyringController.test.ts
- packages/message-manager/package.json
- packages/network-controller/package.json
- packages/notification-controller/package.json
- packages/permission-controller/package.json
- packages/signature-controller/package.json
- packages/transaction-controller/package.json
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- yarn.lock
This PR updates `@ethereumjs/tx` and `@ethereumjs/common`, as well as `@metamask/utils` across the monorepo packages.
* Related to #1441 
* Related to #1315 
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated `@ethereumjs/tx` to `^4.2.0`
- **CHANGED**: Updated `@ethereumjs/common` to `^3.2.0`
- **CHANGED**: Updated `@keystonehq/metamask-airgapped-keyring` to `^0.13.1`
- **CHANGED**: Updated `@metamask/utils` to `^6.2.0`
- **CHANGED**: Updated …
> Update `@ethereumjs/tx` and `@ethereumjs/common`

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
When the network switches, the `TokenRatesController` was relying upon the combination of two state updates (from the network controller and the tokens controller), both of which were needed in order to ensure the controller configuration was valid. These events don't arrive at the same time, meaning that the controller was potentially making one invalid call each network switch.
Additionally, there is a risk that the second event could result in no update (e.g. because the destination network isn't supported, or because there were no tokens), resulting in the data from the invalid call remaining in state.
This has been prevented by updating the controller to use the `allTokens` and `allDetectedTokens` state rather than the `tokens` state. A network switch now triggers a single event, and …
> Fix another `TokenRatesController` event ordering bug

- packages/assets-controllers/src/TokenRatesController.test.ts
- packages/assets-controllers/src/TokenRatesController.ts
The `TokenRatesController` was updating token rates each time any state change event was recieved, even when the change was totally unrelated.
The controller now ignores irrelevant state changes. Only relevant state changes will trigger token rate updates.
Fixes #1466
- Fixed: Prevent the `TokenRateController` from making redundant token rate updates
> Prevent redundant token rate updates

- packages/assets-controllers/src/TokenRatesController.test.ts
All ESLint warnings in the `TokenRateController` tests have been addressed. They were all related to the state change listners: they all had the wrong type signature, and some of them were mistakenly called without `await`.
None
None
> Fix `TokenRateController` test ESLint warnings

- packages/phishing-controller/src/PhishingController.test.ts
- packages/phishing-controller/src/PhishingController.ts
The default phishing warning configuration has been removed. This fallback configuration was used as a starting point, and was especially useful for users who were unable to access phishing configuration updates for whatever reason (e.g. network issue). However, this default configuration is too stale and has been the source of many problems. It also contributes to our project being occasionally flagged as malware due to the presence of malicious URLs. It also bloats the application bundle size quite a bit.
We have removed the default config. The default phishing list is now blank.
Closes #1225
- **BREAKING**: Remove fallback phishing configuration
- The default configuration is now blank. A custom initial configuration can still be specified via the constructor to preserve the old …
> Remove fallback phishing configuration

- packages/base-controller/src/BaseControllerV2.test.ts
- packages/base-controller/src/BaseControllerV2.ts
The state derivation functions will throw an error today if any state properties are missing metadata. This interrupts the state operation completely. There are a few state operations that we want to ensure are never interrupted, even if some data is invalid, so this behavior has been changed.
Instead we will skip any state properties with missing metadata, and throw an error in a timeout handler so that the problem is still captured.
None
- Changed: When deriving state, skip properties with invalid metadata
- The previous behavior was to throw an error
- An error is thrown in a timeout handler so that it can still be captured in the console, and by global unhandled error handlers.
> Improve error handling when state metadata is missing

- packages/controller-utils/CHANGELOG.md
The changelog for `@metamask/controller-utils` has been updated to reference a breaking change that made its way into v3.1.0 without us noticing. v3.1.0 and all minor releases following it have been marked as deprecated to help others avoid this problem.
Discovered while working on https://github.com/MetaMask/metamask-mobile/pull/6903
N/A
> Update controller-utils changelog with breaking change

- packages/assets-controllers/src/TokenListController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/transaction-controller/src/TransactionController.test.ts
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1005
Fixes: #1560 
- **BREAKING**: NetworkStatus is moved into networkDetails.
- **BREAKING**: Network status and details are no longer on the networkcontroller state root. The same values are retrieved by networkClientId via `networkController.state.networksMetadata[<networkClientId>]`. Most cases can update to use 
`networkController.state.networksMetadata[networkController.state.selectedNetworkClientId]` to get at the status and details in the following shape:
```
{
status: NetworkStatus,
EIPS: {
...
}
}
```
> Network meta

- package.json
- packages/message-manager/CHANGELOG.md
- packages/message-manager/package.json
New release of message managers.
> Release 68.0.0

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds the `getEncryptionPublicKey` method on `KeyringController`.
This method calls the homonym `EthKeyringController` method, which returns the encryption public key of the specified address.
- **ADDED**: `getEncryptionPublicKey` method
* Fixes: #1556
> Add getEncryptionPublicKey on KeyringController

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/network-controller/src/NetworkController.ts
- packages/network-controller/src/create-auto-managed-network-client.test.ts
- packages/network-controller/src/types.ts
- packages/network-controller/tests/NetworkController.test.ts
- packages/network-controller/tests/provider-api-tests/helpers.ts
- packages/transaction-controller/src/TransactionController.test.ts
Adding chainId to the network configurations allows other code to treat the configurations as the same wether they are infura or a custom network.
As a result it simplifies the implementation for `findNetworkClientIdByChainId`.
We need `findNetworkClientIdByChainId` because the dapp API accepts chainId via `switchEthereumChain` and possibly caip-27 in the future. We need a way to map from chainId to networkClientId. If there are multiple networkClientIds for a given chainId we just naively return the first one. 
* Related to https://github.com/MetaMask/MetaMask-planning/issues/1006
- **ADDED**: `findNetworkClientIdByChainId`
- **ADDED**: chainId to built-in network configurations
> Chainid network configs

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
This PR aims to add an additional parameter on `TxController.wipeTransaction` function to support wiping only the transactions with supplied address. 
- **ADDED**: Adds optional `address` parameter to `TransactionController.wipeTransaction` function to support wiping the transactions only given address.
> Adds a support of wiping transactions with specific address on current chain

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
In order to align Tx controller public APIs between mobile & extension, this PR aims to add an options bag instead of inline arguments for `addTransaction` function. 
- **BREAKING**: Adds option bag to `addTransaction` public API method instead of inline arguments.
> Add options bag to `addTransaction` public API method

- packages/network-controller/src/NetworkController.ts
We need this type in extension & mobile.
* Related to https://github.com/MetaMask/MetaMask-planning/issues/1006
- **ADDED**: Added an export for NetworkClientId in NetworkController
> Added an export for NetworkClientId in NetworkController

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/utils.test.ts
- packages/transaction-controller/src/utils.ts
This PR aims to add  `initApprovals` function to support re-create approval requests based on unapprovedTx when the client restarts. This is an existent function in the extension and it's coming to the core as part of the effort to unify the `TransactionController` in the core and in the extension.
Changes:
- Addtional parameter in `processApproval` and `requestApproval` to determine if when creates an approval request it should be shown (`shouldShowRequest`).
- Created an utility function `transactionMatchesNetwork` to facilitate the validation of whether a given transaction matches the specified network or chain ID.
resolves: https://github.com/MetaMask/MetaMask-planning/issues/959
- **ADDED**: Adds `initApprovals` function to support re-create approval requests based on unapprovedTx …
> Adds support re-create approval requests based on unapprovedTx when client restarts

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
This PR aims to add `requireApproval` option to `addTransaction` method options in order to either force or skip creating approval for transactions.
As seen in the PR `requireApproval` default value will be `true` to keep the same behavior as before, and set explicitly to `false` in order to skip approval. 
- **ADDED**: Adds `requireApproval` option to `addTransaction` method options.
> Add `requireApproval` option to `addTransaction` method option bag

- packages/preferences-controller/src/PreferencesController.test.ts
- packages/preferences-controller/src/PreferencesController.ts
Adding `securityAlertsEnabled` to preference controller, this is required for enabling blockaid on mobile.
> Adding preference for security alerts

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds a `addNewKeyring` method to `KeyringController`, which can be used to add a keyring for a given type. 
This method internally calls `EthKeyringController.addNewKeyring`.
This is needed to migrate the last interactions between the extension and EthKeyringController.
* Related to https://github.com/MetaMask/core/issues/1595
- **ADDED**: `addNewKeyring` method to add a new keyring for a given type
> Add `addNewKeyring` method

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
This PR aims to pull couple of public methods into private since they are not used by clients. 
- **BREAKING**: Make `prepareUnsignedEthTx` and `getCommonConfiguration` methods to private.
> Minimise public API of Tx controller

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds the `addNewAccountForKeyring` method to `KeyringController`, that can be used to add a new account for a specific keyring, which might not be the primary simple keyrings.
To align it with the `addNewAccount` method that works for primaryKeyring, also `addNewAccountForKeyring` expects an optional `accountCount` parameter to make the function idempotent.
This method is needed to migrate some controllers from `@metamask/eth-keyring-controller` to `@metamask/keyring-controller`.
* Related to https://github.com/MetaMask/core/issues/1595
- **ADDED**: Added `addNewAccountForKeyring` method
> Add `addNewAccountForKeyring` method

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.test.ts
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.ts
- packages/transaction-controller/src/IncomingTransactionHelper.test.ts
- packages/transaction-controller/src/IncomingTransactionHelper.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/constants.ts
- packages/transaction-controller/src/etherscan.test.ts
- packages/transaction-controller/src/etherscan.ts
- packages/transaction-controller/src/types.ts
Currently the `TransactionController` retrieves incoming transactions when explicitly requested via the `fetchAll` method meaning the cadence of polling is dictated by the client.
This PR removes the `fetchAll` method and instead uses the `blockTracker` instance provided to the controller to automatically poll for incoming transactions whenever the current network has a new block.
This polling can be started and stopped using the `startIncomingTransactionPolling` and `stopIncomingTransactionPolling` methods respectively. Or an update can be required immediately via the `updateIncomingTransactions` method.
Additional optional arguments have also been added to the constructor to configure the incoming transaction support.
Closes [#965](https://github.com/MetaMask/MetaMask-planning/issues/965 …
> Use block tracker to poll incoming transactions

- packages/assets-controllers/CHANGELOG.md
The changelog for `@metamask/assets-controllers@v6` included an incorrect entry, a breaking change that didn't actually exist. The referenced change only affected a test file within the `assets-controllers` package, and the real change in the `network-controller` package wasn't released until the v49 release.
Release created here: #1231
The changelog update was accidentally omitted, but added here: #1232
The change mistakenly referenced is #1191
N/A
> Fix changelog for `@metamask/assets-controllers@v6`

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
This PR aims to persist `txReceipt` on `txMeta` after checking blockchain for confirmed transaction.
- **ADDED**: Persist `txReceipt` on `txMeta` for confirmed txs
> Persist txReceipt on txMeta for confirmed txs

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
The extension `TransactionController` persists in a `baseFeePerGas` value for each confirmed transaction. Including this property into the transaction state in the core to support the unification initiative between the core and extension.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1072
- **ADDED**:  add `baseFeePerGas` to the transaction state and persists the value for each confirmed transaction
> Add baseFeePerGas to transaction state

- docs/contributing.md
When using a preview version, we don't want to replace the production version across the dependency tree; we only really want to target its direct usage by the project in question. This commit updates the instructions for using preview builds to ensure that this happens by asking the developer to include a specific version on the left-hand side of the resolution entry when updating `package.json`.
Relates to #1075.
(No consumer-facing changes)
> Recommend focused resolutions for preview builds

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
This PR aims to add `dappSuggestedGasFees` if transaction creation origin is not MetaMask.
- **ADDED**: Add `dappSuggestedGasFees` to transaction meta
> Add `dappSuggestedGasFees` to transaction

- packages/transaction-controller/src/TransactionController.ts
Temporary patch branch (`refactor/transaction-controller-patch-mobile`)update for mobile
> Add options bag to `addTransaction` public API method (#1576)

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
This PR aims to add `submittedTime` to transactionMeta while tx submitted to network.
- **ADDED**: Add `submittedTime` to transaction meta
> Add `submittedTime` to transaction meta

- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
Rename the `rawTransaction` property to `rawTx` in the persisted transaction metadata as part of the unification initiative between the core and extension. 
The following task will take place to handle the migration and adoption of the patch/release.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1080
- **BREAKING**:  rename the `rawTransaction` property to `rawTx` in the persisted `TransactionMeta`.
> Rename rawTransaction to rawTx in the persisted transaction metadata

- README.md
- packages/selected-network-controller/CHANGELOG.md
- packages/selected-network-controller/LICENSE
- packages/selected-network-controller/README.md
- packages/selected-network-controller/jest.config.js
- packages/selected-network-controller/package.json
- packages/selected-network-controller/src/SelectedNetworkController.ts
- packages/selected-network-controller/src/SelectedNetworkMiddleware.ts
- packages/selected-network-controller/src/index.ts
- packages/selected-network-controller/tests/SelectedNetworkController.test.ts
- packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts
- packages/selected-network-controller/tests/utils.ts
- packages/selected-network-controller/tsconfig.build.json
- packages/selected-network-controller/tsconfig.json
- packages/selected-network-controller/typedoc.json
- tsconfig.build.json
- tsconfig.json
- yarn.lock
This is a PR which moves the [proposed Selected Network Controller](https://github.com/MetaMask/metamask-extension/pull/20456) out of extension. 
It also adds tests (coverage @ 100%)
fixes https://github.com/MetaMask/MetaMask-planning/issues/1006
- **ADDED**: starting implementation
> Added SelectedNetworkController

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds actions to the `KeyringController` messenger to: 
- `signMessage`, `signPersonalMessage`, `signTypedMessage`, used by `SignatureController`
- `decryptMessage`, `getEncryptionPublicKey`, used by `EncryptionPublicKeyController` and `DecryptMessageController` in the extension.
* Related to https://github.com/MetaMask/metamask-extension/issues/20510
* See https://github.com/MetaMask/core/pull/1593
- **ADDED**: `KeyringController` messenger actions:
- `KeyringController:signMessage`
- `KeyringController:signPersonalMessage` 
- `KeyringController:signTypedMessage`
- `KeyringController:decryptMessage`
- `KeyringController:getEncryptionPublicKey`
> Add `KeyringController` message sign and encryption actions

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/IncomingTransactionHelper.test.ts
- packages/transaction-controller/src/IncomingTransactionHelper.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/constants.ts
- packages/transaction-controller/src/etherscan.test.ts
- packages/transaction-controller/src/etherscan.ts
Update the incoming transaction support in the `TransactionController` to include the API key (if specified) in the Etherscan request only if the domain is the standard `etherscan.io`.
Currently only the mobile client provides an API key however this is specifically for the Etherscan domain rather than the same software on alternate hosts such as `lineascan.build`.
This PR also includes incoming transaction fixes already patched in the mobile client including:
- Querying the entire transaction history if no last fetched block numbers are found, unless the new `queryEntireHistory` option is set to `false`.
- Using the correct `sort` parameter rather than `order` in Etherscan requests.
- Sorting the transactions when trimming.
- Replacing the `lastFetchedBlockNumbers` otpion with a callback …
> Use API key only with Etherscan domain

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
This PR aims to persist `originalGasEstimate` in `addTransaction` and `speedUpTransaction`. 
- **ADDED**: Persist `originalGasEstimate` in transaction metadata.
> Add originalGasEstimate to transaction metadata

- packages/transaction-controller/src/EtherscanRemoteTransactionSource.test.ts
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.ts
- packages/transaction-controller/src/IncomingTransactionHelper.test.ts
- packages/transaction-controller/src/IncomingTransactionHelper.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
Rename the `transactionHash` property to `hash` in the persisted transaction metadata as part of the unification initiative between the core and extension. 
The following task will take place to handle the migration and adoption of the patch/release.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1077
- **BREAKING**:  rename the `transactionHash` property to `hash` in the persisted `TransactionMeta`.
> Rename transactionHash property to hash in the persisted transaction metadata

- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
Cherry-picking https://github.com/MetaMask/core/pull/1636 into branch `refactor/transaction-controller-patch-mobile` used to create transaction controller patches.
> Adding code changes to include blockaid response to transaction metadata to transaction controller patch branch

- packages/assets-controllers/src/AssetsContractController.test.ts
- packages/assets-controllers/src/AssetsContractController.ts
- packages/assets-controllers/src/AssetsContractControllerWithNetworkClientId.test.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/TokenBalancesController.test.ts
- packages/assets-controllers/src/TokensController.ts
- packages/network-controller/src/NetworkController.ts
`AssetsContractController` currently relies on the proxied provider and `onNetworkStateChange` listener to ensure it is performing checks against the correct network. As part of multichain efforts, we want to decouple this controller from the notion of a single active network. We do this by adding an optional `networkClientId` argument to each of the external facing methods. This arg is used to resolve to a `NetworkClient` from the `NetworkController` when set. 
* Fixes [mmp-1021](https://github.com/MetaMask/MetaMask-planning/issues/1021)
- **ADDED**: `NetworkController` exposes `getNetworkClientById()` in a `NetworkController:getNetworkClientById` action
- **ADDED**: `AssetsContractController` constructor options requires `getNetworkClientById`
- **CHANGED**: …
> Use networkClientId in AssetsContractController

- packages/signature-controller/package.json
- packages/signature-controller/src/SignatureController.test.ts
- packages/signature-controller/src/SignatureController.ts
- packages/signature-controller/tsconfig.build.json
- packages/signature-controller/tsconfig.json
- yarn.lock
The `SignatureController` accepts an entire `KeyringController` instance as a constructor option, but would be better to use messenger actions instead, since this controller is a BaseControllerV2.
* Related to https://github.com/MetaMask/metamask-extension/issues/20510
- **BREAKING**: Remove `keyringController` constructor option: messenger actions are now being used
> Use messenger actions instead of `KeyringController` as constructor param

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
- packages/transaction-controller/src/utils.ts
This PR aims to add `sendFlowHistory` property to the transaction metadata. 
`updateTransactionSendFlowHistory` also added in this PR which appends given `sendFlowHistory` with current state. 
Closes https://github.com/MetaMask/MetaMask-planning/issues/1096
- **BREAKING**: `disableSendFlowHistory` option added to the constructor.
- This determines whether generate sendFlowHistory or not. 
- This option should be explicitly set to `true` in mobile. (This is a BC for mobile)
- Defaults to `false`
- **ADDED**:  Add `sendFlowHistory` property to transaction meta.
- **ADDED**:  Add `updateTransactionSendFlowHistory` function to the public API of the controller.
> Add `sendFlowHistory` to transactionMeta and `updateTransactionSendFlowHistory` function to public API

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/package.json
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/history-utils.ts
- packages/transaction-controller/src/history.ts
- packages/transaction-controller/src/types.ts
- yarn.lock
This PR aims to add `history` property to the transaction metadata. 
There are few points that history is extended or added.
- While using public `addTransaction` function it adds initial history.
- While using public `confirmExternalTransaction` function. First it checks if the history property is in place, if not it initiates as it in the `addTransaction`. (Please note that there were no checks/tests in extension for this case)
- Since history is useful for debugging, all the `updateTransaction` calls will add operation entry array of what is changed.
Transaction history adds considerable space in the persisted state (and this is unwanted in mobile), `TransactionController` now has new option called `disableHistory` boolean flag to prevent history generation.
- **BREAKING**: …
> Add `history` to `transactionMeta`

- packages/transaction-controller/src/EtherscanRemoteTransactionSource.test.ts
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.ts
- packages/transaction-controller/src/IncomingTransactionHelper.test.ts
- packages/transaction-controller/src/IncomingTransactionHelper.ts
- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/external-transactions.test.ts
- packages/transaction-controller/src/external-transactions.ts
- packages/transaction-controller/src/types.ts
- packages/transaction-controller/src/utils.test.ts
- packages/transaction-controller/src/utils.ts
Rename the `transaction` object to `txParams` in the persisted transaction metadata as part of the unification initiative between the core and extension. 
The following task will take place to handle the migration and adoption of the patch/release in the mobile client.
- **BREAKING**:  rename the `transaction` object to `txParams` in the persisted `TransactionMeta`.
> Rename transaction object to txParams in the persisted transaction metadata

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/types.ts
This PR aims to add `r`, `s` and `v` properties to `TransactionMeta` for context it has been included because the extension `TransactionController` populates `r`, `s`, and `v` values on the state after each signed transaction. 
- ADDED: `r`, `s` and `v`  properties to `TransactionMeta`.
- These properties are populated after a transaction is signed.
> Add r, s, v to TransactionMeta

- packages/transaction-controller/jest.config.js
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.test.ts
- packages/transaction-controller/src/EtherscanRemoteTransactionSource.ts
- packages/transaction-controller/src/IncomingTransactionHelper.test.ts
- packages/transaction-controller/src/IncomingTransactionHelper.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/etherscan.test.ts
- packages/transaction-controller/src/etherscan.ts
- packages/transaction-controller/src/logger.ts
- packages/transaction-controller/src/types.ts
Addresses legacy issues from the mobile client concerning incoming transactions, specifically:
- Removes support for Etherscan API keys as no client is using them in production.
- Prevents rate limit errors in Etherscan requests by alternating between normal and token requests on each poll.
- Updates the last fetched block cache to maintain separate entries for `normal` and `token` transactions.
- Moves Etherscan error parsing to `EtherscanRemoteTransactionSource` for better encapsulation.
- Adds optional logging to the incoming transactions logic for easier debug.
- **BREAKING**: Remove `apiKey` property from `RemoteTransactionSourceRequest` type.
- **BREAKING**: Remove unused `FetchAllOptions` type from `TransactionController`.
- **BREAKING**: Remove `incomingTransactions.apiKey` …
> Remove incoming transaction API key support

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
This PR adds actions to the KeyringController messenger to:
getKeyringsByType, getKeyringForAccount, getAccount actions to be used by the AccountsController in the extension.
- **ADDED**: Keyring controller messenger actions:
- KeyringController:getKeyringsByType
- KeyringController:getKeyringForAccount
- KeyringController:getAccounts
> Add getKeyringsByType getKeyringForAccount getAccounts actions

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
- packages/keyring-controller/tests/mocks/mockShallowGetAccountsKeyring.ts
Currently, the `addNewAccountForKeyring` method calls `keyring.getAccounts()` (where `keyring` is the arg passed to the func) to store a list of accounts and later diff it with a new one to determine the account added in the operation, and then return it.
This strategy to find the new account does not work with `CustodyKeyring`:
`CustodyKeyring.getAccounts()` returns a *reference* to its `this.accounts` state property, which is stored in `oldAccounts`.  The reference is created [here](https://github.com/consensys-vertical-apps/metamask-institutional/blob/15610d6d184e11a47cb8b2bbb0d93b9c12763172/packages/custodyKeyring/src/CustodyKeyring.ts#L172).
As this is a reference, when we call `CustodyKeyring.getAccounts()` the second time and compare it with `oldAccounts`, what we are actually …
> Fix `addNewAccountForKeyring` for `CustodyKeyring`

- packages/name-controller/src/NameController.test.ts
- packages/name-controller/src/NameController.ts
Currently all proposed names are persisted in state until overridden with a new value. This means when a provider stops using a source ID, such as with the snaps provider, any associated proposed names persist indefinitely.
This change makes `updateProposeNames` remove any proposed names for any source IDs that are no longer used by any of the providers for the specified `type` such as `NameType.ETHEREUM_ADDRESS`.
Also updates the `SetNameRequest` type and associated validation to support removing a saved name using a `null` value.
- **CHANGED**: Dormant proposed names are automatically removed when calling `updateProposedNames`.
- **CHANGED**: The `setName` method accepts a `null` value for the `name` property to enable removing saved names.
> Remove dormant proposed names

- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
Currently, the extension is directly subscribing to the `QRKeyring` store, to determine whether to open the modal for syncing and signing. 
This raises concerns when the instance of the QRKeyring will be held by `KeyringController` instead of the client because it will be tricky to handle `subscribe` and `unsubscribe` in the keyring's lifecycle, risking to have multiple subscriptions to the same QRKeyring instance or even no subscriptions at all!
This PR gives this responsibility to `KeyringController`.
`KeyringController` will subscribe to the QRKeyring instance in these methods:
- `submitPassword` - because here we unlock the vault and potentially find a QRKeyring (even in case of re-construction from backup)
- `submitEncryptionKey` - same as above
- `getOrAddQRKeyring` - because here …
> Subscribe to `QRKeyring` store and publish updates

- packages/accounts-controller/package.json
- packages/address-book-controller/package.json
- packages/announcement-controller/package.json
- packages/approval-controller/package.json
- packages/assets-controllers/package.json
- packages/base-controller/package.json
- packages/composable-controller/package.json
- packages/controller-utils/package.json
- packages/ens-controller/package.json
- packages/gas-fee-controller/package.json
- packages/keyring-controller/package.json
- packages/logging-controller/package.json
- packages/message-manager/package.json
- packages/name-controller/package.json
- packages/network-controller/package.json
- packages/notification-controller/package.json
- packages/permission-controller/package.json
- packages/phishing-controller/package.json
- packages/preferences-controller/package.json
- packages/rate-limit-controller/package.json
- packages/selected-network-controller/package.json
- packages/signature-controller/package.json
- packages/transaction-controller/package.json
- yarn.lock
The `typedoc` package has been updated to match the version used by the module template. This was done in preparation for updating the TypeScript version used by the core monorepo as well. The current version of `typedoc` we use doesn't support TypeScript v4.8.
The `typedoc-plugin-missing-exports` package required an update to maintain compatibility with `typedoc`.
In both cases, none of the breaking changes affect our usage of the package. Mostly they include improvements to the generated documentation, and dropping support for older Node.js and TypeScript versions.
`typedoc` changelog: https://github.com/TypeStrong/typedoc/releases/tag/v0.23.0
`typedoc-plugin-missing-exports` changelog: https://github.com/Gerrit0/typedoc-plugin-missing-exports/blob/main/CHANGELOG.md#0230-2022-06-26
None …
> chore: Update `typedoc` and related packages

- packages/phishing-controller/src/PhishingController.test.ts
- packages/phishing-controller/src/PhishingController.ts
This migrates the `PhishingController` to `BaseControllerV2`
- Add `maybeUpdateState` and `testOrigin` actions
- **BREAKING:** `PhishingController` now inherits from BaseControllerV2
- **BREAKING:** `PhishingController`now expects a `messenger` option (and corresponding type `PhishingControllerMessenger` is now available)
-  **BREAKING:**  The constructor takes a single argument, an options bag, instead of three arguments
- **BREAKING:**  The `disabled` configuration is no longer supported
> Migrate `PhishingController` to BaseControllerV2

- packages/assets-controllers/package.json
- packages/assets-controllers/src/TokenListController.ts
- packages/assets-controllers/src/TokensController.ts
- packages/assets-controllers/src/token-service.test.ts
- packages/controller-utils/package.json
- yarn.lock
The `AbortController` polyfill has not been required since updating to a minimum Node.js version of v16 in #1262. This API has been [built into Node.js since v15.4.0](https://nodejs.org/docs/latest-v16.x/api/globals.html#class-abortcontroller), and is included in all versions of v16. It is also supported by [all browsers that our extension supports](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#browser_compatibility), and has been [supported by React Native since v0.60.0](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0600).
This helps unblock the TypeScript update to v4.8.4. The update resulted in some type errors from this polyfill package.
None
- **BREAKING:** Remove AbortController polyfill
- This package now assumes that the …
> chore: Remove AbortController polyfill

- packages/transaction-controller/src/TransactionController.test.ts
- packages/transaction-controller/src/TransactionController.ts
- packages/transaction-controller/src/utils.test.ts
- packages/transaction-controller/src/utils.ts
This PR aims to include a validation existent in the Extension in the `TransactionController` core. The validation gets the current network and current account to check if they support EIP-1559 transactions. If the transaction is an EIP-1559 transaction, meaning it contains `maxFeePerGas` and `maxPriorityFeePerGas` values, but the network or account does not support EIP-1559, then an error is thrown.
In order to support it two callbacks are passed to the controller constructor  `getCurrentAccountEIP1559Compatibility`  and `getCurrentNetworkEIP1559Compatibility`.
- **BREAKING**: Add required `getCurrentAccountEIP1559Compatibility`  and `getCurrentNetworkEIP1559Compatibility` callback arguments to constructor.
> Add EIP-1559 compatibility validation for transaction creation

- package.json
- packages/accounts-controller/package.json
- packages/address-book-controller/package.json
- packages/announcement-controller/package.json
- packages/approval-controller/package.json
- packages/assets-controllers/package.json
- packages/base-controller/package.json
- packages/composable-controller/package.json
- packages/controller-utils/package.json
- packages/ens-controller/package.json
- packages/gas-fee-controller/package.json
- packages/keyring-controller/package.json
- packages/logging-controller/package.json
- packages/message-manager/package.json
- packages/name-controller/package.json
- packages/name-controller/src/providers/etherscan.ts
- packages/name-controller/src/util.ts
- packages/name-controller/src/utils.test.ts
- packages/network-controller/package.json
- packages/notification-controller/package.json
- packages/permission-controller/package.json
- packages/phishing-controller/package.json
- packages/polling-controller/package.json
- packages/preferences-controller/package.json
- packages/rate-limit-controller/package.json
- packages/selected-network-controller/package.json
- packages/signature-controller/package.json
- packages/transaction-controller/package.json
- yarn.lock
The `typescript` package has been updated to v4.8.4 to align with the module template. This was done to simplify the process of migrating libraries into the monorepo.
None
N/A
> Update typescript v4.8

- packages/keyring-controller/src/KeyringController.ts
The property `keyringTypes` has been removed from `KeyringController`'s store, but as `EthKeyringController` still has this property in its `memStore`, and as in the `KeyringController.#fullUpdate` we destructure the entire object, we also carry over `keyringTypes` - a property we don't have metadata for.
This PR changes the `#fullUpdate` internal method to only take these properties from `EthKeyringController` stores:
- `vault`
- `keyrings`
- `isUnlocked`
- `encryptionKey`
- `encryptionSalt`
- **FIXED**: Removed `keyringTypes` from updated properties from `EthKeyringController` stores
> `KeyringController`: select only supported properties in `fullUpdate`

- packages/accounts-controller/src/AccountsController.ts
Removes `selectedAccount` from the metadata of AccountsControllerMetadata because it is a nested value in `internalAccounts`
- **Removed**: 
`selectedAccount` from `AccountsControllerMetadata`
> Remove selectedAccount from AccountsControllerMetadata

- packages/message-manager/src/MessageManager.ts
- packages/message-manager/src/PersonalMessageManager.ts
- packages/message-manager/src/TypedMessageManager.ts
This PR has no functional change, it removes `delete` operator and uses spread in order to mitigate a potential issue while making preparation before signing operations.
Blocker for https://github.com/MetaMask/MetaMask-planning/issues/1321
- **Fixes**: Removes `delete` operator and uses spread in order to mitigate an issue on removing a property from frozen `messageParams` object
> Use spread operator instead of `delete` on frozen `messageParams`

- packages/name-controller/src/NameController.test.ts
- packages/name-controller/src/NameController.ts
- packages/name-controller/src/providers/ens.test.ts
- packages/name-controller/src/providers/ens.ts
- packages/name-controller/src/providers/etherscan.test.ts
- packages/name-controller/src/providers/etherscan.ts
- packages/name-controller/src/providers/lens.test.ts
- packages/name-controller/src/providers/token.test.ts
- packages/name-controller/src/providers/token.ts
- packages/name-controller/src/types.ts
Normalize addresses and chain IDs in the `NameController` state by storing them in lowercase, to avoid persisting multiple names for the same address. The UI components in the extension won't display the lowercase address but instead will render the checksummed address.
Also replace the `getChainId` callback with the `variation` option in the `SetNameRequest` and `UpdateProposedNamesRequest`. This decouples the controller from the selected network and supports requests on any chain.
- **BREAKING**: Save addresses and chain IDs as lowercase in state.
- **BREAKING**: Remove `getChainId` constructor callback.
- **BREAKING**: Require a `variation` property when calling `setName` or `updateProposedNames` with the address type.
> Normalize addresses in name controller

- constraints.pro
- package.json
- packages/accounts-controller/package.json
- packages/address-book-controller/package.json
- packages/announcement-controller/package.json
- packages/approval-controller/package.json
- packages/assets-controllers/package.json
- packages/base-controller/package.json
- packages/composable-controller/package.json
- packages/controller-utils/package.json
- packages/ens-controller/package.json
- packages/gas-fee-controller/package.json
- packages/keyring-controller/package.json
- packages/logging-controller/package.json
- packages/message-manager/package.json
- packages/name-controller/package.json
- packages/network-controller/package.json
- packages/notification-controller/package.json
- packages/permission-controller/package.json
- packages/phishing-controller/package.json
- packages/polling-controller/package.json
- packages/preferences-controller/package.json
- packages/rate-limit-controller/package.json
- packages/selected-network-controller/package.json
- packages/signature-controller/package.json
- packages/transaction-controller/package.json
Clearing jest cache can be necessary for debugging, especially when dealing with dependency version changes. Adding this functionality as a build script will make it more visible to future contributors as an available option for troubleshooting. 
- A new `test:clean` build script that runs `jest --clearCache` in every submodule of the monorepo, and then runs the existing `test` script. 
- Originally attempted to have each submodule run `jest --clearCache && jest`, but this causes issues with failed tests due to concurrent read/writes to the jest cache directory. 
- A `constraint.pro` entry that will enforce the addition of a `test:clean` script in future submodules. 
None
> Add `test:clean` build script that clears jest cache before running tests

- packages/polling-controller/src/PollingController.test.ts
- packages/polling-controller/src/PollingController.ts
- packages/polling-controller/src/index.ts
`start/stop` were a good start but are proving difficult when trying to not break existing apis with v1 controllers that use start/stop for their own polling. the interface is too different to work nicely with our merged mixin class.
> Changed Pollingcontroller method names

- package.json
- packages/name-controller/CHANGELOG.md
- packages/name-controller/package.json
Release new version of the `NameController` to unblock extension PRs.
No package dependencies on any other controllers (except `BaseController`).
- **BREAKING**: Normalize addresses and chain IDs ([#1732](https://github.com/MetaMask/core/pull/1732))
- Save addresses and chain IDs as lowercase in state
- Remove `getChainId` constructor callback
- Require a `variation` property when calling `setName` or `updateProposedNames` with the `ethereumAddress` type
> Release 80.0.0

- packages/assets-controllers/src/AssetsContractController.ts
- packages/assets-controllers/src/NftController.test.ts
- packages/assets-controllers/src/NftController.ts
- packages/assets-controllers/src/NftDetectionController.test.ts
- packages/assets-controllers/src/NftDetectionController.ts
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1022
- **BREAKING:** `NFTController` now expects `getNetworkClientById` in constructor options
- **BREAKING:** `NftController. addNft()` function signature has changed:
- Previously 
```
address: string,
tokenId: string,
nftMetadata?: NftMetadata,
accountParams?: {
userAddress: string;
chainId: Hex;
},
source = Source.Custom,
```
now:
```
tokenAddress: string,
tokenId: string,
{
nftMetadata?: NftMetadata;
chainId?: Hex; // extracts from AccountParams
userAddress?: string // extracted from AccountParams
source?: Source;
networkClientId?: NetworkClientId; // new
},
```
- CHANGED: `NftController.addNftVerifyOwnership`: now accepts optional `networkClientId` which is used to fetch NFT metadata and determine by which chainId the added …
> Parameterize `NftController.addNft` by `networkClientId`

- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/gas-fee-controller/src/GasFeeController.ts
- packages/gas-fee-controller/tsconfig.build.json
- packages/gas-fee-controller/tsconfig.json
- packages/network-controller/src/NetworkController.ts
- yarn.lock
Integrates recently introduced  [`PollingController` mixin](https://github.com/MetaMask/core/pull/1736)  with `GasFeeController`. Leaves old polling pattern in pace for now so as to not force a ton of breaking changes for mobile, but with intention to activate new pattern in both clients ASAP.
Addresses: https://github.com/MetaMask/MetaMask-planning/issues/1314
> Integrate PollingController mixin with GasFeeController

- packages/keyring-controller/jest.config.js
- packages/keyring-controller/src/KeyringController.test.ts
- packages/keyring-controller/src/KeyringController.ts
As we now emit the `KeyringController:accountRemoved` event, used by `PreferencesController` to remove identities each time it is emitted, we don't need to also call `this.removeIdentity` on KeyringController - or the account will be already absent when the event will reach `PreferencesController`.
As each controller should be responsible for its own state, the correct behavior is to let `PreferencesController` handle account removal events.
Unrelated to this fix, I also noticed that jest had a lower coverage thresholds - I set them to 100 since that's `KeyringController` current coverage
- **FIXED**:  Removed call to `PreferencesController.removeIdentity` as PreferencesController already handles account removal side effects through messenger events.
> fix: remove call to `removeIdentity`

- packages/assets-controllers/src/TokensController.test.ts
- packages/assets-controllers/src/TokensController.ts
Fixes a subtle bug: when multiple `wallet_watchAsset` calls of ERC20 tokens are batched, only the last of the tokens added was getting added because the calls were not properly single threaded, since the mutex was acquired after reading state in the `addToken` call.
- Fixes bug where batched addToken calls overwrite each other because mutex is acquired after reading state
> Fix issue where mutex is acquired after state is read in `addToken` resulting in overwritten state with batched addToken/watchAsset calls

- packages/selected-network-controller/src/SelectedNetworkController.ts
- packages/selected-network-controller/tests/SelectedNetworkController.test.ts
Currently, the SelectedNetworkController does not set a value for the default `metamask` domain on initial `NetworkController:stateChange` event because it does not count `selectedNetworkId` as actually changed in the patch yet. This manifests itself in extension with the SelectedNetworkMiddleware setting undefined for the `req.networkClientId` attribute. ~~This PR adds one more check to the event listener to ensure that the first `NetworkController:stateChange` event is used to populate the networkClientId for the default `metamask` domain.~~ See resolution in comments
* Fixes https://github.com/MetaMask/MetaMask-planning/issues/1370
- **FIXED**: `setNetworkClientIdForDomain()` will now ignore the passed in domain value and set the networkClientId for the `metamask` domain instead when …
> Fix SelectedNetworkController default metamask networkClientId

- merged-packages/eth-json-rpc-provider/yarn.lock
- The contents of `merged-packages/` shouldn't be altered, as it's a temporary directory used for migrating packages into the monorepo. 
- Any dependency updates for the migration target package need to be handled manually. The migration process involves aligning dependency versions with the monorepo (which may not use the latest version), removing dependencies that are defined in the monorepo root, and removing the `yarn.lock` file from the migration target subpackage.
- Blocks https://github.com/MetaMask/core/pull/1764
- See https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302 for context on the role of `merged-packages/`.
> Revert "Bump postcss from 8.4.20 to 8.4.31 in /merged-packages/eth-json-rpc-provider"

- packages/accounts-controller/package.json
- packages/accounts-controller/src/AccountsController.test.ts
- packages/accounts-controller/src/AccountsController.ts
- yarn.lock
This PR adds a new method, `getAccountByAddress` to the AccountsController and removes unused dependencies. 
- **ADDED**: getAccountByAddress
- **REMOVED**: Unused dependencies,  `nanoid` `eth-rpc-errors`
> Add getAccountByAddress to AccountsController

- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokenListController.ts
- packages/assets-controllers/src/token-service.test.ts
- packages/assets-controllers/src/token-service.ts
- packages/assets-controllers/tsconfig.build.json
- packages/assets-controllers/tsconfig.json
Resolves: https://github.com/MetaMask/MetaMask-planning/issues/1032
Integrates new `PollingController` abstraction into the `TokenListController`, implements the `executePoll` method and parameterizes the `fetchTokenList` method by `networkClientId` such that tokenLists can be fetched and cached for different networks via concurrent polling sessions. 
**A note:** As is our current controller refactor strategy, these changes are additive, backwards compatible and coexist alongside the existing globally selected network pattern. Once we fully adopt this polling pattern we should no longer access the root `tokenList` state but rather access from the cache with a chainId selector.
> Parameterize `TokenListController` by `NetworkClientId` + Integrate `PollingController`

- packages/assets-controllers/package.json
- yarn.lock
Fix issue where `@metamask/polling-controller` was mistakenly omitted from `@metamask/assets-controller` dependencies
> Fix issue where @metamask/polling-controller was mistakenly omitted from @metamask/assets-controller dependencies

- packages/network-controller/tests/NetworkController.test.ts
Removing unnecessary type casting.
- See https://github.com/MetaMask/core/pull/1653#discussion_r1357296408
N/A
> Remove `as` assertion casting `FakeBlockTracer` to `BlockTracker`

- packages/assets-controllers/src/TokenListController.test.ts
- packages/assets-controllers/src/TokenListController.ts
- packages/gas-fee-controller/src/GasFeeController.test.ts
- packages/gas-fee-controller/src/GasFeeController.ts
- packages/polling-controller/src/PollingController.test.ts
- packages/polling-controller/src/PollingController.ts
Fast-follow to https://github.com/MetaMask/core/pull/1776, just a few (breaking) naming cleanups
- **BREAKING:** `executePoll` renamed to `_executePoll`
-  **BREAKING:** `stopPollingByNetworkClientId` renamed to `stopPollingByPollingToken`
> Rename `executePoll` -> `_executePoll` + `stopPollingByNetworkClientId` -> `stopPollingByPollingToken`

- README.md
- Updating root README to include @metamask/eth-json-rpc-provider.
- Updating dependency graph to reflect changes made between releases v78.0.0 through v81.0.0.
- See https://github.com/MetaMask/core/pull/1738
- **CHANGED**: Updated README dependency graph.
> Update root README dependency graph with `eth-json-rpc-provider` and changes from recent releases

- packages/eth-json-rpc-provider/README.md
- Removes content in `eth-json-rpc-provider` README that is no longer relevant due to its migration as a non-root package in the monorepo.
- During future migrations, this step should be performed while the package is in `merged-packages/`.
- TODO: Restore links to GitHub Pages docs once the `publish-docs` workflows are set up in core.
- See https://github.com/MetaMask/core/issues/1845
- Closes https://github.com/MetaMask/core/issues/1846
- **CHANGED**: Removed outdated README contents.
> Remove outdated `eth-json-rpc-provider` README content

- packages/eth-json-rpc-provider/CHANGELOG.md
- packages/network-controller/CHANGELOG.md
Records CHANGELOG entries from `eth-json-rpc-provider` migration under "Unreleased" headers for reference during the next version release. 
- Closes #1849 
N/A
> Record CHANGELOG entries from `eth-json-rpc-provider` migration

- packages/accounts-controller/src/AccountsController.ts
Removes `@ts-ignore` directives in `AccountsController.ts`
- Types `currentState` as `Draft<AccountsControllerState>` to align with input argument type expected by `BaseController.update()`
- Resolves "Type instantiation is excessively deep" errors triggered by assigning a complex type `T` to `Draft<T>`, by casting `Draft<T>` to `T`.
- Marks one remaining error with `@ts-expect-error`. Narrowed down source of error as much as possible.
- See #1839
> Typing fixes for #1839 (Feat/update on keyring state change in accounts controller)

- README.md
- packages/accounts-controller/package.json
- packages/accounts-controller/src/AccountsController.test.ts
- packages/accounts-controller/src/AccountsController.ts
- packages/accounts-controller/src/index.ts
- packages/accounts-controller/src/utils.ts
- packages/keyring-controller/src/KeyringController.ts
- yarn.lock
This PR refactors how the `AccountsController` handles the subscription to keyring state changes and removes the `keyringApiEnabled` flag
- **REMOVED**: keyringApiEnabled flag
- **CHANGED**: `onSnapStateChange` and `onKeyringStateChange` handlers to be sync instead of async
- **ADDED**: `trezor`, `ledger`, `custody`, `lattice`, `snap`  to `KeyringTypes`
> Update the `onKeyringStateChange` and `onSnapStateChange` methods, and remove the `keyringApiEnabled` from the AccountsController
