packages/eth-json-rpc-provider/package.json
yarn.lock

When running `yarn install`, I'm getting this warning:
➤ YN0002: │ @metamask/eth-json-rpc-provider@workspace:packages/eth-json-rpc-provider doesn't provide typescript (pa8d7f), requested by ts-jest
➤ YN0002: │ @metamask/eth-json-rpc-provider@workspace:packages/eth-json-rpc-provider doesn't provide typescript (p270b9), requested by typedoc
This is happening because `typescript` needs to be added as a development dependency for `eth-json-rpc-provider`.
(No consumer-facing changes)

Add missing TS dep to eth-json-rpc-provider

---

package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/package.json
packages/permission-controller/package.json
packages/queued-request-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Reverts MetaMask/core#1897
The release failed because of an invalid prepack script.

Revert "Release 83.0.0"

---

constraints.pro

The `prepack` build script from incoming migration packages interfere with the release CI and need to be replaced with the `prepack` script in the root `package.json`. 
This `constraints.pro` rule enforces that redundant `prepack` scripts in non-root packages are removed. 
- See https://github.com/MetaMask/core/pull/1902
- See https://github.com/MetaMask/core/actions/runs/6629214754/job/18008299892?pr=1897
- Closes https://github.com/MetaMask/core/issues/1906
N/A

Adds `constraints.pro` rule that removes `prepack` build scripts

---

merged-packages/json-rpc-engine/package.json
packages/accounts-controller/package.json
packages/address-book-controller/package.json
packages/announcement-controller/package.json
packages/approval-controller/package.json
packages/assets-controllers/package.json
packages/base-controller/package.json
packages/composable-controller/package.json
packages/controller-utils/package.json
packages/ens-controller/package.json
packages/eth-json-rpc-provider/package.json
packages/gas-fee-controller/package.json
packages/keyring-controller/package.json
packages/logging-controller/package.json
packages/message-manager/package.json
packages/name-controller/package.json
packages/network-controller/package.json
packages/notification-controller/package.json
packages/permission-controller/package.json
packages/phishing-controller/package.json
packages/polling-controller/package.json
packages/preferences-controller/package.json
packages/queued-request-controller/package.json
packages/rate-limit-controller/package.json
packages/selected-network-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Bumps all `packages/` usage of `auto-changelog` from `3.4.0` to `3.4.2`

bump `@metamask/auto-changelog` to `^3.4.2`

---

packages/permission-log-controller/src/PermissionLog.ts
packages/permission-log-controller/src/permissions.ts

Typing fixes for the `PermissionLogController`:
- Removes `any`, adds null checks. 
- Derive request type from JsonRpcRequestStruct.TYPE instead of hardcoding `jsonrpc` version to "2.0".
- Narrow `req.params` type to `Json[]` where appropriate. 
@cryptodev-2s Feel free to cherry-pick, merge, or disregard!
- TypeScript compiles without errors.
- Failing same tests as parent PR: https://github.com/MetaMask/core/actions/runs/6632538517/job/18018504013?pr=1908
- See https://github.com/MetaMask/core/pull/1871
N/A

Typing fixes for `PermissionLogController`

---

packages/queued-request-controller/src/QueuedRequestMiddleware.ts

Unfortunately we missed a few methods from the list of methds which require confirmations. This pr addresses this.
https://github.com/MetaMask/metamask-extension/pull/21522#issuecomment-1782059264
- **ADDED**: Added methods that require confirmation

Update list of methods requiring confirmation

---

packages/assets-controllers/CHANGELOG.md

Currently, the v16 [changelog](https://github.com/MetaMask/core/blob/ba7d8327bddc6f652e787670280f1f6251ab6873/packages/assets-controllers/CHANGELOG.md#added) incorrectly missed information about [two commits](https://github.com/MetaMask/core/compare/@metamask/assets-controllers@15.0.0...@metamask/assets-controllers@16.0.0): [bc04f49](https://github.com/MetaMask/core/commit/bc04f496f494defc8496b4c9229ad59af541e086) and [deb9317](https://github.com/MetaMask/core/commit/deb9317bff171883a8b7f140aa6cf391d200bc27).
This PR introduces those lines retroactively into the changelog.

fix v16 changelog

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/types.ts

With the Transaction Controller under active development, it's important to ensure that its tests are valid. This PR improves typing in the tests by removing `any` usage and fixing `as` assertions, mainly by enforcing that `TransactionMeta` mock objects correctly conform to the type they're intended to test. 
Typing mock objects as `any` can be convenient for omitting required but non-essential properties, but it also keeps TypeScript from alerting us when objects with invalid shapes are being used for tests. If necessary, type assertions that don't use `any` e.g. `as TransactionMeta` are a much better compromise.
- Fixed test mock object typing:
- `TransactionMeta` with failed status should contain an error property.
- `from`, `to` should be located in the `txParams` property (or the …

Typing fixes for `TransactionController.test.ts`

---

packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.ts

ATM the queued request middleware is not receiving the correct info back from the approval controller. Further, it really should not be using the data returned by the approval controller since we already have the required details.
- **FIXED**: issue where switching chain would ultimately fail due to the wrong networkClientId / type

use network confiurations always

---

packages/accounts-controller/package.json
yarn.lock

Bumps the dependencies snaps-utils and snaps-controller to 3.2.0
- **CHANGED**: Bumped @metamask/snaps-utils and @metamask/snaps-controllers to 3.2.0

Bump snaps-utils and snaps-controller to 3.2.0

---

packages/assets-controllers/src/CurrencyRateController.test.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/TokenBalancesController.test.ts
packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts
packages/assets-controllers/src/TokenListController.test.ts
packages/assets-controllers/tsconfig.json
packages/controller-utils/src/util.ts
packages/polling-controller/package.json
packages/polling-controller/src/PollingController.test.ts
packages/polling-controller/tsconfig.json
tests/helpers.ts
yarn.lock

This PR introduces an `advanceTime` utility function to @metamask/controller-utils for unifying our testing patterns when using fake timers with controllers that execute asynchronous code in setTimeout/setInterval loops (controllers that poll) and ensuring that chained promises and timers are comprehensively processed within tests.
This new function and pattern is added to the test suites for the following controllers:
- `PollingController`,
- `CurrencyRateController`
- `NFTDetectionController`,
- `TokenListController`
- `TokenDetectionController`
Changelog Entry:
- Fixes issue where interval was not getting set on the TokenDetectionController for the PollingController mixin.

Advance time utility function

---

packages/json-rpc-engine/README.md

Adds an "Installation" and "Contributing" section to the `@metamask/json-rpc-engine` README, as it has been migrated into the monorepo.
In future migrations, this step will be performed in "Phase B" (see https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740), while the package is being staged in the `merged-packages/` temporary directory.
- Partially implements https://github.com/MetaMask/core/issues/1981.
N/A

Update `@metamask/json-rpc-engine` README to reflect migration into monorepo subpackage

---

package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json

Release queued request controller with fixes for network nickname & addEthereumChain

Release 89.0.0

---

packages/eth-json-rpc-provider/CHANGELOG.md
packages/json-rpc-engine/CHANGELOG.md
packages/json-rpc-middleware-stream/CHANGELOG.md
packages/permission-controller/CHANGELOG.md
packages/queued-request-controller/CHANGELOG.md
packages/selected-network-controller/CHANGELOG.md

Records CHANGELOG entries from `@metamask/json-rpc-engine` and `@metamask/json-rpc-middleware-stream` migrations under "Unreleased" headers for reference during the next version release.
- ~Records changes made to downstream repos.~
- Partially implements https://github.com/MetaMask/core/issues/1981
- Partially implements https://github.com/MetaMask/core/issues/1982
N/A

Record CHANGELOG entries from `@metamask/json-rpc-{engine,middleware-stream}` migrations

---

tsconfig.build.json
tsconfig.json

- Fixes missing `json-rpc-middleware-stream` entries in root tsconfig files that causes build failure during release workflow.
- Will add note in migration process guide (https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740) about the importance of step C-2.
- See https://github.com/MetaMask/core/issues/1552

Add `json-rpc-middleware-stream` to root `tsconfig` files

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

Add function to uodate securityAlertResponse in a transaction.
Ref: 
https://github.com/MetaMask/core/pull/1985
https://github.com/MetaMask/metamask-mobile/pull/7680
NA
NA
NA

For creating patch: Add method for adding params to transaction meta

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts

This PR adds `estimateGasBuffered` public method to transaction controller in order to satisfy needs of `SwapsController` in extension: https://github.com/MetaMask/metamask-extension/blob/16592dd65d328a7fc72f479dbe9acce1ffd42d85/app/scripts/metamask-controller.js#L1527
Ticket will be soon created
- **Added**: Added `estimateGasBuffered` public method

Adds `estimateGasBuffered` public method

---

packages/transaction-controller/src/types.ts

This PR adds `accessList` to `txParams` type. 
Related to https://github.com/MetaMask/MetaMask-planning/issues/1621
- **Added**: Added `accessList` to `txParam` types

Add `accessList` to txParam types

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/gas-fee-controller/src/GasFeeController.ts
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/provider-api-tests/helpers.ts
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.ts
yarn.lock

Recent changes in `@metamask/utils` caused SafeEventEmitterProvider, the type of the provider that NetworkController exposes, to no longer align with the provider that `@metamask/eth-query` expects. We temporarily worked around this with the use of `// @ts-expect-error`, but this merely hid the problem. A fix was made in `@metamask/eth-query`, so this commit bumps that package and removes the associated `// @ts-expect-error` lines.
Fixes #1823.
Also see: https://github.com/MetaMask/eth-query/pull/21
(See updates to changelogs in this PR.)

Align NetworkController provider type w/ eth-query

---

packages/assets-controllers/jest.config.js
packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

- `watchNft`, `removeNft`, `removeAndIgnoreNft`, `removeNftContract`, `updateNftFavoriteStatus`, and `checkAndUpdateAllNftsOwnershipStatus` methods on `NftController` all now accept an optional options object argument containing `networkClientId` and `userAddress` to identify where in state to mutate.
- **BREAKING**: `addNft` no longer accepts a `chainId` property in its options argument since this value can be retrieved by the `networkClientId` property and is therefore redundant.
- **BREAKING**: The third and fourth arguments on NftController's `addNftVerifyOwnership` method, have been replaced with an options object containing optional properties `networkClientId`, `userAddress` and `source`. This method signature is more aligned with the options pattern for passing `networkClientId` …

Add optional `networkClientId` and `userAddress` args to remaining `NftController` public methods

---

packages/base-controller/src/BaseControllerV2.ts
packages/base-controller/src/ControllerMessenger.ts

Renames all single-letter type parameter names in `base-controller` to be more descriptive.
- Extracted from https://github.com/MetaMask/core/pull/1890
- **CHANGED**: Renamed all single-letter generic parameter names to be descriptive

[`base-controller`] Fix single-letter type param names

---

packages/controller-utils/src/util.test.ts
packages/gas-fee-controller/src/fetchBlockFeeHistory.test.ts
packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory.test.ts
packages/transaction-controller/src/utils/transaction-type.test.ts

Fixes `// @ts-expect-error Mock eth query does not fulfill type requirements` annotations throughout core repo.
- Builds upon
- https://github.com/MetaMask/eth-query/pull/21
- https://github.com/MetaMask/core/pull/2028
- Related https://github.com/MetaMask/core/issues/1823
- Closes https://github.com/MetaMask/core/issues/2036
N/A

Fix misaligned mock eth query types in controller tests

---

packages/base-controller/src/BaseControllerV2.ts
packages/base-controller/src/ControllerMessenger.ts
packages/base-controller/src/RestrictedControllerMessenger.ts

All uses of the `private` keyword have been replaced with a `#` prefix (except those in the deprecated `BaseController`). The use of `private` is discouraged in our repositories, as `#`-prefixed properties are truly private and are easier to work with.
Technically this could be considered a breaking change because there are ways to work around `private`, but I would consider this non- breaking because these properties were clearly intended to be private.
Tangentially related to #2047 (not strictly required, but when I was investigating that issue, I ended up doing this as well because our lint rules were forcing me to destructure `this` in order to access properties, which was very awkward for one line where I needed to upcast something)
None

refactor(base-controller): Replace `private` keyword

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/ens-controller/CHANGELOG.md
packages/ens-controller/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/polling-controller/CHANGELOG.md
packages/polling-controller/package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
yarn.lock

- Releases major version of `network-controller`, which enables usage of updated `Provider` type and `getEthQuery` messenger action.
- Releases major version of `transaction-controller`, which includes [a large number of significant changes](https://github.com/MetaMask/core/pull/2044/files#diff-d2a0ba2c61bc1c4862fd8cf52c56eeecf51037b90a3e9eb832b68ad9706195bc).
- Releases major version of `assets-controllers`, which includes [breaking changes in `NfTController`](https://github.com/MetaMask/core/pull/2044/files#diff-ee47d03d53776b8dd530799a8047f5e32e36e35765620aeb50b294adc3339fab).
- Releases patch versions of `{ens,gas-fee,polling,queued-request,selected-network}-controller`, which are downstream of `network-controller`.

Release 91.0.0

---

packages/signature-controller/package.json
yarn.lock

The signature controller has been updated to include `@metamask/keyring-controller` as a dependency and as a peer dependency. The keyring controller types are relied upon by the signature controller, and are referenced by the `.d.ts` files included in the signature controller package.
- **BREAKING**: Add `@metamask/keyring-controller` as a dependency and peer dependency
- This was relied upon by past versions, but this was not reflected in the package manifest until now

fix(signature-controller): Add missing dependency on keyring controller

---

packages/base-controller/src/RestrictedControllerMessenger.test.ts
packages/base-controller/src/RestrictedControllerMessenger.ts

The restricted controller messenger now allows using all internal events and actions. Previously internal events were treated the same as external events, they had to be explicitly allowed.
This is a non-breaking change; internal actions/events are still permitted to be list as "allowed", it's just no longer necessary.
Resolves #2047
- CHANGED: The restricted controller messenger now allows calling all internal events and actions
- Previously internal events and actions were only usable if they were listed as "allowed". They are still permitted to be listed as "allowed" now, but it is no longer necessary.

feat(base-controller): Allow using internal events/actions

---

packages/base-controller/jest.config.js
packages/base-controller/src/RestrictedControllerMessenger.test.ts
packages/base-controller/src/RestrictedControllerMessenger.ts

- Previously, error handling branches for `RestrictedControllerMessenger` methods were not being tested on the basis of compile-time checks: "Branches unreachable with valid types".
- However, given that these methods are being called by our JavaScript clients, we also need assurances on runtime error-handling behavior.
- This PR adds jest tests for the previously ignored error handling branches: coverage is brought up to 100%.
- `@ts-expect-error` is used to suppress the compile-time type errors to simulate a JavaScript environment. 
- Closes https://github.com/MetaMask/core/issues/2059
- See https://github.com/MetaMask/core/pull/2051#discussion_r1396339975

[`base-controller`] Add `RestrictedControllerMessenger` tests for runtime error handling

---

packages/permission-controller/src/rpc-methods/revokePermissions.test.ts
packages/permission-controller/src/rpc-methods/revokePermissions.ts

This changes the `revokePermissions` rpc method params to be by-position similar to `requestPermissions`

wallet revoke permissions

---

jest.config.packages.js

- Fixes main branch CI failure: https://github.com/MetaMask/core/actions/runs/6944013982/job/18901645361
- Increases jest `testTimeout` option from default of 5000 to 30000.
- Closes https://github.com/MetaMask/core/issues/2075
N/A

Fix main branch CI failure by increasing jest `testTimeout` option

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/swaps.ts
packages/transaction-controller/src/utils/utils.test.ts
packages/transaction-controller/src/utils/utils.ts

Add multiple fixes to support usage by the extension, including:
- Add `getTransactions` method to search transactions using the specified criteria and options.
- Re-add `initApprovals` method to allow client to finish initialisation before creating approvals.
- Remove unnecessary gas property update during initialisation since transactions are not added to the state until gas properties are updated.
- Normalise the gas fee values provided to `speedUpTransaction` and `stopTransaction` to support the extension arguments.
- Update the transaction after the `afterSign` hook to persist any updated properties.
- Report success to the result callback after publish is skipped to unblock the UI during the MMI flows.
- Set the `value` parameter to `0x0` if not specified.
- Limit properties updated …

Add method to get transactions

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json

Minor release of `@metamask/transaction-controller` only to support the migration in the extension.
No breaking changes, and have verified no changes are required from other unreleased packages.

Release 94.0.0

---

packages/controller-utils/package.json

In #1815, `@metamask/eth-query` was moved from deps to devDeps under the assumption that this would be safe because the dependency is only used for types. This assumption is false as the type import is shipped in `utils.d.ts` and will be attempted to be resolved in packages that consume the library. This in turn causes build errors like: `Error: node_modules/@metamask/controller-utils/dist/util.d.ts(2,27): error TS2307: Cannot find module '@metamask/eth-query' or its corresponding type declarations.` 
- **Fixed**: Move `@metamask/eth-query` from devDependencies to dependencies

Move `eth-query` back from devDeps to deps

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/nonce.test.ts
packages/transaction-controller/src/utils/nonce.ts
packages/transaction-controller/src/utils/utils.test.ts
packages/transaction-controller/src/utils/utils.ts

Support the use of custom nonces through the `customNonceValue` property used by the extension, in addition to the standard `txParams.nonce` field.
In addition:
- Encapsulate all nonce logic in a new `nonce.ts` file with additional logging.
- Add `type` to incoming transactions.
- **ADDED**: Add the `customNonceValue` property to the transaction metadata.
- **CHANGED**: Update transaction metadata after approval if the approval result includes the `value.txMeta` property.
- **CHANGED**: Add `type` property to all incoming transactions.

Support custom nonce value

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json

Minor release of `@metamask/transaction-controller` only to fix issues in the extension.
No breaking changes, and have verified no changes are required from other unreleased packages.

Release 96.0.0

---

packages/selected-network-controller/src/SelectedNetworkController.ts

We were not able to use persisted values because the initial state could not be passed in. This fixes the issue.
- **Added**: Ability to pass in initial state.

allow initial state to be passed into the constructor

---

README.md
packages/build-utils/CHANGELOG.md
packages/build-utils/LICENSE
packages/build-utils/README.md
packages/build-utils/jest.config.js
packages/build-utils/package.json
packages/build-utils/src/index.ts
packages/build-utils/src/transforms/README.md
packages/build-utils/src/transforms/remove-fenced-code.test.ts
packages/build-utils/src/transforms/remove-fenced-code.ts
packages/build-utils/src/transforms/utils.test.ts
packages/build-utils/src/transforms/utils.ts
packages/build-utils/tsconfig.build.json
packages/build-utils/tsconfig.json
packages/build-utils/typedoc.json
tsconfig.build.json
tsconfig.json
yarn.lock

In https://github.com/MetaMask/metamask-mobile/pull/7734, code fence support was added to MetaMask Mobile by essentially copypasting the implementation from the extension. This PR extracts the shared logic from the extension and mobile implementations of code fencing into a new package, `@metamask/build-utils`, which can be imported into the respective clients. A draft integration in the extension can be found in https://github.com/MetaMask/metamask-extension/pull/22033, which uses local copies of the built version of the new package.
`@metamask/build-utils` currently implements the shared logic for code fence parsing and removal,, as well as linting transformed files. The consumer is responsible for integrating the fence parser into the given build system, and configuring the ESLint …

Add `@metamask/build-utils` package

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Add an optional constructor callback to provide external pending transactions that will be checked when generating nonces.
Required to fully support smart transactions in the extension since their pending state is known only to the `SmartTransactionController` and scenarios such as swaps requiring approval need to generate multiple sequential nonces for pending transactions.
- **ADDED**: Add optional `getExternalPendingTransactions` callback argument to constructor.

Support external pending transactions in nonce calculation

---

package.json
packages/build-utils/CHANGELOG.md
packages/build-utils/package.json

`@metamask/build-utils@1.0.0`, the first release of this new package.

Release 98.0.0

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

The `updateExchangeRatesByChainId` method has been updated to no longer perform any updates if the controller is disabled.
Likely the `disabled` configuration is something we'll at least consider removing soon, as I don't think we use it. But as long as it's here, we should use it consistently.
Fixes #3595
- The `TokenRatesController` method `updateExchangeRatesByChainId` now respects the `disabled` configuration

fix: Make `updateExchangeRatesByChainId` respect `disabled`

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

Fixes a bug where turning on / off the request queue feature flag requires dapps to be manually refreshed in order for the changes to take effect.
- **ADDED**: A method on selected-network-controller that can be called when changing the feature flag. This will update the proxies accordingly.
- **FIXED**: Fixed a bug where when the feature flag was off, we were not savng network selections for domains.

add method to reset proxies when flag toggled

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

While debugging an issue with SwapsController's provider instance being updated too soon due to the remove networkId refactor, I noticed many of our controllers listen to `NetworkController:stateChange` which fires numerous times each time the network switches. Some of these controllers keep track of the `chainId` it's last seen between these events to ensure it only fires off any necessary side effects once. Some controllers don't keep track of if it's seen the `chainId` at all and will fire off the side effects for each and every `stateChange` event. Using `chainId` as a guard isn't even necessarily correct in some cases as the provider may have changed despite the chainId remaining the same.
It seems more appropriate/accurate for these controllers to be listening to …

Add `NetworkState` payload to `NetworkController:networkWillChange` and `NetworkController:networkDidChange`

---

packages/approval-controller/tsconfig.build.json
packages/approval-controller/tsconfig.json
packages/composable-controller/tsconfig.build.json
packages/composable-controller/tsconfig.json
packages/keyring-controller/tsconfig.build.json
packages/keyring-controller/tsconfig.json
packages/logging-controller/tsconfig.build.json
packages/logging-controller/tsconfig.json
packages/notification-controller/tsconfig.build.json
packages/notification-controller/tsconfig.json
packages/permission-log-controller/tsconfig.build.json
packages/permission-log-controller/tsconfig.json

- Removes superfluous TypeScript reference paths to non-dependencies.
- TODO: We should have `yarn constraints` rules to enforce this.
None

Remove superfluous typescript reference paths

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts
packages/assets-controllers/src/index.ts
packages/assets-controllers/src/token-prices-service/abstract-token-prices-service.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts
packages/assets-controllers/src/token-prices-service/index.test.ts
packages/assets-controllers/src/token-prices-service/index.ts
packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/util.ts

CoinGecko is planning on retiring their `/simple/token_price` endpoint soon. This endpoint is critical for us, as we use to fetch prices for tokens. This commit removes all code related to CoinGecko in TokenRatesController so that it hits an internal API instead.
This is set up in such a way that we can upgrade to newer versions of the API (or even other services) in the future without breaking backward compatibility. However, at the moment it does introduce breaking changes to TokenRatesController.
Fixes #3574.
(Updated in PR)

Get token prices from our API instead of CoinGecko

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/tests/mocks/mockEncryptor.ts
yarn.lock

This PR bumps `@metamask/eth-keyring-controller` minimum version to `^15.1.0`.
To adapt unit tests, and to align the two packages, the MockEncryptor has been ported from `@metamask/eth-keyring-controller`
n/a
- **CHANGED**: Bump `@metamask/eth-keyring-controller` to `^15.1.0`

Bump `@metamask/eth-keyring-controller`

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

The TokenRatesController has been updated to ensure that the two sets of exchange rate state are always consistent with each other. Previously if the method `updateExchangeRatesByChainId` was called directly, it would not update the `contractExchangeRates` state even if the equivalent part of `contractExchangeRatesByChainId` was updated by that call.
The tests have undergone a substantial refactor to ensure that we cover all cases between both of these update methods. The test cases written previously left out many test cases. We should now have better (but not perfect) coverage, and the tests are now shared between the two methods because they have identical test cases.
Fixes #3597
- Fixed: Fixed bug where the `contractExchangeRates` state would sometimes be stale after calling …

fix(assets-controllers): TokenRatesController state consistency

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

Previously it was possible for two redundant token rate updates to be ongoing at the same time. This is non-optimal for performance reasons, and because the answer might change between the two requests and get persisted in the wrong order.
We now guard against this by storing in-progress updates as a private instance variable. Any redundant calls will wait on the in-progress call to finish, then return as a no-op.
Fixes #3606
-Fixed: Prevent overlapping token rate updates
- This should have no impact to the API at all, it just reduces network traffic

fix(assets-controllers): Prevent overlapping token rate updates

---

packages/assets-controllers/package.json
packages/assets-controllers/src/index.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts
packages/assets-controllers/src/token-prices-service/index.test.ts
packages/assets-controllers/src/token-prices-service/index.ts
yarn.lock

The `token-prices-service` will now retry token price updates if they fail. The retry strategy is designed to let the API recover if it is experiencing high traffic volumes.
The service now requires state in order to hold onto the retry policy. It has been converted to a class for that reason. This required no changes to the abstract price service type or to the `TokenRatesController`.
Closes #2084
- Changed: The `CodefiTokenPricesServiceV2` will retry if the token price update fails
- We retry each request up to 3 times using a randomized exponential backoff strategy
- If the token price update still fails 5 times consecutively (including the 3 retries each attempt, so 15 consecutive failures total), we stop trying for 30 minutes before we try again.
- The service has been converted from …

Retry failed token price updates

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

This fixes `startTrackingByNetworkClientId`'s trackingMap as well as adds `stopTrackingByNetworkClientId` and some initial tests for them both

Transaction multichain fix starttracking

---

packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts

The `CodefiTokenPricesServiceV2` service now accepts an `onBreak` event handler. This handler is called upon each circuit break. This allows us to collect metrics on circuit breaks, which would help is detect widespread failures of this service.
N/A
- Added: Add `onBreak` option to `CodefiTokenPricesServiceV2`

feat: Add `onBreak` handler to token price service

---

packages/assets-controllers/package.json
yarn.lock

The package `cockatiel` was mistakenly pinned when it was introduced. It has been updated to use a caret range, and the minimum has been bumped to v3.1.2. v3.1.2 removes test files from the package, which reduces the package size and resolves a false positive security warning from Socket.
N/A
- Changed: Update `cockatiel` to `^3.1.2`

chore(assets-controllers): Update `cockatiel` and widen range

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

- Moves state update call after networkClient was instantiated so that `NetworkController:stateChange` event can be safely used to identify when new networkClients have been added and are available for use

Move state update call after networkClient is instantiated and added to registry in `upsertNetworkConfiguration`

---

packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/assetsUtil.ts

OpenSea renamed the field `supply`, which used to be required, to `total_supply`.  Fixes the error:
`undefined is not an object (evaluating 'contract.supply.toString')`
A more accurate `total_supply` was also added to the collection object, which is now preferred to the one on the contract.
- **FIXED**: OpenSea response from `supply` to `total_supply`

OpenSea supply -> total_supply

---

packages/assets-controllers/src/TokenRatesController.ts
packages/assets-controllers/src/token-prices-service/abstract-token-prices-service.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts

This used to throw an error;
Noticed that on the import flow, if you try to import two tokens exp (USDC and STEELO) where it should succeed to fetch prices for USDC and not for STEELO. It will throw for STEELO preventing fetching for USDC; hence you end up on the home page where you do not see the user token amount for USDC.
Steps to REPRODUCE:
1- Go to home page on extension (IDEALLY remove the extension and import again so u don't have cached rate values)
2- search for STEELO and select it
3- search for USDC and select it
4- Click next and click import
5- go to home page and notice you do not see the USDC token amount in fiat
- Fixed: removed the throw error in codefi-v2.ts file and changed it to just console the error

fix: fix fetch price

---

packages/assets-controllers/src/TokenRatesController.ts
packages/assets-controllers/src/assetsUtil.test.ts
packages/assets-controllers/src/assetsUtil.ts
packages/assets-controllers/src/index.ts

Export a function from assets controller to fetch token exchange rates.
This function will be used by extension to compute user token fiat amount and display it on the import token modal confirmation page.
* Fixes [#12345](https://consensyssoftware.atlassian.net/browse/MMASSETS-88)
* Related to [#67890](https://github.com/MetaMask/metamask-extension/pull/22263)
- **<CATEGORY>**: Updated `assetsUtil `file to export `fetchAndMapExchangeRates `function

feat: export exchange rates fct

---

packages/base-controller/src/BaseControllerV2.ts

The `subscribe` property was removed in #3590 because it is no longer used. It has been restored here so that we can release the `@metamask/base-controller` without any breaking changes.
This property's description has been updated to clarify that it's no longer used, and it's now marked as deprecated.
Discussed in the v104 release candidate PR: https://github.com/MetaMask/core/pull/3695#discussion_r1435225330
- Changed: Deprecate the `subscribe` property of `BaseControllerV2`
- This property was used to differentiate between `BaseControllerV1` and `BaseControllerV2` controllers. It is no longer used, so it has been marked as deprecated.

chore(base-controller): Restore `subscrbe` property

---

packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts

The option `onDegraded` has been added to the `CodefiTokenPricesServiceV2` service, which lets us react to situations where the service is still presumed to be available (i.e. there is no outage, the circuit has not broken) but a request failed, or succeeded too slowly. We can use this option to track instances of degraded service in production.
The option `degradedThreshold` has also been added. This acts as a definition of "degraded service"; if requests are slower than this duration, we consider the service to be degraded.
Closes #3689
- Added: Add support to `CodefiTokenPricesServiceV2` for tracking degraded service
- The constructor has two new options: `onDegraded` and `degradedThreshold`. `onDegraded` is an event handler for instances of degraded service (i.e. failed or slow …

feat(assets-controllers): token price service degraded metrics

---

packages/name-controller/src/NameController.test.ts
packages/name-controller/src/NameController.ts

In this PR, we introduced a "fallback" variation (denoted as "*") in the ﻿NameController specifically for the handling of petnames. In the case of ethereum addresses, variations typically are the hexadecimal chainID, implicitly defining petnames for a specific address within a particular chain.
The rationale behind adding a fallback variation is to accommodate scenarios where the petnames are not strictly tied to a particular chain. Instead of enforcing a chain-specific petname, the fallback variation operates on a more flexible rule: Given an Ethereum address, if a chain-specific petname does not exist, the fallback variation is automatically inspected to determine if a petname exists for this general scenario.
* Related to https://github.com/MetaMask/MetaMask-planning/issues/1624
- …

Addition of "fallback" Variation to the NameController for Petnames

---

packages/assets-controllers/src/AccountTrackerController.test.ts
packages/preferences-controller/src/PreferencesController.ts

The `PreferencesController` types are now declared as types rather than interfaces, in accordance with our conventions, and they are now fully documented. The state properties have also been alphabetized so that they are easier to maintain.
Additionally, the old "ContactEntry" type has been renamed to "Identity", which is a more accurate name for what it is being used for here.
This was an effort to reduce the scope of the BaseControllerV2 migration, tracked by #3708
- **BREAKING**: Replace `ContactEntry` interface with `Identity` type
- **BREAKING:** Convert `PreferencesState` from an interface to a type

chore(preferences-controller): Clean up types

---

packages/permission-controller/src/SubjectMetadataController.test.ts
packages/permission-controller/src/SubjectMetadataController.ts

The `SubjectMetadataController` is currently being called with a direct reference to the controller in the extension client: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L2367-L2373
To simplify this and make it easier for the SnapController to handle the population of metadata, this PR adds an exposed action for `addSubjectMetadata`.
- **Added**:  Add `SubjectMetadataController:addSubjectMetadata` action

Add `SubjectMetadataController:addSubjectMetadata` action

---

package.json
packages/accounts-controller/package.json
packages/accounts-controller/src/AccountsController.ts
yarn.lock

The snaps dependencies had breaking changes blocking Dependabot from bumping them automatically. This PR addresses them.
- **Changed**: Bump snaps dependencies

Bump snaps dependencies

---

packages/assets-controllers/src/AccountTrackerController.test.ts
packages/preferences-controller/src/PreferencesController.ts

The `AccountTrackerController` tests have been updated to remove instances of the `PreferencesController`. Mocks are now used instead of the real controller.
It was useful to have a reference in tests to the default `PreferencesController` state, so I added a `getDefaultPreferencesState` function. This was added as a function to protect against accidental mutations.
- Add `getDefaultPreferencesState` function

refactor(assets-controllers): Simplify `AccountTrackerController` tests and add `getDefaultPreferencesState`

---

packages/assets-controllers/src/TokensController.test.ts

The `TokensController` tests have been refactored to use mocks instead of a real `PreferencesController` instance. This should make the tests easier to read, and it will decouple them from the `PreferencesController`.
No changes

refactor(assets-controllers): Simplify `TokensController` tests

---

packages/assets-controllers/src/TokenBalancesController.test.ts
packages/assets-controllers/src/TokensController.ts

The `TokenBalancesController` tests have been refactored to use mocks instead of `NetworkController` and `PreferencesController` instances. This should make the tests easier to read, and it decouples the tests further from the other controllers.
- Add `getDefaultTokensState` function to the `TokensController`

refactor(assets-controllers): Simplify `TokenBalancesController` tests

---

packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts

The `NftDetectionController` tests have been refactored to use mocks rather than full `AssetsContractController`, `PreferencesController`, and `NftController` references. The `withController` pattern has been introduced as well, to simplify the controller setup and ensure all polling has stopped after each test.
A few tests were found to be testing functionality that was internal to the `NftController`, so they have been removed. Coverage for the `NftDetectionController` remains unchanged.
- Add `getDefaultNftState` function to the `NftController`

refactor(assets-controllers): Simplify `NftDetectionController` tests

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenListController.ts
packages/assets-controllers/src/TokensController.test.ts

The `TokenDetectionController` tests have been refactored to use mocks instead of real controller instances, and to use the `withController` pattern to simplify controller setup and ensure that polling has stopped after each test.
A `getDefaultTokenListState` function has been added to the `TokenListController` to enable us to use that default state in tests.
One test was added to the `TokensController` tests to prevent a coverage drop (it was previously being tested indirectly via the `TokenDetectionController` tests).
- Add `getDefaultTokenListState` function to `TokenListController

refactor(assets-controllers): Simplify `TokenDetectionController` tests

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/assetsUtil.test.ts
packages/assets-controllers/src/assetsUtil.ts

Makes 2 perf improvements to price API calls:
- Batch size of 30 instead of 100
- Sort token addresses in query params for more cache hits
- https://github.com/MetaMask/MetaMask-planning/issues/1891
- https://github.com/MetaMask/mobile-planning/issues/1458
- **CHANGED**: Price API batch size reduced from 100 to 30

Price API perf improvements

---

packages/assets-controllers/src/TokenRatesController.ts

Sort token addresses before batching calls to price API for more cache hits.
- https://github.com/MetaMask/MetaMask-planning/issues/1891
- https://github.com/MetaMask/mobile-planning/issues/1458
- **CHANGED**: Sort token addresses before batching calls to price API

Sort token addresses before batching calls to price API

---

packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

The `PreferencesController` has been migrated to `BaseControllerV2`. As part of this migration, the unused `name` state property has also been removed.
Closes #3708
- **BREAKING:** Convert to `BaseControllerV2`
- The constructor parameters have changed; rather than accepting an empty "config" parameter and a "state" parameter, there is now just a single object for all constructor arguments. This object has a mandatory `messenger` and an optional `state` property.
- Additional type exports have been added for the controller messenger and associated types

feat(preferences-controller): Convert to BaseControllerV2

---

packages/base-controller/src/ControllerMessenger.test.ts
packages/base-controller/src/ControllerMessenger.ts
packages/base-controller/src/RestrictedControllerMessenger.test.ts
packages/base-controller/src/RestrictedControllerMessenger.ts

The "selectors" feature of the `ControllerMessenger` did not work correctly for the first event published after subscribing, because the original value of the payload (at time of subscribing) was not available for comparison.
To address this, a `registerInitialEventPayload` method has been added to the `ControllerMessenger` and `RestrictedControllerMessenger`. This allows registering a function that returns the "event payload state" at a given time, which is used internally by the `subscribe` method to correctly initialize the payload cache when a subscriber with a selector is added. This ensures that the selector works correctly even for the initial state change, in that it will return the correct previous value, and not fire at all if the selected piece of state is unchanged.
In a later …

fix(base-controller): Fix selectors initial value comparison

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Rather than modify NonceTracker to accept a static chainId arg in its constructor we can bind the `getNonceTrackerPendingTransaction` callback with the chainId for the networkClient it is concerned with.

Bind `getNonceTrackerPendingTransactions` with chainId when passing to NonceTracker constructor

---

packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/BaseControllerV2.ts
packages/name-controller/src/NameController.test.ts
packages/signature-controller/src/SignatureController.test.ts
packages/user-operation-controller/src/UserOperationController.test.ts
packages/user-operation-controller/src/helpers/PendingUserOperationTracker.test.ts

Subscribers to the `stateChange` event of any `BaseControllerV2`-based controllers will now correctly handle the initial state change event.
Previously the initial state change would always result in this event firing, even for subscriptions with selectors where the selected value has not changed. Additionally, the `previousValue` returned was always set to `undefined` the first time.
`BaseControllerV2` has been updated to correctly compare with the previous value even for the first state change. The returned `previousValue` is also now guaranteed to be correct even for the initial state change.
Fixes #3701
- Fixed: Subscribers to the `stateChange` event of any `BaseControllerV2`-based controllers will now correctly handle the initial state change event
- Previously the initial state …

fix(base-controller): Fix `stateChange` subscriptions with selectors

---

packages/transaction-controller/src/TransactionController.ts

* Makes `getEthQuery` #private
* Leaves existing ts private keywords in place
Related https://github.com/MetaMask/MetaMask-planning/issues/1892

Make getEthQuery private

---

packages/network-controller/jest.config.js
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

The `setActiveNetwork` method (and action) has been updated to support both network client IDs and built-in network types, letting us use it for switching to any type of network.
Note that the coverage has been updated, increasing coverage for branches but reducing it for lines and statements. The reductions were due to lines being removed; there are no lines or statements that have become uncovered in this PR.
This was done to assist with #3763
Closes #2020
- The `setActiveNetwork` method and action now supports built-in network types.
- Previously this would only accept a network configuration ID. Now it will accept the type of a built-in network as well, using it like an ID. This lets you switch to a built-in or custom network with a single method/action.
- Deprecate the …

refactor(network-controller): Consolidate `setActiveNetwork` and `setProviderType`

---

package.json
packages/accounts-controller/package.json
packages/address-book-controller/package.json
packages/approval-controller/package.json
packages/assets-controllers/package.json
packages/assets-controllers/src/TokenRatesController.ts
packages/base-controller/package.json
packages/build-utils/package.json
packages/controller-utils/package.json
packages/ens-controller/package.json
packages/eth-json-rpc-provider/package.json
packages/gas-fee-controller/package.json
packages/json-rpc-engine/package.json
packages/json-rpc-middleware-stream/package.json
packages/keyring-controller/package.json
packages/message-manager/package.json
packages/name-controller/package.json
packages/network-controller/package.json
packages/notification-controller/package.json
packages/permission-controller/package.json
packages/permission-log-controller/package.json
packages/polling-controller/package.json
packages/queued-request-controller/package.json
packages/selected-network-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

The `createDeferredPromise` function that had been defined in the `TokenRatesController` has been replaced by the function with the same name from the `@metamask/utils` package. It behaves identically.
The `@metamask/utils` package has been updated from `^8.2.0` to `^8.3.0` in all packages because the `createDeferredPromise` function was added in `v8.3.0`.
This is a follow-up to #3635. The function was temporarily inlined in that PR, but the plan was always to ship it as part of utils.
This was done now because it helps somewhat with #3763, but it's not a complete blocker.
This change entry applies to all packages in the diff for this PR.
- Bump `@metamask/utils` to `^8.3.0`

refactor: Update `@metamask/utils` and use `createDeferredPromise` from utils

---

packages/assets-controllers/src/TokenBalancesController.test.ts
packages/assets-controllers/src/TokenBalancesController.ts
packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/index.ts
packages/transaction-controller/src/TransactionController.test.ts
tests/helpers.ts

The `TokenBalancesController` has been migrated to `BaseControllerV2`.
Closes #1808
- **BREAKING:** Convert to `BaseControllerV2`
- The constructor parameters have changed; rather than accepting a "config" parameter for interval and tokens we now pass both values as controller options, and a "state" parameter, there is now just a single object for all constructor arguments. This object has a mandatory `messenger` and an optional `state`, `tokens`, `interval`  properties a disabled property has also been added.
- State now saves tokens  balances as strings and not as a BNs.
- Additional BN export has been removed as it was intended to be removed in the next major release.

feat: migrate token balances controller to base controller v2

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

Transaction multichain init tracking map

---

docs/migrate-tags.md
docs/package-migration-process-guide.md

fix typos:
docs/migrate-tags.md
docs/package-migration-process-guide.md

docs: fix typos

---

packages/network-controller/package.json
packages/queued-request-controller/package.json
packages/selected-network-controller/package.json
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
yarn.lock

Network controller and selected network controller are the two places updated by this PR.
[See here for more details](https://github.com/MetaMask/swappable-obj-proxy/pull/53)
not required for https://github.com/MetaMask/metamask-extension/pull/22202 but updating this here is a matter of good package hygene. 
- **FIXED**: Event listeners added to the blockTracker via a different proxy are migrated undesireably.
- **FIXED**: Event listeners added to the blockTracker via a different proxy (or directly on the blockTracker) are migrated undesireably.

update swappable-obj-proxy to 2.2.0

---

packages/assets-controllers/src/token-prices-service/codefi-v2.ts

Adds Linea to the list of chains the price API supports.  To enable pricing ERC20 tokens.
Before:
After:
- **ADDED**: Add Linea to the price api supported chains

Add Linea to price api supported chains

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts

* Add scenario to `getNonceLock` to checks if the right nonceTracker is used when a networkClientId is provided
* Add integration tests for `getNonceLock` that test result and that an acquired lock blocks subsequent attempts to acquire
* Lint IncomingTxOptions jsdoc 

add getNonceLock tests

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR fixes the edge case that leads to the reset of the Accounts Controller state. The accounts controller listens to the keyring controller state change, when the extension client executes two submit passwords in succession, there is a race condition where the [keyring controller would empty its keyring state ](https://github.com/MetaMask/KeyringController/blob/2d73a4deed8d013913f6ef0c9f5c0bb7c614f7d3/src/KeyringController.ts#L910)causing the accounts controller to clear its state.
For example:
* [Fixes #215](https://github.com/MetaMask/accounts-planning/issues/215)
- **CHANGED**: onKeyringState only triggers when the keyring controller is unlocked and has keyrings.
- [] I've highlighted breaking changes using the "BREAKING" category above as appropriate

fix: quick succession of submit password causing Accounts Controller state to be cleared

---

packages/network-controller/jest.config.js
packages/network-controller/src/NetworkController.ts

The internal variable `#provider` has been removed. It was not used.
N/A
None

chore(network-controller): Remove unused internal variable

---

packages/assets-controllers/src/AssetsContractController.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.ts

All uages of the deprecated `NetworkController` method `setProviderType` have been removed from this repository. They have been replaced by calls to `setActiveNetwork`, which now also supports being given network types, just like `setProviderType` did.
N/A
- The action `NetworkController:setProviderType` is no longer used, so it's no longer required by the `QueuedRequestController` messenger.

refactor: Remove usage of deprecated `setProviderType`

---

packages/network-controller/jest.config.js
packages/network-controller/src/NetworkController.ts

The method `setProviderType` has been updated to use `setActiveNetwork` internally, allowing us to remove a bunch of code that was duplicated between both methods.
N/A
None

refactor: Remove duplicated code in `setProviderType`

---

packages/accounts-controller/package.json

Move the keyring-controller from a dependency to to dev dependency in Accounts Controller. This was accidentally recategorized in #3747, this PR undoes that change.
- **Changed**: Move keyring-controller from a dependency to devDependency in the AccountsController

Move keyring-controller dep to devdep in Accounts Controller

---

packages/keyring-controller/package.json
packages/keyring-controller/src/KeyringController.ts
packages/keyring-controller/tsconfig.build.json
packages/keyring-controller/tsconfig.json
packages/preferences-controller/package.json
packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts
packages/preferences-controller/tsconfig.build.json
packages/preferences-controller/tsconfig.json
yarn.lock

The `PreferencesController` now listens for `KeyringController` state changes, and updates its own state in response to account removals or additions. New accounts are added to the `identities` state and given default labels. Removed accounts are removed from the `identities` state, and the `selectedAddress` is updated if it was removed.
The dependency between these two packages has been flipped; the `@metamask/preferences-controller` package now depends upon `@metamask/keyring-controller` rather than the other away around, so that the `KeyringController` state type and state change event can be accessed. The dependency the other way was just to get the types for the four `PreferencesController` methods that are passed into the `KeyringController` constructor. These types were easily …

feat: Keep `PreferencesController` in sync with keyring state

---

packages/user-operation-controller/package.json
yarn.lock

The `@metamask/user-operation-controller` package has been updated to remove the peer dependency `@metamask/polling-controller`. Contrary to what the name might suggest, `@metamask/polling-controller` is not itself a controller package, so it's not subject to our policy of making controller dependencies peer dependencies. It's just a regular library.
N/A
- Remove `@metamask/polling-controller` peer dependency
- This was mistakenly added as a peer dependency in v1. Now it's a regular dependency.

chore(user-operation-controller): Remove unnecessary `peerDependency`

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/tests/mocks/mockKeyring.ts
packages/keyring-controller/tests/mocks/mockTransaction.ts

This PR adds some test coverage for cases where the requested method is not supported by the keyring linked with the provided account. These are the methods tested:
* removeAccount
* exportAccount
* getEncryptionPublicKey
* decryptMessage
* signMessage
* signPersonalMessage
* signTypedMessage
* signTransaction
The remaining methods related to user operations will be addressed [in another PR](https://github.com/MetaMask/core/pull/3832), as they also need more refactoring to be aligned with how tests for other methods are written.
* Related to #3830
No documentable changes

Add coverage for unsupported keyring methods

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

When the feature flag for per dapp network is turned off, we should keep all the proxies for all the domains in sync. To do that, we add some code to the end of the function used to set network client id for a given domain. When the user is setting the domain for 'metamask', and when the feature flag is off, we do the update to all the domains, not just metamask.
- **CHANGED**: NetworkClientId for each domain will be the same as metamask when the feature flag is off

Selected network controller should update all domains when feature flag is off

---

packages/keyring-controller/src/KeyringController.test.ts

This PR refactors tests related to user operations methods, to align them with the structure used for other methods.
It also adds test coverage for keyrings that do not support user operations
* Related to #3830 
No functional changes

Refactor user operations tests

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR adds additional tests for edge cases, useful for #3830.
Some `istanbul ignore if` statements are also being removed
* Fixes #3767 
* See #3830 
No functional changes

Add tests for KeyringController edge cases

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

This PR aims to fix an issue with the custodian transaction where the promise is not resolved.
- **FIXED**: Emit `txId:finished` when custodian transaction status is updated to `submitted` or `failed`

fix: resolve tx custodian promise when set transaction to submitted or failed

---

packages/transaction-controller/src/types.ts

Reverts MetaMask/core#3828
no longer needed after discovering we can update the event fragment ad-hoc using the useTransactionEventFragment hook
Related to https://github.com/MetaMask/metamask-extension/pull/22631

Revert "feat: add externalLinkClicked to TransactionMetaBase type"

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
packages/transaction-controller/test/EtherscanMocks.ts

* Moves etherscan mocks into `test` folder outside of the `src` folder which also means it won't be included in builds

Move etherscan mocks

---

packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts

Addresses [feedback](https://github.com/MetaMask/core/pull/3643#discussion_r1470225885) given on the feature branch.
We no longer wait til the rate limit time is up to return the fetchedTransaction. We only wait the full time to unlock the mutex to prevent another request until 5 seconds have elapsed.

Improve rate limiting logic in `etherscanRemoteTransactionSource`

---

packages/composable-controller/src/ComposableController.test.ts
packages/composable-controller/src/ComposableController.ts

This PR removes the `flatState` getter from `@metamask/composable-controller`
* Fixes #3812 
- **BREAKING**: Remove `flatState` getter
- This method was confusing to use in practice. Consumers should use the ComposableController state directly.

[composable-controller] Remove `flatState` getter

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/jest.config.js
packages/assets-controllers/package.json
packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts
packages/assets-controllers/tsconfig.build.json
packages/assets-controllers/tsconfig.json
yarn.lock

Merges the core `TokenDetectionController` with `DetectTokensController` from the extension   and patches for this controller from mobile. 
- Aims to replace the extension and mobile versions of this controller and implement a unified interface that consolidates the functionality of all three iterations.
- Generally assumes `DetectTokensController` to be more up-to-date, and prioritizes preserving extension and mobile behavior to minimize disruption.
Significant API changes: see [Changelog](https://github.com/MetaMask/core/pull/3775/files#diff-ee47d03d53776b8dd530799a8047f5e32e36e35765620aeb50b294adc3339fab) for details.
- Closes #3626
- See #1813 
- **BREAKING:** Adds `@metamask/accounts-controller` ^8.0.0 and `@metamask/keyring-controller` ^12.0.0 as dependencies and peer dependencies. …

[token-detection-controller] Consolidate with `DetectTokensController` from extension

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/jest.config.js
packages/assets-controllers/src/TokenBalancesController.test.ts
packages/assets-controllers/src/TokenBalancesController.ts
packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts
packages/assets-controllers/src/TokensController.test.ts
packages/assets-controllers/src/TokensController.ts
packages/assets-controllers/src/index.ts

Remove `TokenDetectionController` constructor callbacks for `TokensController`.
- `TokensController` features should be exposed as messenger actions/events so that consumers don't need to import the entire class.
- `TokensController` should use messenger action/events to consume external controller features instead of callbacks.
- Replaces constructor options callbacks `onPreferencesStateChange`, `onNetworkDidChange`, `onTokenListStateChange`, `getNetworkClientById` with messenger actions (`NetworkController:getNetworkClientById`) and events (`PreferencesController:stateChange`, `NetworkController:networkDidChange`, `TokenListController:stateChange`).
- Replaces tokens-controller callbacks in token-detection-controller and token-balances-controller with `TokensController:getState`, …

[assets-controllers] Upgrade `TokensController` to fully utilize controller-messenger pattern

---

packages/permission-controller/src/rpc-methods/requestPermissions.test.ts
packages/permission-controller/src/rpc-methods/requestPermissions.ts

The type for the RPC method hook `requestPermissionsForOrigin` did not previously match the implementation `PermissionController.requestPermission`. This PR rectifies that and thus simplifies the implementation of the RPC method by removing effectively dead code.
Previously we were passing in a string as the optional options bag. Since this options bag has sane defaults, those were always used: https://github.com/MetaMask/core/blob/main/packages/permission-controller/src/PermissionController.ts#L1884
With this change, we just always use the options bag defaults and can remove complexity from the RPC implementation.
I'm not sure this warrants a changelog entry tbh.

Simplify `wallet_requestPermissions` implementation

---

packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

The `NftDetectionController` was making unnecessary HTTP requests.
(1) It was fetching NFTs when any setting changes:
https://github.com/MetaMask/core/assets/3500406/297b1889-ee17-4c57-890b-8f94e4b1be4b
(2) When each polling interval arrives, it can send ~7 identical requests instead of 1.  See timeline:
(3) one redundant request when switching accounts
All come from `onPreferencesStateChange` triggering a re-start.
(2)  happens because it fires ~7 times on startup from keyring related updates.  This causes each to run:
```
this.stopPolling();
await this.detectNfts();
this.intervalId = setInterval(...)
```
Because `detectNfts` is async, `intervalId` is still undefined.  So they each schedule their own interval without stopping a previous interval.
Fix: Only start/stop when relevant …

fix: NFT detection running too many times

---

packages/preferences-controller/jest.config.js
packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

Upon wallet lock, `PreferencesController` will capture a `KeyringController:stateChange` event, with an empty keyring array in the payload. While this is normal behaviour, `PreferencesController` will sync its identities with this empty array of identities, which will result in setting the selected address to `undefined`.
With these changes `PreferencesController` will skip the sync when there is no identity, and throw an error in case the `syncIdentities` method is called with an empty array.
* See: https://github.com/MetaMask/metamask-extension/pull/22949#discussion_r1495890404
- **FIXED**: Identities are not synced when locking anymore

fix(preferences-controller): skip sync when locking

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1964
- The `SelectedNetworkController` now listens for `networkConfiguration` removal events on the `NetworkController` and if a removed `networkClientId` matches the set networkClientId for any `domains` in its state, it updates them to the globally selected networkClientId and repoints the proxies accordingly.

Fix `SelectedNetworkController` state corruption when networkClients are removed

---

packages/permission-log-controller/src/PermissionLogController.ts
packages/permission-log-controller/tests/PermissionLogController.test.ts
packages/permission-log-controller/tests/helpers.ts

This pull request is designed to align the tests for `PermissionLogController` with the guidelines outlined in our contributor documentation. The objective is to refactor these tests in accordance with best practices recommended for unit testing, as detailed in the provided documentation [link](https://github.com/MetaMask/contributor-docs/blob/main/docs/unit-testing.md).
* Fixes #1827
- Discontinued the use of beforeEach for the majority of the tests, with exceptions made for certain tests that utilize fake timers. Now, each test individually initializes a new controller and middleware within its own scope, enhancing test isolation and clarity.
- Split long test scenarios for more focused test cases.

Refactor PermissionLogController tests

---

packages/assets-controllers/src/token-prices-service/codefi-v2.ts

Sets `Cache-Control: no-cache` on price API requests.
See: https://consensys.slack.com/archives/C065W3877E3/p1708468886411439?thread_ts=1708466257.782319&cid=C065W3877E3
- **CHANGED**: HTTP requests to the price API now use the `no-cache` directive.

fix: price api cache control

---

packages/transaction-controller/src/TransactionController.ts

This patches transaction-controller 6.1.0, introducing a fallback for gas estimations. In cases of failed gas estimation, the transaction will default to using 95% of the latest block gas limit. This ensures that transactions have viable gas.
Previously, if gas estimation for a transaction failed (for example, due to the transaction being reverted), the `gasHex` value would remain undefined. This issue led to the transaction being assigned zero gas, causing it to be submitted to the mempool where it would get "stuck".
This change is specific to version 6.1.0 of the transaction-controller. Later versions of the TransactionController include this fix.
- related: https://github.com/MetaMask/metamask-mobile/issues/8533

patch: fallback to 95% of block gas limit if gas estimation fails

---

packages/queued-request-controller/src/index.ts

These two types were added in #3919, but these exports were accidentally omitted.
This change was missing from #3919
This change was documented already in #3919

fix(queued-request-controller): Add missing type exports

---

packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts
packages/queued-request-controller/src/index.ts

The event `QueuedRequestController:countChanged` and the method `length` have been removed. Both the event and method were deprecated as part of #3919, which also provided an alternative by adding the queued request count to the controller state.
Related to #3919
- **BREAKING**: Remove the `QueuedRequestController:countChanged` event
- The number of queued requests is now tracked in controller state, as the `queuedRequestCount` property. Use the `QueuedRequestController:stateChange` event to be notified of count changes instead.
- **BREAKING**: Remove the `length` method
- The number of queued requests is now tracked in controller state, as the `queuedRequestCount` property.

chore(queued-request-controller): Remove `countChanged` event

---

packages/base-controller/CHANGELOG.md
packages/base-controller/src/BaseControllerV1.ts

- For runtime property assignment, use `as unknown as` instead of `as any`.
- Change the types for `BaseControllerV1` class fields `initialConfig`, `initialState` from `C`, `S` to `Partial<C>`, `Partial<S>`.
- Initial user-supplied constructor options do not need to be complete `C`, `S` objects, since `internal{Config,State}` will be populated with `default{Config,State}`.
- For empty objects, prefer no type assertions or `as never` (`never` is assignable to all types).
- Fix code written based on outdated TypeScript limitation.
- Generic spread expressions for object literals are supported by TypeScript: https://github.com/microsoft/TypeScript/pull/28234
- Closes #3715

[base-controller] Fix `any` usage in `BaseControllerV1`

---

packages/selected-network-controller/package.json
packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
packages/selected-network-controller/tsconfig.build.json
packages/selected-network-controller/tsconfig.json
yarn.lock

See here for more info: https://app.zenhub.com/workspaces/wallet-api-platform-63bee08a4e3b9d001108416e/issues/gh/metamask/metamask-planning/2142
When there exists a permission for a domain, we will then start saving their network selection. We also retroactively add network selections for domains which already have permissions.
- **CHANGED**: Domain selection is written/deleted when permissions are added/removed

Listen to permissions changes and add/remove `domains`

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

See [here](https://app.zenhub.com/workspaces/wallet-api-platform-63bee08a4e3b9d001108416e/issues/gh/metamask/metamask-planning/2143) for more details
- **ADDED**: SelectedNetworkController constructor now takes a `getUseRequestQueue` function.
- **REMOVED**: SelectedNetworkController no longer has a perDappNetwork feature flag saved in state.

remove redundant perDomainNetwork state

---

packages/queued-request-controller/package.json
packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts
packages/queued-request-controller/src/index.ts
packages/queued-request-controller/tsconfig.build.json
packages/queued-request-controller/tsconfig.json
yarn.lock

When the `QueuedRequestController` requires the globally selected network to be changed, we now emit an event rather than triggering a confirmation. This aligns with recent designs for this use case.
The actions `NetworkController:getNetworkConfigurationByNetworkClientId` and `ApprovalController:addRequest` were only used for triggering the switch network confirmation, so they are no longer needed now. They have been removed. This removes the last dependency of this controller on the `ApprovalController`, so it has been removed as a dependency as well.
Closes #3983
- **BREAKING:** The `QueuedRequestController` no longer triggers a confirmation when a network switch is needed
- The network switch now happens automatically, with no confirmation.
- A new …

feat(queued-request-controller): Replace confirmation with switch event

---

packages/selected-network-controller/package.json
yarn.lock

in response to https://github.com/MetaMask/core/pull/3996#pullrequestreview-1907920534
- **CHANGED**: Move permissions-controller from devDeps to deps and peerDep

move permission controller from devdep to regular dep

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/utils/utils.test.ts
packages/transaction-controller/src/utils/utils.ts

The transaction parameters include the `data` property which is a hex string.
When processed by the RPC provider / node, `data` with an odd-length is treated the same as an even-length value, meaning the `data` value of `0x123` is treated the same as `0x0123`.
This PR applies equivalent normalization in the `TransactionController` to ensure the client UIs receive the `data` in a consistent format with an even length hex string.
Also export the `normalizeTransactionParams` method so it can be utilised directly by any layer of the client to format transaction parameters with the same logic.
- **ADDED**: Add `normalizeTransactionParams` method.
- **CHANGED**: Normalize `data` property into an even length hex string.

Normalize transaction data length

---

packages/transaction-controller/src/constants.ts

This PR replaces the reference to OP goerli to OP sepolia. It also renames the variable `OPTIMISM_TESTNET` to `OPTIMISM_SEPOLIA`.
Only made this change on the transaction controller.
Renaming the variable and switching to Sepolia is a breaking change, please use Sepolia and `OPTIMISM_SEPOLIA` instead of `OPTIMISM_TESTNET`.
* Fixes https://github.com/MetaMask/mobile-planning/issues/1569
* Related to [#67890](https://github.com/MetaMask/metamask-mobile/pull/8784)
**Removed**
- **BREAKING**: Renamed `OPTIMISM_TESTNET` to `OPTIMISM_SEPOLIA` and updated the chainId accordingly.
- **BREAKING**: Updated the etherscan subdomain that was for  OPTIMISM_TESTNET from goerli to sepolia.

fix: update OPTIMISM_TESTNET to OPTIMISM_SEPOLIA

---

packages/controller-utils/package.json
yarn.lock

This PR moves `bn.js` to be a non-dev dependency of `controller-utils` as it is used directly in https://github.com/MetaMask/core/blob/main/packages/controller-utils/src/util.ts
It also adds `@types/bn.js` to the dependencies, mirroring the implementation from `assets-controllers`.
For more context see this CI failure: https://github.com/MetaMask/snaps/actions/runs/8154723823/job/22288793408?pr=2245
- **Changed**: Add `bn.js` to dependencies

Move `bn.js` to `controller-utils` dependencies

---

packages/base-controller/src/ControllerMessenger.ts

- **BREAKING**: Add `string` as generic constraint to the `Name` generic parameter of the types `NamespacedBy` and `NotNamespacedBy`.

[base-controller] minor type fixes

---

packages/announcement-controller/src/AnnouncementController.test.ts
packages/approval-controller/src/ApprovalController.test.ts
packages/assets-controllers/src/AssetsContractController.test.ts
packages/assets-controllers/src/CurrencyRateController.test.ts
packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/TokensController.test.ts
packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/ControllerMessenger.ts
packages/base-controller/src/RestrictedControllerMessenger.test.ts
packages/composable-controller/src/ComposableController.test.ts
packages/ens-controller/src/EnsController.test.ts
packages/keyring-controller/src/KeyringController.test.ts
packages/logging-controller/src/LoggingController.test.ts
packages/network-controller/tests/NetworkController.test.ts
packages/notification-controller/src/NotificationController.test.ts
packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/SubjectMetadataController.test.ts
packages/permission-log-controller/tests/PermissionLogController.test.ts
packages/phishing-controller/src/PhishingController.test.ts
packages/preferences-controller/src/PreferencesController.test.ts
packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/rate-limit-controller/src/RateLimitController.test.ts
packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/utils/swaps.test.ts

This commit implements a fundamental solution to aligning runtime and type-level behavior for `getRestricted`: removing the option to omit its function parameters altogether. 
- This makes the expected runtime behavior of the method explicit and predictable. 
- This completely prevents type inference from deriving ambiguous conclusions from the omission of function or generic parameters, or otherwise exhibiting unexpected behavior.
The downsides of this approach are a bit more redundant code and inconvenience, but having to write an extra empty array or two doesn't seem like a terrible cost for getting unambiguous, explicit behavior.
Note that this solution does not directly resolve the observed bug that motivated this ticket. It does make the bug irrelevant for `getRestricted`, because …

[base-controller] Make `allowed{Actions,Events}` required parameters of `getRestricted`

---

packages/base-controller/src/BaseControllerV2.ts

#3949 narrows the return type of the `deriveStateFromMetadata` function from `Record<string, Json>` to `Record<keyof ControllerState, Json>`. However, the resulting changes to functions `getAnonymizedState` and `getPersistentState` weren't reflected in that PR. 
This commit fixes the return type annotations for these functions to the correct type: `Record<keyof ControllerState, Json>`.
- Closes #3962
- Follows from #3949
- **BREAKING:** Narrow the return types of functions `getAnonymizedState<ControllerState>` and `getPersistentState<ControllerState>` from `Record<string, Json>` to `Record<keyof ControllerState, Json>`. ([#3949](https://github.com/MetaMask/core/pull/3949), [#4040](https://github.com/MetaMask/core/pull/4040))

[base-controller] Narrow return types of `get{Anonymized,Persistent}State`

---

docs/contributing.md

The preview build documentation wrongly implied that the steps for using a local or preview build were different for MetaMask team members versus independent contributors. The steps are exactly the same.
Additionally, the examples that use npm have been removed. The override syntax listed was not correct (npm doesn't use the same syntax for the version specifier), and the other instructions all reference Yarn anyway so the document already doesn't make much sense for a reader only familiar with npm.
N/A
None

fix: Preview build doc corrections

---

packages/permission-controller/src/PermissionController.ts

Fixes a problem with the `SideEffectMessenger` type introduced in a recent release. The type was changed and would disallow permission specifications adding further actions and events to the messenger allowlist. This PR fixes that problem and lets permission specifications once again extend the messenger by leveraging the existing generic types.
- **Fixed**: Fix `SideEffectMessenger` type not respecting generic parameter types

Fix `SideEffectMessenger` type not respecting generic parameter types

---

packages/assets-controllers/src/NftController.ts

Removes export of a type because it is not used anywhere else
- **REMOVED**: Removed export on the `NftUpdate` type in `Nftcontroller.ts` because it is not used anywhere else.

fix: remove export of type

---

packages/assets-controllers/src/Standards/NftStandards/ERC1155/ERC1155Standard.test.ts
packages/assets-controllers/src/index.ts
packages/assets-controllers/src/token-prices-service/index.test.ts
packages/assets-controllers/src/token-prices-service/index.ts

PR to export `SUPPORTED_CHAIN_IDS` constant.
This constant is imported in extension like this:
`import { SUPPORTED_CHAIN_IDS } from '@metamask/assets-controllers/dist/token-prices-service/codefi-v2';`
Which was causing issues when trying to upgrade assets-controllers to latest. It was not able to find it.
With this change we can import it like this instead of from dist which can abstract how the code is transpiled;
`import { SUPPORTED_CHAIN_IDS } from '@metamask/assets-controllers';`
* Related to [#67890](https://github.com/MetaMask/metamask-extension/pull/23574)
- **ADDED**: Added export for const SUPPORTED_CHAIN_IDS

fix: export const

---

packages/assets-controllers/src/assetsUtil.test.ts
packages/assets-controllers/src/assetsUtil.ts

While i was testing NFT refreshing mechanism on Mobile with an Opensea collection, noticed that the tokenURI returned was the old URI,  that was because the compareNftMetadata fct was returning false while it should have returned true.
I added the TokenURI as a key to compare with.
- **FIXED**: Added tokenURI key to compareNftMetadata fct

fix: add tokenURI to compare nft data

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/simulation-api.test.ts
packages/transaction-controller/src/utils/simulation-api.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts
yarn.lock

Multiple additions to the simulation support in the `TransactionController` including:
- Export all simulation types. 
- Include error data in the `SimulationData` type including `code` and `message` if available, plus whether the error is due to the transaction being reverted in the simulation.
- Continue to trigger simulation when adding a transaction, but do not block the creation of the approval request.
- Automatically update the simulation data if the transaction parameters are changed, specifically `to`, `data` and `value`.
- Replace use of `JsonRpcProvider` with `fetch` to allow greater control when parsing error responses.
- Provide zero value gas fees in simulation requests to disable gas fee suggestions.
* Fixes [#2250](https://github.com/MetaMask/MetaMask-planning/issues/2250), …

Include errors in simulation data

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/utils/simulation-api.test.ts
packages/transaction-controller/src/utils/simulation-api.ts

Currently the networks supporting transaction simulation are hardcoded along with their associated subdomains.
This PR instead queries the supported networks dynamically using the `/networks` endpoint to automatically support new networks without requiring a new controller and client release.
Fixes [#2268](https://github.com/MetaMask/MetaMask-planning/issues/2268)
- **CHANGED**: Determine networks supporting simulation dynamically using API.

Query networks supporting simulation

---

packages/transaction-controller/src/TransactionController.ts

This PR aims to fix an issue (MMI) where custodial transactions are getting finalized without notifying the dapp.
- **FIXED**: Adds emit `{transactionMeta.id}:finished` when updating custodial transaction to `submitted` or `failed`

fix: add emit finished event for custodial transactions

---

packages/assets-controllers/package.json
packages/transaction-controller/package.json
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/transaction-type.ts
packages/user-operation-controller/src/utils/validation.test.ts
yarn.lock

Creates the `tokenMethodIncreaseAllowance` transaction type, and adds the FiatTokenV2 token to be able to parse transactions with the increaseAllowance method, since it's not part of the ERC20 standard.
* Related to [#2224](https://github.com/MetaMask/MetaMask-planning/issues/2224)
- **ADDED**: Adds support for `increaseAllowance` token method and corresponding transaction type.

Adds 'tokenMethodIncreaseAllowance'

---

packages/announcement-controller/src/AnnouncementController.test.ts
packages/announcement-controller/src/AnnouncementController.ts

Adds a method in the AnnouncementController to support the new Developer Options Settings Page → Reset State → What's New Announcements
Partially Fixes: https://github.com/MetaMask/metamask-extension/issues/23592
Blocks: https://github.com/MetaMask/metamask-extension/pull/22382
- **Feat**: Add resetIsShownStates method

feat: add AnnouncementController#resetViewed

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Fix the use of the `publishHook` by ensuring the updated transaction metadata is provided to it, rather than the initial data lacking values such as the `nonce`.
- **FIXED**: Provide updated transaction metadata to publish hook.

Fix publish hook by providing final transaction metadata

---

packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts
packages/assets-controllers/src/assetsUtil.ts
packages/controller-utils/src/constants.ts

Migrates the calls from OpenseaV2 to Reservoir.
Removes unused Opensea types and add Reservoir types.
Ideally the types are shared from NFT-API to other consuming clients rather than hardcoding them on core. We will address this in the future.
- **REMOVED**: Removed opensea map functions from assetsUtil.ts like `mapOpenSeaNftV2ToV1`,  `mapOpenSeaDetailedNftV2ToV1` and `mapOpenSeaContractV2ToV1`.
- **ADDED**: Added `NFT_API_BASE_URL` in constants.ts
- **ADDED**: Added reservoir types in NftDetectionController.ts
- **REMOVED**: Call to openseaV2 to get user nfts in NftDetectionController.ts
- **Added**: Call to reservoir to get user nfts in NftDetectionController.ts
- **REMOVED**: Removed Opensea types from NftController.ts
- **REMOVED**: Removed call Opensea to get NFT information and …

feat: reservoir migration

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/errors.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/simulation-api.test.ts
packages/transaction-controller/src/utils/simulation-api.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts

Skip the simulation of new transactions if `requireApproval` is false and therefore no user confirmation is required.
Provide error codes using new `SimulationErrorCode` enum for local simulation errors.
Remove the `isReverted` property.
Fixes [#2307](https://github.com/MetaMask/MetaMask-planning/issues/2307)
- **BREAKING**: Remove `isReverted` property from `SimulationError` type.
- **ADDED**: Add `SimulationErrorCode` enum.
- **CHANGED**: Skip simulation if `requireApproval` is `false`.
- **CHANGED**: Provide simulation error code in locally generated errors.

Skip simulation if no approval

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/src/index.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

In a [preceding PR](https://github.com/MetaMask/core/pull/4063), the SelectedNetworkController will start to keep proxy instances for all domains seen without a way to remove them when they become stale. This PR exposes the private proxies cache map as a constructor param which will enable callers to implement their own cache invalidation strategies without needing to concern the SelectedNetworkController of the implementation details themselves. This is needed because Mobile and Extension will need to follow different cache invalidation strategies.
This PR should be merged before https://github.com/MetaMask/core/pull/4063
Fixes: https://github.com/MetaMask/core/issues/4062
See: https://github.com/MetaMask/core/pull/4063
- **BREAKING**:  `SelectedNetworkController` now expects the …

Refactor: Expose `SelectedNetworkController` proxies map in the constructor params

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts
packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
tsconfig.packages.json

The SelectedNetworkController currently constructs a proxy for any domain that has permissions. Other domains have no associated proxy, so the getProviderAndBlockTracker method would throw an error.
This is problematic because we grab the network client for an origin a single time when constructing an RPC pipeline for that origin in the MetaMask extension. We don't re-create the RPC pipeline when permissions change. That means that the pipeline is setup with the wrong network client (see here for more details on this bug: https://github.com/MetaMask/metamask-extension/issues/23509 )
To resolve this problem, we can instead keep network client proxies for all origins, not just those with permissions. Origins without permissions still should not have a selected network client ID state, but …

Fix: `SelectedNetworkController` should return globally selected networkClient from `getProviderAndBlockTracker` when domain not in state

---

packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts

This PR fixes a bug on extension, where when a user imports an NFT when IPFS and display media toggles are off, then enables them, the metadata wont be refreshed.
We added a check in NftController to see if any of the toggles are on then proceed to update nft metadata.
We will update the metadata only for NFTs that are missing name/image or description.
https://github.com/MetaMask/metamask-extension/assets/10994169/c0d09b77-1cd2-495e-aec8-a4ba965ed38f
https://github.com/MetaMask/metamask-extension/assets/10994169/06e56b4f-5c1b-4402-b6e2-154daff291d5
- **ADDED**: Added a check inside `onPreferencesStateChange` to check if IPFS toggle or display media toggle is ON. If so i update the users nft metadata.
- **REMOVED**: Removed Nfts argument from `updateNftMetadata` function.

fix: fix update nft metadata when toggles off

---

package.json
packages/announcement-controller/CHANGELOG.md
packages/announcement-controller/package.json
packages/assets-controllers/package.json
packages/ens-controller/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/network-controller/CHANGELOG.md
packages/network-controller/package.json
packages/polling-controller/package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/CHANGELOG.md
packages/user-operation-controller/package.json
yarn.lock

This release includes:
- `@metamask/announcement-controller` 6.0.1 -> 6.1.0
- `@metamask/gas-fee-controller` 14.0.1 -> 15.0.0
- `@metamask/network-controller` 18.0.1 -> 18.1.0
- `@metamask/queued-request-controller` 0.6.1 -> 0.7.0
- `@metamask/selected-network-controller` 10.0.1 -> 11.0.0
- `@metamask/transaction-controller` 25.3.0 -> 26.0.0
- `@metamask/user-operation-controller` 6.0.0 -> 7.0.0

Release 133.0.0

---

packages/base-controller/src/BaseControllerV2.ts

The parameter name of the "derived state" was named `persistedState` because that function was originally written for the `getPersistedState` function, and was later moved to a separate function because the state derivation process was identical for `getAnonymizedState`.
N/A
N/A
- x ] I've updated the test suite for new or updated code as appropriate
- x ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- x ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

refactor: Fix misnamed parameter name

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
packages/transaction-controller/src/helpers/PendingTransactionTracker.ts

Change `isResubmitEnabled` constructor boolean to a callback to support dynamic support in the client based on preferences and other functionality.
Force an initial check of the pending transaction tracker during construction to ensure any previously pending transactions are updated after restarting the browser. 
- **BREAKING**: Change `pendingTransactions.isResubmitEnabled` from optional `boolean` to  optional callback.
- **CHANGED**: Check pending transactions on startup.

Support dynamic enablement of automatic resubmit

---

packages/transaction-controller/src/constants.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts

Add simulation support for:
- Wrapped ERC-20 tokens, such as WETH.
- Legacy ERC-721 tokens where none of the `Transfer` event fields are indexed, such as CryptoKitties.
In addition, verify ERC-721 balances using the `ownerOf` method rather than `balanceOf` to ensure correct balances in the token balance changes.
Fixes [#2311](https://github.com/MetaMask/MetaMask-planning/issues/2311) [#2312](https://github.com/MetaMask/MetaMask-planning/issues/2312)
- **ADDED**: Include wrapped ERC20 and legacy ERC721 tokens in simulation balance changes.
- **CHANGED**: Verify ERC-721 balances using `ownerOf` method.

Support wrapped ERC20 and legacy ERC721 in simulations

---

packages/assets-controllers/src/TokenDetectionController.ts

During account change, the token detection trigger was guarded by the `useTokenDetection` setting. But on mainnet, detection should run against the static token list even if the setting is disabled. So remove the guard.
https://github.com/MetaMask/metamask-extension/pull/23798
- **FIXED**: Token detection during account change

fix: token detection during account change

---

packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/keyring-controller/package.json
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts
packages/user-operation-controller/src/UserOperationController.test.ts
packages/user-operation-controller/src/UserOperationController.ts
packages/user-operation-controller/src/helpers/SnapSmartContractAccount.test.ts
packages/user-operation-controller/src/helpers/SnapSmartContractAccount.ts
packages/user-operation-controller/src/types.ts
packages/user-operation-controller/src/utils/chain-id.test.ts
packages/user-operation-controller/src/utils/chain-id.ts
yarn.lock

This pull request updates the dependencies in the project, including bumping snap dependencies, keyring-api, and eth-snap-keyring. It also fixes the failing tests.
Closes: https://github.com/MetaMask/accounts-planning/issues/307

Update snap and keyring api dependencies and fix tests

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/GasFeePoller.test.ts
packages/transaction-controller/src/helpers/GasFeePoller.ts
packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts

Fix the update of the `layer1GasFee` from the `GasFeePoller` by avoiding mutating a frozen object.
In addition:
- Emit a single `transaction-updated` event from the `GasFeePoller` including the gas fee estimates and layer 1 gas fee.
- Avoiding overlapping updates from the `GasFeePoller` and simulations by refactoring `#updateTransactionInternal` to require a callback rather than the entire `TransactionMeta` instance.
- Update the `getLayer1GasFee` method to use an object argument with an optional `chainId` and `networkClientId`.
- Reduce level of logging from `GasFeePoller` if gas flows are not in use.
- **BREAKING**: Change `getLayer1GasFee` arguments to a request object.
- **FIXED**: Automatic update of layer 1 gas fee after interval.

Fix layer 1 gas fee polling

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts
packages/accounts-controller/src/utils.ts

While reading the implementation of the `AccountsController`, I spotted a unsafe access in the function generating the next account ID.
It seems this code path was never really used, but there still one problem left, the account id generation was wrong when there's a "gap" in between accounts:
```
accounts = ["Account 1", "Account 2"]
`-> next account ID would be: "Account 3"
accounts = ["Account 1", "Account 3"]
`-> next account ID **SHOULD BE**: "Account 4", but current
implementation will generate "Account 3" (since we fallback to: accounts.length + 1 -> "Account 3")
```
N/A
- **FIXED**: Fixed normal accounts ID generation when there was a "index gap" between accounts.

fix(accounts): fix normal account indexing naming with index gap

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/constants.ts
packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.ts
packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.ts
packages/transaction-controller/src/gas-flows/ScrollLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/ScrollLayer1GasFeeFlow.ts

Create the abstract `OracleLayer1GasFeeFlow` to provide a template for all layer 1 fees derived through smart contract oracles.
Create the `ScrollLayer1GasFeeFlow` to provide layer 1 gas fees on scroll networks.
Fixes [#2368](https://github.com/MetaMask/MetaMask-planning/issues/2368)
- **ADDED**: Support retrieval of layer 1 gas fees on Scroll networks.

Add layer 1 gas fee flow for Scroll network

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR addresses a bug in the keyring controller where invoking addNewAccount inadvertently retrieves addresses from all keyrings, rather than exclusively from the HD keyring. This behavior leads to inconsistencies and errors when accounts from different keyring types are present. The primary symptom of this bug is the retrieval of an incorrect number of accounts, with some operations potentially resulting in an undefined address. This issue is notably impactful as it can cause the selectedAddress to be undefined in clients, leading to unexpected behavior and degraded user experience.
* Fixes #4157
- **BREAKING**: Use getAccounts on HD keyring when calling `addNewAccount` instead of `this.getAccounts` which retrieves every account.

fix!: bug 4157, use getAccounts on HD Keyring when calling addNewAccount

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR updates the logic of setSelectedAccount to reject unknown account ids. 
- **CHANGED**: Reject unknown account ids in setSelectedAccount

fix: update setSelectedAccount to throw if the id is not found

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

This PR fixes a bug where the proxies used to manage per dapp selected network connections do not stay in sync when the user toggles on or off the "Select networks for each site" preference (which turns request queueing on and off):
This PR fixes this bug by subscribing to `PreferenceController` changes and, when the "Select networks for each site" toggle is flipped repointing the proxy from the (nested) globally selected network proxy to its own independently managed proxy, and when flipped off repoint the proxy to the globally selected network proxy.
To test: pull into [this extension PR](https://github.com/MetaMask/metamask-extension/compare/ad/fix/queue-toggle-proxies?expand=1) -> you'll need to link to a local build of selected-network-controller with these commits.
- **ADD**: …

Fix: Keep proxies in sync across "Select networks for each site" toggling on/off

---

packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

`persistAllKeyrings` and `#unlockKeyrings` have been refactored to update the state in one single call, to avoid side effects to be executed in the middle of the lock or unlock operations.
`persistAllKeyrings` and `#unlockKeyrings` can now be executed once per time, since they are both behind the same mutex: this ensures that each vault read/write operation is executed in a mutually exclusive way
N.D.
- **FIXED**: State updates are executed in a single call when locking or unlocking the `KeyringController`.

[keyring-controller] Update state in single call when persisting or unlocking

---

packages/permission-controller/jest.config.js
packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/PermissionController.ts

When re-throwing validation errors in `requestPermissions()`, include original message from all well-formed errors. Also restore 100% unit test coverage.
- **ADDED**: Make permission request validation errors more informative

feat(permission-controller): Re-throw all well-formed errors

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts
packages/keyring-controller/src/constants.ts

This PR adds a check to the `persistAllKeyrings` method to avoid removing the HD Key Tree keyring.
Related to https://github.com/MetaMask/mobile-planning/issues/1507
- **CHANGED**: Add check to avoid removing HD Key Tree keyring during execution of `persistAllKeyrings`

fix: add HD keyring check to `persistAllKeyrings`

---

packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/PermissionController.ts

For certain use-cases, such as the SDK, it may be beneficial to be able to store additional metadata about permission requests. This PR adds a `metadata` property to the `requestPermission` options which is merged into the existing `metadata` object and ultimately stored in the `ApprovalController`.
- **Added**: Allow passing additional metadata during requestPermissions

feat(permission-controller): Allow passing additional metadata during requestPermissions

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

This change fixes a bug where if `getProviderAndBlockTracker` is called with a domain that 1) does not have permissions, 2) does not have a cached proxy and 3) the `useRequestQueue` preference is on, it's newly created networkProxy will not be pointed correctly. Under these conditions the network proxy for this domain should point to the NetworkController's own proxied selectedNetworkClient. 
I've added tests to ensure that all possible permutations are pointing the proxy correctly:
e.g. 
- useRequestQueue preference on + domain does not have permissions 
- useRequestQueue preference off + domain does have permissions
- useRequestQueue preference on + domain does have permissions
- etc
- **FIXED**: When `getProviderBlockTracker` is called with domain for which there is no cached …

Fix `getProviderAndBlockTracker` client selection logic

---

packages/accounts-controller/package.json
packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts
packages/assets-controllers/package.json
packages/keyring-controller/package.json
yarn.lock

This PR bumps the `@metamask/keyring-api`, `@metamask/eth-snap-keyring` and snap dependencies in the `AccountsController`
Resolves: [4135](https://github.com/MetaMask/core/issues/4135)
- **CHANGED**: Bump dependency `@metamask/keyring-api` to `^6.0.0`
- **CHANGED**: Bump dependency `@metamask/eth-snap-keyring` to `^4.0.0`
- **CHANGED**: Bump dev dependency `@metamask/snaps-controller` to `^7.0.1`
- **CHANGED**: Bump dependency `@metamask/snaps-sdk` to `^4.0.1`
- **CHANGED**: Bump dependency `@metamask/snaps-utils` to `^7.1.0`

chore(deps): bump @metamask/keyring-api to 6.0.0, @metamask/eth-snap-keyring to 4.0.0 and snap dependencies

---

package.json
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
yarn.lock

- When getProviderBlockTracker is called with domain for which there is no cached networkProxy in the domainProxyMap, if the useRequestQueue preference is off and the domain does not have permissions the newly created network proxy for this domain should be pointed at the NetworkController's own proxied selectedNetworkClient. ([#4187](https://github.com/MetaMask/core.git/pull/4187))

Release 142.0.0

---

packages/assets-controllers/src/AssetsContractController.ts
packages/assets-controllers/src/assetsUtil.ts

Adds support for erc20 token detection on 7 more networks.  After this, we match the set of networks supported by MetaMask Portfolio.
https://consensyssoftware.atlassian.net/browse/MMASSETS-207
- **CHANGED**: Token detection is now supported on cronos, celo, gnosis, fantom, polygon_zkevm, moonbeam, and moonriver.

feat: token detection on 7 more networks

---

packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

Updates limit value from 200 to 50.
- **<CHANGED>**: Changed limit parameter from 200 to 50

fix: update limit param

---

packages/approval-controller/src/ApprovalController.ts
packages/permission-controller/src/Caveat.ts
packages/permission-controller/src/Permission.ts
packages/permission-controller/src/PermissionController.ts
packages/permission-controller/src/SubjectMetadataController.ts

Prior to TypeScript@4.4, I added various TODOs about marking certain object interfaces properties as optional instead of `type | null`. Now, years later and a long time after TS4.4 shipped, I have concluded that it's not worth the trouble. The same goes for a TODO exhorting us to enable `noUncheckedIndexedAcces` in the PermissionController, which appears to be something we have to do in a monorepo-wide fashion, if the test failures it produced doing it in just one package are any indication.
None.

docs: Remove various TypeScript@4.4 TODOs

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR is an intermediate refactor needed for #4192.
Since operations are eventually rolled back, the internal method will not be able to return the last controller state, risking returning a stale one. Moreover, function returns make more sense now.
This PR needs these changes to be merged **first**:
- **BREAKING**: Change various `KeyringController` methods so they no longer return the controller state
- Changed `addNewAccount` return type to `Promise<string>` 
- Changed `addNewAccountWithoutUpdate` return type to `Promise<string>`
- Changed `createNewVaultAndKeychain` return type to `Promise<void>`
- Changed `createNewVaultAndRestore` return type to `Promise<void>`
- Changed `importAccountWithStrategy` return type to `Promise<string>`
- Changed `removeAccount` return type to …

[keyring-controller] Remove `#getMemState` returns

---

packages/gas-fee-controller/src/GasFeeController.test.ts
packages/gas-fee-controller/src/GasFeeController.ts

Fixes a bug with the GasFeeController where the globally selected state (gasFeeEstimates, estimatedGasFeeTimeBounds, gasEstimateType) is incorrectly updated regardless of if the gasFeeEstimate fetched is for the currently selected network or not
- **FIXED**: Only update `gasFeeEstimates`, `estimatedGasFeeTimeBounds`, and `gasEstimateType` when fetching gas fee estimates if they are for the currently selected network

fix GasFeeController incorrectly setting globally selected state

---

packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

This PR makes `KeyringController` operations atomic, with the addition of `#persistOrRollback`. Each of these operations will be executed mutually exclusively, and before each of them, a snapshot of the current keyrings state is kept and restored in case of errors in the operation execution.
More details on why this is needed [here](https://github.com/MetaMask/MetaMask-planning/issues/2382)
This PR needs these changes to be merged **first**:
- https://github.com/MetaMask/core/pull/4182
- https://github.com/MetaMask/core/pull/4199
* Fixes https://github.com/MetaMask/MetaMask-planning/issues/2382
- **FIXED**: All mutable operations are now atomic: each method will roll back keyring instances in case of errors

[keyring-controller] Atomic Operations

---

packages/accounts-controller/src/AccountsController.ts
packages/permission-controller/src/Caveat.test.ts
packages/permission-controller/src/Caveat.ts
packages/permission-controller/src/Permission.ts
packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/PermissionController.ts
packages/permission-controller/src/SubjectMetadataController.ts
packages/permission-controller/src/rpc-methods/getPermissions.test.ts
packages/permission-controller/src/rpc-methods/requestPermissions.test.ts
packages/permission-controller/src/rpc-methods/revokePermissions.test.ts
packages/permission-controller/src/rpc-methods/revokePermissions.ts

Replaces almost all `any` type casts with `@ts-expect-error` directives or more specific types. Of the original 81 `any` type casts in the permission controller and its tests, only 3 remain. No behavioral changes.
None.

refactor(permission-controller): Clean up use of `any`

---

packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts
packages/keyring-controller/src/constants.ts

Part of `KeyringController` responsibilies is ensuring each operation is [mutually exclusive](https://github.com/MetaMask/core/pull/4182) and [atomic](https://github.com/MetaMask/core/pull/4192), updating keyring instances and the vault (or rolling them back) in the same mutex lock.
However, the ability of clients to have direct access to a keyring instance represents a loophole, as with the current implementation they don’t have to comply with the rules enforced by the controller: we should provide a way for clients to interact with a keyring instance through safeguards provided by KeyringController.
The current behavior is this one:
1. Client obtains a keyring instance through `getKeyringForAccount`
2. Client interacts with the instance
3. Client calls `persistAllKeyrings` 
We should, …

[keyring-controller] Add `withKeyring` method

---

packages/preferences-controller/src/index.ts

- **<ADDED>**: export of ETHERSCAN_SUPPORTED_CHAIN_IDS for clients

chore: Export ETHERSCAN_SUPPORTED_CHAIN_IDS constant from Preferences Controller

---

packages/assets-controllers/src/TokensController.test.ts
packages/base-controller/tests/helpers.ts
packages/base-controller/tsconfig.json
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/helpers.ts

We want to change TokensController so that it relies on `selectedNetworkClientId` instead of `providerConfig` to know which chain is selected, and this will require updating the tests to match. However, the TokensController tests are written in such a way that makes updating them difficult.
This commit rewrites each test to use the `withController` pattern that we've adopted for other controller tests. It also removes usage of `beforeEach` so that each test is isolated.
Note that this commit isn't a complete refactor of the tests; there is more work we could do to make them easier to maintain, such as removing a reliance on ApprovalController and using `describe` to group tests by method. This step can be done later.
In addition, this commit also adds some NetworkController-related and …

Refactor TokensController tests

---

packages/accounts-controller/src/AccountsController.ts
packages/accounts-controller/src/utils.ts

While discussing the logic around `#listNormalAccounts` for non-0x addresses, I found out this function could be rewritten to do the filtering during the accounts listing rather than creating the full list of accounts and then filter out non-normal accounts afterward.
Doing it this way also prevent from calling `getUUIDOptionsFromAddressOfNormalAccount` for non-0x addresses, which is probably better than this solution:
- https://github.com/MetaMask/core/pull/4243
- https://github.com/MetaMask/core/pull/4243
None

refactor(accounts-controller): remove extra filter for normal accounts

---

packages/keyring-controller/src/KeyringController.ts

This PR apply patch code from this [PR](https://github.com/MetaMask/metamask-extension/pull/23903) to keyringController  to fix the issue found in this [issue](https://github.com/MetaMask/metamask-extension/issues/23804)
[PR 23903](https://github.com/MetaMask/metamask-extension/pull/23903)
Fix [Issue 23804](https://github.com/MetaMask/metamask-extension/issues/23804)
- **Fixed**: Fix creation of new QR keyrings
- Previously the QR keyring would get initialized with invalid state when created for the first time

feat: add patch code from PR 23903 to keyringController.

---

packages/assets-controllers/src/token-service.test.ts
packages/assets-controllers/src/token-service.ts

Lower occurenceFloor for linea mainnet to only 1 list instead of 3.
Add a filter for lineaTeam aggregator when we fetch token list from token-api when the user is on linea-mainnet.
- **CHANGED**: Changed query parameter occurenceFloor in getTokensURL to equal 1 for linea-mainnet and default to 3 for other networks.
- **Added**: Added a filter for `lineaTeam` aggregator on the returned list by `fetchTokenListByChainId`  when the user is on linea mainnet.

fix: lower occurenceFloor for linea mainnet to 1

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

Reverts MetaMask/core#4265
This is being reverted so that we can fix a publishing error

Revert "Release 149.0.0"

---

packages/profile-sync-controller/package.json

The version of the `@metamask/profile-sync-controller` package has been updated to `0.0.0`, which is what our publishing automation expects of all unpublished public packages.
The current version is `0.1.0`, which caused problems for our most recent release, requiring a rollback. It broke publishing because our publishing scripts tried to find version `0.1.0` in the package changelog but were unable to.
This should have been caught by our linter, but it wasn't due to a deficiency in the `@metamask/auto-changelog` validation command (it doesn't validate that the current release exists). This problem has been documented here: https://github.com/MetaMask/auto-changelog/issues/192
Unblocks https://github.com/MetaMask/core/pull/4272
N/A

fix: Fix `profile-sync-controller` version

---

packages/keyring-controller/package.json
yarn.lock

- `deps(keyring-controller)`: Bump `@keystonehq/metamask-airgapped-keyring` from `^0.13.1` to `^0.14.1`
- Updates `@metamask/obs-store` from v7 to v9
- Removes dependency on `readable-stream` `2.x`.
- `devDeps(keyring-controller)`: Bump `@keystonehq/bc-ur-registry-eth` from `^0.9.0` to `^0.19.0` 
- Deduplicates from 2 instances of the package to 1 
- Removes instance of devDependency on `ethereumjs-util` 
- https://github.com/KeystoneHQ/keystone-airgaped-base/pull/140
- https://github.com/KeystoneHQ/keystone-airgaped-base/pull/143
- **FIXED**: Bump `@keystonehq/metamask-airgapped-keyring` from `^0.13.1` to `^0.14.1`

deps(keyring-controller): Bump @keystonehq/metamask-airgapped-keyring to ^0.14.1

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts
packages/keyring-controller/src/constants.ts

This PR adds `changePassword` as a new method for KeyringController, useful for changing the current password.
This addition aims to make it easier for clients to update the password, which is something that they currently need to [implement themself](https://github.com/MetaMask/metamask-mobile/blob/9cb6e741b7f48b5f75855687f0c6f19152d8ef05/app/core/Vault.js#L63) 
- **ADDED**: Added `changePassword` method
- This method can be used to change the password used to encrypt the vault

[keyring-controller]: Add `changePassword` method

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Changed `approveTransaction` to use `#updateTransactionInternal`.
Addresses https://github.com/MetaMask/metamask-extension/issues/24183 – Manually verified in extension.
@matthewwalsh0 observed:
The implementation of approveTransaction is throwing away the raw signed transaction that signTransaction was adding to the metadata state by holding onto a stale version of the tx metadata.
```typescript
function approveTransaction(id) {
const updatedMetadata = ...
// signTransaction calls updateTransaction
// So any existing references to the txMetadata will be stale.
this.signTransaction(updatedMetadata)
updateTransaction(updatedMetadata) // BUG: updatedMetadata is now stale.
//...
```
Long-term @matthewwalsh0 recommends replaying updateTransaction with the more modern updateTransactionInternal …

fix: transaction-controller – approveTransaction should not throw away raw signed transaction

---

package.json
packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/keyring-controller/package.json
yarn.lock

This pull request updates the following dependencies
- `@metamask/keyring-api` to `^6.1.1`, 
- `@metamask/eth-snap-keyring` to `^4.1.1` 
- `@metamask/snaps-utils` to `^7.4.0`
- `@metamask/snaps-controllers` to `^8.1.1`

chore(deps): bump dependencies 

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in NftDetectionController to get the currently selected chain, but `selectedNetworkClientId` can be used instead. This commit makes that transition so that we can fully drop `providerConfig`.
(Updates to changelog in PR.)

NftDetectionController: providerConfig -> selectedNetworkClientId

---

docs/contributing.md

@Gudahtt [wrote](https://consensys.slack.com/archives/C01V1L10W2E/p1715878493772209?thread_ts=1715869562.944709&cid=C01V1L10W2E):
> there is a missing step, you should run yarn constraints --fix and yarn to update package versions across the repository, and then to update the lockfile.
>
> Unfortunately I don't think this step is documented at the moment. It was an unanticipated consequence of some recent-ish changes to the release tool and to how the monorepo is structured. We have plans to automate this step as well.

chore: update docs/contributing.md with yarn constraints --fix

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in TokenRatesController to get the currently selected chain and ticker, but `selectedNetworkClientId` can be used instead to get the currently selected network client, and then the appropriate information can be read from that object. This commit makes that transition so that we can fully drop `providerConfig`.
(Included in the PR.)

TokenRatesController: providerConfig -> selectedNetworkClientId

---

package.json
packages/json-rpc-engine/package.json
packages/keyring-controller/package.json
yarn.lock

This bumps ranges for `@lavamoat/allow-scripts` to latest.
Effectively no-op as the latest version is already resolved in `yarn.lock`.

chore(devDependencies): @lavamoat/allow-scripts@^3.0.2>^3.0.4

---

packages/assets-controllers/package.json
packages/keyring-controller/package.json
packages/name-controller/package.json
packages/network-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Update `async-mutex` to latest.
[Changelog](https://github.com/DirtyHairy/async-mutex/blob/master/CHANGELOG.md)
- **FIXED**: Update `async-mutex` from `^0.2.6` to `^0.5.0`
- **FIXED**: Update `async-mutex` from `^0.2.6` to `^0.5.0`
- **FIXED**: Update `async-mutex` from `^0.2.6` to `^0.5.0`
- **FIXED**: Update `async-mutex` from `^0.2.6` to `^0.5.0`
- **FIXED**: Update `async-mutex` from `^0.2.6` to `^0.5.0`

deps: async-mutex@^0.2.6->^0.5.0

---

packages/assets-controllers/src/index.ts

These types were mistakenly exported in a previous commit when converting NftDetectionController to BaseController v2. They can still be exports in `NftDetectionController.ts`, but just not be exports from the perspective of the whole `assets-controllers` package. This commit takes these exports away by replacing the `*` export in `index.ts` with explicit names and ensures not to include the two aforementioned types.
This is a followup to https://github.com/MetaMask/core/pull/4312.
The changelog in https://github.com/MetaMask/core/pull/4342 already does not mention the existence of these two exports, so nothing should need to be done.

assets-controllers: Remove AllowedActions, AllowedEvents

---

packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts

fix the case if market data are not available for given token.
- **<FIXED>** : catch the case when data are not available for given token

fix: fix market data of assets controller if no data

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

The KeyringController comes with two built-in keyrings: Simple and HD. Unfortunately it's impossible to overwrite these because when we build a new keyring, we look for the first keyring builder in the list that matches the type we want to build, and the built-in keyrings are always first.
The order has been switched so that built-in keyrings come second, after custom keyring builders. This allows them to be overwritten.
This makes it possible to test behavior that is specific to simple or HD keyrings. This is something that I wanted to do in the mobile repository.
N/A
- Add support for overwriting built-in keyring builders for the Simple and HD keyring.

feat: Allow overwriting built-in keyring builders

---

packages/ens-controller/src/EnsController.test.ts
packages/ens-controller/src/EnsController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in EnsController to get the currently selected chain, but `selectedNetworkClientId` can be used instead. This commit makes that transition so that we can fully drop `providerConfig`.
(There should be no functional changes, so no changelog updates are needed.)

EnsController: providerConfig -> selectedNetworkClientId

---

packages/assets-controllers/src/TokensController.test.ts
packages/assets-controllers/src/TokensController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in TokensController to get the currently selected chain, but `selectedNetworkClientId` can be used instead. This commit makes that transition so that we can fully drop `providerConfig`.
(There should be no functional changes, so no changelog updates are needed.)

TokensController: providerConfig -> selectedNetworkClientId

---

packages/gas-fee-controller/src/GasFeeController.test.ts
packages/gas-fee-controller/src/GasFeeController.ts

The `providerConfig` state property is being removed from NetworkController. Currently this property is used in GasFeeController to get the currently selected chain, but `selectedNetworkClientId` can be used instead. This commit makes that transition so that we can fully drop `providerConfig`.
(There should be no functional changes, so no changelog updates are needed.)

GasFeeController: providerConfig -> selectedNetworkClientId

---

packages/assets-controllers/src/NftDetectionController.test.ts
packages/network-controller/tests/NetworkController.test.ts
packages/network-controller/tests/helpers.ts
packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
tests/fake-block-tracker.ts
yarn.lock

`transaction-controller` constructor takes a `provider` and a `blockTracker`. In tests, there is mocking of these. A `BlockTracker` has its own `provider` and while in reality the `blockTracker.provider == provider`, it appears inconsistent in tests where a test may use both a mocked and a "real" provider instance at the same time.
This aims at making this more transparent by making the `provider` parameter of `FakeBlockTracker` mandatory.

chore(test): Refactor FakeBlockTracker provider injection

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

Fixes a bug with `SelectedNetworkController` where it incorrectly sets the networkClientId for a newly permitted domain when the useRequestQueue flag is set to false.
See: https://github.com/MetaMask/metamask-extension/pull/25046
- **FIXED**: No longer sets the networkClientId for a newly permitted domain unless the `useRequestQueuePreference` flag is true

fix: `SelectedNetworkController` permission state change handler

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR fixes the issue where getAccountByAddress doesn't retrieve non evm accounts.
- **FIXED**: `getAccountByAddress` now also consider non-EVM accounts.

fix: use listMultichainAccount in getAccountByAddress

---

packages/assets-controllers/src/token-prices-service/codefi-v2.ts

The price API added support for mantle network.  Adding it here too.
https://github.com/consensys-vertical-apps/va-mmcx-price-api/pull/302
- **ADDED**: Token price API support for mantle network

feat: add mantle to price api supported chains

---

packages/assets-controllers/src/TokenRatesController.ts

When adding market data for tokens in https://github.com/MetaMask/core/pull/4206, it also changed the token addresses to be lowercased instead of checksum.  This PR moves it back to the checksum format, since some places on the client expected it.
- **CHANGED**: Token rates controller uses checksum instead of lowercase format for token addresses

[TokenRatesController] - Keep addresses in checksum format

---

packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

This PR updates removes `selectedAddress` and uses the controller messenger to get InternalAccounts in the Nft Controllers
Fixes https://github.com/MetaMask/accounts-planning/issues/381
- **BREAKING**: `NftController` constructor argument `selectedAddress` has been removed.
- **BREAKING**: `NftController` now requires `AccountsControlelr:get{Account,SelectedAccount}` messenger actions.
- **BREAKING**: `NftController` now requires `AccountsController:selectedEvmAccountChange` event.
- **BREAKING**: `NftDetectionController` now requires `AccountsControlelr:getSelectedAccount` messenger actions.

refactor: update Nft Controllers to use selectedAccountId instead of selectedAddress

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

Our previous SelectedNetworkController fix that [added a guard to permission state changes](https://github.com/MetaMask/core/pull/4368) was not sufficient. This PR properly addresses the underlying issue of setting networkClientId for domains when the `useRequestQueuePreference` flag is false by moving the guard into the `setNetworkClientId()` method itself
* Fixes: https://github.com/MetaMask/metamask-extension/issues/25097
- **FIXED**: `setNetworkClientId()` will now result in a noop if `useRequestQueuePreference` is false

fix: add `SelectedNetworkController` setNetworkClientId useRequestQueuePreference guard

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR remove the setting of a newly added account as the last selected account. 
Related: https://github.com/MetaMask/metamask-mobile/pull/9764
- **CHANGED**: Newly added account is no longer set as the last selected account.

fix: remove setting new account as the last selected account

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts
packages/network-controller/CHANGELOG.md
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
packages/transaction-controller/src/TransactionController.test.ts

Historically, the `providerConfig` property in NetworkController has been used to track the currently selected network as well as provide access to information about that network. The selected network is now tracked via `selectedNetworkClientId`, and information about that network can be retrieved by looking at the `networkConfigurations` property or the `configuration` property on the NetworkClient interface. This means that we no longer need `providerConfig` and we can remove this redundant state.
Fixes #4185.
(Updated in PR)

Remove providerConfig from NetworkController

---

packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.ts

The existing `methodsWithConfirmation` array param is not sufficient for determining if a method will cause a confirmation to be presented to the user or not because some methods such as `eth_requestAccounts` may only cause a prompt in some scenarios but not others.
This PR replaces the array params used in the QueuedRequestController and its middleware to be callbacks that accept the entire request object instead.
See: https://github.com/MetaMask/metamask-extension/pull/25310
- **BREAKING**: `QueuedRequestController` constructor no longer accepts the `methodsRequiringNetworkSwitch` array param. It's now replaced with the `shouldRequestSwitchNetwork` function param which should return true when a request requires the globally selected network to match that of the dapp.
- **BREAKING**: …

feat: change `queued-request-controller` methods array params to callbacks

---

packages/accounts-controller/package.json

This PR moves `@metamask/keyring-controller` to dependency from devDependency in `@metamask/accounts-controller`
- **CHANGED**: move `@metamask/keyring-controller` from `devDependencies` to `dependencies`

fix: move `@metamask/keyring-controller` to dependency in `@metamask/accounts-controller`

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR adds a new action, `listMultichainAccounts` to `@metamask/accounts-controller`
- **ADDED**: Adds `listMultichainAccounts` action

feat: add listMultichainAccounts action

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/notification-services-controller/src/NotificationServicesController/index.ts
packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
packages/notification-services-controller/src/NotificationServicesPushController/index.ts
packages/profile-sync-controller/src/controllers/authentication/index.ts
packages/profile-sync-controller/src/controllers/user-storage/encryption/index.ts
packages/profile-sync-controller/src/controllers/user-storage/index.ts
packages/profile-sync-controller/src/sdk/encryption.ts

it seems we were inconsistent and forgot to correctly handle default exports and controller exports

refactor: update notification package exports

---

packages/notification-services-controller/package.json
yarn.lock

This was removed as it was blocking publishing of profile sync controller. Adding here so it unblocks the next release for this controller: https://github.com/MetaMask/core/pull/4438

refactor: add back profile sync dependency

---

packages/transaction-controller/src/types.ts

Met with @matthewwalsh0 who took the time to explain each status.

docs: document TransactionStatus enum

---

scripts/create-package/utils.test.ts
scripts/create-package/utils.ts

The `create-package` tool automatically updates `tsconfig.build.json` with an entry for the new package, but this entry is invalid. It should reference the package-level `tsconfig.build.json` file, but instead it just references the package directory (so the `tsconfig.json` file is used instead.
This mistake resulted in very confusing build errors when I recently created a new package.
This has been corrected, and tests have been updated accordingly.
None
None

fix: Fix `create-package` changes to `tsconfig.build.json`

---

README.md
scripts/update-readme-content.ts

The `update-readme-content` script will automatically update the package graph in the README. This script was omitting the first package in the list, the `accounts-controller` package.
The script has been updated to stop removing this package, and the script was run to update the current README (one dependency between core packages was missing).
It's unclear why the first line was removed in the first place. It's possible that an earlier version of Yarn had one additional line in the output.
None
None

fix: Fix `update-readme-content` script

---

scripts/create-package/package-template/package.json

The package template used by the `create-package` tool has been updated to fix two constraint violations. These failures appeared on a package created with this tool.
None
None

fix: Update `create-package` package template

---

jest.config.scripts.js
scripts/create-package/index.test.ts
tests/scripts-setup.ts

The test for `create-package` was causing the test command to fail with a non-zero exit code even when tests passed. This was because the code under test was setting `process.exitCode`, and this causes Jest to exit with that same code.
The test was updated to mock `process` to ensure that the real `process.exitCode` was not changed. Additionally, an `afterEach` hook has been added for all script tests that will catch such issues in the future.
Alternative to #4415 
N/A

fix: Fix `create-package` tests that cause test command to fail

---

packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts

Currently when a request is queued, it does not cause the existing confirmation window to be focused. This is because queued requests are withheld from the `ApprovalController` which is responsible for showing batched/scrubbable confirmations to the user. Since the `ApprovalController` never actually receives queued requests until they are ready to be shown to the user, it becomes the responsibility of the `QueuedRequestController` to determine when the confirmation window must be focused because a new confirmation has been enqueued.
This PR adds a new callback/hook to the `QueuedRequestController`, enabling it to trigger the notification window receiving focus.
Fixes: https://github.com/MetaMask/metamask-extension/issues/25397
- **BREAKING**: `QueuedRequestController` constructor params …

feat: Focus approval request UI when a request is queued

---

packages/gas-fee-controller/src/GasFeeController.test.ts

Commit 2b1841c introduced [unnecessary changes to `GasFeeController.test.ts`](https://github.com/MetaMask/core/commit/2b1841c#diff-46b4165a6fef6c662829473a7ae3dd5c12454ca7ea811b539c0e88dc464f7e3b), complicating the process of rebasing and merging subsequent changes to this file.
To see the net diffs to `GasFeeController.test.ts` in this branch, you can compare that file to 2b1841c's parent commit, ca683e8:
```bash
git diff ca683e8...djb/gas-fee-tests packages/gas-fee-controller/src/GasFeeController.test.ts
```

chore: reduce diffs to GasFeeController.test.ts introduced by 2b1841c

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This pull request enhances the robustness of our onboarding process by addressing an edge case where selectedAccount is undefined because there aren't any accounts. Specifically, it ensures that the `getSelectedMultichainAccount` function can be safely called during onboarding, even if the selectedAccount has not been set. 
- **FIXED**: Fixed an edge case where selectedAccount could be undefined, ensuring getSelectedMultichainAccount can be safely invoked during the onboarding phase.

fix: handle edge case of undefined accountId during onboarding for getSelectedMultichainAccount

---

packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

Reverts MetaMask/core#4469
We need to redo this release because the version was not set on the `package.json` and did not go out 🤦🏾 , apologies!

Revert "Release/168.0.0"

---

scripts/prepare-preview-builds.jq

These steps handled updating `workspace:` references, but we don't use those anymore (since #1623).
Related to #1623
None

chore: Remove unnecessary steps from prepare preview builds script

---

packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts

This is for mobile integration support. Allows developers to provide an async metametrics ID (if this needs to be computed async).
- **CHANGED**: `getMetaMetricsId` interface to support async.

refactor: AuthenticationController - Add Async MetaMetrics Id support

---

packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
packages/profile-sync-controller/src/controllers/authentication/services.test.ts
packages/profile-sync-controller/src/controllers/authentication/services.ts

mobile uses a different OIDC than extension, which generates different access tokens.
- **Added**: AuthenticationController - platform field when logging in
- **Added**: AuthenticationController - metametrics validation check on constructor

refactor: Authentication Controller - add mobile OIDC support

---

docs/contributing.md
scripts/create-package/cli.ts
scripts/create-package/commands.ts

Fixes a typo in `./contributing.md`.

docs: Fix typos contributing.md

---

packages/assets-controllers/src/NftController.test.ts
packages/assets-controllers/src/NftController.ts

We encountered cases where tokenURI we fetched from the contract is an encoded image:
`data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaW5ZTWluIG1lZXQiIHZpZXdCb3g9IjAgMCAzNTAgMzUwIj48c3R5bGU+LmJhc2UgeyBmaWxsOiBibGFjazsgZm9udC1mYW1pbHk6IHNlcmlmOyBmb250LXNpemU6IDE0cHg7fTwvc3R5bGU+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0id2hpdGUiIHJ5PSI0MCIgcng9IjQwIiBzdHlsZT0ic3Ryb2tlOiNGRjJGMDA7IHN0cm9rZS13aWR0aDo1OyBvcGFjaXR5OjAuOSIgLz48dGV4dCB4PSI1MCUiIHk9IjIwJSIgY2xhc3M9ImJhc2UiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkV4YW1wbGUgTkZUPC90ZXh0Pjx0ZXh0IHg9IjUwJSIgeT0iMzAlIiBjbGFzcz0iYmFzZSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG9rZW4gSUQ6IDM8L3RleHQ+PHRleHQgeD0iMS4yJSIgeT0iOTAlIiBjbGF …

fix: add support for tokenURI encoded images

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR fixes the following:
1. Emits `selectedAccountChange` for initial account
2. Updates `lastSelected` for initial account
3. Uses `listMultichainAccounts` instead of `listAccounts` for multichain methods
Fixes https://github.com/MetaMask/accounts-planning/issues/507
- **FIXED**: Emits `selectedAccountChange` and updates last selected for initial account.
- **FIXED**: Uses `listMultichainAccounts` instead of `listAccounts` for multichain methods

fix: use `listMultichainAccounts` and set `lastSelected` for initial account

---

packages/network-controller/src/create-auto-managed-network-client.test.ts
packages/network-controller/tests/NetworkController.test.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

After updating the [`SafeEventEmitterProvider` to support EIP-1193](https://github.com/MetaMask/core/issues/4095), I have made the following changes:
- Deprecated the use of `sendAsync` and replaced it with the `request` method.
- Updated instances in the `core` repository:
- `NetworkController` tests
- Modified areas where we previously expected the provider returned by NetworkController to have a `sendAsync` method. These now use the `request` method with the correct method signature:
- `SelectedNetworkController` tests
- `createAutoManagedNetworkClient` tests
* Fixes #4100

Adapt to eip 1193 provider changes

---

packages/message-manager/src/AbstractMessageManager.ts

Adds a type annotation for the `EventEmitter` in `AbstractMessageMessenger`.
Without this, TypeScript would infer `EventEmitter` to be generic and break types in packages consuming this package.
```
hub: EventEmitter<[never]>;
```
Following this change, the EventEmitter is no longer inferred as generic.
```
hub: EventEmitter;
```
- **Fixed**: Fix `EventEmitter` inferred type

Add type annotation to `EventEmitter`

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

The tests for `createNewVaultAndKeychain` have been improved. Many of them did not call the function-under-test at all, or they called it in the wrong circumstances.
The inline comment for the function was updated to be more accurate. It implied that an existing vault would be wiped out, but that's not necessarily true.
N/A
None

chore(keyring-controller): Improve `createNewVaultAndKeychain` tests and docs

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

- Currently, when a user locks the app and then resets their password, they are not able to log in wth their new password. 
- This is because the encryption key was generated with the old password and not cleared.
- The solve this we will remove the encryption key from state when the user locks the wallet as well as when `#createNewVaultWithKeyring` is called.
- This allows for a new encryption key to be generated with the new password when the user logs in again and `submitPassword` is called.
* Fixes https://github.com/MetaMask/metamask-extension/issues/25696
* Moves path from [this PR](https://github.com/MetaMask/metamask-extension/pull/25753) into the KeyringController
- **FIXED**: Reset encryption key when wallet is locked or when new vault is created to ensure that encryption key is …

fix: clear encryption salt and key

---

packages/assets-controllers/src/NftController.ts
packages/assets-controllers/src/NftDetectionController.ts

Added optional types on the `NftMetadata` type.
- **ADDED**: Added optional `topBid` type in `NftMetadata` type
- **ADDED**: Added optional `floorAsk` in `TokenCollection` type
- **FIXED**:  Fixed type. attributes in NftMetadata to be `Attributes[]`

fix: fix types

---

packages/profile-sync-controller/package.json

This change fixes build errors on the extension that the ethers dependency introduced.
We were not aware of these build errors before because this package has not been used yet in the extension (but migration is in progress!).
Ethers is eventually only needed as a devDependency so I'm moving it here.
- **CHANGED**: Switch ethers to a devDependency

Switch ethers to a devDependency

---

packages/permission-controller/.eslintrc.js
packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/PermissionController.ts
packages/permission-controller/src/SubjectMetadataController.ts
packages/permission-controller/src/errors.ts
packages/permission-controller/src/rpc-methods/getPermissions.test.ts
packages/permission-controller/src/rpc-methods/getPermissions.ts
packages/permission-controller/src/rpc-methods/requestPermissions.test.ts
packages/permission-controller/src/rpc-methods/requestPermissions.ts
packages/permission-controller/src/rpc-methods/revokePermissions.test.ts
packages/permission-controller/src/rpc-methods/revokePermissions.ts
packages/permission-controller/src/utils.ts

Fixes various `@typescript-eslint` violations in the permission controller. Due to the prevalence of RPC method names as object literal keys in a couple of files, an `.eslintrc.js` has been added to the permission controller workspace to accommodate this exception to our naming convention.
n/a
- **BREAKING**: Rename enum property names to follow PascalCase instead of camelCase
- The affected enums are:
- `CaveatMutatorOperations`
- `MethodNames`

refactor(permission-controller)!: Fix various lint rule violations

---

packages/profile-sync-controller/package.json
packages/profile-sync-controller/src/controllers/authentication/auth-snap-requests.ts
yarn.lock

Removed NodeJs dependency that was breaking the SDK usage on the client

feat: removed node dependancy from profile-sync-sdk

---

packages/permission-controller/src/rpc-methods/getPermissions.test.ts
packages/permission-controller/src/rpc-methods/requestPermissions.test.ts
packages/permission-controller/src/rpc-methods/revokePermissions.test.ts

There are some `permission-controller` tests which attempt to push an async middleware function onto an engine. Although this works in practice, `@typescript-eslint` balks at this, because the type for `JsonRpcEngine.push` says it takes a `JsonRpcMiddleware`, and a `JsonRpcMiddleware` has a return type of `void`, not `Promise<void>`. We could change that return type to `void | Promise<void>` but that would cause other changes we may not want to make. So this commit merely ignores the lint violations. This should be safe because `JsonRpcEngine` doesn't await middleware anyway.
Interestingly, the lint violations caused by this discrepancy only appear locally and not on CI. I am not sure why this is.
Also see: https://github.com/MetaMask/core/pull/4521
(No consumer-facing changes to log)

Fix permission-controller lint violations

---

packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-siwe.ts
packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
packages/profile-sync-controller/src/sdk/utils/validate-login-response.test.ts
packages/profile-sync-controller/src/sdk/utils/validate-login-response.ts

Profile Syncing. Adds login response validation from the developer/users storage medium.
The user could lie and pass in an invalid login response, so this makes sure that there is some validation around the response shape.
NOTE - we can improve this in the future by adding a runtime parser/validator like Zod. But this is out of scope and we can add in a separate PR.
[NOTIFY-881](https://consensyssoftware.atlassian.net/browse/NOTIFY-881)
- **ADDED**: Validation around the LoginResponse shape.

refactor: add login response validation

---

packages/accounts-controller/src/AccountsController.ts
packages/assets-controllers/src/NftDetectionController.test.ts

For some reason, two lint violations show up on my computer when running `yarn lint:eslint`. I have attempted to remove `node_modules`, remove all `dist` directories, remove `.eslintcache`, run `yarn cache clear`, etc. to no avail. I think an ultimate fix here may be to upgrade ESLint packages but that would be a larger change, so as egregious as it is, this commit skirts around the issue by adding some ignore lines.
Intermittent lint violations have been a problem for a long time. Also see #4540.
(N/A)

Fix lint issues

---

packages/notification-services-controller/src/NotificationServicesController/ui/constants.ts

This is so we can easily reuse these block explorers for all platforms that consume notifications. We may start moving more shared logic to shared libraries for this same reason.
https://consensyssoftware.atlassian.net/browse/NOTIFY-941
- **ADDED**: New constant for the block explorers for chains we support notifications for.

feat: notification-services-controller - add shared notification block explorer domains

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/utils/history.test.ts
packages/transaction-controller/src/utils/history.ts

The TransactionController has been updated to compress transaction history if it exceeds the max transaction history size, which for now has been set to 100. Each time a new entry is added to a transaction history already at max size, we merge two entries to make room for the new one.
Note that we never compress entries used for display in the transaction activity log, because compressing those entries might hide events that we want to display. If there are no non-displayed entries to compress, history is allowed to exceed the max size.
This is a temporary solution to prevent unbounded growth of the transaction history. While technically it is still unbounded at this level because we don't strictly limit displayed history entries, we don't know of any cases where displayed entries can be …

fix: Compress transaction history upon update

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

Currently, deleting a network configuration which is also the current selected network will corrupt the state, since the selected ID will not point to any valid config.
With this PR, `removeNetworkConfiguration` throws an error if the caller tries to remove the selected network.
* Fixes #4563 
- **FIXED**: Selected network client configuration cannot be removed

fix: throw error when removing selected network

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR adds a new `updateAccountMetadata` method/action for the `AccountsController`.
This method will be needed for the Account syncing feature (from @MetaMask/notifications ), but can also come handy in the future if / when we decide to expand the contents of the metadata object for new features.
On the account syncing side, we're still deciding if we're going to manage conflicting names resolution, but in either scenario, this new `updateAccountMetadata` method is needed.
Scenario 1: we don't manage conflicting names
- We'll add a new `lastUpdated` metadata key to the `InternalAccount` type from `@metamask/keyring-api`
- We'll read this key when syncing accounts, and act accordingly (replace account name OR decide it's the SOT and keep the account name)
- If we replace the account …

feat: add new method `updateAccountMetadata`

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/notification-services-controller/src/NotificationServicesController/services/onchain-notifications.ts
packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/on-chain-notification.ts
packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
packages/notification-services-controller/src/NotificationServicesPushController/services/push/push-web.ts
packages/notification-services-controller/src/shared/to-raw-notification.ts

There were a set of additional extension fixes that also need to be ported over to the shared libraries.
We are actively working on replacing the extension controllers with the shared libraries (this way we don't need to do this weird back and forth syncing).
N/A
- **ADDED**: New events when notifications list is updated or when notifications are marked as read.
- **ADDED**: shared function `toRawOnChainNotification` that is used to polyfill and complete raw on chain notifications (before they get processed).
- **FIXED**: update push notifications to correctly use polyfilled/complete raw notifications.
- **ADDED**: new type `UnprocessedOnChainRawNotification` to signify the actual raw data we receive from servers.

feat: update notifications controllers from extension fixes.

---

packages/assets-controllers/src/RatesController/RatesController.test.ts
packages/assets-controllers/src/RatesController/RatesController.ts

We missed to rename that field in that PR: https://github.com/MetaMask/core/pull/4242
N/A
- FIXED: Fix `RatesController.setCryptocurrencyList`
- It was not using the correct field when updating the internal state (`fromCurrencies` -> `cryptocurrencies`)

fix: fix RatesController.setCryptoCurrencyList invalid internal field

---

packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts

Redirects the native currency $OMNI to the correct token price
- Wrong: https://www.cryptocompare.com/coins/omni
- Correct: https://www.cryptocompare.com/coins/omninet
- **FIXED**: Fetch correct price for the $OMNI native currency

fix: fetch correct price for $OMNI

---

packages/composable-controller/src/ComposableController.ts

[DO-NOT-MERGE] `ComposableController` sanity check

---

packages/accounts-controller/src/AccountsController.ts
packages/accounts-controller/src/index.ts

This PR fixes the `updateAccountMetadata` action type name, and exports it correctly.
- **FIXED**: `AccountsControllerUpdateAccountMetadataAction` type name
- **ADDED**: `AccountsControllerUpdateAccountMetadataAction` export

fix: updateAccountMetadata action type name and export

---

packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/chain-controller/package.json
packages/keyring-controller/package.json
packages/transaction-controller/package.json
yarn.lock

This PR bumps the `@metamask/keyring-api` to version `8.1.0` in every core package that depends on it.
- **CHANGED**: bump `@metamask/keyring-api` to version `8.1.0`
- **CHANGED**: bump `@metamask/keyring-api` to version `8.1.0`
- **CHANGED**: bump `@metamask/keyring-api` to version `8.1.0`
- **CHANGED**: bump `@metamask/keyring-api` to version `8.1.0`
- **CHANGED**: bump `@metamask/keyring-api` to version `8.1.0`

chore: bump `@metamask/keyring-api` to version `8.1.0`

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockStorage.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts

this is a temp fix so that mobile does not compute these fixtures are runtime. we do need to support multiple exports to ensure that these are not called.
https://consensyssoftware.atlassian.net/browse/NOTIFY-958
- **CHANGED**: profile sync fixture mocks to be evaluated lazily (by making them functions)
- **CHANGED**: Update notification services controller event type names.

fix: profile-sync-controller - make fixture constants lazy

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
yarn.lock

Reverts https://github.com/MetaMask/core/pull/4597/files
We need to redo this release since I missed some CI config/naming and this did not go out 🤦🏾 , apologies!

Revert "Release/182.0.0"

---

packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
yarn.lock

Fix the `TransactionController` integration tests with version `6.0.0` of `@metamask/nonce-tracker`.
This version of the nonce tracker constructs a new `Web3Provider` instance every time a `eth_getTransactionCount` call is required, this is needed in order to support the proxy provider which can dynamically point to different networks.
This `Web3Provider` extends the `JsonRpcProvider` whose constructor has the side effect of creating a timeout to determine the chain ID, if not provided in the constructor. When calling `getTransactionCount` on this provider, it first awaits the network being identified as a result of the timeout.
https://github.com/ethers-io/ethers.js/blob/v5.7.2/packages/providers/src.ts/json-rpc-provider.ts#L416 …

test: fix transaction controller integration tests with nonce tracker 6

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/validation.test.ts
packages/transaction-controller/src/utils/validation.ts

This PR repairs some gaps in our validation of transaction parameters:
* validate that if a transaction envelope type is specified that it is a valid type
* validate transaction parameters before right before adding transaction to state
* catch and log async errors
Notes
* The steps to reproduce in https://github.com/MetaMask/metamask-extension/issues/23180 revealed an async error that was being swallowed.
This PR will fix these bugs once clients are updated:
* Related: https://github.com/MetaMask/MetaMask-planning/issues/2341 
* Related: https://github.com/MetaMask/metamask-extension/issues/23180
- **FIXED**: Fixes gaps in transaction parameter validation and async error logging

fix(TXL-207): fixes gaps in transaction validation and async error logging

---

packages/signature-controller/package.json
packages/signature-controller/src/SignatureController.test.ts
packages/signature-controller/src/SignatureController.ts
yarn.lock

When signatures are rejected the UI sends some extra information in the error data property. This information is stripped off when the error is re-thrown in the controller. This change aims as throwing the error back to the UI as received.
Removes the @metamask/rpc-errors package from the Signature controller as this is not used anymore.
None

fix: Return error as sent from the UI instead of throwing a new one

---

packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts

Fix an issue where we don't pass the notification on the click callback. Clients can still function by introspecting the event to get the notification.
N/A
- **ADDED**: notification parameter to the push notification click callback.

fix: add notification on push notification click callback

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

Currently it is not possible to change the rpcUrl for an existing network configuration without first removing it then re-adding it. This poses an issue on extension when the rpcUrl for the currently selected network is changed via the `NetworkForm`. The NetworkForm first removes the existing networkClient which causes the SelectedNetworkController to replace any references to the networkClientId being removed with the selectedNetworkClientId, but the problem is that the selectedNetworkClientId is no longer valid at that point. Really what we want in this case is to allow the network configuration to be updated in place by id, but only if the rpcUrl isn't changing to one that already exists on a different network configuration.
This PR achieves that by changing …

feat: NetworkController.upsertNetworkConfiguration allow upsert by networkConfigurationId

---

packages/transaction-controller/jest.config.js
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts

Add an optional `trace` constructor callback to the `TransactionController` to support generating Sentry traces within the controller, without coupling to the Sentry package.
Add an optional `traceContext` argument to `addTransaction` to facilitate generating nested traces within a parent trace generated within a client.
Add initial instrumentation of the transaction lifecycle.
[#2849](https://github.com/MetaMask/MetaMask-planning/issues/2849) [#2903](https://github.com/MetaMask/MetaMask-planning/issues/2903)
- **ADDED**: Add optional `trace` callback to constructor.
- **ADDED**: Add optional `traceContext` option to `addTransaction` method.

feat: add initial tracing to transaction controller

---

packages/phishing-controller/src/PhishingController.test.ts
packages/phishing-controller/src/PhishingController.ts
packages/phishing-controller/src/utils.test.ts

This PR removes PhishFort from the core MetaMask repository due to the termination of our contract with them for phishing detection. The immediate goal is to eliminate the PhishFort list from the PhishingController to prevent any potential false positives they might introduce. Given the urgency, this PR focuses solely on removing PhishFort from the client-side. Subsequent updates will address the removal of PhishFort from the API and the related test cases.
- **REMOVED**: PhishFort list and related references have been removed from the PhishingController.

feat: Remove the Phishfort list from the PhishingController

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR fixes `updateAccounts` in the `AccountsController` to handle the edge case where the selected account is undefined. This follows the same logic used in `onKeyringStateChange` 
Fixes: https://github.com/MetaMask/metamask-extension/issues/26377
- **FIXED**: `updateAccounts` logic to handle when the selectedAccount is undefined.

fix: handle undefined selectedAccount in updateAccounts

---

packages/composable-controller/package.json
packages/composable-controller/src/ComposableController.test.ts
packages/composable-controller/src/ComposableController.ts
yarn.lock

This commit fixes issues with the `ComposableController` class's interface, and its logic for validating V1 and V2 controllers.
These changes will enable `ComposableController` to function correctly downstream in the Mobile Engine, and eventually the Wallet Framework POC.
The previous approach of generating mock controller classes from the `ComposableControllerState` input using the `GetChildControllers` was flawed, because the mock controllers would always be incomplete, complicating attempts at validation. 
Instead, we now rely on the downstream consumer to provide both a composed type of state schemas (`ComposableControllerState`) and a type union of the child controller instances (`ChildControllers`). For example, in mobile, we can use (with some adjustments) `EngineState` for the …

[composable-controller] Fix incorrect behavior and improve type-level safeguards

---

packages/assets-controllers/src/TokenRatesController.ts
packages/assets-controllers/src/index.ts

For example:
Helps to fix: https://github.com/MetaMask/metamask-mobile/issues/10205
n/a

chore: Add export of MarketDataDetails type

---

packages/controller-utils/src/constants.ts

This is a part of https://github.com/MetaMask/metamask-extension/pull/26304#discussion_r1701658713, we upstream the constant to the core monorepo and after, we should update the metamask-extension on next release.
Part of https://github.com/MetaMask/core/issues/4598
- **ADDED**: Added default snap dialog constant to `ApprovalType`.

Add default snap dialog to ApprovalType

---

packages/base-controller/jest.config.js
packages/base-controller/package.json
packages/base-controller/src/BaseControllerV1.test.ts
packages/base-controller/src/BaseControllerV1.ts
packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/BaseControllerV2.ts
packages/base-controller/src/RestrictedControllerMessenger.ts
packages/base-controller/src/index.ts
packages/base-controller/tsconfig.json
packages/composable-controller/package.json
packages/composable-controller/src/ComposableController.ts
packages/composable-controller/src/index.ts
yarn.lock

This commit moves `BaseController`-related types and functions in `@metamask/composable-controller` to `@metamask/base-controller`.
Because applying these changes requires a concurrent major update of `@metamask/base-controller`, this commit will be excluded from `@metamask/composable-controller@8.0.0` (https://github.com/MetaMask/core/pull/4467), so that complications can be avoided while applying `8.0.0` to mobile.
- Blocked by https://github.com/MetaMask/core/pull/4467
- Blocked by https://github.com/MetaMask/metamask-mobile/pull/10441
- Migrate from `@metamask/composable-controller@8.0.0` into `@metamask/base-controller`: types `LegacyControllerStateConstraint`, `RestrictedControllerMessengerConstraint` and type guard functions `isBaseController`, `isBaseControllerV1` …

Move composable-controller utility types to base-controller

---

package.json
yarn.lock

Resolves dependabot security alerts by pinning affected packages to patched versions using yarn resolutions.
To minimize the footprint of this change, we're only adding yarn resolutions entries for the specific version strings that are currently found in the core monorepo dependency tree. This should make it easier to keep track of and revert resolutions entries if any problems arise, at the cost of needing to manually add entries for any upcoming affected dependency versions.
For future security alerts involving direct dependencies we should also consider scoping the entries to packages/dependencies.
- https://github.com/MetaMask/core/security/dependabot/52
- https://github.com/MetaMask/core/security/dependabot/54
- https://github.com/MetaMask/core/security/dependabot/58
- …

Set yarn resolutions for dependencies affected by dependabot security alerts

---

package.json
packages/notification-services-controller/package.json
yarn.lock

- Removes yarn resolutions entry for `axios` that pinned it to a version patched for a [level high security threat](https://github.com/MetaMask/core/security/dependabot/58).
- Resolves security issue by updating `axios` via a `contentful` version bump.
- `axios` is a transitive dependency of core: `@metamask/notification-services-controller` > `contentful` > `axios`.
- Fixes yarn resolutions introduced by: https://github.com/MetaMask/core/pull/4632
```md
- Bump `contentful` from `^10.3.6` to `^10.15.0` ([#4637](https://github.com/MetaMask/core/pull/4637))
```

Replace yarn resolutions entry for `axios` security patch with version bump

---

packages/logging-controller/src/LoggingController.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/phishing-controller/src/PhishingController.ts
packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

Fixes controllers and messengers in the core repo that do not fulfill their intended specifications correctly:
- [Define the `*:getState` action using the `ControllerGetStateAction` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-getstate-action-using-the-controllergetstateaction-utility-type)
- [Define the `*:stateChange` event using the `ControllerStateChangeEvent` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-statechange-event-using-the-controllerstatechangeevent-utility-type)
- [Define and export a type union for internal action types](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-and-export-a-ty …

Fix controllers with missing or incorrect messenger action/event types

---

packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
packages/notification-services-controller/src/index.ts

Fixes various errors in the `NotificationServicesPushController`:
- [Define the `*:getState` action using the `ControllerGetStateAction` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-getstate-action-using-the-controllergetstateaction-utility-type)
- [Define the `*:stateChange` event using the `ControllerStateChangeEvent` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-statechange-event-using-the-controllerstatechangeevent-utility-type)
- [Define and export a type union for internal action types](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-and-export-a-type-union-for-internal-action-types)
- …

fix(notification-services-push-controller): Add missing messenger action/events

---

packages/phishing-controller/src/PhishingController.ts
packages/phishing-controller/src/PhishingDetector.test.ts
packages/phishing-controller/src/PhishingDetector.ts

The existing phishing detection system in the `PhishingDetector` class did not include functionality for handling an allowlist when checking C2 domain blocklists. This meant that you were not able to continue to the website when a c2 was detected
No dependencies were updated in this PR.
- **ADDED**: Allowlist functionality to the C2 domain detection system.

feat: add allowlist to c2 domain detection

---

packages/assets-controllers/src/CurrencyRateController.test.ts
packages/assets-controllers/src/CurrencyRateController.ts

We think in https://github.com/MetaMask/metamask-mobile/issues/11035, the intermittent 0 balances were caused by transient errors in requests to crypto compare.  Instead of setting the conversion rate to null in this case, we'll omit the state update and keep the conversion rate from the previous successful fetch.
- **FIXED**: In `CurrencyRateController` if unexpected errors occur during requests to crypto compare, the conversion rate in state will remain unchanged instead of being set to null.

don't update currency rates on transient errors

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

This PR adds a new event `accountRenamed` to the `AccountsController`.
This event will be listened to by the `UserStorageController` in order to granularly upload the new account state to user storage whenever a user changes one of their account's name.
[Account Syncing](https://www.figma.com/board/sx26FtZcQc0zs0z5hpdqBh/Account-Syncing-Solution?node-id=0-1&node-type=CANVAS&t=nutSwHmXAxcG869V-0)
[NOTIFY-1046](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1046)
- **ADDED**: `accountRenamed` event
[NOTIFY-1046]: https://consensyssoftware.atlassian.net/browse/NOTIFY-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add `accountRenamed` event to `AccountsController`

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json

This is a release candidate for v197.0.0.
- `@metamask/notification-services-controller@0.4.1`
```md
- Bump `@metamask/notification-services-controller` from `^0.4.0` to `^0.4.1` ([#4666](https://github.com/MetaMask/core/pull/4666))
```

Release 197.0.0

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR adds listeners for `AccountsController` events to `UserStorageController`: 
- `accountAdded`
- `accountRenamed`
`UserStorageController` will update the user storage whenever these events are received.
[NOTIFY-1046](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1046)
- **ADDED**:  `accountAdded` and `accountRenamed` events will now trigger upwards account syncing
[NOTIFY-1046]: https://consensyssoftware.atlassian.net/browse/NOTIFY-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NOTIFY-1046): attach account sync upwards sync to `AccountsController` events

---

packages/notification-services-controller/package.json

Updates the `@metamask/notification-services-controller` `contentful` package to be a dev dependency.
We are only using contentful for its types. This also cleans up extension/mobile lavamoat policies.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1076
- **CHANGED**: Moved `Contentful` to `devDependencies`

refactor: move contentful as a dev dependency

---

packages/phishing-controller/src/index.ts

`PhishingDetectorResult` expects a `PhishingDetectorResultType` enum as `type` property, but the enum was previously not exported. Since it's an enum, we can't access it by using `PhishingDetectorResult['type']` either.
We need access to this to mock the result of the phishing controller in tests in the Snaps repo.
- **FIXED**: Export `PhishingDetectorResultType` enum

Export phishing detector result type

---

packages/profile-sync-controller/src/controllers/user-storage/schema.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts

Scaffolding - adds a new supported storage schema. This will unlock network syncing.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1032
- **Added**: `networks` to the User Storage Schema.
- **CHANGED**: moved `nativeScryptCrypto` into the `UserStorageBaseOptions`

feat: scaffolding - update storage schema

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/test-utils.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts

This is a follow up on https://github.com/MetaMask/core/pull/4685, and adds the controller integration for the network mutation syncs.
NOTE - we are currently using mock/temporary events that are not yet exposed on the network controller. We will add these network events in an upcoming PR.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1032
- **ADDED**: temporarily added non-existing `NetworkController:networkAdded`; `NetworkController:networkChanged`; and `NetworkController:networkDeleted` events.
- These will be provided in a future PR.
- **ADDED**: add `isNetworkSyncingEnabled` environment switch to `UserStorageController` to control when we enable network syncing.
- **ADDED**: add `startNetworkSyncing()` to initialise and listen to all the events required for network syncing.

feat: network-syncing and user storage controller integration

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR ensures we don't fire account syncing if the conditions are not entirely met.
- **ADDED**: Add a `canSync` check to account syncing

feat: add a `canSync` check for account syncing

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR replaces the parameter for `UserStorageController` `saveInternalAccountToUserStorage` from an account address to an `InternalAccount`.
This helps because we're listening to `AccountsController` events and they are passing an `InternalAccount` as their return value. By using this return value directly, we remove some unnecessary logic & queries.
- **CHANGED**: use `InternalAccount` instead of account address for `saveInternalAccountToUserStorage` parameter

refactor: use `internalAccount` instead of account address for granular updates

---

packages/accounts-controller/package.json
packages/chain-controller/package.json
packages/profile-sync-controller/package.json
yarn.lock

This bumps all Snaps packages used in the core repo to the latest version. This is necessary to unblock #4648.

Bump Snaps packages

---

packages/profile-sync-controller/src/controllers/user-storage/network-syncing/__fixtures__/mockNetwork.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.test.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.test.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/types.ts
packages/profile-sync-controller/src/controllers/user-storage/utils.test.ts
packages/profile-sync-controller/src/controllers/user-storage/utils.ts

This adds support for the "main-sync" on network syncing feature. This will get all a users local networks, and saved remote networks; then will append/update/delete networks synced across their devices.
We will add the controller integration in a following PR.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1040
- **CHANGED**: Renamed the `sync.ts` file to `sync-mutations.ts`
- **ADDED**: `utils` to the `UserStorageController` subpath.
- **ADDED**: `findNetworksToUpdate()` function which will perform the "main-sync" logic for local and remote network configurations.

feat: network sync - add main sync logic

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR adds callbacks that will be used for analytics in the account sync context.
[Notify-1102](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1102)
- **ADDED**: `onAccountAdded` and `onAccountNameUpdated` account syncing big sync callbacks

feat(NOTIFY-1102): add account sync analytics callbacks

---

packages/notification-services-controller/notification-services/mocks/package.json
packages/notification-services-controller/notification-services/package.json
packages/notification-services-controller/notification-services/ui/package.json
packages/notification-services-controller/package.json
packages/notification-services-controller/push-services/mocks/package.json
packages/notification-services-controller/push-services/package.json
packages/profile-sync-controller/auth/mocks/package.json
packages/profile-sync-controller/auth/package.json
packages/profile-sync-controller/package.json
packages/profile-sync-controller/sdk/package.json
packages/profile-sync-controller/user-storage/mocks/package.json
packages/profile-sync-controller/user-storage/package.json

We have moved from tsup to ts-bridge, which generates a different path/file for typescript definition files.
This updates the notifications team packages that use subpath exports:
- `@metamask/profile-sync-controller`
- `@metamask/notification-services-controller`
https://consensyssoftware.atlassian.net/browse/NOTIFY-1108
- **CHANGED**: Subpath exports `"types"` files.
- **ADDED**: SDK to supported `"files"` in package.json
- **CHANGED**: Subpath exports `"types"` files.

fix: update subpath exports to use new .d.cts definition files.

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
packages/profile-sync-controller/src/controllers/user-storage/schema.test.ts
packages/profile-sync-controller/src/controllers/user-storage/schema.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
packages/profile-sync-controller/src/sdk/user-storage.test.ts

This is a critical fix that ensures that we use the correct path hash used in extension for creating UserStorage for notification settings.
```diff
- notificationSettings
+ notification_settings
```
https://consensyssoftware.atlassian.net/browse/NOTIFY-1115
- **CHANGED**: **BREAKING** Updates the profile sync `notification_settings` path hash.
- This means that the hash for the storage entry will change.
- **CHANGED**: changes `notificationSettings` to `notification_settings` to use correct storage schema.

fix: update profile-sync notification settings path hash

---

packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts

Our package has exported async arrow functions, which cannot be compiled during the `detox build android` step on mobile.
<details><summary>See error logs</summary>
</details> 
It is most likely related to this hermes error: https://github.com/facebook/hermes/issues/1395
This removes the exported async arrow functions in the bundle for normal async functions.
Long term we should either:
- Add ESLint rules to prevent other devs or teams being burnt by this
- Or have a transpilation step to avoid async arrow functions.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1144
- **CHANGED**: updated exported async arrow functions to normal async functions.

fix: profile-sync-controller mobile compilation issues

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts
packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
packages/profile-sync-controller/src/sdk/user-storage.test.ts
packages/profile-sync-controller/src/sdk/user-storage.ts
packages/profile-sync-controller/src/shared/storage-schema.ts

This PR adds support for the new batch PUT endpoint.
[NOTIFY-1128](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1128)
- **ADDED**: batch PUT endpoint support for both SDK and controllers
[NOTIFY-1128]: https://consensyssoftware.atlassian.net/browse/NOTIFY-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NOTIFY-1128): add batch PUT endpoint support

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/chain-controller/CHANGELOG.md
packages/chain-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/notification-controller/CHANGELOG.md
packages/notification-controller/package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/permission-controller/package.json
packages/preferences-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This is a RC for v208.0.0. See changelog for more details
N/A
N/A

Release 208.0.0

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/approval-controller/CHANGELOG.md
packages/approval-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/chain-controller/CHANGELOG.md
packages/chain-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/notification-controller/CHANGELOG.md
packages/notification-controller/package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json
packages/permission-controller/package.json
packages/preferences-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This reverts commit 9949c81f5d6cf06e28d6dac36f26760d8be95e2c.
The `assets-controllers` version was wrong for the last RC. So we have to revert this RC and re-create it while fixing the `assets-controllers` bad version.
Version during that release [was `38.0.2`](https://github.com/MetaMask/core/blob/eb656db1704c6dcfa9474086434b267b15e62c97/packages/assets-controllers/package.json#L3) but it should have been `38.1.0`.
- https://github.com/MetaMask/core/pull/4731
N/A

Revert "Release 208.0.0 (#4731)"

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR ensures the `onAccountNameUpdated` callback only fires when the new name is different from the previous one
[NOTIFY-1166](https://consensyssoftware.atlassian.net/browse/NOTIFY-1166)
- **FIXED**: `onAccountNameUpdated` will now fire only when the new name is different from the previous one
[NOTIFY-1166]: https://consensyssoftware.atlassian.net/browse/NOTIFY-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NOTIFY-1166): only fire callback when account name has changed

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.ts

The `LineaGasFeeFlow` in the `TransactionController` aims to provide more accurate gas fee estimates derived from a specific transaction, rather than just at the network level.
This is achieved via a request to the custom `linea_estimateGas` RPC method on the provider.
Originally, the `gasPrice` property was necessary to prevent a bug, but now that issue has been fixed remotely, it is itself causing an alternate bug that returns the following error mesage:
`transaction up-front cost 0x16e360000000000 exceeds transaction sender account balance 0x7b2c1918e11642`
This PR simply removes the `gasPrice` property from the request. 
```
- Remove `gasPrice` from requests to `linea_estimateGas` ([#4737](https://github.com/MetaMask/core/pull/4737))
```

fix: remove gasPrice property from linea_estimateGas request

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts

This adds the ability for users or developers to reset their remote notification state. For example recovering from a corrupted state, or to just clear existing notifications.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1168
- **ADDED**: `resetNotifications` option during the notification creation flow

feat: add reset notifications flow

---

package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json

This is a RC for v210.0.0. See changelog for more details
- @metamask/queued-request-controller@5.1.0
- Batch processing now considers both origin and `networkClientId`, ensuring requests targeting different networks are processed separately. ([#4718](https://github.com/MetaMask/core/pull/4718))
- Incoming requests to `enqueueRequest` now must include a `networkClientId`; an error is thrown if it's missing. This was previously a required part of the type but since consumers like the extension do not have extensive typescript coverage this wasn't definitively enforced. ([#4718](https://github.com/MetaMask/core/pull/4718))

Release 210.0.0

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts
packages/profile-sync-controller/src/controllers/user-storage/utils.test.ts
packages/profile-sync-controller/src/controllers/user-storage/utils.ts
packages/profile-sync-controller/src/shared/encryption/cache.ts
packages/profile-sync-controller/src/shared/encryption/encryption.ts

This PR solves various performance issues with user storage encryption / decryption + account syncing specific bugs. More info in the changelog.
- https://consensyssoftware.atlassian.net/browse/NOTIFY-1171
- https://consensyssoftware.atlassian.net/browse/NOTIFY-1177
- **CHANGED**: batch GET / PUT now encrypts and decrypts sequentially in order to leverage cache 
- **FIXED**: don't save `nameLastUpdatedAt` to user storage if account name is a default name
- **REMOVED**: remove `randomBytes` from the encryption mechanism
- **REMOVED**: remove `waitForExpectedValue` and stop waiting for `AccountsController:accountAdded` callback

fix(NOTIFY-1171): fix account syncing performance

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts
packages/transaction-controller/src/utils/etherscan.test.ts
packages/transaction-controller/src/utils/etherscan.ts

Support the use of API keys when polling for incoming transactions in the `TransactionController`.
Provided by the client via the optional `incomingTransactions.etherscanApiKeysByChainId` property, since API keys may be exclusive to specific chains, based on the Etherscan host / domain.
- **ADDED**: Add optional `incomingTransactions.etherscanApiKeysByChainId` constructor property to support API keys in requests to Etherscan.

feat: support Etherscan API keys

---

packages/transaction-controller/src/TransactionController.ts

Ensure boot cleanup only occurs when initialising the controller and not when the network is changed.
Boot cleanup involves clearing unapproved transactions and failing approved and signed transactions.
Fixes [#27499](https://github.com/MetaMask/metamask-extension/issues/27499)
- **FIXED**: Cleanup transactions only during initialisation.

fix: remove boot cleanup on network switch

---

.github/CODEOWNERS

We, the MetaMask team (holistically), have recently spent time discussing code ownership around the packages in core. As a team we have aligned on which teams own which packages/controllers within core. This PR is to reflect that alignment. Additionally, in order to not make releasing challenging for the Wallet Framework (who are the stewards of the core repo) we have added this team as codeowners of the manifest file and the changelog file for all packages. 
For a little context being code owners doesn’t mean you are the only ones who work in that code but rather that you will take responsibility for making sure that the code is maintained, healthy, up to date and that others contributing to it do so in a manner that is aligned with our guidelines, processes and principles.
- [Internal …

chore: Update codeowners to match EM agreed ownership

---

packages/profile-sync-controller/src/shared/encryption/encryption.ts
packages/profile-sync-controller/src/shared/encryption/utils.ts
packages/profile-sync-controller/src/shared/types/encryption.ts

This PR fixes a bug where we passed a `string` parameter instead of a `UInt8Array` to the react native `scrypt` function.
This resulted in faulty key generation, bugs in encryption / decryption, and inconsistencies between mobile and the other clients.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1190
- **CHANGED (BREAKING**): use `UInt8Array` instead of `string` for the password argument of `nativeScryptCrypto`

fix(NOTIFY-1190): key generation bug for react native scrypt

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

The `TokenRatesController` used to only fetch prices for tokens on the currently selected account.  With this change, it will fetch prices for tokens across all accounts.
This will power UI features like showing portfolio $ values in the account picker, and avoids needing to re-fetch prices when switching accounts which causes some UI lag.
- **CHANGED**: `TokenRatesController` now fetches prices for tokens across all accounts

feat: fetch token rates across accounts

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts
packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
packages/profile-sync-controller/src/sdk/user-storage.test.ts
packages/profile-sync-controller/src/sdk/user-storage.ts

This PR adds profile-sync SDK and `UserStorageController` support for the DELETE endpoint.
This exposes new methods that permit deleting all user entries for a specific feature.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1192
- **ADDED**: `UserStorageController` and profile-sync SDK support for the `DELETE` all feature entries endpoint

feat(NOTIFY-1192): add DELETE endpoint support

---

packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts

This PR reduce gas limit fallback from 95% to 35% of the block gas limit to improve how we handle failed gas limit estimations.
Fixes: https://github.com/MetaMask/metamask-extension/issues/19692
- **CHANGED**: Reduce gas limit fallback from 95% to 35% of the block gas limit on failed gas limit estimations

fix: change gas limit fallback

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenListController.test.ts
packages/assets-controllers/src/token-service.test.ts
packages/assets-controllers/src/token-service.ts

What motivates this change is this user report https://github.com/MetaMask/metamask-extension/issues/27614
Based on discussions we had with teams; seems like initially, we added the `includeDuplicateSymbolAssets` because there were concerns around duplicate symbols being scammy and the increased size of tokenList.
For the duplicate symbols being scammy concern;  i think our usage of `occurrencesFloor=3` is helping us filter out any scam tokens.
Having tokens with the same symbol is not unusual and it does not necessarily mean that the token is a scam.
For the tokenList size; we thought that; today; the tokenList we get without `includeDuplicateSymbolAssets` has around 4500 tokens. With the `includeDuplicateSymbolAssets` it has around 4000. Which does not seem like it should have a huge …

fix: remove includeDuplicateSymbolAssets filter

---

yarn.config.cjs

This allows adding explicit exceptions for the Yarn constraint `expectConsistentDependenciesAndDevDependencies`.
An exception entry consists of a package name and a set of exact version ranges to be ignored in checking.
This is useful when we have "repo-circular" dependencies, where package A (in this repo) depends on package B (in another repo), which in its turn depends on package C (back again in this repo), finally depending on some package D.
In some cases, bumping D atomically in the monorepo makes things very heavy-handed. This change allows to slice it up in such situations.
- Example of heavy-handed PR: #4769
- `C = @metamask/json-rpc-engine`
- `D = @metamask/rpc-errors`
- Blocking: #4773
None

chore(constraints): allow exceptions for dependency-range consistency

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR fixed an unintended behavior where we were syncing imported accounts.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1215
- **CHANGED**: Account syncing will not sync imported accounts anymore

fix: do not sync imported accounts

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts
packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
packages/profile-sync-controller/src/sdk/user-storage.test.ts
packages/profile-sync-controller/src/sdk/user-storage.ts

This PR adds profile-sync SDK and `UserStorageController` support for the DELETE endpoint.
This exposes new methods that permit deleting one user entry for a specific feature.
https://consensyssoftware.atlassian.net/browse/NOTIFY-1214
- **ADDED**: `UserStorageController` and profile-sync SDK support for the `DELETE` one feature entry endpoint

feat(NOTIFY-1214): add support for DELETE ONE endpoint

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json

This is a RC for v218.0.0. See changelog for more details
-   @metamask/notification-services-controller:0.9.0
https://consensyssoftware.atlassian.net/browse/NOTIFY-1202
```
- Add new functions for creating new mock notifications ([#4780](https://github.com/MetaMask/core/pull/4780))
```

Release 218.0.0

---

package.json
packages/notification-services-controller/CHANGELOG.md
packages/notification-services-controller/package.json

This is a RC for v219.0.0. See changelog for more details
-  @metamask/notification-services-controller:0.10.0
https://consensyssoftware.atlassian.net/browse/NOTIFY-1159
```
- update `createMockNotification` functions to provide more realistic data for use in tests and component rendering in Storybook ([#4791](https://github.com/MetaMask/core/pull/4791))
- added the ability for the `fetchFeatureAnnouncementNotifications` function, within the `notification-services-controller`, to fetch draft content from Contentful. This is made possible by passing a `previewToken` parameter ([#4790](https://github.com/MetaMask/core/pull/4790))
```

Release 219.0.0

---

packages/json-rpc-engine/package.json
yarn.config.cjs
yarn.lock

Bump `@metamask/rpc-errors` to latest for `@metamask/json-rpc-engine`.
- https://github.com/MetaMask/rpc-errors/releases/tag/v7.0.0
- Relevant change: https://github.com/MetaMask/rpc-errors/pull/158
- Consistent upgrade across the monorepo: https://github.com/MetaMask/core/pull/4769
- https://github.com/MetaMask/eth-json-rpc-middleware/pull/342
- https://github.com/MetaMask/metamask-extension/pull/22875
- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.3.1` to `^7.0.0`

deps(json-rpc-engine): @metamask/rpc-errors@^6.3.1->^7.0.0

---

yarn.config.cjs

Allow configuring yarn constraints to allow exceptions for dependency range consistency checks for workspace dependencies and devDependencies.
- Follow-up to #4772
- #4798
None

chore(constraints): respect ALLOWED_INCONSISTENT_DEPENDENCIES for workspace packages; simplify logic

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

This PR fixes a rare problem that would occur when deleting a network after a proxy in `SelectedNetworkController` has been garbage collected. When this happens, `getProviderAndBlockTracker` will fail to find the old network client ID and thus updating the network client ID for the domain will fail. 
This could be reproduced in an E2E test that would only fail on this branch: https://github.com/MetaMask/metamask-extension/pull/27306 which enables `initialConnections` for a preinstalled Snap. `initialConnections` adds a permission for an origin to connect to a Snap which causes the `SelectedNetworkController` to register the domain. My theory is that since the user has not accessed the origin in question yet, the proxy may not be used and may be garbage collected. If a network is deleted …

fix: Ensure that network client ID is updated before use

---

packages/multichain/src/caip25Permission.test.ts
packages/multichain/src/caip25Permission.ts

Mirrors the [wallet_createSession handler
](https://github.com/MetaMask/metamask-extension/pull/27782/files#diff-107459889087f2776c6db636bd45498bef6749302f9d2dc633b4de17fede40a3R96-R108) in how eth account support is checked/asserted. Opted to do this rather than modify `assertScopeSupported` because the `bucketScopes` helper also relies on `assertScopedSupported` but doesn't care about accounts (which is why eth accounts are checked outside of assertScopeSupported in the wallet_createSession handler currently)

add account support check in validator

---

packages/keyring-controller/package.json
packages/message-manager/package.json
packages/signature-controller/package.json
yarn.lock

This PR updates `eth-sig-util` dependency for `signature-controller`. Recent change in package remove the normalization for numerical addresses.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3298
- **CHANGED**: Bump `eth-sig-util` dependency to `8.0.0`

Bump `eth-sig-util` dependency to `8.0.0` for `signature-controller`

---

packages/controller-utils/package.json
packages/controller-utils/src/util.test.ts
packages/controller-utils/src/util.ts
yarn.lock

The API for this part is equivalent between the two libraries. Allowing both eases migrations.
- https://github.com/MetaMask/metamask-mobile/pull/11932
- **ADDED**: Types indicate `bignumber.js` instances are valid input to `BNToHex`.

feat(controller-utils): support BigNumber as input to BNToHex

---

packages/controller-utils/package.json
packages/notification-services-controller/package.json
yarn.lock

- **FIXED**: Upgrade `bignumber.js` from `^4.1.0` to `^9.0.1`

deps(notification-services-controller): bignumber.js@^4.1.0->^9.1.2

---

packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

**Current state:**
The `PreferencesController` does not include support for two new features related to network validation and multi-RPC migration behavior. Specifically, there is no existing functionality to:
1. Control the display of the multi-RPC migration modal (`useMultiRpcMigration`).
**Solution:**
This PR adds two new properties to the `PreferencesController` state: 
- `useMultiRpcMigration`: Controls whether the multi-RPC migration modal is displayed.
Along with these additions, corresponding setter methods ( `setUseMultiRpcMigration`) have been implemented. These methods allow for toggling the state of the new properties.
**Additional details:**
- Test cases have been added to ensure that the new properties are correctly updated in the state when their respective setter methods …

fix: Add useMultiRpcMigration to PreferencesController

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/notification-services-controller/src/NotificationServicesController/types/index.ts

* What is the current state of things and why does it need to change? The `deleteNotificationsById` doesn't fire an event with the updated list of notifications and thus, the `updateBadge` function inside the extension is not fired.
* What is the solution your changes offer and how does it work? Publish an event after notifications are deleted
* Are there any changes whose purpose might not obvious to those unfamiliar with the domain? Adding export for snap types, not able to pull the type out directly otherwise.
- **FIX**: The `deleteNotificationsById` function did not fire an event with the updated notifications list, this was added after the function runs through all the notifications it needs to delete.

fix: add publish event in `deleteNotificationsById` and export snap types

---

packages/controller-utils/package.json
packages/controller-utils/src/util.test.ts
packages/controller-utils/src/util.ts
yarn.lock

- Extend types to indicate support for passing in bn.js v4 instances to BN.js utility functions
- Affected functions:
- `BNToHex`
- `fractionBN`
- `fromHex`
- `toHex`
- If input is v4 instance, return as v4. Otherwise use v5, as previously.
- `fractionBN` now uses the original BN implementation when passed a v4 BN instance
- Use [overload signatures](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) to more specifically type BN-related util functions
- Context: https://github.com/MetaMask/metamask-mobile/pull/11972
- Note that these functions are _already_ used with v4 input but this was not caught due to the way `bn.js` is imported downstream. Making this support explicit facilitates resolving the type issue without requiring a prior full migration off …

feat(controller-utils): support bn.js v4 input to BN functions

---

packages/controller-utils/package.json
packages/controller-utils/src/util.test.ts
packages/controller-utils/src/util.ts
yarn.lock

Reverts MetaMask/core#4844
This is being reverted temporarily because `create-release-branch` is incompatible with the `npm:` dependency alias format used in that PR. We can reintroduce this change after resolving that problem.

Revert "feat(controller-utils): support bn.js v4 input to BN functions"

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/ens-controller/CHANGELOG.md
packages/ens-controller/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/polling-controller/CHANGELOG.md
packages/polling-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/CHANGELOG.md
packages/user-operation-controller/package.json
yarn.lock

Recently, a new version of `@metamask/network-controller`, 22.0.0, was released, but packages which have a peer dependency on `@metamask/network-controller` were not included in this release. This means that clients which are using current versions of these dependents will experience peer dependency warnings if they attempt to upgrade `@metamask/network-controller`. This release makes it so that clients can also upgrade these dependents while they upgrade `@metamask/network-controller`, avoiding the peer dependency warnings.
This is a prequisite for https://github.com/MetaMask/MetaMask-planning/issues/3568.

Release 232.0.0

---

.github/CODEOWNERS

This exception was missing, which was preventing @MetaMask/wallet-framework-engineers to approve changes made for the `@metamask/chain-controller` package during releases.
N/A.
N/A

chore: add wallet-framework-engineers as CODEOWNERS for chain-controller for releases

---

packages/assets-controllers/src/CurrencyRateController.test.ts
packages/assets-controllers/src/CurrencyRateController.ts
packages/assets-controllers/src/RatesController/RatesController.test.ts
packages/assets-controllers/src/RatesController/RatesController.ts
packages/assets-controllers/src/RatesController/types.ts
packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts

Updates the currency rate controller to use the `pricemulti` endpoint of crypto compare.  This allows us to fetch exchange rates for multiple native currencies in a single http request.
- **BREAKING**: `CurrencyRateController` now accepts an array of native currencies as its polling input.
- **BREAKING**: `RatesController` now types the `conversionRate` and `usdConversionRate` in its state as `number` instead of `string`, to match what it was actually storing.

feat: use crypto compare multi api for currency rate controller

---

packages/controller-utils/package.json

Since `bignumber.js` is used for typing in `controller-utils`, it should likely be a dependency to prevent issues when building with TS downstream.
There is probably a larger conversation to have here about when to use types as devDeps and when to use them as deps, but in our architecture today we rely heavily on all types to be included as dependencies. This causes a lot of potentially avoidable dependency management.
- **Fixed**: Move `bignumber.js` to dependencies

chore: Move BigNumber.js to dependencies

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts
packages/assets-controllers/src/multi-chain-accounts-service/multi-chain-accounts.test.ts
packages/assets-controllers/src/multi-chain-accounts-service/multi-chain-accounts.ts

Following the documentation in https://docs.cx.metamask.io/docs/further-info/internalClientId, pass a `x-metamask-clientproduct` header when calling the account api.
- **BREAKING**: A `platform` argument must now be passed to the `TokenDetectionController` constructor.
- **CHANGED**: The `TokenDetectionController` now passes a `x-metamask-clientproduct` header when calling the account API.

[TokenDetectionController] pass header to accounts API

---

package.json
yarn.lock

The `@metamask/create-release-branch` package has been updated one minor version. This was done to get support for `npm:` aliases, which is needed to re-introduce #4844 (which was reverted).
Unblocks the re-application of #4844
N/A

chore: Bump `@metamask/create-release-branch` from v3.0 to v3.1

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

Updates the polling input for `TokenRatesController` to a chain id instead of a network client id.
* Related to https://github.com/MetaMask/metamask-extension/pull/28158
- **BREAKING**: The `TokenRatesController` now accepts `{chainId: Hex}` as its polling input to `startPolling()` instead of `{networkClientId: NetworkClientId}`

update TokenRatesController to poll on chain id instead of network client id

---

.github/workflows/create-update-issues.yaml

The `create-update-issues` workflow was failing because it didn't have access to the secrets it needed. The `CORE_CREATE_UPDATE_ISSUES_TOKEN` secret is only available on hte `default-branch` environment.
The workflow has been updated to use that environment so that it may access the secret.
Example failure: https://github.com/MetaMask/core/actions/runs/11633589453/job/32399521142
Fixes bug introduced in https://github.com/MetaMask/core/pull/4763
N/A

ci: Fix `create-update-issues` workflow secret access

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts

* What is the current state of things and why does it need to change? If notifications are disable while there is an unread notification, the notifications are wiped from state.
* What is the solution your changes offer and how does it work? In the disable function, we repopulate the list with the currently exist snap notifications.
* Are there any changes whose purpose might not obvious to those unfamiliar with the domain? This was only uncovered in manual QA in my extension PR: https://github.com/MetaMask/metamask-extension/pull/27975
- **FIX**: Updated disable notifications function to repopulate state with existing snap notifications instead of emptying the list entirely.

fix: disable notifications

---

packages/assets-controllers/src/AccountTrackerController.test.ts
packages/assets-controllers/src/AccountTrackerController.ts
packages/assets-controllers/src/AssetsContractController.test.ts
packages/assets-controllers/src/AssetsContractController.ts
packages/assets-controllers/src/AssetsContractControllerWithNetworkClientId.test.ts
packages/assets-controllers/src/assetsUtil.ts

**What is the current state of things and why does it need to change?**
- Currently the `metamask-mobile` app using the `assets-controllers` to get information about account token balances. We need to be able to support getting a new type of asset on mainnet and holesky chains, _Staked Ethereum_, which is not a token but represents the amount of ETH staked using our products.
**What is the solution your changes offer and how does it work?**
- We update the `AssetContractController` with a new method, `getStakedBalanceForChain`, which gets staked ethereum balances per account from the Stakewise vault contract. We update the AccountTrackerController with options to `includeStakedAssets` and to add a `getStakedBalanceForChain` method. 
- We bind …

feat: Show Staked ETH position in mobile homepage along with other tokens

---

.github/workflows/add-prs-to-project.yml

This GitHub Action automatically adds pull requests to a project board for the Wallet Framework Team. It triggers on PR events like opening, labeling, or review requests. The action checks if the PR is relevant by matching the requested team or labels against the Wallet Frameworks team name and label. If matched, it adds the PR to our project board using a GitHub token for authentication. This will allow the team to more easily see PRs which need our attention
n/a
n/a
I did manual testing on a fork of the repo. It is not a one for one match because the access token setup is slightly different based on Organization -> projects vs Individual -> projects but the core of the workflow worked and is the same.

chore: add PRs to PR queue for WF team

---

packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

We want to enable smart transactions by default for new users.
```md
- Enable smart transactions by default for new users by setting the initial value of the `smartTransactionsOptInStatus` state property to 'true' ([#4885](https://github.com/MetaMask/core/pull/4885))
```

feat: enable smart transactions by default for new users

---

packages/queued-request-controller/src/QueuedRequestController.test.ts
packages/queued-request-controller/src/QueuedRequestController.ts

Fix issue where `QueuedRequestController.state.queuedRequestCount` is not updated after flushing requests for an origin
- https://github.com/MetaMask/core/pull/4846
- https://github.com/MetaMask/metamask-extension/pull/28090
- Bug identified [in v12.7.0 RC Thread](https://consensys.slack.com/archives/C029JG63136/p1730918073046389?thread_ts=1729246801.516029&cid=C029JG63136)
https://drive.google.com/file/d/1ujdQgVLlT8KlwRwO-Cc3XvRHPrkpxIg_/view?usp=drive_link
https://github.com/user-attachments/assets/e77928e5-165b-441a-b4da-0e10471c0529
- **FIX**: Ensure queuedRequestCount value is updated properly after flushing the queue for a given origin

fix: issue where `QueuedRequestController.state.queuedRequestCount` is not updated after flushing requests for an origin

---

packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts

Prevent the following error when estimating gas limits on specific chains:
```
invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go struct field TransactionArgs.gas of type hexutil.Uint64
```
Specifically:
- Remove the calculated fallback `gas` property from the `eth_estimateGas` request.
- Remove all gas fee properties (`gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`) from the `eth_estimateGas` request.
- Calculate fallback gas, max gas limit, and buffer using fractions rather than decimals.
Fixes [#28307](https://github.com/MetaMask/metamask-extension/issues/28307) [#28175](https://github.com/MetaMask/metamask-extension/issues/28175)
- **FIXED**: Gas limit estimation on new transactions and via `estimateGas` and `estimateGasBuffered` methods.

fix: gas limit estimation 

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR add checks to prevent unwanted account syncs.
- Prevent multiple parallel account sync processes
- Prevent single operations if conditions aren't met
- **ADDED**: Account syncing safeguards to prevent multiple parallel syncs

feat: prevent parallel account syncs

---

packages/assets-controllers/src/TokensController.ts

As autodetection is now multi-chain, the `addTokens` function must be adjusted by taking the `allTokens` and filter on `chainId` into account to avoid importing the wrong tokens.
The `addTokens` function currently operates by taking the existing list of imported tokens ( without considering the network ) and adding the tokens specified in the `tokensToImport` parameter. This approach can result in incorrect tokens being imported, as it doesn’t filter by chain. To address this, we use `allTokens` to ensure accurate filtering by chain.
- **CHANGED**: addTokens should rely now on `allTokens`

fix: fix token import flow

---

.github/CODEOWNERS

`@metamask/profile-sync-controller` will now be maintained by @MetaMask/identity and @MetaMask/notifications.
This PR adds this to `CODEOWNERS`

chore: update CODEOWNERS to reflect co-ownership of profile-sync-controller

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts
packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
packages/profile-sync-controller/src/sdk/user-storage.test.ts
packages/profile-sync-controller/src/sdk/user-storage.ts

This PR adds support for the batch delete endpoint, for both `UserStorageController` and the SDK
Fixes https://github.com/MetaMask/core/issues/4936
- **ADDED**: support for the batch delete endpoint for both `UserStorageController` and profile-sync SDK

feat: add batch delete endpoint support for UserStorageController & profile sync SDK

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR adds various account syncing improvements. 
- New `UserStorageController` state keys `hasAccountSyncingSyncedAtLeastOnce` and `isAccountSyncingReadyToBeDispatched`
- `onAccountSyncErroneousSituation` analytics callback to track how often erroneous situations happen during account syncing
- Set `hasAccountSyncingSyncedAtLeastOnce` also for a profile id first sync ever in `UserStorageController`
- **ADDED**: new `UserStorageController` state keys `hasAccountSyncingSyncedAtLeastOnce` and `isAccountSyncingReadyToBeDispatched`
- **ADDED**: `onAccountSyncErroneousSituation` analytics callback to track how often erroneous situations happen during account syncing
- **FIXED**: set `hasAccountSyncingSyncedAtLeastOnce` also for a profile id first sync ever in `UserStorageController`

feat: add account sync analytics & add state helpers

---

packages/accounts-controller/package.json
packages/accounts-controller/src/tests/mocks.ts
packages/assets-controllers/package.json
packages/chain-controller/package.json
packages/keyring-controller/package.json
packages/profile-sync-controller/package.json
packages/transaction-controller/package.json
yarn.lock

Updating accounts related packages. We do skip 1 major for the `keyring-api` which is ok:
- 9.0.0 was about Bitcoin changes (renaming the only BTC method we support)
- 10.1.0:
* bumps the `@metamask/providers` to the same version than the one expected by `snaps-*` packages and the `eth-snap-keyring`
* adds basic Solana support
N/A
- **CHANGED**: Bump `keyring-api` to `^10.1.0`
- **CHANGED**: Bump `eth-snap-keyring` to `^5.0.1`
- **CHANGED**: Bump `snaps-utils` to `^8.3.0`
- **CHANGED**: Bump `snaps-sdk` to `^6.7.0`
- **CHANGED**: Bump peer dependency `snaps-controllers` to `^9.10.0`
- **CHANGED**: Bump `keyring-api` to `^10.1.0`
- **CHANGED**: Bump `keyring-api` to `^10.1.0`
- **CHANGED**: Bump `snaps-utils` to `^8.3.0`
- **CHANGED**: Bump `snaps-sdk` to `^6.7.0`
- **CHANGED**: Bump …

chore: bump `@metamask/{keyring-api,eth-snap-keyring,snaps-*}`

---

packages/transaction-controller/package.json
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/types.ts
yarn.lock

Remove dependency on `@metamask/keyring-api` from `@metamask/transaction-controller` as it was only used for types in unit tests.

chore: remove keyring-api dependency from transaction controller

---

packages/accounts-controller/package.json
yarn.lock

This change was not required, and bumping peer dependency does require the "consumer" of that packages to potentially update his packages too, which would result in a breaking change for the `accounts-controller` here.
- https://github.com/MetaMask/core/pull/4956#discussion_r1852398241
N/A (since we would revert to the state of the last release of the `accounts-controller` for that specific line).

chore: downgrade `snaps-controllers` peer dependency from `^9.10.0` to `^9.7.0`

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenDetectionController.ts

Currently, the TokenDetectionController detects tokens only for the active network when switching accounts. This behavior does not account for the added networks in the NetworkController. Consequently, token detection is limited and does not cover all networks where the user might have assets.
- **ADDED**: Token detection now supports all added networks when switching accounts.

fix detect tokens on account switch

---

package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json

Minor version bump of assets controllers.
- @metamask/assets-controllers@45.1.0
```md
- Bump `@@metamask/assets-controllers` from `^45.0.0` to `^45.1.0` ([#4966](https://github.com/MetaMask/core/pull/4966))
```

Release 256.0.0

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

I am getting a lint error on my machine. Once again, `@typescript-eslint/restrict-template-expressions` is mistakingly creating this error. This commit skirts around the problem until we can figure out what's going on.
(N/A, something I noticed locally)
(N/A)

Suppress mistaken lint violation in UserStorageController

---

packages/assets-controllers/src/TokensController.test.ts
packages/assets-controllers/src/TokensController.ts

Currently, the `ignoreTokens` method in the `TokensController` is using a static set of tokens (`ignoredTokens`, `detectedTokens`, and `tokens`) without accounting for tokens scoped to specific networks. This causes issues when attempting to hide tokens that do not belong to the currently active network, potentially leading to incorrect behavior.
- Updated the method to use `allTokens`, `allDetectedTokens`, and `allIgnoredTokens`, scoped by `interactingChainId` or the current network's `chainId` and selected address.
- Ensured the `ignoredTokens` array is derived dynamically based on the active network and address, preventing interference from tokens of other networks.
- The changes introduce a more granular approach by retrieving the correct token lists (`allTokens`, `allDetectedTokens`, …

fix: prevent non-current network tokens from being hidden incorrectly

---

package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This is a re-release of 257.0.0 due to an incorrectly named commit.

Release 257.0.0

---

.github/workflows/add-prs-to-project.yml

Right now for PRs where the WF team are codeowners but our label isn't there or we aren't specifically added as requested reviewers, they aren't getting added to our repo for review. This PR is intended to fix that.
n/a
n/a

Fix to capture codeowner plus ability to run on existing PRs

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/package.json
packages/chain-controller/CHANGELOG.md
packages/chain-controller/package.json
packages/controller-utils/CHANGELOG.md
packages/controller-utils/package.json
packages/gas-fee-controller/CHANGELOG.md
packages/gas-fee-controller/package.json
packages/json-rpc-engine/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/notification-services-controller/package.json
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/CHANGELOG.md
packages/user-operation-controller/package.json
yarn.lock

When running `yarn install`, several packages generate peer dependency warnings. 
- `@lavamoat/preinstall-always-fail` is now a peer dependency of `@lavamoat/allow-scripts`, so we need to add it as a new dev dependency.
- For the other packages — `@babel/runtime`, `@metamask/providers`, `webextension-polyfill` — we really expect the _client_ to have these dependencies, so we also add them as dev and peer dependencies instead of dependencies. We have to do this because they will not get forwarded along.
Fixes #4906.
Changes are documented in changelogs.

Fix peer dependency warnings

---

packages/transaction-controller/src/types.ts

This PR adds a new field to the `TransactionMeta` type to facilitate Bridge transactions.
The primary purpose is to ensure that `destinationTokenAddress` refers to the correct token on the correct chain.
A slimmed down version of https://github.com/MetaMask/core/pull/4918
Related to https://github.com/MetaMask/metamask-extension/pull/28460
- **ADDED**: `destinationChainId` to the `TransactionMeta` type

feat: add destinationChainId to support cross chain txs

---

packages/remote-feature-flag-controller/package.json

The package name in the changelog scripts had a typo. So to validate our changelogs correctly, this needs to be fixed to correctly match the package name.
- **fix**: fix the name of the package in the changelog update and validate scripts in package.json

Fix the package name in the changelog scripts defined in package.json

---

packages/remote-feature-flag-controller/CHANGELOG.md
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts

The controller metadata for the `RemoteFeatureFlagController` has been updated to declare the feature flag state as anonymous. These values are set by us and do not contain any PII. This allows us to capture this state in Sentry debug snapshots, which could be very useful for debugging.
N/A
See changelog diff

feat: Allow capturing feature flags in debug snapshots

---

package.json
tsconfig.build.json
tsconfig.json
yarn.lock

Update @ts-bridge/cli from `0.5.1` to `0.6.1`. This version can build project references in parallel, significantly improving build speed. It also properly handles reexports when detecting CJS exports https://github.com/ts-bridge/ts-bridge/pull/69.
None

chore: Update `@ts-bridge/cli` to `0.6.1`

---

.github/CODEOWNERS

It has been discussed that having "Engineering" as codeowners on `core` repo is a bit too wide so we are removing that line. 
n/a
n/a
N/A

chore: Removing the too wide codeowners rule

---

packages/composable-controller/CHANGELOG.md
packages/composable-controller/src/ComposableController.test.ts
packages/composable-controller/src/ComposableController.ts

Expensive operations during `ComposableController` instantiation contribute to downstream performance issues in our client apps' initialization times. Optimizing these operations may be especially impactful since `ComposableController` takes large inputs consisting of all of the controllers used by a given client.
- Remove wasteful `reduce` operations that create temporary objects on each iteration and replace with implementations that re-use their output objects.
- Refactor `ComposableController` to accept an object instead of an array. Now that the mobile Engine creates a controllers object, this saves us an extra operation for converting the object into an array.
- For downstream application, see https://github.com/MetaMask/metamask-mobile/pull/10441/commits/5ceb81c587c7b5d038f53d678dab …

[composable-controller] perf: Optimize expensive reduce operations, fix metadata instantiation

---

packages/multichain/src/index.test.ts
packages/multichain/src/index.ts
packages/multichain/src/scope/filter.test.ts
packages/multichain/src/scope/filter.ts

Adds and exports `filterScopeObjectsSupported` which filters out unsupported methods and notifications from each ScopeObject in a ScopesObject

Jl/caip multichain api/drop unsupported methods notifications

---

packages/multichain/package.json
yarn.lock

Bumps `@metamask/eth-json-rpc-filters` to `^9.0.0` in the `multichain` package
- **CHANGED**: Bump `@metamask/eth-json-rpc-filters` to `^9.0.0`

chore: bump `@metamask/eth-json-rpc-filters` to `^9.0.0` in the `multichain` package

---

.github/workflows/create-update-issues.yaml

We have a github project setup to track client controller upgrade issues that are created by this github action. Github projects workflow is not working for auto adding solely based on title match and the options for what to match on are very limited. Labels are one way we can do that.
This PR adds a label that we can trigger the auto add workflow on. 
n/a
n/a

Add label for use in github project auto add workflow

---

packages/remote-feature-flag-controller/CHANGELOG.md
packages/remote-feature-flag-controller/package.json
packages/remote-feature-flag-controller/src/remote-feature-flag-controller-types.ts
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts
packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.ts
yarn.lock

This PR added ability for @metamask/remote-feature-flag-controller to take in a new param `metametricsId` and applied to the featureFlag processing. Furthermore, a threshold will be generated using a simple function, which generates a deterministic random group number between 0 and 1 from `metametricsId`. If encounters a flag from api with scope as `type: "threshold"`, controller will drill down to return the value that's matching the threshold generated based on `metametricsId`. 
Note: `metametricsId` will always be provided from client, a random SHA-256 hash will be used as fallback
Fixes https://github.com/MetaMask/MetaMask-planning/issues/3742
- **ADDED**: Added support for threshold-based feature flag scoping

feat(3742): Feature Flag Values with Scope Based on threshold

---

packages/permission-controller/ARCHITECTURE.md
packages/permission-controller/src/Caveat.ts
packages/permission-controller/src/Permission.ts
packages/permission-controller/src/PermissionController.ts

Via discussion during https://github.com/MetaMask/metamask-extension/pull/27847, it became apparent that there was confusion re: the purpose of permission vs. caveat validators and when to use one vs. the other. This has now been properly documented in multiple places in the permission controller package.
In addition, the permission controller implementation contained some irregularities regarding its own permission validation logic. This surfaced in the form of redundant permission and caveat validator calls, both of which have now been removed. (In addition, one overly complicated "optimization" to avoid redundant caveat validator calls has been removed.)
Reviewers: although I doubt it's a problem, we should take care to ensure that we weren't relying on the old behavior in any of our …

refactor(permission-controller): Rationalize permission and caveat validation

---

packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
packages/queued-request-controller/src/QueuedRequestMiddleware.ts
packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

This reverts commit 4814cf11670c76f7d3015206dbe3c78b383ddc3a.
We are not yet ready to release per-dapp selected network functionality on the mobile client and with this change there is no clean way to [update the version of SelectedNetworkController](https://github.com/MetaMask/metamask-mobile/issues/12434#issuecomment-2537358920) in the mobile client without having the Domains state starting to populate and possibly become corrupt since its not being consumed by/updated by the frontend in the expected way and may need to be migrated away when its time to actually start using the controller. 
Without this revert the @MetaMask/wallet-framework team is blocked from completing their goal to get both clients up to the latest versions of all controllers.
- **ADDED**: **BREAKING:** …

Revert "chore: Remove `useRequestQueue` toggle to turn on/off Per Dapp Selected Network Feature (#4941)"

---

packages/base-controller/CHANGELOG.md
packages/base-controller/src/BaseControllerV1.test.ts
packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/BaseControllerV2.ts
packages/base-controller/src/Messenger.test.ts
packages/base-controller/src/Messenger.ts
packages/base-controller/src/RestrictedMessenger.test.ts
packages/base-controller/src/RestrictedMessenger.ts
packages/base-controller/src/index.ts

Rename the `ControllerMessenger` to `Messenger` so that it is clear it can be used for more than just controllers.
This was decided by this ADR: https://github.com/MetaMask/decisions/blob/main/decisions/core/0001-messaging-non-controllers.md
Previous names have been preserved as aliases to avoid making this a breaking change.
See diff

chore: Rename `ControllerMessenger` to `Messenger`

---

packages/notification-services-controller/src/NotificationServicesPushController/services/push/push-web.test.ts
packages/notification-services-controller/src/NotificationServicesPushController/services/push/push-web.ts
packages/notification-services-controller/src/NotificationServicesPushController/services/services.ts

Before we were initialising firebase without checking if the browser has correct setup for it. Thus causing errors logs to be made. (not breaking the app, but still producing errors).
We now do a check to ensure we can initialise firebase.
https://github.com/MetaMask/metamask-extension/issues/26173
- **ADDED**: `getPushAvailability` method to check if we can use push notifications.
- **CHANGED**: `getFirebaseMessaging()` now optionally returns null. This is an internal method not exposed outside.
- **CHANGED**:  `unsubscribePushNotifications` is not optional. This is internal and not exposed outside module.

fix: check push notification compatibility before setting up firebase

---

.github/CODEOWNERS

There was a new package added the `core` repo for `@metamask/multichain`. We want to make sure the proper team is set as CODEOWNERS

chore(codeowners): Add Wallet API team as CODEOWNERS for multichain package

---

packages/profile-sync-controller/src/controllers/authentication/services.ts
packages/profile-sync-controller/src/controllers/user-storage/services.ts

This improves service logs by adding the HTTP response status to the log metadata. This should help us debug and differentiate server errors a client is producing.
- **ADDED**: HTTP response status to error logs in services files.

feat: improve profile sync services logs

---

packages/signature-controller/src/SignatureController.test.ts
packages/signature-controller/src/SignatureController.ts

Ensure the signature request `id` and message params `metamaskId` use the same value so that legacy code using only the message params can locate the associated signature request.
- **FIXED**: Use same value for signature request `id` and message params `metamaskId`.

fix: match signature request and message params ID

---

packages/assets-controllers/src/assetsUtil.test.ts
packages/assets-controllers/src/assetsUtil.ts
packages/assets-controllers/src/crypto-compare-service/crypto-compare.test.ts
packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts
packages/assets-controllers/src/index.ts

PR to fix the MANTLE price fetched for chainId: 5000.
Cryptocompare api provides prices for both MANTLE and MNT: https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH%2CMNT%2CMANTLE&tsyms=usd
And it is returning the the price for 'MNT' when the user in on MANTLE chain.
- **FIXED**: Added a check if any of the provided cyrptocurrencies to `fetchMultiExchangeRate` fct exists in `nativeSymbolOverrides` map
- **ADDED**: Added utility function `getKeyByValue` to assetsUtils

fix: fix mantle price when calling fetchMultiExchangeRate

---

packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts
packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.ts

Changes introduced in this PR including:
- remove fallback of metaMetricsId and rely on client side always returning a value
- refactor getMetaMetricsId to only handle synchronous (extension) function
Addressed feedback https://github.com/MetaMask/core/pull/5051#discussion_r1883046468
- **CHANGED**: Modify signature of `getMetaMetricsId` to handle only synchronous function
- **CHANGED**:  Remove fallback of `metaMetricsId`

fix(3742): change getMetaMetricsId to only sync func type

---

scripts/create-package/utils.test.ts
scripts/create-package/utils.ts

This PR addresses a bug in the yarn `create-package` script introduced in [this change](https://github.com/MetaMask/core/pull/3672/files#diff-3424bcceb4f9219f700e2bd2da507f2c742767c7a30f6be5512f62d3b44ffd7aR97), where `fstatSync` was replaced with `await fs.stat(packagePath)).isDirectory()`.
The issue arises because fs.stat now throws an `ENOENT` error if the packagePath is empty. To resolve this, the script has been updated to handle empty paths gracefully, ensuring the process works as expected when creating new packages.

fix: create-package script

---

packages/multichain/src/middlewares/multichainMethodCallValidator.test.ts
packages/multichain/src/middlewares/multichainMethodCallValidator.ts

improve testing of nested errors in multichainMethodCallValidator

improve testing of nested errors in multichainMethodCallValidator

---

docs/writing-controllers.md
examples/example-controllers/src/gas-prices-controller.test.ts
examples/example-controllers/src/gas-prices-controller.ts
examples/example-controllers/src/index.ts
examples/example-controllers/src/pet-names-controller.test.ts
examples/example-controllers/src/pet-names-controller.ts

Rename `ControllerMessenger` to `Messenger` in the controller docs and examples.
N/A

chore(docs): Rename `ControllerMessenger` to `Messenger`

---

eslint.config.mjs

The default behavior for this rule enforces that a switch statement handle all possible values that the given variable could be, including type unions. This rule seems to be acting differently in different environments, especially CI, preventing developers from merging PRs. We could disable this rule entirely, but let's try relaxing it a bit to see if that improves the situation.
(N/A; developer-only change)

Relax switch-exhaustiveness-check lint rule

---

eslint-warning-thresholds.json
eslint.config.mjs

The `n/no-unsupported-features/es-builtins`, `n/no-unsupported-features/es-syntax`, and `n/no-unsupported-features/node-builtins` ESLint rules ensure that production code is not using features of JavaScript that are unsupported by the expected version of Node. It does this by keeping track of which versions various features will become generally available and failing if the version of Node it sees does not match.
By default, this rule uses `engines.node` to know which is the "expected version of Node". While that is fine for production code, we use a later version of Node — which is set to the current LTS version — for tests, and therefore we may be allowed to use features that were once experimental in previous versions.
To fix this, this commit overrides the three …

Use dev Node to check for unsupported Node builtins in tests

---

packages/accounts-controller/package.json
yarn.lock

Bumping accounts-related dependencies.
N/A
- **CHANGED**: Bump `@metamask/eth-snap-keyring` from `^8.0.0` to `^8.1.0`

chore(accounts-controller): bump eth-snap-keyring to 8.1.0

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/keyring-controller/package.json
packages/message-manager/CHANGELOG.md
packages/message-manager/package.json
packages/profile-sync-controller/package.json
packages/transaction-controller/package.json
yarn.lock

New RC for the `284.0.0`
- **BREAKING:** Base class of `DecryptMessageManager` and `EncryptionPublicKeyManager`(`AbstractMessageManager`) now expects new options to initialise ([#5103](https://github.com/MetaMask/core/pull/5103))
- Bump `@metamask/base-controller` from `^7.0.0` to `^7.1.0` ([#5079](https://github.com/MetaMask/core/pull/5079))
- **BREAKING:** Removed internal event emitter (`hub` property) from `AbstractMessageManager` ([#5103](https://github.com/MetaMask/core/pull/5103))
- **BREAKING:** `unapprovedMessage` and `updateBadge` removed from internal events. These events are now emitted from messaging system ([#5103](https://github.com/MetaMask/core/pull/5103))
- Controllers should now listen to `DerivedManagerName:X` event instead of using internal event emitter.
- Bump …

Release `284.0.0`

---

package.json
packages/queued-request-controller/CHANGELOG.md
packages/queued-request-controller/package.json
packages/selected-network-controller/CHANGELOG.md
packages/selected-network-controller/package.json
yarn.lock

This release centers around reverting changes to the following packages so that a per-dapp selected network is not the default, but rather opt-in. This is required in order to be able to keep Mobile on the latest versions of these packages as it has not yet been updated to support the Per-Dapp Selected Network feature.
- `@metamask/queued-request-controller` (8.0.2 -> 9.0.0)
- `@metamask/selected-network-controller` (20.0.2 -> 21.0.0)

Release 286.0.0

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/create-service-policy.test.ts
packages/controller-utils/src/create-service-policy.ts
packages/controller-utils/src/index.ts

Both RetryPolicy and CircuitBreakerPolicy from the Cockatiel library allow for listening for events using `on*` methods. For instance, if you have a retry policy, you can listen for when the function is retried like so:
``` typescript
retryPolicy.onRetry(() => {
// ...
})
```
Our "service policy" allows for listening to some of the same events as well as the "degraded" event. Instead of exposing `on*` methods, however, `createServicePolicy` takes callbacks in an options bag:
``` typescript
createServicePolicy({
// ...
onRetry: () => {
// ...
}
)
```
For parity with Cockatiel — and for easier use in general — this commit changes the API so that the object that `createServicePolicy` returns now includes similar `on*` methods. This way you can say:
``` typescript
const policy = …
```

createServicePolicy: Convert callbacks to methods

---

eslint-warning-thresholds.json
packages/network-controller/CHANGELOG.md
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

When running tests, we are seeing the following warning:
> An input selector returned a different result when passed same arguments. This means your output selector will likely run more frequently than intended.
This is happening because the "input selector" in `selectAvailableNetworkClientIds` returns a new object reference (returned by `getNetworkConfigurations`) each time it is called. This violates the Redux guidelines outlined here: <https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization>.
To fix this, we split off the "input selector" into its own selector function which we then memoize.
(Updated in PR.)

Fix NetworkController Redux selectors

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/jest.config.js
packages/controller-utils/src/create-service-policy.ts
packages/controller-utils/src/index.test.ts
packages/controller-utils/src/index.ts

Expose these exports from `cockatiel` so consumers can use them without needing to depend on the library directly:
- `BrokenCircuitError`
- `CircuitState`
- `handleAll`
- `handleWhen`
Also, update `createServicePolicy` to expose the retry and circuit breaker policies so that we can access their state in other modules that use this utility function.
This is needed to be able to create an RPC service.
Progresses https://github.com/MetaMask/core/issues/4994.
Pre-requisite to https://github.com/MetaMask/core/issues/4990.
(Updated in changelog.)

Update `createServicePolicy` to expose sub-policies; add re-exports from `cockatiel`

---

packages/notification-services-controller/package.json
yarn.lock

Updates the `firebase` module from `^10.11.0` to `^11.2.0`.
This update fixes a undici audit issue (see references).
I've checked the v11 update:
1. It resolves the audit issue. (currently) there is no `v10.x.x` firebase package that resolves this audit issue.
2. We only use `firebase/messaging`, which is not a major version bump and has been validated to be work with `v11.x.x`
**NOTE:**
Ideally it would be nice to just utilise `firebase/messaging`, but the firebase npm recommends the full package.
Maybe we can explore a smaller, trimmed down firebase package that doesn't include everything?
**TEST:**
1. Navigate to the `notification-services-controller` package.
2. Run `yarn npm audit --recursive --environment production --severity moderate` and see audit logs.
Extension PR to fix undici …

feat: update notification controller firebase package

---

packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/multichain-transactions-controller/package.json
packages/profile-sync-controller/package.json
yarn.lock

This PR bumps `@metamask/snaps-sdk `to v6.16.0
N/A
- **CHANGED**: Bump `@metamask/snaps-sdk` to `v6.16.0`
- **CHANGED**: Bump `@metamask/snaps-sdk` to `v6.16.0`
- **CHANGED**: Bump `@metamask/snaps-sdk` to `v6.16.0`
- **CHANGED**: Bump `@metamask/snaps-sdk` to `v6.16.0`

feat: bump snaps-sdk to v6.16.0

---

packages/approval-controller/src/ApprovalController.test.ts
packages/approval-controller/src/ApprovalController.ts

Rename `ControllerMessenger` to `Messenger` in the `@metamask/approval-controller` package.

chore(approval): Rename `ControllerMessenger` to `Messenger`

---

packages/ens-controller/src/EnsController.test.ts
packages/ens-controller/src/EnsController.ts

Rename `ControllerMessenger` to `Messenger` in the `@metamask/ens-controller` package.

chore(ens): Rename `ControllerMessenger` to `Messenger`

---

packages/composable-controller/src/ComposableController.test.ts
packages/composable-controller/src/ComposableController.ts

Rename `ControllerMessenger` to `Messenger` and `RestrictedControllerMessenger ` to `RestrictedMessenger ` in the `@metamask/composable-controller` package.

chore(composable): Rename `ControllerMessenger` to `Messenger`

---

packages/multichain-transactions-controller/src/MultichainTransactionsController.test.ts
packages/multichain-transactions-controller/src/MultichainTransactionsController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/multichain-transactions` package.

chore(multichain-transactions):  Rename `RestrictedControllerMessenger` to `RestrictedMessenger`

---

packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/keyring-controller` package.

chore(keyring): Rename `RestrictedControllerMessenger` to `RestrictedMessenger`

---

packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/notification-services-controller` package.

chore(notification-services): Rename `ControllerMessenger` to `Messenger`

---

packages/polling-controller/src/BlockTrackerPollingController.test.ts
packages/polling-controller/src/StaticIntervalPollingController.test.ts

Rename `ControllerMessenger` to `Messenger` in the `@metamask/polling-controller` package.

chore(polling): Rename `ControllerMessenger` to `Messenger`

---

packages/permission-log-controller/src/PermissionLogController.ts
packages/permission-log-controller/tests/PermissionLogController.test.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/permission-log-controller` package.

chore(permission-log): Rename `ControllerMessenger` to `Messenger`

---

packages/base-controller/src/BaseControllerV1.test.ts
packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/BaseControllerV2.ts
packages/base-controller/src/Messenger.ts
packages/base-controller/tests/helpers.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/base-controller` package.

chore(base): Rename `ControllerMessenger` to `Messenger`

---

packages/permission-controller/ARCHITECTURE.md
packages/permission-controller/src/PermissionController.test.ts
packages/permission-controller/src/PermissionController.ts
packages/permission-controller/src/SubjectMetadataController.test.ts
packages/permission-controller/src/SubjectMetadataController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/permission-controller` package.

chore(permission): Rename `ControllerMessenger` to `Messenger`

---

packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/preferences-controller` package.

chore(preferences): Rename `ControllerMessenger` to `Messenger`

---

packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/network-controller` package.

chore(network): Rename `ControllerMessenger` to `Messenger`

---

packages/phishing-controller/src/PhishingController.test.ts
packages/phishing-controller/src/PhishingController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/phishing-controller` package.

chore(phishing): Rename `ControllerMessenger` to `Messenger`

---

packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockMessenger.ts
packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/profile-sunc-controller` package.

chore(profile-sync): Rename `ControllerMessenger` to `Messenger`

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/selected-network-controller` package.

chore(selected-network): Rename `ControllerMessenger` to `Messenger`

---

packages/earn-controller/src/EarnController.test.ts
packages/earn-controller/src/EarnController.ts

Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger` in the `@metamask/earn-controller` package.

chore(earn): Rename ControllerMessenger to Messenger

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts

This PR removes MetaMetrics dependencies in `UserStorageController` as those are needed only for `AuthenticationController`. 
Fixes: https://consensyssoftware.atlassian.net/browse/IDENTITY-15
- **BREAKING**: Remove MetaMetrics dependencies from `UserStorageController`

feat: remove metametrics dependencies in UserStorageController

---

packages/assets-controllers/src/MultichainAssetsController/MultichainAssetsController.test.ts

Rename `ControllerMessenger` to `Messenger`  in the `MultichainAssetsController.test.ts` in `@metamask/assets-controllers` package.

chore(multichain-assets): Rename `ControllerMessenger` to `Messenger`

---

packages/token-search-discovery-controller/CHANGELOG.md
packages/token-search-discovery-controller/src/index.ts

We are not explicitly exporting the `TokenSearchDiscoveryControllerMessenger` type from package index and therefor consumers are forced to import from the common js module.
Needed to resolve a comment in related to these types of imports: https://github.com/MetaMask/metamask-mobile/pull/13111
- **Added**: export `TokenSearchDiscoveryControllerMessenger` type from index

chore: export controller messenger type to index

---

.github/workflows/create-update-issues.yaml

This PR modifies how tags are fetched in the create-update-issues workflow by replacing the `fetch-tags` input parameter with an explicit `git fetch` command.
- Removed `fetch-tags: true` from checkout action
- Added separate step to fetch tags using `git fetch --prune --unshallow --tags`
This change provides more explicit control over tag fetching and ensures we get a complete tag history with pruning of stale refs.

chore: Improve tag fetching in create-update-issues workflow

---

package.json
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/package.json
packages/assets-controllers/package.json
packages/earn-controller/package.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/package.json
packages/multichain-transactions-controller/package.json
packages/notification-services-controller/package.json
packages/preferences-controller/package.json
packages/profile-sync-controller/package.json
packages/signature-controller/package.json
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

Release for the support of OneKey devices.
Those devices were already supported, but they will use a new specific keyring `OneKeyKeyring` to distinguish them from normal Trezor devices. Both keyring shares the same logic and the same bridge logic too.

Release 298.0.0

---

packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR exposes all (but the dangerous `deleteAllFeatureEntries`) user storage methods
Fixes: 
- https://github.com/MetaMask/core/issues/4937
- https://consensyssoftware.atlassian.net/browse/IDENTITY-29
- **ADDED**: Added `performBatchSetStorage`, `performDeleteStorage` and `performBatchDeleteStorage` to the exposed messenger actions

feat: expose all user storage methods through messenger actions

---

packages/multichain/src/handlers/wallet-getSession.ts

`@metamask/multichain` was importing `src/scope/types`, which does not work when importing the library in other projects. I've changed it to `../scope/types` instead.
- **FIXED**: Fix invalid type import path

Fix invalid type import path in `@metamask/multichain`

---

.github/CODEOWNERS

The package `@metamask/selected-network-controller` is now owned solely by the Wallet API Platform team, rather than being shared between multiple teams. This team has the most context for what this code does, and it will in the future be increasingly less relevant to the rest of the wallet apart from supporting the EIP-1193 provider.
N/A
N/A

chore: Change ownership of SelectedNetworkController

---

packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts

This PR changes the default value for account syncing's `maxNumberOfAccountsToAdd` from `100` to `Infinity`.
It will become the client's responsibility to set this number to a specific value. If not specified, account sync will synchronize every account.
Related to: https://consensyssoftware.atlassian.net/browse/IDENTITY-28
- **CHANGED**: change `maxNumberOfAccountsToAdd` default value from `100` to `Infinity`

fix: change maxNumberOfAccountsToAdd default value from 100 to Infinity

---

packages/keyring-controller/src/KeyringController.ts

This is a suggestion on how to improve error handling for keyring metadata in the PR #5112. See #5112 for more details.
Related discussion thread: https://github.com/MetaMask/core/pull/5112/files#r1946679193
N/A

chore: Improve error handling related to keyring metadata

---

packages/accounts-controller/package.json
packages/multichain-network-controller/package.json
yarn.lock

The 2 controllers depend on each other, however we cannot really express this with peer deps.
So for now, we only declare this "relation" on the new controller `mutltichain-network-controller`.
Also downgrading some peer dep to use the major version.
N/A
N/A

fix: fix peer deps for `@metamask/{accounts,multichain-network}-controller`

---

jest.config.packages.js
jest.config.scripts.js
package.json
yarn.lock

Jest doesn't support Prettier 3, so after the migration to ESLint 9 (requiring Prettier 3), Jest snapshots could no longer be created or updated. The recommended solution by Jest is to add `prettier-2` as separate dependency and referencing that in the config.

Use Prettier 2 for Jest

---

.github/CODEOWNERS

The Wallet Framework team must be co-owners of all `package.json` and `CHANGELOG.md` to ease releases.
It's only important for transversal version bumps (like when bumping `@metamask/utils`.
N/A
N/A

chore: fix selected-network-controller CODEOWNERS

---

.github/CODEOWNERS

There were no official owners for the `remote-feature-flag-controller`.
N/A
N/A

chore: fix remote-feature-flag-controller CODEOWNERS

---

.github/CODEOWNERS

CODEOWNER rules have been added for all packages that are currently missing them:
* `example-controllers`: These are examples maintained by the wallet framework team.
* `mutlichain-network-controller`: This package has been a collaboration between many teams, but for now the owners have been set to the same as the `network-controller` plus the accounts team (who proposed this controller's creation). We can change this further if appropriate.
The `multichain-network-controller` package was added here: https://github.com/MetaMask/core/pull/5215
N/A

chore: Add missing CODEOWNER package rules

---

yarn.config.cjs

Add Yarn constraints to ensure each package has a designated owner, and that any non-wallet-frameowrk packages have the wallet framework team set as co-owners of release related files.
N/A
N/A

ci: Add CODEOWNER constraints

---

packages/assets-controllers/src/crypto-compare-service/crypto-compare.test.ts
packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts

Inspecting extension shows that we fetch the conversion rate using this URL:
https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=MNT
This is incorrect as it is not using the correct symbol override. The url should be:
https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=MANTLE
This gives a much better unsupported conversion number that what it currently is.
- **FIXED**: update `crypto-compare-service` `fetchExchangeRate` to allow symbol overrides for mantle.

fix: Add MANTLE support for conversion rates

---

packages/bridge-controller/src/bridge-controller.test.ts
packages/bridge-controller/src/bridge-controller.ts
packages/bridge-controller/src/constants/bridge.ts
packages/bridge-controller/src/types.ts
packages/bridge-status-controller/src/bridge-status-controller.test.ts
packages/bridge-status-controller/src/bridge-status-controller.ts
packages/bridge-status-controller/src/constants.ts
packages/bridge-status-controller/src/index.ts
packages/bridge-status-controller/src/types.ts

This PR changes the state shape of `BridgeController` and `BridgeStatusController` to better match the standard shape with all the relevant fields at the root of `state` rather than behind a redundant field like `state.bridgeState` or `state.bridgeStatusState`.
It also changes the default values from `undefined` to `null` to better support Mobile efforts.
- BREAKING: Data fields have been moved to the root of the `state` object, rather than behind a redundant field `state.bridgeState`
- BREAKING: Default values have been changed from `undefined` to `null`.
- BREAKING: Data fields have been moved to the root of the `state` object, rather than behind a redundant field `state.bridgeStatusState`
- BREAKING: Redundant type `BridgeStatusState` removed from exports

chore: change bridge state structure to have all fields at root of state

---

packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/eip7702.test.ts
packages/transaction-controller/src/utils/eip7702.ts

Update the `TransactionController` to use the sign authorization action type defined in the `KeyringController` rather than the internal one created for testing.
- **BREAKING**: Require messenger permissions for `KeyringController:signEip7702Authorization` action.

chore: align keyring controller sign authorization action

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

The calling workflow needs to set the permissions

fix(actions): Calling workflow must have the permissions set

---

.github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml

We are using classic projects so need to add additional permissions of `projects: write`

fix(actions): Update to work for classic projects

---

packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

Speed up account iteration logic in `updateAccounts` by using `KeyringController:getState` instead of getting all of the addresses upfront and matching them to the keyring afterwards. The current implementation is fast on extension, but really slows down on mobile once you have a couple of accounts added. This simplified implementation has better performance characteristics and as such performs better on mobile.
- **Changed**: Speed up `updateAccounts` logic when iterating over multiple accounts
- This requires allowlisting `KeyringController:getState` as an allowed action for the AccountsController

perf: Simplify account iteration logic

---

packages/earn-controller/src/EarnController.ts

This PR updates the default `days` value from `30` to `365` when refreshing pooled staking vault apys. This means we pull one year worth of apys by default.
- **CHANGED**: Updated `refreshPooledStakingVaultDailyApys` `days` argument default value from `30` to `365`

feat: updated refreshPooledStakingVaultDailyApys days arg default value to 365

---

packages/assets-controllers/src/NftDetectionController.test.ts
packages/assets-controllers/src/NftDetectionController.ts

This PR addresses an issue in NFT detection where the code attempts to destructure the imageOriginal property from the NFT token's metadata field. When metadata is null, this results in the runtime error:
`"null is not an object (evaluating '(w=void 0===w?{}:w).imageOriginal')"`
To fix the issue, the NFT detection logic has been updated to safely handle cases where metadata is null by providing a fallback (e.g., using an empty object or optional chaining). This prevents the error and ensures that NFT tokens without metadata are processed without causing a runtime exception.
Fixes: [12517](https://github.com/MetaMask/metamask-mobile/issues/12517) 
- **FIXED**: Resolved runtime error in NFT detection by safely handling null metadata during destructuring.

fix: fix case when metadata are null

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

Support batch ID associated with each transaction.
Specifically:
- Add optional `batchId` to `TransactionMeta`.
- Add optional `batchId` to `addTransaction` options.
- Add optional `batchId` to `TransactionBatchRequest`.
- Throw if batch ID is duplicate.
- Add missing properties to `TransactionReceipt` and `Log`.

feat: add transaction batch ID

---

eslint-warning-thresholds.json
packages/signature-controller/package.json
packages/signature-controller/src/SignatureController.test.ts
packages/signature-controller/src/SignatureController.ts
packages/signature-controller/src/types.ts
packages/signature-controller/src/utils/validation.test.ts
packages/signature-controller/src/utils/validation.ts
packages/signature-controller/tsconfig.build.json
packages/signature-controller/tsconfig.json
yarn.lock

Add additional validations to `signTypedData` requests to protect EOAs that have been upgraded to a smart contract account via EIP-7702.
Specifically:
- Throw if `verifyingContract` matches any internal EOA account.
- Throw if `primaryType` is `Delegation` and `delegator` matches any internal EOA account.
- Add dependency on `@metamask/accounts-controller`.

feat: add EIP-7702 signature validations

---

packages/bridge-controller/src/index.ts

This PR exports enums from `bridge-controller` as values rather than just as types.
- CHANGED: `AssetType, SortOrder, BridgeFlag, ActionTypes, ChainId, BridgeFeatureFlagsKey, RequestStatus, BridgeUserAction, BridgeBackgroundAction, FeeType` enums now exported properly rather than just as types.

chore: export enums properly rather than as types

---

.github/workflows/ensure-blocking-pr-labels-absent.yml
.github/workflows/lint-build-test.yml
.github/workflows/main.yml
.github/workflows/publish-preview.yml
.github/workflows/publish-release.yml
.github/workflows/security-code-scanner.yml

This updates all workflows to remove the use of `actions/checkout`, `actions/setup-node`, `actions/cache`. The implementation here is based on MetaMask/snaps#3214.
MetaMask-planning#3925.
n/a, this doesn't make any changes to packages directly.

Update workflows to use `MetaMask/action-checkout-and-setup`

---

packages/base-controller/src/BaseControllerV2.test.ts
packages/base-controller/src/BaseControllerV2.ts

Some controllers may use conditionals inside `this.update()` and potentially end up not modifying the `draftState` at all. In this case, we would currently still emit `:stateChange` and listening controllers would treat this as a state update if they don't inspect the `patches`. This PR adjusts this logic slightly, letting us only emit events when the state has actually changed. This reduces unnecessary events being emitted and consumed by listening controllers.
Feedback appreciated!
- **Changed**: Don't emit `:stateChange` from `BaseController` unnecessarily

perf: Don't emit `:stateChange` from `BaseController` unnecessarily

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

The root problem is that an uppercase hex string is being passed into new BN(..., 10), causing it to be interpreted as a decimal value. To fix this, avoid calling toHex on addresses that are already in 0x format.
* Fixes [#13450](https://github.com/MetaMask/metamask-mobile/issues/13450)
- **FIXED**: Resolved the issue that was causing an invalid character error.

fix: fix invalid character error

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts
packages/transaction-controller/src/utils/eip7702.test.ts
packages/transaction-controller/src/utils/eip7702.ts

Add additional transaction metadata to support client metrics for transaction batch.
Specifically:
- Save `delegationAddress` for each transaction.
- Determine `transactionType` for each nested transaction.
- Add `error` to metadata in `transactionRejected` event.
- Simplify `TransactionMetadata` type.

feat: support transaction batch metrics

---

packages/network-controller/CHANGELOG.md
packages/network-controller/src/NetworkController.ts
packages/network-controller/src/create-network-client.ts
packages/network-controller/src/index.ts
packages/network-controller/src/rpc-service/rpc-service.ts
packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
packages/network-controller/tests/provider-api-tests/block-param.ts
packages/network-controller/tests/provider-api-tests/no-block-param.ts

In the clients we want the ability to decide whether or not to create a Segment error when a request to Infura fails too many times in a row. Specifically, we want to be able to ignore connection errors, as they may indicate that the user is offline, in which case we don't need to fail over to Quicknode.
To accommodate this need:
- Expose the error that was encountered while making the request in the `NetworkController:rpcEndpointUnavailable` event data.
- Export `isConnectionError` from `RpcService`.
Progresses https://github.com/MetaMask/core/issues/5493.
(Updated in PR.)

Expose error in NetworkController:rpcEndpointUnavailable event

---

packages/network-controller/CHANGELOG.md
packages/network-controller/src/NetworkController.ts
packages/network-controller/src/create-network-client.ts

This represents the ID of the chain that the degraded RPC endpoint represents, and is necessary in order to submit a Segment event that includes that chain ID.
(Updated in PR.)

Add chainId to NetworkController:rpcEndpointDegraded

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/feature-flags.ts
packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts
packages/transaction-controller/src/utils/simulation-api.ts

The gas for type 4 transactions that include `data` to the upgraded account can only be estimated using `eth_estimateGas` if the real signature properties are included, otherwise the upgraded address cannot be known since it is derived from the signature itself.
As we don't want to sign an authorisation until the user approves the transaction, we will instead:
1. Estimate only the upgrade, with no data and a dummy signature, using `eth_estimateGas`.
2. Estimate the data only on the resulting upgraded EOA using the simulation API to override the account code.
3. Add the two values together, and subtract the intrinsic gas cost (`21000`).
Fixes [#31140](https://github.com/MetaMask/metamask-extension/issues/31140)

fix: gas estimation for type 4 transactions

---

packages/assets-controllers/src/TokenRatesController.test.ts
packages/assets-controllers/src/TokenRatesController.ts

When onboarding, we make token rates requests with 0 tokens, and then follows up with >0 tokens (once detected).
However the old approach aborts the most recent request (that contains new tokens), which prevents the UI from updating with rates until the next polling cycle (or if we stop/start polling again).
My hypothesis is, since we've improved the front-end performance on Extension and Mobile to reduce re-renders, we have optimised our polling hooks to not be recalled (reducing the number of times we stop/start the polling services). And because of the reduced poll restarts, we've uncovered this bug.
- **FIXED**: updated token rate request key to handle when new tokens are detected inside the `TokenRatesController`

fix: improve token rate response aborting

---

packages/earn-controller/src/EarnController.test.ts
packages/earn-controller/src/EarnController.ts
packages/earn-controller/src/types.ts

This PR updates a few earn-controller methods to have an options bag argument. It also updates the `selectedAccountChange` subscription handler to pass the `account.address` from the event payload into the underlying methods instead of relying on `getSelectedAccount`.
Recently, a [race condition](https://github.com/MetaMask/accounts-planning/issues/887) was discovered in the `accounts-controller` that causes a discrepancy between the account data in the `selectAccountChange` event payload and what's retrieved using `getSelectedAccount`. 
The `selectAccountChange` event payload has the accurate account state and is now passed into `refreshStakingEligibility` and `refreshPooledStakes` to ensure they have the latest account data to work with. 
Once the issue has been resolved and the …

feat: earn controller convert method args to options bags

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

Support triggering security validation in the client while processing transaction batches.
Specifically:
- Add `ValidateSecurityRequest` type.
- Add optional `validateSecurity` callback to `TransactionBatchRequest` type.
- Add optional `securityAlertId` to `AddTransactionBatchRequest` type.
- Add optional `securityAlertId` to `SecurityAlertResponse` type.
- Call `validateSecurity` callback after generating EIP-7702 transaction.
- Include `delegationMock` if an EIP-7702 type 4 transaction.
Relates to [ #31263](https://github.com/MetaMask/metamask-extension/issues/31263)

feat: transaction batch security validation

---

eslint-warning-thresholds.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

Backporting https://github.com/MetaMask/core/commit/9ba2967325bfcd355a033968d1ef43a055be8a51 into KeyringController v19.x
Changelog updated in the original PR

[19.x] Backport `fix: keyrings restore failure`

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/simulation-api.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts

Retrieve the available gas fee tokens from the simulation API when adding a transaction, and save them in the transaction metadata.
Specifically:
- Add `gasFeeTokens` to `TransactionMetadata`.
- Add `selectedGasFeeToken` to `TransactionMetadata`.
- Add additional request and response properties to types in `utils/simulation-api.ts`.
- Update `utils/simulation.ts` to parse the gas fee tokens from the response. 
Fixes [#4458](https://github.com/MetaMask/MetaMask-planning/issues/4458)

feat: add gas fee tokens to transaction metadata

---

packages/chain-agnostic-permission/src/caip25Permission.test.ts
packages/chain-agnostic-permission/src/caip25Permission.ts

We need to add further caveat validation to throw when no scopes are requested in either `requiredScopes` or `optionalScopes`
See this thread: https://consensys.slack.com/archives/C089Q8CQZHT/p1742825693477409
- **ADDED**: **BREAKING** Validation check in `caip25CaveatBuilder` to prevent creating permission requests with no scopes. This ensures that all CAIP-25 permission requests must specify at least one scope in either `requiredScopes` or `optionalScopes`.

throw error in caveat validator when caip25:endowment permission caveat when no scopes are requested

---

packages/chain-agnostic-permission/src/index.test.ts
packages/chain-agnostic-permission/src/index.ts

Tiny oversight. Need to export `KnownSessionProperties` from the package index file!

export `KnownSessionProperties` from chain-agnostic-permission package

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/GasFeePoller.test.ts
packages/transaction-controller/src/helpers/GasFeePoller.ts
packages/transaction-controller/src/utils/utils.ts

This PR aims to fix an issue where `updateTransactionGasFees` updater rejects updating draft state with following error:
`TypeError: Cannot perform 'get' on a proxy that has been revoked`
The fix is to remove that async operation because it's unnecessary to check it again since it's been check while `addTransaction`
- **FIXED**: Fix type error when `enableTxParamsGasFeeUpdates` is set to `true`

fix: Remove async operation from `updateTransactionGasFees`

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/network-controller/src/NetworkController.ts
packages/network-controller/src/types.ts
packages/network-controller/tests/NetworkController.test.ts
packages/transaction-controller/src/constants.ts
tests/mock-network.ts

Further to Previous PR: #5495 
We are adding MegaETH Testnet as default network on `Network Controller` default state - `networkConfigurationsByChainId` with the constants and type from the latest `controller-utils`
In additional, a new constructor option `addtionalDefaultNetworks` has introduced in `NetworkController` to 
**_prevent client push the new network unintentionally_** 
(such as bump up the network controller without support on the client side)
- Add Constructor Option `addtionalDefaultNetworks `  to specify the additional default networks to be included, which allows backward compatible and only include the Network if it has ready on client side (by developer specify)
- Refactor the logic to separate the construction of default network configurations to …

feat: add `MegaETH Testnet` to network-controller

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.ts
packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.ts
packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.ts
packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.ts
packages/transaction-controller/src/gas-flows/RandomisedEstimationsGasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/RandomisedEstimationsGasFeeFlow.ts
packages/transaction-controller/src/gas-flows/ScrollLayer1GasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/ScrollLayer1GasFeeFlow.ts
packages/transaction-controller/src/gas-flows/TestGasFeeFlow.test.ts
packages/transaction-controller/src/gas-flows/TestGasFeeFlow.ts
packages/transaction-controller/src/helpers/GasFeePoller.test.ts
packages/transaction-controller/src/helpers/GasFeePoller.ts
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/feature-flags.test.ts
packages/transaction-controller/src/utils/feature-flags.ts
packages/transaction-controller/src/utils/gas-fees.test.ts
packages/transaction-controller/src/utils/gas-fees.ts
packages/transaction-controller/src/utils/gas-flow.test.ts
packages/transaction-controller/src/utils/gas-flow.ts
packages/transaction-controller/src/utils/layer1-gas-fee-flow.test.ts
packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts

This PR aims to add `RandomisedEstimationsGasFeeFlow` to gas fee flows in `TransactionController`.
Depending on the remote feature flags, `RandomisedEstimationsGasFeeFlow` randomises the last digits of given estimations. To see exact randomisation it is happening `randomiseDecimalValueAndConvertToHex` function in the `RandomisedEstimationsGasFeeFlow.ts` file. Also in case of any error this gas fee flow will default to `DefaultGasFeeFlow`.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/4446
https://github.com/user-attachments/assets/4000ba5b-30b9-42f9-bc07-8ffac40ffc3d
- **ADDED**: Adds `RandomisedEstimationsGasFeeFlow` to gas fee flows in `TransactionController`
- Added flow only will be activated if `chainId` is defined in feature flags.

feat: Add `RandomisedEstimationsGasFeeFlow` to gas fee flows

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/feature-flags.test.ts
packages/transaction-controller/src/utils/feature-flags.ts

Pad chain ID with leading zero if odd-length in order to prevent signature validation from silently failing.
Relates to [#31388](https://github.com/MetaMask/metamask-extension/issues/31388)

fix: validation of EIP-7702 contract signatures with odd-length chain ID

---

packages/assets-controllers/src/TokenDetectionController.test.ts
packages/assets-controllers/src/TokenListController.test.ts
packages/gas-fee-controller/src/GasFeeController.test.ts
packages/network-controller/src/NetworkController.ts
packages/network-controller/src/constants.ts
packages/network-controller/tests/NetworkController.test.ts
packages/network-controller/tests/helpers.ts
packages/network-controller/tests/provider-api-tests/shared-tests.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts

This PR is not to deprecated `goerli` and `linea goerli` , but just remove `goerli` and `linea goerli` from `network-controller` as default network, which will not impact to the reference of those network constants / type
Hence the mobile / extension no longer require to using patching or hardcode to remove the network for new installed user
- **CHANGED**: Remove `goerli` and `linea goerli` network as default network

chore: remove `goerli` and `linea goerli` from `network-controller` as default network

---

packages/multichain-transactions-controller/src/MultichainTransactionsController.test.ts
packages/multichain-transactions-controller/src/MultichainTransactionsController.ts
packages/multichain-transactions-controller/src/index.ts

We are sending two events `transactionFinalized` and `transactionSubmitted` in order to track these in the client, and send out the necessary metrics.

chore: sends transaction update events

---

packages/signature-controller/src/utils/validation.test.ts
packages/signature-controller/src/utils/validation.ts

It seems we've broken some dapps that rely on EIP712 / `eth_signTypedData_v4` signatures which don't include `verifyingContract` as part of their payload.
See: https://github.com/MetaMask/metamask-extension/issues/31607
For example:
* Fixes #12345
* Related to #67890
-->

Stop throwing an error if `verifyingContract` field in EIP712 payloads is undefined or not a string

---

packages/earn-controller/package.json
packages/earn-controller/src/EarnController.test.ts
packages/earn-controller/src/EarnController.ts
packages/earn-controller/tsconfig.build.json
packages/earn-controller/tsconfig.json
yarn.lock

This PR updates the `EarnController` to refresh a user's pooled-staking data when a staking transaction is confirmed. Non-staking transaction types are ignored.
- Added a new subscription to the `TransactionController:transactionConfirmed` event has been added.
- Added `@metamask/transaction-controller` has been added as a dev dependency.
- Added related tests.
Jira ticket: [[Earn-Controller] Refresh staking data when staking transactions are confirmed](https://consensyssoftware.atlassian.net/browse/STAKE-1005)

feat: STAKE-1005: refresh staking data when staking txs are confirmed

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/TransactionControllerIntegration.test.ts
packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.ts
packages/transaction-controller/src/helpers/GasFeePoller.test.ts
packages/transaction-controller/src/helpers/GasFeePoller.ts

This PR aims to rename `enableTxParamsGasFeeUpdates` to `isAutomaticGasFeeUpdateEnabled` and make it a callback function instead of a boolean.
This callback is invoked before performing `txParams` gas fee updates. The update will proceed only if the callback returns a truthy value.
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/4595
Mobile update PR: https://github.com/MetaMask/metamask-mobile/pull/14470 (Not updated package yet since major update PR in review https://github.com/MetaMask/metamask-mobile/pull/14326 )
Extension update PR:

fix: Rename `enableTxParamsGasFeeUpdates` to `isAutomaticGasFeeUpdateEnabled` and also callback

---

packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/src/controllers/authentication/auth-snap-requests.ts

We are making a change to the SnapController to more strictly validate the `origin` parameter. This disallows empty string which was previously allowed. This PR updates the `profile-sync-controller` to comply with these new requirements.

fix: Update origin in Snap requests

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.test.ts
packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.ts
packages/transaction-controller/src/types.ts

If `queryEntireHistory` is `false`, query incoming transactions from the last 24 hours.
If no cursor is returned, cache the `startTimestamp` and use that in subsequent queries until a cursor is available.
Fixes [#30902](https://github.com/MetaMask/metamask-extension/issues/30902)

fix: cache incoming transaction timestamps

---

packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.test.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.test.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.ts
packages/profile-sync-controller/src/controllers/user-storage/account-syncing/types.ts

Since account syncing is now enabled by default in both clients, we are removing the possibility to control `isAccountSyncingEnabled` from the `UserStorageController` contructor `env` property.
In a subsequent PR, we'll introduce a new `isAccountSyncingEnabled` state property, and expose a way to toggle it from the clients. For now, all clients dispatch account syncing depending on if `isProfileSyncingEnabled` is `true`, so we can do this change in another PR without risking to break anything.
The UTs flagged with `it.todo` in the PR will then be updated using this new state property.
This change is **BREAKING**, and the clients need to remove the `isAccountSyncingEnabled` property from `UserStorageController` `env` when instantiating the controller.
Related to: …

feat: remove `isAccountSyncingEnabled` `env` property from `UserStorageController` constructor

---

packages/multichain-network-controller/CHANGELOG.md
packages/multichain-network-controller/src/MultichainNetworkController.test.ts
packages/multichain-network-controller/src/MultichainNetworkController.ts
packages/multichain-network-controller/tests/utils.ts

This PR introduces two small changes,
1. Remove object de-structuring on controller constructor
2. Fix the condition to update the active network based on the account event
Fixes https://github.com/MetaMask/accounts-planning/issues/857
```
- Fix the condition to update the active network based on the account event.
```

fix: update active network based on account's namespace

---

packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

This PR removes unused `UserStorageController` action handlers: `setIsBackupAndSyncFeatureEnabled`, `syncInternalAccountsWithUserStorage` and `saveInternalAccountToUserStorage`, as they should not be callable through the messaging system.
This is a **BREAKING** change, although no other Controller should use them at the moment.
Fixes: https://consensyssoftware.atlassian.net/browse/IDENTITY-84
Extension test drive PR (CI ✅): https://github.com/MetaMask/metamask-extension/pull/31945
View CHANGELOG.md changes.

feat: remove unused action handlers

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/constants.ts
packages/transaction-controller/src/utils/feature-flags.test.ts
packages/transaction-controller/src/utils/feature-flags.ts
packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts

Use feature flags to configure the gas estimation buffers, including support for specific chain and type-4 buffers.
```js
[FeatureFlag.GasBuffer]?: {
/** Fallback buffer for all chains and transactions. */
default?: number;
/**
* Buffer for included network RPCs only and not those added by user.
* Takes priority over `default`.
*/
included?: number;
/** Buffers for specific chains. */
perChainConfig?: {
[chainId: Hex]: {
/**
* Buffer for the chain for all transactions.
* Takes priority over non-chain `included`.
*/
base?: number;
/**
* Buffer if network RPC is included and not added by user.
* Takes priority over `base`.
*/
included?: number;
/**
* Buffer for the chain for EIP-7702 / type 4 transactions only.
* Only if `data` included and `to` matches `from`.
* Takes priority over …
```

feat: use feature flags for gas estimation buffers 

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

When calling `submitPassword` with the wrong password, a confusing error is shown instead of `Incorrect password`. This is due to the recently added metadata length check in `#restoreSerializedKeyrings`, which doesn't match the correct behavior when `isUnlocked = true`.
We can move the metadata length check to `#unlockKeyrings`, so that it will be skipped everytime the controller is locked
* Related to https://github.com/MetaMask/metamask-extension/issues/31373
Changelog updated in the PR

fix: confusing error message when using wrong password

---

packages/token-search-discovery-controller/CHANGELOG.md
packages/token-search-discovery-controller/src/index.ts

`SwappableTokenSearchParams` is needed by clients to do proper type checking on params passed to the controller.

Export `SwappableTokenSearchParams` from index

---

.github/workflows/changelog-check.yml

Removes the 'branches' filter from the pull_request trigger for the changelog check workflow.
This allows the workflow to run on pull requests targeting any branch, including release branches, ensuring changelog entries (including dependency bumps) are validated consistently across all PR types.

chore: remove branch filtering from changelog check workflow

---

packages/assets-controllers/src/DeFiPositionsController/__fixtures__/mock-responses.ts
packages/assets-controllers/src/DeFiPositionsController/fetch-positions.ts
packages/assets-controllers/src/DeFiPositionsController/group-defi-positions.test.ts
packages/assets-controllers/src/DeFiPositionsController/group-defi-positions.ts

Use the protocol display name value from the API instead of building it internally.
They are internal changes, no need to add them to changelog.
- **CHANGED**: DeFi protocol name is now received from the API

feat: use new api field for protocol name

---

package.json
yarn.lock

This PR bumps `@metamask/create-release-branch` to `^4.1.2`(see [changelog](https://github.com/MetaMask/create-release-branch/blob/main/CHANGELOG.md#412))
- Improved error handling when opening browser fails due to System Events permissions or non-standard browser configurations

chore: bump `@metamask/create-release-branch` to `^4.1.2`

---

packages/multichain-network-controller/CHANGELOG.md
packages/multichain-network-controller/src/MultichainNetworkController/MultichainNetworkController.test.ts
packages/multichain-network-controller/src/MultichainNetworkController/MultichainNetworkController.ts
packages/multichain-network-controller/src/MultichainNetworkService/MultichainNetworkService.test.ts

This PR temporarily restricts the `getNetworksWithTransactionActivityByAccounts` method to EVM networks only. This change is necessary because:
1. The non-EVM network endpoint support is still being completed and needs additional work
2. We want to ensure reliable functionality for EVM networks while non-EVM support is being finalized
3. This allows us to maintain stable service for our primary use case (EVM networks) while API platform team completes the full multi-chain implementation
- Added a filter to exclude non-EVM accounts from network activity checks
- Updated the `CHANGELOG` to reflect this temporary limitation
- This is an interim solution that will be reverted once non-EVM endpoint support is complete (expected in the coming weeks)
- Related to …

fix(multichain-network): temporarily restrict network activity to EVM

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts

Add optional `afterAdd` hook to mutate transactions added via `addTransaction` method.
Persist original transaction params in new `txParamsOriginal` property.
Fixes [#4688](https://github.com/MetaMask/MetaMask-planning/issues/4688)

feat: Add afterAdd hook to transaction controller

---

packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Remove `private` syntax in favour of `#`, plus sort all property definitions and assignments.

chore: remove private syntax in transaction controller

---

eslint-warning-thresholds.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

Current checks for duplicate accounts only work for imported private keys, and only enforced when creating and restoring keyrings. That is, we don't have proper checks in place to avoid duplicates, and the few checks we have are locking out users instead of ensuring no duplicate is persisted in the vault altogether.
More info on the issue referenced below.
* Fixes https://github.com/MetaMask/core/issues/5411

fix: ensure no duplicate accounts are persisted

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

There's a mechanism in KeyringController to upgrade the vault encryption parameters during a successful login to ensure users always use the safest encryption available without needing additional actions for the vault to be upgraded.
However, when the vault encryption upgrade fails during login, we don't want to interrupt and rollback the entire operation. We can move the vault upgrade to a standalone, mutually exclusive operation that can fail gracefully.
This fix can be tested on extension with this draft PR (instructions included): https://github.com/MetaMask/metamask-extension/pull/32438
* Fixes https://github.com/MetaMask/core/issues/5745

fix: do not throw error when encryption upgrade fails during login

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/api/simulation-api.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts
packages/transaction-controller/src/utils/eip7702.ts
packages/transaction-controller/src/utils/simulation.test.ts
packages/transaction-controller/src/utils/simulation.ts

Include `authorizationList` and `with7702` properties in simulation request to return EIP-7702 gas fee tokens, and include upgrade gas.
Add optional `isEIP7702GasFeeTokensEnabled` property to constructor.

feat: generate EIP-7702 gas fee tokens

---

packages/chain-agnostic-permission/CHANGELOG.md
packages/chain-agnostic-permission/src/adapters/caip-permission-adapter-permittedChains.test.ts
packages/chain-agnostic-permission/src/adapters/caip-permission-adapter-permittedChains.ts

Fixes `getAllNamespacesFromCaip25CaveatValue` to return only the reference of the passed in scope string when it is `wallet` namespaced. I.e. `wallet:eip155` should return only `eip155` and an exact value of `wallet` should still return `wallet.

Fix `getAllNamespacesFromCaip25CaveatValue` to return only reference when value is wallet namespaced

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

Include `origin` in call to `addTransaction` from EIP-7702 batch transaction.
Wasn't causing a linting error as `origin` is default global variable.

fix: include origin in 7702 transaction

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/gas-fees.test.ts
packages/transaction-controller/src/utils/gas-fees.ts

This PR aims to fix `userLevelFee` to be settled to `medium` instead of `dappSuggested` fallback when `gasPrice` is suggested.

fix: Fix `userLevelFee` to be `medium` instead of `dappSuggested` when `gasPrice` is suggested

---

.github/workflows/changelog-check.yml

This PR updates the changelog-check workflow to use commit [85fffce169c0fd35028ecde6b38dfb3f932882ec](https://github.com/MetaMask/github-tools/commit/85fffce169c0fd35028ecde6b38dfb3f932882ec), which pins a safe version and prevents breaking changes in the shared workflow from affecting this repo. The change that adds this protection was introduced in [this commit](https://github.com/MetaMask/github-tools/commit/4e692425299b2beb849e6b9316f940f9a528541c).

chore: pin changelog-check workflow to safe commit to prevent breakages

---

packages/profile-sync-controller/CHANGELOG.md

This PR moves a changelog entry from **13.0.0** to **Unreleased** for `@metamask/profile-sync-controller`.
This entry was mistakenly placed in an already released version's changelog.

fix: misplaced changelog entry for `@metamask/profile-sync-controller`

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/api/simulation-api.ts
packages/transaction-controller/src/utils/gas.test.ts
packages/transaction-controller/src/utils/gas.ts

When simulating gas for type-4 transactions, use `gasLimit` rather than `gasUsed` from simulation response.

fix: use gas limit from simulation response

---

eslint-warning-thresholds.json
packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/jest.config.js
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts

Dependent on:
- https://github.com/MetaMask/core/pull/5725
It is no longer possible to persist duplicates in the vault, though users that already have duplicates will see them in the accounts list, and won't be able to do any action with their vault. These changes aim to discard duplicates, moving the keyring including a duplicate account to the unsupported array.
Can be tested on extension with https://github.com/MetaMask/metamask-extension/pull/32621

fix: discard duplicate accounts on unlock

---

eslint-warning-thresholds.json
packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/TokenListController.ts

This improves how we perform state updates in the TokenListController.
It reduces the mobile commits/renders from 27-30 commits down to 10-15.
Here is a test-drive mobile PR:
https://github.com/MetaMask/metamask-mobile/pull/15330
| Before | After |
|--------|--------|
| ![Screenshot 2025-05-14 at 14 27 19](https://github.com/user-attachments/assets/506cee83-144e-4c34-b9e4-335002b821b6) | ![Screenshot 2025-05-14 at 14 52 07](https://github.com/user-attachments/assets/ee4d666a-c1c0-4a95-9edb-949231bcc099) |

perf: improve token-list-controller state updates and caching

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/create-service-policy.ts
packages/network-controller/CHANGELOG.md
packages/network-controller/src/rpc-service/rpc-service.ts
packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
packages/network-controller/tests/provider-api-tests/block-param.ts
packages/network-controller/tests/provider-api-tests/no-block-param.ts

This PR improves the handling of HTTP status codes in the RPC service by properly handling 405 (Method Not Allowed) and 429 (Too Many Requests) responses without triggering the circuit breaker.
- Added handling for 405 status code, RPC Error code -32601 (Method not found)
- Added handling for 429 status code,  RPC Error code-32005 (Request rate limit exceeded)
Previously, these status codes would trigger the circuit breaker, which could lead to unnecessary failover to backup endpoints. These status codes represent expected error conditions that should be handled gracefully without triggering the circuit breaker.
* Fixes https://github.com/MetaMask/core/issues/5766

fix(rpc-service): handle 405 and 429 status codes without triggering circuit breaker

---

packages/network-controller/CHANGELOG.md
packages/network-controller/src/rpc-service/rpc-service.test.ts
packages/network-controller/src/rpc-service/rpc-service.ts

An error case was added to our network middleware long ago to workaround load balancer errors that we encountered with Infura at the time. These errors were fixed long ago, so this workaround is no longer needed.
I [checked with the Infura team](https://consensys.slack.com/archives/CV90KPED9/p1747252611880119), and they confirmed that this case should no longer be possible for Infura RPC endpoints.
Removing this check allowed me to update how we're parsing the response body as well. We're now using `response.json()` rather than parsing the raw body as text. As a consequence of this, we no longer have the raw text to attach to parsing errors, but this seems OK to remove given that we don't reference it anywhere, and the full response can be seen in devtools in a development environment. …

chore: Remove obsolete workaround

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/constants/tokens.ts

`getNativeAssetForChainId` returns the assetId for SOL instead of a recognized native token address. This can cause duplicate SOL tokens to appear in the clients. This updates the address to the ZeroAddress, which clients use for native assets

fix: use zero address as native address instead of assetId

---

packages/controller-utils/CHANGELOG.md
packages/controller-utils/src/create-service-policy.ts
packages/controller-utils/src/index.test.ts
packages/controller-utils/src/index.ts
packages/controller-utils/src/util.test.ts
packages/controller-utils/src/util.ts
packages/network-controller/CHANGELOG.md
packages/network-controller/src/rpc-service/rpc-service.test.ts
packages/network-controller/src/rpc-service/rpc-service.ts
packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
packages/network-controller/tests/provider-api-tests/block-param.ts
packages/network-controller/tests/provider-api-tests/no-block-param.ts
packages/network-controller/tests/provider-api-tests/rpc-failover.ts

The "create-service-policy" utility (specifically the circuit breaker) has been updated to handle fetch errors rather than RPC errors.
This utility was recently updated to handle the JSON-RPC "Internal error" response, but this is only expected for one specific place where this utility is used (the RPC service). Additionally, there remained some cases that would still inappropriately trigger the circuit break policy (i.e. there were some "internal errors" that don't indicate service failure).
The utility will now consider all network errors and HTTP 5XX errors as indicative of service failure. HTTP 4XX errors will no longer trigger the circuit breaker.
To accomodate these changes, the RPC service now only handles the fetch request and response parsing inside the policy execution phase. …

fix: Prevent circuit break for HTTP 4XX errors

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/validation.ts

Throw the correct error code from `addTransaction` if an EIP-7702 upgrade is rejected.
Relates to [#32956](https://github.com/MetaMask/metamask-extension/issues/32956)

fix: cancel upgrade error code

---

packages/selected-network-controller/src/SelectedNetworkController.ts
packages/selected-network-controller/tests/SelectedNetworkController.test.ts

This removes some checks in the `SelectedNetworkController` which disallow a Snap from using their own network, and default to the globally selected network. After this change, Snaps will be able to select their own network just like websites.
Related to MetaMask/MetaMask-planning#2938.
- **CHANGED**: Allow Snaps to change own network

Use selected network controller for Snaps

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/transaction-type.test.ts
packages/transaction-controller/src/utils/transaction-type.ts

This PR aims to fix where the `addTransaction` function incorrectly identifies a transaction as a `simpleSend` type when the recipient is a smart account.
* Fixes https://github.com/MetaMask/MetaMask-planning/issues/4920
* Extension PR: https://github.com/MetaMask/metamask-extension/pull/33013

fix: Fix sending native token to smart account

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/utils/gas-fees.test.ts
packages/transaction-controller/src/utils/gas-fees.ts

This PR aims to add `userFeeLevel` as `dappSuggested` initially when `txParams` contains gas values also for `legacy` transactions.
* Issue found while implementing gas modal: https://github.com/MetaMask/metamask-mobile/pull/15234

fix: Add `userFeeLevel` as `dappSuggested` initially when `txParams` contains gas values for `legacy` transactions

---

packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/bridge-status-controller.test.ts
packages/bridge-status-controller/src/bridge-status-controller.ts

After a swap is submitted the status controller keeps calling getTxStatus. This is unnecessary and can cause clients to keep polling until the user clears their activity log

fix: don't poll for swap status

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/MultichainAssetsRatesController/MultichainAssetsRatesController.ts

PR to add an optional account to fetchHistoricalPricesForAsset to be used instead of accountsController getSelectedMultichainAccount.

fix: add optional account for fetching historical prices

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/gas-fees.test.ts
packages/transaction-controller/src/utils/gas-fees.ts

This PR aims to fix minor issue on `gweiDecimalToWeiDecimal` utility. 
If given value is more than 9 decimal places then generated WEI value will have decimal part which we don't expect / want in WEI value. 
Fixes: https://github.com/MetaMask/MetaMask-planning/issues/4973

fix: Remove lingering decimal in return of `gweiDecimalToWeiDecimal`

---

packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

`AccountsController:accountAdded` events were missing the `.options.entropySource` property, causing account syncing to misbehave, registering new accounts to the primary SRP instead of the actual SRP used to add the account.
We now add the `entropySource` to these new `InternalAccount`s based on the `keyring` that was used to create them.
Relates to #5618
Relates to #5725
Relates to #5753

feat(accounts-controller): Add `entropySource` to new `InternalAccount`

---

packages/network-controller/CHANGELOG.md
packages/network-controller/src/rpc-service/rpc-service-chain.test.ts
packages/network-controller/src/rpc-service/rpc-service-chain.ts
packages/network-controller/src/rpc-service/rpc-service.test.ts
packages/network-controller/src/rpc-service/rpc-service.ts
packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
packages/network-controller/tests/provider-api-tests/block-param.ts
packages/network-controller/tests/provider-api-tests/no-block-param.ts

Improves error handling in the RPC service by making it more specific and consistent. The changes include:
- Clarifies error handling for different HTTP status codes:
- 401: Unauthorized error
- 402/404/5xx: Resource unavailable error
- 429: Rate limiting error
- Other 4xx responses now throw a generic HTTP client error
- Invalid JSON: Parse error
Fixes https://github.com/MetaMask/core/issues/5844

fix(rpc-service): improve error handling for HTTP status codes

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/types.ts
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

This PR ensures the origin (URL) that initiates a `wallet_sendCalls` request is sent to the security alerts API. This additional context is important for improving PPOM validation and threat detection accuracy.
Changes:
- Added `origin`  property to `ValidateSecurityRequest` type.
- Updated `validateSecurity` callback to pass the `origin`.
Related to https://github.com/MetaMask/MetaMask-planning/issues/5030

Includes `origin` for `wallet_sendCalls` security alert requests

---

packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts

We assume the `snap` will always be defined, but they could be deleted/reloaded during some flows. To prevent using an `undefined` `snap` here, we check if it's defined first, if not, we consider it to be disabled.
- https://github.com/MetaMask/metamask-mobile/issues/15628

fix(accounts-controller): fix Snap account's metadata update when Snaps during wallet reset flow

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/bridge-controller.test.ts
packages/bridge-controller/src/bridge-controller.ts

This fixes L1 and Solana fee calculations in the BridgeController such that some quotes can be returned if exceptions are thrown by dependencies (snap and RPCs). 
Fixes https://consensyssoftware.atlassian.net/browse/MMS-2568

fix: fail gracefully when L1 gas fees are not available

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/utils/batch.test.ts
packages/transaction-controller/src/utils/batch.ts

With the previous syntax, publishBatchHook would be coerced into a boolean, which would halt execution further down the function when it is awaited. This PR fixes normal function execution by avoiding coercion.

fix: Avoid coercing publishBatchHook to a boolean

---

packages/earn-controller/CHANGELOG.md
packages/earn-controller/src/EarnController.ts
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/types.ts

- Add `lendingWithdraw` type to `@metamask/transaction-controller`
- Replace hardcoded `"lendingWithdraw"` in `@metamask/earn-controller`

feat: Add lendingWithdraw type to TransactionController and EarnController

---

package.json
packages/assets-controllers/package.json
packages/phishing-controller/CHANGELOG.md
packages/phishing-controller/package.json
yarn.lock

This reverts commit 1e17aea8d892a250d3261bec8bbf86af8dd1ea5c.
Reverting due to incorrect PR title.

Revert "release: 435.0.0 (#5965)"

---

packages/bridge-controller/CHANGELOG.md

Removes uncategorized changelog entry from the bridge controller. This entry was only for bumping a dev dependency, so doesn't need to remain in the changelog.

chore: remove uncategorized changelog entry

---

packages/chain-agnostic-permission/CHANGELOG.md
packages/chain-agnostic-permission/src/adapters/caip-permission-adapter-accounts.test.ts
packages/chain-agnostic-permission/src/adapters/caip-permission-adapter-accounts.ts

Temporary fix for the issue where the internal account has no scopes and or scopes is undefined
there is currently a bug where an account associated with a snap can fail to add scopes to the internal account in time
before we attempt to access this state
For example:
* Fixes https://github.com/MetaMask/metamask-extension/issues/32451
* [Sentry Error](https://metamask.sentry.io/issues/6683351210/?project=273505)
* Slack thread: https://consensys.slack.com/archives/C08T784K955/p1750172591818219
*CHANGED*: `isInternalAccountInPermittedAccountIds` now returns false when passed an `InternalAccount` where `scopes` is `undefined`

fix case where internal accounts can be undefined

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts

Support the clients polling incoming transactions only when viewing the transaction activity list.
Specifically:
- Delete incoming transactions when calling `wipeTransactions` method.
- Poll immediately when calling `startIncomingTransactionPolling` method.

feat: support incoming transaction polling only when viewing activity

---

packages/keyring-controller/CHANGELOG.md
packages/keyring-controller/src/KeyringController.test.ts
packages/keyring-controller/src/KeyringController.ts
packages/keyring-controller/src/constants.ts

Keyring Controller:
* Add method `controller.exportEncryptionKey` to export vault key.
* Change method `controller.submitEncryptionKey` to have an optional salt.
* If the salt is provided, the controller will check that it is consistent with the locally stored salt.
* If the salt is not provided, this check is omitted.
* Before, the salt was mandatory, but it might not be required in the case of unlocking the vault during vault recovery.
This feature is relevant for resolving an audit finding with the seedless onboarding controller.
Previously, seedless onboarding was backing up the keyring password to allow for vault recovery after a password change. Now we backup the keyring encryption key.
See the [ADR](https://github.com/MetaMask/decisions/pull/85) for more details.
This is part of …

feat(KeyringController): add `exportEncryptionKey` method to export vault key

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts

Support updating `containerTypes` property of `TransactionMeta` via `updateEditableParams` method.

feat: update container types

---

packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

Preferences controller: initialise smartAccountOptIn with true value
Related to https://github.com/MetaMask/MetaMask-planning/issues/5235

fix: Preferences controller: initialise smartAccountOptIn with true value

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/bridge-controller.ts
packages/bridge-controller/src/utils/validators.ts
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/bridge-status-controller.ts
packages/bridge-status-controller/src/utils/__snapshots__/validators.test.ts.snap
packages/bridge-status-controller/src/utils/bridge-status.ts
packages/bridge-status-controller/src/utils/transaction.ts
packages/bridge-status-controller/src/utils/validators.test.ts
packages/bridge-status-controller/src/utils/validators.ts

Undoing type change for ChainId. Was changed to `number | string` in an earlier PR, but bridge-api only returns `number`. The earlier change is causing type errors in clients

fix: use number as expected bridge ChainId type

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/utils/feature-flags.test.ts
packages/bridge-controller/src/utils/validators.ts
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
packages/bridge-status-controller/src/bridge-status-controller.test.ts
packages/bridge-status-controller/src/bridge-status-controller.ts
packages/bridge-status-controller/src/utils/transaction.test.ts
packages/bridge-status-controller/src/utils/transaction.ts

**BREAKING** Submit Solana transactions using `onClientRequest` RPC call by default, which hides the Snap confirmation page from clients. Clients will need to remove conditional redirect the the confirmation page on tx submission
Fixes https://github.com/MetaMask/metamask-extension/issues/34148

chore: remove LD flag check for isSnapConfirmationEnabled

---

packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

Remove preference smartAccountOptInForAccounts as it is not going to be used
* Related to [#67890](https://github.com/MetaMask/MetaMask-planning/issues/5262)

chore: Remove preference smartAccountOptInForAccounts as it is not going to be used

---

packages/preferences-controller/CHANGELOG.md
packages/preferences-controller/src/PreferencesController.test.ts
packages/preferences-controller/src/PreferencesController.ts

Revert PreferenceController changes to remove preference `smartAccountOptInForAccounts` and rather add `@deprecated` tag to it.
* Related to https://github.com/MetaMask/MetaMask-planning/issues/5262

fix: revert PreferenceController changes

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/__snapshots__/bridge-controller.test.ts.snap
packages/bridge-controller/src/bridge-controller.test.ts
packages/bridge-controller/src/utils/quote.ts

**BREAKING** Require `destWalletAddress` in `isValidQuoteRequest` if bridging to or from Solana. This prevents getQuote network calls from being made if the user has not selected a destination wallet address
Fixes: https://github.com/MetaMask/metamask-extension/issues/32700 , https://github.com/MetaMask/metamask-extension/issues/32771

fix: validate destWalletAddress when bridging to or from Solana

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts

This PR removes the `access_token` validation from the `checkIsPasswordOutdated` and `#executeWithTokenRefresh` when the wallet locked and the following issue.
The `checkIsPasswordOutdated` method can be called even when the wallet (vault) is locked but during the locked period, `access_token` is not accessible. This triggers the `refreshAuthToken` method whenever wallet is unlocked.

fix: Removed access token validation on wallet locked

---

README.md

Recent changes to the profile sync controller were not yet represented in the diagram in the README.
The diagram changes are due to https://github.com/MetaMask/core/pull/6081
N/A

chore: Update README diagram

---

scripts/create-package/package-template/package.json

Update the template used by the `create-package` script. The previous template was no longer compatible with our Yarn constraints.
Here are the PRs related to these specific changes:
* #4648
* #3645
* #1390
* #3668
N/A

fix: Update `create-package` template

---

scripts/create-package/cli.ts

The `create-package` script was failing due to unused `ts-expect-error` directives. The directives became unused recently in #5810 after an update.
To test this, run `yarn create-package --help`. It should no longer throw an error.
Broken since #5810
N/A

fix: Fix `yarn create-package`

---

docs/contributing.md

Add a missing step in the contributor documentation for creating a new package. The template covers most things, but the team ownership is at the root level and required by our Yarn constraints.
N/A
N/A

docs: Add missing step in "new package" docs

---

.github/CODEOWNERS
README.md
packages/messenger/CHANGELOG.md
packages/messenger/LICENSE
packages/messenger/README.md
packages/messenger/jest.config.js
packages/messenger/package.json
packages/messenger/src/Messenger.test.ts
packages/messenger/src/Messenger.ts
packages/messenger/src/RestrictedMessenger.test.ts
packages/messenger/src/RestrictedMessenger.ts
packages/messenger/src/index.test.ts
packages/messenger/src/index.ts
packages/messenger/tsconfig.build.json
packages/messenger/tsconfig.json
packages/messenger/typedoc.json
teams.json
tsconfig.build.json
tsconfig.json
yarn.lock

The `Messenger` class and related code has been copied from the `@metamask/base-controller` package to a new `@metamask/messenger` package. Separating the messenger from the base controller reduces the impact of base controller breaking changes, and aligns well with our plans to use the `Messenger` class more often for non-controllers.
This move will also simplify the effort to implement some new breaking changes to the `Messenger` class (the new `delegation` method, see issue #5626). This new package will not be released until the breaking changes have been applied here. Those changes will come in later PRs; for now, the code was copied over with zero changes.
Related to #5626
N/A

feat: Create new `@metamask/messenger` package

---

scripts/create-update-issues.sh

The "fetch all issues" calls are now made once per repo rather than once per package per repo.
This is a suggestion for #6090

chore: Optimize "create-update-issues" script

---

packages/permission-log-controller/CHANGELOG.md
packages/permission-log-controller/src/PermissionLogController.ts

The `permissionActivityLog` property of the `PermissionLogController` state tracks all calls to restricted methods. This was intended as a diagnostic aid, but in practice it is rarely used. This log is causing performance issues related to disk writes because it can be triggered while the wallet is idle (by snaps calling restricted methods).
To reduce the performance burden of this property, it is no longer persisted. This list will still be available in-memory for diagnosing problems, but will not be preserved across restarts.
Relates to https://github.com/MetaMask/metamask-extension/issues/33879
Here is the draft PR of this update for `metamask-extension` that addresses the breaking changes: https://github.com/MetaMask/metamask-extension/pull/34465
This controller is not used by mobile, …

feat: Stop persisting `permissionActivityLog` state

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/MultichainAccountService.ts

This `.name` is required by the controller-init pattern on our clients, see:
- https://github.com/MetaMask/metamask-extension/blob/f1214299a2db41b310c31d14a7a15639c3f3c7b3/app/scripts/controller-init/types.ts#L23-L24
N/A
N/A

fix(multichain-account-service): add missing `name` class field

---

packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/src/utils.ts

This is required since Snaps that supports BIP-44 accounts might have more options than the one we use to detect "legacy BIP-44 options".
`superstruct.object` is strict and does not allow extra-properties, while `superstruct.type` acts as normal structural typing (like in TypeScript).
N/A
N/A

fix(accounts-controller): allow extra-properties in options BIP-44 Snap accounts

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
packages/seedless-onboarding-controller/tests/mocks/toprfEncryptor.ts

- This PR moves revoke token call in a separate public function. Revoking refresh token  is not a must after submit password so can be done post unlock and even when it fails it shouldn't affect user wallet unlock.

feat: adds revokeRefreshToken public function.

---

packages/foundryup/CHANGELOG.md
packages/foundryup/src/index.ts

Makes the symlinks that foundryup installs relative instead of absolute, to fix MetaMask/MetaMask-planning#5448
Fixes: MetaMask/MetaMask-planning#5448

fix: make anvil symlink relative

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/MultichainAssetsRatesController/MultichainAssetsRatesController.ts

Prevent unnecessary state updates by using a selector when listening to `CurrencyRateController:stateChange` in `MultichainAssetsRatesController`.

perf: Prevent unnecessary state updates by using a selector in `MultichainAssetsRatesController`

---

package.json
packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/package.json
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/group.ts
packages/account-tree-controller/src/rules/entropy.ts
packages/account-tree-controller/src/wallet.ts
packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/package.json
packages/multichain-account-service/src/MultichainAccountGroup.test.ts
packages/multichain-account-service/src/MultichainAccountGroup.ts
packages/multichain-account-service/src/MultichainAccountService.test.ts
packages/multichain-account-service/src/MultichainAccountService.ts
packages/multichain-account-service/src/MultichainAccountWallet.test.ts
packages/multichain-account-service/src/MultichainAccountWallet.ts
packages/multichain-account-service/src/index.ts
packages/multichain-account-service/src/tests/accounts.ts
packages/multichain-account-service/src/tests/index.ts
packages/multichain-account-service/src/tests/providers.ts
packages/multichain-account-service/src/types.ts
yarn.lock

Moving the implementations out of `@metamask/account-api` to have them closer to the service (which makes more sense too).
Beware, `MultichainAccount` has been renamed to `MultichainAccountGroup` to emphasis more on the the "group" aspect of multichain accounts.
- https://github.com/MetaMask/accounts/pull/333
N/A

refactor(multichain-account-service)!: move `MultichainAccount{Wallet,Group}` implementations

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/MultichainAccountService.ts
packages/multichain-account-service/src/providers/BaseAccountProvider.ts

We now use `KeyringAccount` instead of `InternalAccount` since we don't really have any use of the `account.metadata` anymore since the introduction of groups/wallets `metadata`:
- https://github.com/MetaMask/core/pull/6214
We still rely on the `AccountsController` to get the `KeyringAccount`-compatible accounts for EVM accounts.
Once we have the unified keyring API, we could just use keyrings to get their accounts, though, for the moment we rely on `getAccount` and `getAccounts` to be sync methods, and we would have to change this to fit the current multichain account architecture. 
- Discussion started here: https://github.com/MetaMask/core/pull/6222/files#r2247301489
N/A

feat(multichain-account-service)!: add `KeyringAccount` instead of `InternalAccount`

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/MultichainAccountService.test.ts
packages/multichain-account-service/src/MultichainAccountService.ts
packages/multichain-account-service/src/types.ts

This PR adds the already existing `MultichainAccountWallet.createMultichainAccountGroup` method to `MultichainAccountService`, exposes it as a public method, and adds it as a messenger action.

feat(multichain-account-service): expose `createMultichainAccountGroup` action

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/index.ts

This PR exports those action types:
- `MultichainAccountServiceCreateMultichainAccountGroupAction`
- `MultichainAccountServiceCreateNextMultichainAccountGroupAction`

chore(multichain-account-service): export missing types from `MultichainAccountService`

---

packages/chain-agnostic-permission/CHANGELOG.md
packages/chain-agnostic-permission/src/caip25Permission.test.ts
packages/chain-agnostic-permission/src/caip25Permission.ts
packages/chain-agnostic-permission/src/constants.ts
packages/chain-agnostic-permission/src/index.test.ts
packages/chain-agnostic-permission/src/index.ts

While working on [adding Multichain API to Flask on mobile](https://github.com/MetaMask/metamask-mobile/pull/14756), some code that is common to the browser extension repository was also created on the mobile codebase, namely [these permissions utilities](https://github.com/MetaMask/metamask-mobile/blob/main/app/util/permissions/index.ts) which are also present in the `extension` [metamask-controller module](https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/metamask-controller.js):
- `getCaip25PermissionFromLegacyPermissions`
- `requestPermittedChainsPermissionIncremental`
The work proposed in this pull request migrates these common functionalities onto our `@metamask/chain-agnostic-permissions` package, so that they can be imported on both `mobile` and `extension` to …

refactor: address tech debt for chain agnostic permission code repeated on extension and mobile codebases

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts

* What is the current state of things and why does it need to change? Account removal can leave empty nodes in the Account tree controller.
* What is the solution your changes offer and how does it work? My solution prunes the tree when there is an empty group and/or wallet.

feat(account-tree-controller): automatically removes empty groups and wallets

---

packages/base-controller/src/Messenger.ts
packages/base-controller/src/RestrictedMessenger.ts
packages/messenger/src/Messenger.ts

Two Messenger methods were missing template directives. They were added in all three Messenger classes (which are soon to be consolidated into one).
Extracted from #6132

chore: Add missing TSDoc template directives

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/rules/entropy.ts
packages/account-tree-controller/src/wallet.ts

Removing the `wallet.metadata.entropy.index`. This is mainly used by us for the naming, and the "order" is the responsibility of the `KeyringController` mainly, not the `AccountTreeController`.
N/A
N/A

refactor(account-tree-controller): remove `wallet.metadata.entropy.index`

---

.github/pull_request_template.md

This section has not been used for some time now. Leaving it here was helpful for the transition to the new changelog process, but it has been long enough now that I don't think it's needed anymore.
N/A

chore: Remove obsolete changelog section from PR template

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts
packages/account-tree-controller/src/group.ts
packages/account-tree-controller/src/index.ts
packages/account-tree-controller/src/wallet.ts

This implementation is not good enough to start using it.
We will re-enable this once we have a better solution for those. For the moment, we will add actions to the controller to be able to fetch accounts from the selected account group and that should cover most use-cases for the moment.
They will be replaced by:
- https://github.com/MetaMask/core/pull/6266
N/A

refactor(account-tree-controller)!: remove `AccountTree{Wallet,Group}` in-memory instances

---

yarn.config.cjs

Our `yarn constraints` is a bit too strict when developing new packages which can be considered "unstable" (version `<1.0.0`).
With the current contraints, it's not possible to depend on an specific minor/patch version of such package when developing new features (since the `peerDependencies` would automatically be fixed up to `^0.0.0` to match our current contraints).
This PR only forces `peerDependencies` to reference a major version only for peer dependencies with a version `>=1.0.0`.
N/A

chore: relax yarn constraints for peer dep <1.0.0

---

packages/bridge-controller/CHANGELOG.md
packages/bridge-controller/src/__snapshots__/bridge-controller.test.ts.snap
packages/bridge-controller/src/bridge-controller.test.ts
packages/bridge-controller/src/bridge-controller.ts
packages/bridge-controller/src/index.ts
packages/bridge-controller/src/utils/metrics/constants.ts
packages/bridge-controller/src/utils/metrics/properties.test.ts
packages/bridge-controller/src/utils/metrics/properties.ts
packages/bridge-controller/src/utils/metrics/types.ts
packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
packages/bridge-status-controller/src/bridge-status-controller.ts

The `action_type` property indicates whether an event is published before or after the Unified swaps+bridge launch. This change hardcodes `swapbridge_v1` for all future events
Fixes https://consensyssoftware.atlassian.net/browse/SWAPS-2784

fix: hardcode xchain swaps action_type to swapbridge_v1

---

packages/bridge-status-controller/CHANGELOG.md
packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
packages/bridge-status-controller/src/bridge-status-controller.test.ts
packages/bridge-status-controller/src/utils/transaction.ts

Adding the fiat values of the sent amount and the quoted received amount to the batch tx request, so that the confirmations team can consume the data in their metrics. More context in linked ticket
Example value
```
assetsFiatValues: {
sending: "100.431243",
receiving: "99.4",
},
```
Fixes https://consensyssoftware.atlassian.net/browse/SWAPS-2759

chore: include assetsFiatValues in swap and bridge addTransactionBatch params

---

packages/messenger/CHANGELOG.md
packages/messenger/src/Messenger.test.ts
packages/messenger/src/Messenger.ts

Add the `parent` constructor parameter to the `Messenger` class for automatic delegation of all capabilities under that messenger's namespace. This significantly reduces boilerplate, making the messenger easier to use in a similar manner to how the old `RestrictedMessenger` class wored.
See this ADR PR for details: MetaMask/decisions#53
Depends upon #6132
Relates to #5626

feat: Add Messenger `parent` parameter

---

packages/base-controller/CHANGELOG.md
packages/base-controller/src/next/BaseController.test.ts
packages/base-controller/src/next/BaseController.ts

On the `next` version of the `BaseController`, the protected instance variable `messagingSystem` has been renamed to `messenger`.
Fixes #6336

feat: Rename `messagingSystem` to `messenger`

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/selectors/token-selectors.test.ts
packages/assets-controllers/src/selectors/token-selectors.ts

The format for EVM addresses for AccountTrackerController in mobile differs from extension and from the other controller states. This was causing it to miss native account balances.
It also uses the correct internal account type in the assets, so that BTC account types can be identified.
Finally, it fixes an issue with the `mergeAssets` function mutating internal parts of cached objects.

fix: token selector issues

---

packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/src/TransactionController.test.ts
packages/transaction-controller/src/TransactionController.ts
packages/transaction-controller/src/index.ts
packages/transaction-controller/src/types.ts

Add optional `metamaskPay` and `requiredTransactionIds` properties to `TransactionMeta`.
Also add `updateRequiredTransactionIds` method to update new property.

feat: add pay properties to transaction metadata

---

packages/messenger/CHANGELOG.md
packages/messenger/src/Messenger.test.ts
packages/messenger/src/Messenger.ts

Keep delegated handlers around even when unregistering actions. This helps with the resiliency of the messenger system in case actions are unregistered and registered elsewhere in the chain of delegations. This is also very useful for testing.
Additionally adjusts the error message thrown when a delegated action handler cannot be found to match an undelegated one.

fix: Keep delegated handlers when unregistering actions

---

packages/accounts-controller/src/AccountsController.ts
packages/accounts-controller/src/typing.ts

Narrowing the `AccountControllerState` internally to avoid facing this issue:
- https://github.com/MetaMask/utils/issues/168
This has no impact on the controller behavior or interface, it's purely related to the type-system and compiler errors.
I had errors when I was running the test locally with the compiler, but the CI ran fine. Now, it runs fine on both environment with no error/warning.
N/A

fix(accounts-controller): workaround compiler error for recursive type

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts

The `init` function can be used in several scenarios:
- Initial controller initialization
- Other controllers might want to know which group will be selected
- During re-onboarding, all accounts will be removed and the tree might be re-`init`
- We want to fire the group that has been automatically selected after resetting the entire tree
N/A

fix(account-tree-controller): emit `:selectedAccountGroupChange` during tree init

---

packages/subscription-controller/CHANGELOG.md
packages/subscription-controller/src/SubscriptionController.test.ts
packages/subscription-controller/src/SubscriptionController.ts
packages/subscription-controller/src/SubscriptionService.test.ts
packages/subscription-controller/src/SubscriptionService.ts
packages/subscription-controller/src/index.ts
packages/subscription-controller/src/types.ts

Add a "getPricing" method to the SubscriptionController, which allows the frontend to query the available products and their pricing.

feat: SubscriptionController: get pricing

---

packages/eip-5792-middleware/package.json

`@metamask/eip-5792-middleware` was incorrectly initialized with a version of `1.0.0`. We need to initialize packages with a version of 0.0.0 before publication.

`@metamask/eip-5792-middleware` init version to 0.0.0

---

package.json
packages/earn-controller/CHANGELOG.md
packages/earn-controller/package.json

Reverts MetaMask/core#6446 because it was not published correctly due to version being set incorrectly on a new package. This has [since been fixed](https://github.com/MetaMask/core/pull/6449), but we're reverting to re-attempt this publish.

Revert "Release/530.0.0"

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts
packages/account-tree-controller/src/group.ts
packages/account-tree-controller/src/index.ts

Currently there is no method for ensuring account group uniqeuness. This PR adds function that does that.
- Implemented a new private method `#assertAccountGroupNameIsUnique` to ensure account group names are unique across different groups.
- Updated `setAccountGroupName` to validate uniqueness before setting a name.
- Added tests to verify that the same name can be set for the same group and that duplicate names across different groups are prevented.

feat(account-tree-controller): add account group name uniqueness validation

---

packages/subscription-controller/CHANGELOG.md
packages/subscription-controller/src/SubscriptionController.test.ts
packages/subscription-controller/src/SubscriptionController.ts

Add a "triggerAuthTokenRefresh" method to the SubscriptionController, which allows to trigger a refresh of the access token, for example, after the subscription status has changed.

feat: SubscriptionController: trigger token refresh

---

packages/seedless-onboarding-controller/CHANGELOG.md
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
packages/shield-controller/CHANGELOG.md
packages/shield-controller/src/ShieldController.test.ts
packages/shield-controller/src/ShieldController.ts
packages/subscription-controller/CHANGELOG.md
packages/subscription-controller/src/SubscriptionController.test.ts
packages/subscription-controller/src/SubscriptionController.ts

The new metadata properties `includeInStateLogs` and `usedInUi` have been added to all controllers maintained by the Web3Auth team.
* Fixes #6521
* Related to #6443

feat: Add new metadata properties to Web3Auth controllers

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts
packages/account-tree-controller/src/group.ts

This PR changes the account groupc uniqueness checks to validate uniqueness only within the same wallet, allowing duplicates between wallets.
Jira ticket: https://consensyssoftware.atlassian.net/browse/MUL-795

refactor: update account group name uniqueness checks

---

.github/CODEOWNERS

The snaps team and wallet framework teams have been combined into the core platform team. All `snaps-dev` entries in CODEOWNERS have been updated to be owned by `core-platform`.
N/A

chore: Update CODEOWNERS to migrate snaps to core platform

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts
packages/accounts-controller/CHANGELOG.md
packages/accounts-controller/src/AccountsController.test.ts
packages/accounts-controller/src/AccountsController.ts
packages/multichain-transactions-controller/CHANGELOG.md
packages/multichain-transactions-controller/src/MultichainTransactionsController.test.ts
packages/multichain-transactions-controller/src/MultichainTransactionsController.ts
packages/profile-sync-controller/CHANGELOG.md
packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts

The new metadata properties `includeInStateLogs` and `usedInUi` have been added to all controllers maintained by the accounts team.
Related to #6443

feat: Add new metadata properties to accounts controllers

---

packages/network-controller/CHANGELOG.md
packages/network-controller/src/NetworkController.ts
packages/network-controller/tests/NetworkController.test.ts

This updates the `initializeProvider` function of the network controller to be synchronous if `lookupNetwork` is `false`, i.e., when no async operations need to be performed. Previously the function was `async` meaning it would always return a promise, regardless of whether any async operations are performed. With some function overloads and by removing async (returning a promise instead when necessary), we can make it fully synchronous when `lookupNetwork` is `false`.
Doing this will allow for safe initialisation of the network controller state in places where awaiting may be difficult, like in the client's modular controller initialisation.

chore: Synchronously initialise network controller provider if `lookupNetwork` is `false`

---

packages/assets-controllers/CHANGELOG.md
packages/assets-controllers/src/AssetsContractController.ts
packages/assets-controllers/src/assetsUtil.ts
packages/assets-controllers/src/token-prices-service/codefi-v2.ts

This PR adds support for Monad Mainnet to the MetaMask assets controllers by integrating the new blockchain network (chain ID 0x8f) into the token detection and pricing systems.
Monad Mainnet has not launch yet, there is no RPC but only infura to support this network 
Accounts API is not yet merged, so even we add the chain id, it wont discover the balance via API, but the RPC

feat: add `Monad Mainnet` support to `@metamask/assets-controllers`

---

package.json
packages/subscription-controller/CHANGELOG.md

Reverting https://github.com/MetaMask/core/pull/6625 as the [Release CI](https://github.com/MetaMask/core/actions/runs/17764289481/job/50484256349) is failing.
The release was manually created and it looks like we messed something up there.
(The reason for the manual work was that the controller was not showing up when using `yarn create-release-branch -i`. Maybe because it's the first release of the controller?)

Revert "Release 556.0.0 (#6625)"

---

packages/messenger/CHANGELOG.md
packages/messenger/src/Messenger.test.ts
packages/messenger/src/Messenger.ts

The `Messenger` class in `@metamask/messenger` has been updated to accept an optional `captureException` constructor parameter. This is now used to capture subscriber errors, instead of throwing them in a `setTimeout` (which would cause a crash on mobile).
This is the implementation of the 2nd option in this ADR: https://github.com/MetaMask/decisions/blob/main/decisions/core/0016-core-classes-error-reporting.md#optional-captureexception-constructor-parameter-that-inherits-from-parent
Relates to #6613

feat: Add `Messenger` error reporting

---

eslint-warning-thresholds.json
packages/remote-feature-flag-controller/CHANGELOG.md
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts

The new metadata properties `includeInStateLogs` and `usedInUi` have been added to the `RemoteFeatureFlagController`.
Relates to https://github.com/MetaMask/core/issues/6516

feat: Add new metadata properties to `RemoteFeatureFlagController`

---

packages/app-metadata-controller/CHANGELOG.md
packages/app-metadata-controller/src/AppMetadataController.test.ts
packages/app-metadata-controller/src/AppMetadataController.ts

The new metadata properties includeInStateLogs and usedInUi have been added to the `AppMetadataController`.
Fixes https://github.com/MetaMask/core/issues/6515

feat: Add new metadata properties to `AppMetadataController`

---

package.json
packages/assets-controllers/package.json
packages/bridge-controller/package.json
packages/bridge-status-controller/package.json
packages/earn-controller/package.json
packages/eip-5792-middleware/CHANGELOG.md
packages/eip-5792-middleware/package.json
packages/network-enablement-controller/package.json
packages/shield-controller/package.json
packages/transaction-controller/CHANGELOG.md
packages/transaction-controller/package.json
packages/user-operation-controller/package.json
yarn.lock

This release publishes a new minor version of `@metamask/transaction-controller`, which primarily adds new messenger events that `SmartTransactionsController` can now use instead of receiving function references.
---
This release includes:
- `@metamask/transaction-controller` (60.3.0 -> 60.4.0)

Release 561.0.0

---

packages/account-tree-controller/src/backup-and-sync/syncing/group.ts
packages/account-tree-controller/src/backup-and-sync/syncing/legacy.ts

This PR swallows all group creation errors during backup and sync. This was already the case for multichain syncs but we forgot to do it for legacy syncs. It's now swallowed in every flow.

fix(account-tree-controller): swallow group creation errors

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/package.json
packages/multichain-account-service/src/providers/EvmAccountProvider.test.ts
packages/multichain-account-service/src/providers/EvmAccountProvider.ts
yarn.lock

Derive next address instead of creating the account entirely (which triggers `:accountAdded` and adds side-effects for this temporary account).
N/A

fix(multichain-account-service): prevent creating EVM account during discovery

---

packages/gator-permissions-controller/CHANGELOG.md
packages/gator-permissions-controller/src/GatorPermissionsController.test.ts
packages/gator-permissions-controller/src/GatorPermissionsController.ts
packages/gator-permissions-controller/src/index.ts

The method `decodePermissionFromPermissionContextForOrigin` was incorrectly implemented as a synchronous function. This change updates this function and related tests to be synchronous.
Because this function has not yet been released, this is not being considered a breaking change.

method 'decodePermissionFromPermissionContextForOrigin' is now synchronous

---

packages/multichain-account-service/CHANGELOG.md
packages/multichain-account-service/src/index.ts

Add missing exports that needs to be used for the `providerConfigs`.
N/A

fix(multichain-account-service): export providers + constant names

---

packages/assets-controllers/src/utils/formatters.test.ts
packages/assets-controllers/src/utils/formatters.ts

Add a generic `formatNumber` option to allow clients flexibility while using the formatting cache.

feat: add generic number format

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.ts
packages/account-tree-controller/src/backup-and-sync/syncing/metadata.ts

- Set `lastUpdatedAt` to `0` when generating default account group names.
- This created conflicts with backup and sync, where newly created local groups' names were taking precedence over user-defined backed up names.

fix(account-tree-controller): do not save `lastUpdatedAt` for default names

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts

We were not re-using the persisted group name when checking for the next available name during group metadata updates.
Meaning that if somehow, we were receiving a `:accountAdded` before `init` was called, then the groups metadata would be empty, leading to some duplicate names.
I spotted this issue with mobile E2E and our fixture system.
E2E were failing on this PR, because of this bug:
- https://github.com/MetaMask/metamask-mobile/pull/20255

fix(account-tree-controller): fix duplicate names for out-of-order accounts

---

packages/account-tree-controller/CHANGELOG.md
packages/account-tree-controller/src/AccountTreeController.test.ts
packages/account-tree-controller/src/AccountTreeController.ts

We now enforce that `init` got called before making any change to the tree to avoid having out-of-order account groups.
I stumbled upon this bug when running E2E on mobile. Basically, the way the fixture are setup on mobile were triggering `:accountAdded` before calling `AccountTreeController.init`, which resulted in having "Account 2" inserted before "Account 1".
But, since "Account 1" was already part of the initial `internalAccounts` it should have been inserted before any new accounts.
Thus, forcing `init` to be called implicitly fixes this order/sequence.
E2E were failing on this PR, because of this bug:
- https://github.com/MetaMask/metamask-mobile/pull/20255

feat(account-tree-controller): force-init before any account insertion/removal

---

package.json
packages/core-backend/CHANGELOG.md
packages/core-backend/package.json

This PR releases the initial version of the `@metamask/core-backend` package.
`@metamask/core-backend` provides core backend services for MetaMask, serving as the data layer between Backend services (REST APIs, WebSocket services) and Frontend applications (Extension, Mobile). This package enables authenticated real-time data delivery with type-safe controller integration.
This is the **initial release** of the package, introducing:
- **BackendWebSocketService** - WebSocket client providing authenticated real-time data delivery with:
- Connection management and automatic reconnection with exponential backoff
- Message routing and subscription management
- Authentication integration with `AuthenticationController`
- Type-safe messenger-based API for controller integration
- …

Update Release 606.0.0

---

package.json
packages/core-backend/CHANGELOG.md
packages/core-backend/package.json

This reverts commit 679c4e42e65db04adb2ead60582fcb6959f153f5.
The release won't get published because the PR title is wrong
It must match those patterns: https://github.com/MetaMask/core/blob/main/.github/workflows/main.yml#L54

Revert "Update Release 606.0.0 (#6798)"
